// Code generated by goplus from runtime_types.gp. DO NOT EDIT.
//goplus:v v0.28.0

package language

// instantiate replaces inferred type variables using the current call's type
// arguments. It retains nominal names and rules; it never mutates checked ASTs.
func (e *evaluator) instantiate(t *Type, bindings map[string]typeBinding, depth int) *Type {
	if t == nil {
		return nil
	}
	e.step(1, t.At)
	if depth >= evaluationNesting {
		evalError(t.At, "evaluation.depth", "type instantiation nesting limit exceeded")
	}
	result := &Type{At: t.At}
	switch __gp_m0 := any(t.Form).(type) {
	case NamedType:
		name := __gp_m0.Name

		if bound, found := bindings[name]; found {
			return e.instantiate(bound.typ, bound.environment, depth+1)
		}
		return t
	case ListType:
		element := __gp_m0.Element
		result.Form = ListType{Element: e.instantiate(element, bindings, depth+1)}
	case AppliedType:
		fn := __gp_m0.Constructor
		arg := __gp_m0.Argument
		result.Form = AppliedType{Constructor: e.instantiate(fn, bindings, depth+1), Argument: e.instantiate(arg, bindings, depth+1)}
	case ArrowType:
		arg := __gp_m0.Argument
		out := __gp_m0.Result
		result.Form = ArrowType{Argument: e.instantiate(arg, bindings, depth+1), Result: e.instantiate(out, bindings, depth+1)}
	case RecordType:
		fields := __gp_m0.Fields

		out := make([]Field, len(fields))
		for i, field := range fields {
			out[i] = field
			out[i].Type = e.instantiate(field.Type, bindings, depth+1)
		}
		result.Form = RecordType{Fields: out}
	case RefinedType:
		base := __gp_m0.Base
		rules := __gp_m0.Rules
		result.Form = RefinedType{Base: e.instantiate(base, bindings, depth+1), Rules: rules}
	default:
		panic("goplus: impossible enum value in match")
	}
	return result
}

func bareType(t *Type) *Type {
	if t == nil {
		return nil
	}
	for {
		switch __gp_m1 := any(t.Form).(type) {
		case RefinedType:
			base := __gp_m1.Base
			t = base
		default:
			return t
		}
	}
}

// The static checker has already proved these shapes compatible. Matching
// recovers the concrete instantiation of a polymorphic named function, including
// type arguments supplied through higher-order functions and partial application.
func (e *evaluator) bindSignature(template, actual *Type, bindings map[string]typeBinding) {
	originalActual := actual
	template, actual = bareType(template), bareType(actual)
	if template == nil || actual == nil {
		return
	}
	e.step(1, template.At)
	switch __gp_m2 := any(template.Form).(type) {
	case NamedType:
		name := __gp_m2.Name
		if !uppercase(name) {
			bindings[name] = typeBinding{typ: originalActual}
		}
	case ArrowType:
		arg := __gp_m2.Argument
		out := __gp_m2.Result
		switch __gp_m3 := any(actual.Form).(type) {
		case ArrowType:
			a := __gp_m3.Argument
			b := __gp_m3.Result
			e.bindSignature(arg, a, bindings)
			e.bindSignature(out, b, bindings)
		default:
		}
	case AppliedType:
		fn := __gp_m2.Constructor
		arg := __gp_m2.Argument
		switch __gp_m4 := any(actual.Form).(type) {
		case AppliedType:
			a := __gp_m4.Constructor
			b := __gp_m4.Argument
			e.bindSignature(fn, a, bindings)
			e.bindSignature(arg, b, bindings)
		default:
		}
	case ListType:
		element := __gp_m2.Element
		switch __gp_m5 := any(actual.Form).(type) {
		case ListType:
			other := __gp_m5.Element
			e.bindSignature(element, other, bindings)
		default:
		}
	case RecordType:
		fields := __gp_m2.Fields
		switch __gp_m6 := any(actual.Form).(type) {
		case RecordType:
			others := __gp_m6.Fields
			for _, field := range fields {
				for _, other := range others {
					e.step(1, template.At)
					if field.Name == other.Name {
						e.bindSignature(field.Type, other.Type, bindings)
						break
					}
				}
			}
		default:

		}
	case RefinedType:
		panic("bareType retained a refinement")
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (e *evaluator) functionBindings(name string, signature *Type) map[string]typeBinding {
	bindings := make(map[string]typeBinding)
	if signature != nil {
		e.bindSignature(e.functions[name].Signature, signature, bindings)
	}
	for param, symbol := range e.module.functionScopes[name] {
		if bound, ok := bindings[param]; ok {
			bindings[symbol] = bound
		}
	}
	return bindings
}
