// Code generated by goplus from project_openapi_source_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"goforge.dev/refine/native"
	"goforge.dev/refine/project"
)

const cliAuthoredOpenAPITypes = `type Request = {parameters :: {id :: Int}, headers :: {}, body :: Maybe Int}
type Response = {headers :: {}, body :: Maybe Int}
type Context = {request :: Request, response :: Response} where it.request.parameters.id >= 0 @code "request.id"
`
const cliAuthoredOpenAPI = `openapi "3.2.1" {
  title "Authored"
  version "1.0.0"
  operation ping "POST" "/items/{id}" {
    request Request {
      parameter path "id" at parameters.id required
      body "application/json" at body optional
    }
    response "200" Response "ok" {
      body "application/json" at body optional
      context Context
    }
  }
}
`

func authoredOpenAPIProjectFixture(t *testing.T, config string) string {
	t.Helper()
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "pom.xml"), []byte("<project/>"), 0600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "refine.project.json"), []byte(config), 0600); err != nil {
		t.Fatal(err)
	}
	directory := filepath.Join(root, "schemata", "api")
	if err := os.MkdirAll(directory, 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(directory, "types.refine"), []byte(cliAuthoredOpenAPITypes), 0600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(directory, "SNAPSHOT.refine"), []byte("import \"types.refine\"\n"+cliAuthoredOpenAPI), 0600); err != nil {
		t.Fatal(err)
	}
	return root
}

func TestProjectCLIDiscoversAuthoredOpenAPIOperations(t *testing.T) {
	root := authoredOpenAPIProjectFixture(t, `{"families":{"api":{"wire":{"numericExpansion":4096}}}}`)
	input, err := loadProject(root, "refine.project.json", "")
	if err != nil || len(input.Contracts) != 1 {
		t.Fatalf("authored operation discovery: %+v %v", input, err)
	}
	contract := input.Contracts[0]
	if contract.NativeProject == nil || contract.NativeProject.Kind() != native.OpenAPIOperationsProject || contract.RootType != "" || len(contract.Formats) != 1 || contract.Formats[0] != native.OpenAPI || contract.NativeProject.Metadata().NumericExpansion != 4096 {
		t.Fatalf("authored operation target changed: %+v", contract)
	}
	generated, err := project.Generate(input)
	if err != nil {
		t.Fatal(err)
	}
	sourceFound := false
	for _, file := range generated.Files {
		if strings.HasSuffix(file.Path, "/contract.refine") && strings.Contains(string(file.Content), "operation \"ping\"") {
			sourceFound = true
		}
	}
	if !sourceFound {
		t.Fatal("authored OpenAPI source was not retained in generated resources")
	}
}

func TestProjectCLIAuthoredOpenAPIRejectsCompetingConfiguration(t *testing.T) {
	configs := []string{`{"families":{"api":{"root":"Request"}}}`, `{"families":{"api":{"formats":["json-schema"]}}}`, `{"families":{"api":{"wire":{"openapi":{"version":"refine.openapi.operations/v1","operations":[]}}}}}`}
	for _, config := range configs {
		root := authoredOpenAPIProjectFixture(t, config)
		if _, err := loadProject(root, "refine.project.json", ""); err == nil {
			t.Fatalf("competing authored OpenAPI configuration accepted: %s", config)
		}
	}
}
