// Code generated by goplus from project.gp. DO NOT EDIT.
//goplus:v v0.28.0

package cli

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"goforge.dev/refine/language"
	"goforge.dev/refine/native"
	"goforge.dev/refine/project"
	"goforge.dev/refine/release"
	"goforge.dev/refine/schemajson"
)

type projectConfig struct {
	SchemaDir string                  `json:"schemaDir"`
	Package   string                  `json:"package"`
	Families  map[string]familyConfig `json:"families"`
	Release   releaseProjectPolicy    `json:"release"`
}
type familyConfig struct {
	Root        string              `json:"root"`
	Package     string              `json:"package"`
	JavaPackage string              `json:"javaPackage"`
	NoCodegen   []string            `json:"noCodegen"`
	Formats     []native.Format     `json:"formats"`
	Wire        native.WireMetadata `json:"wire"`
	Release     releaseFamilyPolicy `json:"release"`
}

func projectCommand(args []string, output, errorOutput io.Writer) int {
	if len(args) == 0 {
		fmt.Fprintln(errorOutput, "expected project generate or project maven")
		return 2
	}
	command := args[0]
	flags := flag.NewFlagSet("project "+command, flag.ContinueOnError)
	flags.SetOutput(errorOutput)
	if command == "maven" {
		executable := flags.String("executable", "refine", "Refine executable invoked during generate-sources")
		if err := flags.Parse(args[1:]); err != nil || len(flags.Args()) != 0 {
			return 2
		}
		if _, err := io.WriteString(output, project.MavenSnippet(project.MavenOptions{CLIExecutable: *executable})); err != nil {
			return 2
		}
		return 0
	}
	if command != "generate" {
		fmt.Fprintln(errorOutput, "unknown project command")
		return 2
	}
	rootFlag := flags.String("root", "", "project root; defaults to nearest Maven project")
	configFlag := flags.String("config", "refine.project.json", "project-relative configuration path")
	packageFlag := flags.String("package", "", "override all generated Java namespaces")
	outputFlag := flags.String("output", "", "project-relative Java output directory")
	flat := flags.Bool("flat", false, "omit package subdirectories from Java output")
	check := flags.Bool("check", false, "verify generated outputs without writing")
	jsonMode := flags.Bool("json", false, "emit machine-readable result")
	if err := flags.Parse(args[1:]); err != nil || len(flags.Args()) != 0 {
		return 2
	}
	root := *rootFlag
	if root == "" {
		cwd, err := os.Getwd()
		if err != nil {
			fmt.Fprintln(errorOutput, err)
			return 2
		}
		root, err = project.DetectRoot(cwd)
		if err != nil {
			fmt.Fprintln(errorOutput, "no Maven project found; specify --root explicitly")
			return 2
		}
	}
	absolute, err := filepath.Abs(root)
	if err != nil {
		fmt.Fprintln(errorOutput, err)
		return 2
	}
	input, err := loadProject(absolute, *configFlag, *packageFlag)
	result := report{Phase: "project.generate", State: "valid", Diagnostics: []diagnostic{}}
	if err == nil {
		input.Layout = project.Layout{SourceDir: *outputFlag, Flat: *flat}
		var bundle project.Bundle
		bundle, err = project.Generate(input)
		if err == nil {
			if *check {
				err = project.CheckOwned(absolute, bundle, "")
			} else {
				err = project.WriteOwned(absolute, bundle, "")
			}
			if err == nil {
				verb := "Generated"
				if *check {
					verb = "Verified"
				}
				result.Summary = fmt.Sprintf("%s %d files for %d schema versions", verb, len(bundle.Files), len(input.Contracts))
				result.Result = struct {
					Files     int  `json:"files"`
					Contracts int  `json:"contracts"`
					Check     bool `json:"check"`
				}{len(bundle.Files), len(input.Contracts), *check}
			}
		}
	}
	status := 0
	if err != nil {
		status = 1
		result.State = "invalid"
		result.Diagnostics = append(result.Diagnostics, diagnostic{Code: "project.generate", Message: err.Error()})
	}
	if *jsonMode {
		if err := json.NewEncoder(output).Encode(result); err != nil {
			return 2
		}
	} else {
		writer := output
		if status != 0 {
			writer = errorOutput
		}
		text := result.Summary
		if err != nil {
			text = err.Error()
		}
		if _, err := fmt.Fprintln(writer, text); err != nil {
			return 2
		}
	}
	return status
}

func readWithin(root *os.Root, name string) ([]byte, error) {
	if name == "" || path.IsAbs(name) || path.Clean(name) != name || strings.HasPrefix(name, "../") || strings.ContainsAny(name, "\\:\x00") {
		return nil, fmt.Errorf("project input must be a canonical project-relative path")
	}
	file, err := root.Open(filepath.FromSlash(name))
	if err != nil {
		return nil, err
	}
	defer file.Close()
	data, err := io.ReadAll(io.LimitReader(file, (16<<20)+1))
	if err != nil {
		return nil, err
	}
	if len(data) > 16<<20 {
		return nil, fmt.Errorf("project input exceeds 16 MiB")
	}
	return data, nil
}

type schemaSourceKind uint8

const (
	refineSchema schemaSourceKind = iota + 1
	nativeBundleSchema
)

func schemaSourceName(name string) (string, schemaSourceKind, bool) {
	if strings.HasSuffix(name, ".refined.json") {
		return strings.TrimSuffix(name, ".refined.json"), nativeBundleSchema, true
	}
	if strings.HasSuffix(name, ".refine") {
		return strings.TrimSuffix(name, ".refine"), refineSchema, true
	}
	return "", 0, false
}
func emptyWireMetadata(metadata native.WireMetadata) bool {
	return len(metadata.ExtraFields) == 0 && len(metadata.Scalars) == 0 && len(metadata.Discriminators) == 0 && metadata.PublicationNamespace == "" && metadata.NumericExpansion == 0
}

func loadProject(rootPath, configPath, packageOverride string) (project.GenerateInput, error) {
	root, err := os.OpenRoot(rootPath)
	if err != nil {
		return project.GenerateInput{}, err
	}
	defer root.Close()
	config := projectConfig{SchemaDir: "schemata", Families: map[string]familyConfig{}}
	raw, err := readWithin(root, filepath.ToSlash(configPath))
	if err == nil {
		if _, err = schemajson.Parse(raw, schemajson.Limits{}); err != nil {
			return project.GenerateInput{}, err
		}
		decoder := json.NewDecoder(bytes.NewReader(raw))
		decoder.DisallowUnknownFields()
		if err = decoder.Decode(&config); err != nil {
			return project.GenerateInput{}, err
		}
	} else if !errors.Is(err, os.ErrNotExist) || configPath != "refine.project.json" {
		return project.GenerateInput{}, err
	}
	if config.SchemaDir == "" {
		config.SchemaDir = "schemata"
	}
	if config.SchemaDir == "." || path.Clean(config.SchemaDir) != config.SchemaDir || path.IsAbs(config.SchemaDir) || strings.HasPrefix(config.SchemaDir, "../") || strings.ContainsAny(config.SchemaDir, "\\:\x00") {
		return project.GenerateInput{}, fmt.Errorf("schemaDir must be a project-relative directory")
	}
	directory, err := root.Open(filepath.FromSlash(config.SchemaDir))
	if err != nil {
		return project.GenerateInput{}, err
	}
	families, err := directory.ReadDir(-1)
	directory.Close()
	if err != nil {
		return project.GenerateInput{}, err
	}
	sort.Slice(families, func(i, j int) bool { return families[i].Name() < families[j].Name() })
	input := project.GenerateInput{BaseJavaPackage: config.Package}
	seenFamilies := map[string]bool{}
	for _, family := range families {
		if !family.IsDir() {
			continue
		}
		name := family.Name()
		settings := config.Families[name]
		seenFamilies[name] = true
		dirName := path.Join(config.SchemaDir, name)
		folder, err := root.Open(filepath.FromSlash(dirName))
		if err != nil {
			return input, err
		}
		entries, err := folder.ReadDir(-1)
		folder.Close()
		if err != nil {
			return input, err
		}
		sort.Slice(entries, func(i, j int) bool { return entries[i].Name() < entries[j].Name() })
		seenVersions := map[string]string{}
		for _, entry := range entries {
			if entry.IsDir() {
				continue
			}
			basename, kind, recognized := schemaSourceName(entry.Name())
			if !recognized {
				continue
			}
			var version *release.Version
			if basename != "SNAPSHOT" {
				if !strings.HasPrefix(basename, "v") {
					continue
				}
				parsed, err := release.ParseVersion(basename)
				if err != nil {
					return input, err
				}
				if basename != "v"+parsed.String() {
					return input, fmt.Errorf("schema version filename %s is not canonical", entry.Name())
				}
				version = &parsed
			}
			if prior := seenVersions[basename]; prior != "" {
				return input, fmt.Errorf("family %s version %s is defined by both %s and %s", name, basename, prior, entry.Name())
			}
			seenVersions[basename] = entry.Name()
			sourceID := path.Join(dirName, entry.Name())
			noCodegen := false
			for _, excluded := range settings.NoCodegen {
				if excluded == basename {
					noCodegen = true
				}
			}
			javaPackage := settings.JavaPackage
			if packageOverride != "" {
				javaPackage = packageOverride
			}
			if kind == nativeBundleSchema {
				raw, readErr := readWithin(root, sourceID)
				if readErr != nil {
					return input, readErr
				}
				imported, parseErr := native.ParseBundle(raw)
				if parseErr != nil {
					return input, parseErr
				}
				if !emptyWireMetadata(settings.Wire) {
					return input, fmt.Errorf("family %s native bundle owns wire metadata; family wire overrides are not allowed", name)
				}
				if settings.Root != "" && settings.Root != imported.Root().TypeName {
					return input, fmt.Errorf("family %s configured root %s does not match native bundle root %s", name, settings.Root, imported.Root().TypeName)
				}
				input.Contracts = append(input.Contracts, project.Contract{Family: name, Version: version, NativeProject: imported, RootType: settings.Root, LogicalNamespace: settings.Package, JavaPackage: javaPackage, NoCodegen: noCodegen, Formats: settings.Formats})
				continue
			}
			bundle, err := loadSources(root, sourceID)
			if err != nil {
				return input, err
			}
			program := bundle.Program()
			target := settings.Root
			if target == "" {
				types := program.Syntax().Types
				if len(types) == 1 {
					target = types[0].Name
				} else {
					return input, fmt.Errorf("family %s requires a root type in refine.project.json", name)
				}
			}
			namespace := settings.Package
			if namespace == "" {
				namespace = program.Syntax().Package
			}
			input.Contracts = append(input.Contracts, project.Contract{Family: name, Version: version, Program: program, RootType: target, LogicalNamespace: namespace, JavaPackage: javaPackage, NoCodegen: noCodegen, Formats: settings.Formats, Wire: settings.Wire})
		}
		prospective := ""
		if settings.Release.Intended != nil {
			if parsed, e := parsePolicyVersion(*settings.Release.Intended); e == nil {
				prospective = "v" + parsed.String()
			}
		}
		for _, excluded := range settings.NoCodegen {
			if seenVersions[excluded] == "" && excluded != prospective {
				return input, fmt.Errorf("family %s noCodegen refers to missing version %s", name, excluded)
			}
		}
	}
	for name := range config.Families {
		if !seenFamilies[name] {
			return input, fmt.Errorf("configuration refers to missing schema family %s", name)
		}
	}
	if len(input.Contracts) == 0 {
		return input, fmt.Errorf("no schemata/<family>/{vX.Y.Z,SNAPSHOT}.refine files found")
	}
	return input, nil
}

func loadSources(root *os.Root, entry string) (*language.SourceBundle, error) {
	sources := map[string]string{}
	pending := []string{entry}
	bytes := 0
	for len(pending) > 0 {
		name := pending[len(pending)-1]
		pending = pending[:len(pending)-1]
		if _, seen := sources[name]; seen {
			continue
		}
		if len(sources) >= 10000 {
			return nil, fmt.Errorf("source bundle exceeds 10,000 files")
		}
		data, err := readWithin(root, name)
		if err != nil {
			return nil, err
		}
		bytes += len(data)
		if bytes > 16<<20 {
			return nil, fmt.Errorf("source bundle exceeds 16 MiB")
		}
		sources[name] = string(data)
		module, err := language.Parse(string(data))
		if err != nil {
			return nil, err
		}
		for _, reference := range module.Imports {
			if reference.Path == "" || path.IsAbs(reference.Path) || strings.ContainsAny(reference.Path, "\\:\x00") {
				return nil, fmt.Errorf("imports must be project-relative source paths")
			}
			pending = append(pending, path.Join(path.Dir(name), reference.Path))
		}
	}
	return language.CompileSources(entry, sources)
}
