// Code generated by goplus from release_change.gp. DO NOT EDIT.
//goplus:v v0.28.0

package cli

import (
	"encoding/json"
	"fmt"
	"sort"

	"goforge.dev/refine/analysis"
	"goforge.dev/refine/language"
	"goforge.dev/refine/native"
	"goforge.dev/refine/release"
)

// This evidence bounds the author's documentation claim; it does not prove
// native/Java compatibility or decide whether a functional change is a fix.
type releaseDocumentationEvidence struct {
	Baseline string                          `json:"baseline"`
	Syntax   analysis.ContractSyntaxEvidence `json:"syntax"`
	Outcome  analysis.Outcome                `json:"outcome"`
	Reasons  []string                        `json:"reasons"`
}

func documentationEvidence(baseline, snapshot *releaseSchemaEntry, baselineRoot, snapshotRoot string, catalog releaseCatalog) (*releaseDocumentationEvidence, error) {
	syntax, err := analysis.CompareContractSyntax(baseline.program, baselineRoot, snapshot.program, snapshotRoot)
	if err != nil {
		return nil, err
	}
	result := &releaseDocumentationEvidence{Baseline: baseline.version.String(), Syntax: syntax, Outcome: analysis.Yes, Reasons: []string{}}
	different := func(reason string) { result.Outcome = analysis.No; result.Reasons = append(result.Reasons, reason) }
	uncertain := func(reason string) {
		if result.Outcome != analysis.No {
			result.Outcome = analysis.Unknown
		}
		result.Reasons = append(result.Reasons, reason)
	}
	if !syntax.Equal {
		different("checked language declarations, predicates, functions, diagnostics, budgets, or root changed")
	}
	if baseline.kind != snapshot.kind {
		different("schema source format changed")
	}
	oldPackages, err := releaseSourcePackages(baseline, catalog)
	if err != nil {
		return nil, err
	}
	nextPackages, err := releaseSourcePackages(snapshot, catalog)
	if err != nil {
		return nil, err
	}
	if oldPackages != nextPackages {
		different("reachable source publication packages or dependency graph changed")
	}
	old, next := baseline.nativeProject, snapshot.nativeProject
	if old != nil && next != nil {
		oldMetadata, err := json.Marshal(old.Metadata())
		if err != nil {
			return nil, err
		}
		nextMetadata, err := json.Marshal(next.Metadata())
		if err != nil {
			return nil, err
		}
		if string(oldMetadata) != string(nextMetadata) {
			different("native wire, operation, example, or publication metadata changed")
		}
		if old.Format() != next.Format() || old.Version() != next.Version() || old.Root() != next.Root() {
			different("native format, version, or root selection changed")
		}
		if !sameReleaseResources(old.Resources(), next.Resources()) {
			uncertain("native resource changes require classification; documentation-only native equivalence is not proven")
		}
		oldUnits, err := releaseConstraintSyntax(old)
		if err != nil {
			return nil, err
		}
		nextUnits, err := releaseConstraintSyntax(next)
		if err != nil {
			return nil, err
		}
		if oldUnits != nextUnits {
			different("native constraint unit syntax changed")
		}
	} else if (old == nil) != (next == nil) {
		different("native validation boundary changed")
	}
	return result, nil
}

func releaseSourcePackages(entry *releaseSchemaEntry, catalog releaseCatalog) (string, error) {
	type item struct {
		ID, Package string
		Imports     []string
	}
	items := []item{}
	files := []language.SourceFile{}
	root := ""
	canonicalID := func(id string) string {
		if source := catalog.entries[id]; source != nil {
			return "family:" + source.family
		}
		return "file:" + id
	}
	if entry.bundle != nil {
		files = entry.bundle.Files()
		root = entry.sourcePath
	} else if entry.nativeProject != nil {
		files = entry.nativeProject.LanguageFiles()
		root = entry.nativeProject.LanguageEntry()
	}
	for _, file := range files {
		module, err := language.Parse(file.Source)
		if err != nil {
			return "", err
		}
		imports := make([]string, len(file.Imports))
		for i, id := range file.Imports {
			imports[i] = canonicalID(id)
		}
		items = append(items, item{canonicalID(file.ID), module.Package, imports})
	}
	sort.Slice(items, func(i, j int) bool { return items[i].ID < items[j].ID })
	encoded, err := json.Marshal(struct {
		Entry string
		Files []item
	}{canonicalID(root), items})
	return string(encoded), err
}

func sameReleaseResources(a, b []native.Resource) bool {
	if len(a) != len(b) {
		return false
	}
	left, right := append([]native.Resource(nil), a...), append([]native.Resource(nil), b...)
	sort.Slice(left, func(i, j int) bool { return left[i].URI < left[j].URI })
	sort.Slice(right, func(i, j int) bool { return right[i].URI < right[j].URI })
	for i := range left {
		if left[i] != right[i] {
			return false
		}
	}
	return true
}
func releaseConstraintSyntax(project *native.Project) (string, error) {
	units := project.NativeConstraintSources()
	sort.Slice(units, func(i, j int) bool { return units[i].URI < units[j].URI })
	for i := range units {
		module, err := language.Parse(units[i].Source)
		if err != nil {
			return "", err
		}
		units[i].Source = language.Format(module)
	}
	encoded, err := json.Marshal(units)
	return string(encoded), err
}

// Dependency evidence is deliberately narrower than compatibility evidence.
// Only conclusive documentation equivalence makes a changed pin non-affecting;
// unsupported native/resource comparisons remain contract-affecting.
func dependencyAffectsContract(baseline, snapshot *releaseSchemaEntry, catalog releaseCatalog, config projectConfig) (bool, error) {
	if baseline == nil || snapshot == nil {
		return true, nil
	}
	if baseline.policyContent != snapshot.policyContent {
		return true, nil
	}
	baselineRoot, err := releaseEntryRoot(baseline, baseline.family, config.Families[baseline.family])
	if err != nil {
		return true, err
	}
	snapshotRoot, err := releaseEntryRoot(snapshot, snapshot.family, config.Families[snapshot.family])
	if err != nil {
		return true, err
	}
	evidence, err := documentationEvidence(baseline, snapshot, baselineRoot, snapshotRoot, catalog)
	if err != nil {
		return true, err
	}
	return evidence.Outcome != analysis.Yes, nil
}

func classifyDependencyImports(snapshot, baseline releaseEntryImports, catalog releaseCatalog, config projectConfig) ([]release.ImportPin, error) {
	result := append([]release.ImportPin(nil), snapshot.pins...)
	prior := map[string]release.ImportPin{}
	for _, pin := range baseline.pins {
		prior[pin.Family] = pin
	}
	for i, pin := range result {
		old, ok := prior[pin.Family]
		if !ok {
			continue
		}
		if old.Version == pin.Version && old.Content == pin.Content {
			result[i].AffectsContract = false
			continue
		}
		affects, err := dependencyAffectsContract(baseline.entries[pin.Family], snapshot.entries[pin.Family], catalog, config)
		if err != nil {
			return nil, err
		}
		result[i].AffectsContract = affects
	}
	return result, nil
}

func enforceDocumentationClaim(plan *release.PlanResult, evidence *releaseDocumentationEvidence) {
	if evidence == nil || evidence.Outcome == analysis.Yes {
		return
	}
	plan.Ready = false
	plan.Accepted = nil
	plan.Suggested = nil
	plan.NoPendingVersion = false
	plan.Issues = append(plan.Issues, release.Issue{Code: "release.documentation_unproven", Message: fmt.Sprintf("documentation-only classification against %s is not established; classify the change explicitly as fix, feature, or breaking before selecting a version", evidence.Baseline)})
}
