// GoPlus-authored release CLI workflow tests.
package cli

import (
    "bytes"
    "encoding/json"
    "os"
    "path/filepath"
    "strings"
    "testing"

    "goforge.dev/refine/analysis"
    "goforge.dev/refine/native"
    "goforge.dev/refine/project"
    "goforge.dev/refine/release"
)

func releaseFixture(t *testing.T,files map[string]string,config string)string{
    t.Helper();root:=t.TempDir();if err:=os.WriteFile(filepath.Join(root,"pom.xml"),[]byte("<project/>"),0600);err!=nil{t.Fatal(err)}
    for name,content:=range files{target:=filepath.Join(root,filepath.FromSlash(name));if err:=os.MkdirAll(filepath.Dir(target),0755);err!=nil{t.Fatal(err)};if err:=os.WriteFile(target,[]byte(content),0600);err!=nil{t.Fatal(err)}}
    if err:=os.WriteFile(filepath.Join(root,"refine.project.json"),[]byte(config),0600);err!=nil{t.Fatal(err)};return root
}

func releaseConfig(change,intended,extra string)string{return `{"families":{"foo":{"root":"Thing","release":{"change":"`+change+`","intended":"`+intended+`"`+extra+`}}}}`}

func TestReleasePlanAllBaselinesExactOverrideAndDocumentationIdentity(t *testing.T){
    files:=map[string]string{"schemata/foo/v1.0.0.refine":"type Thing = Int\n","schemata/foo/v1.0.1.refine":"-- prior docs\ntype Thing = Int\n","schemata/foo/SNAPSHOT.refine":"-- next docs\ntype Thing = Int\n"};root:=releaseFixture(t,files,releaseConfig("documentation","1.0.2",""));workflow,err:=buildReleaseWorkflow(root,"refine.project.json",nil);if err!=nil{t.Fatal(err)};if len(workflow.reports)!=1||len(workflow.reports[0].Comparisons)!=4{t.Fatalf("did not compare every baseline/direction: %+v",workflow.reports)};report:=workflow.reports[0];if report.Plan.Ready||report.Plan.Suggested==nil||report.Plan.Suggested.String()!="1.0.2"{t.Fatalf("unknown dimensions were not enforced: %+v",report.Plan)}
    latest:=report.Comparisons[2];extra:=`,"overrides":[{"baseline":"1.0.1","baselineSha256":"`+latest.BaselineSHA256+`","snapshotSha256":"`+latest.SnapshotSHA256+`","direction":"backward","reason":"native and Java compatibility reviewed"},{"baseline":"1.0.0","baselineSha256":"`+report.Comparisons[0].BaselineSHA256+`","snapshotSha256":"`+report.Comparisons[0].SnapshotSHA256+`","direction":"backward","reason":"native and Java compatibility reviewed"}]`
    if err:=os.WriteFile(filepath.Join(root,"refine.project.json"),[]byte(releaseConfig("documentation","1.0.2",extra)),0600);err!=nil{t.Fatal(err)};workflow,err=buildReleaseWorkflow(root,"refine.project.json",nil);if err!=nil||!workflow.reports[0].Plan.Ready{t.Fatalf("exact overrides rejected: %v %+v",err,workflow.reports[0].Plan)}
    stale:=strings.Replace(extra,latest.SnapshotSHA256,strings.Repeat("0",64),1);if err:=os.WriteFile(filepath.Join(root,"refine.project.json"),[]byte(releaseConfig("documentation","1.0.2",stale)),0600);err!=nil{t.Fatal(err)};workflow,err=buildReleaseWorkflow(root,"refine.project.json",nil);if err!=nil{t.Fatal(err)};if workflow.reports[0].Plan.Ready{t.Fatal("stale content-bound override was accepted")}
}

func TestReleaseCLIRejectsLooseConfiguration(t *testing.T){
    files:=map[string]string{"schemata/foo/SNAPSHOT.refine":"type Thing = Int\n"};configs:=[]string{`{"families":{},"families":{}}`,`{"unknown":true,"families":{}}`,releaseConfig("patch","0.1.0",""),releaseConfig("feature","v0.1.0","")}
    for _,config:=range configs{root:=releaseFixture(t,files,config);var out,stderr bytes.Buffer;if code:=releaseCommand([]string{"plan","--root",root,"--json"},&out,&stderr);code!=1{t.Fatalf("invalid config accepted (%d): %s / %s",code,&out,&stderr)}}
}

func TestReleaseCLIRequiresDistinctBreakingFixJustification(t *testing.T){
    files:=map[string]string{"schemata/foo/v1.0.0.refine":"type Thing = Int where it >= 0\n","schemata/foo/SNAPSHOT.refine":"type Thing = Int where it >= 1\n"};root:=releaseFixture(t,files,releaseConfig("breaking","1.0.1",""));workflow,err:=buildReleaseWorkflow(root,"refine.project.json",nil);if err!=nil{t.Fatal(err)};backward:=workflow.reports[0].Comparisons[0];identity:=`"baseline":"1.0.0","baselineSha256":"`+backward.BaselineSHA256+`","snapshotSha256":"`+backward.SnapshotSHA256+`","direction":"backward"`;extra:=`,"overrides":[{`+identity+`,"reason":"acknowledge accepted-value break"}],"breakingFixes":[{`+identity+`,"justification":"repairs an incorrectly broad lower bound"}]`;if err:=os.WriteFile(filepath.Join(root,"refine.project.json"),[]byte(releaseConfig("breaking","1.0.1",extra)),0600);err!=nil{t.Fatal(err)};workflow,err=buildReleaseWorkflow(root,"refine.project.json",nil);if err!=nil||!workflow.reports[0].Plan.Ready{t.Fatalf("breaking fix rejected: %v %+v",err,workflow.reports[0].Plan)}
    same:=strings.Replace(extra,"repairs an incorrectly broad lower bound","acknowledge accepted-value break",1);if err:=os.WriteFile(filepath.Join(root,"refine.project.json"),[]byte(releaseConfig("breaking","1.0.1",same)),0600);err!=nil{t.Fatal(err)};workflow,err=buildReleaseWorkflow(root,"refine.project.json",nil);if err!=nil{t.Fatal(err)};if workflow.reports[0].Plan.Ready{t.Fatal("one reason was accepted for override and breaking fix")}
}

func TestReleaseOverrideIdentityIncludesRootPackageAndWirePolicy(t *testing.T){
    files:=map[string]string{"schemata/foo/v1.0.0.refine":"type First = String\ntype Second = String\n","schemata/foo/SNAPSHOT.refine":"-- docs\ntype First = String\ntype Second = String\n"};base:=`{"package":"base.pkg","families":{"foo":{"root":"First","package":"logical.pkg","javaPackage":"java.pkg","formats":["json-schema"],"release":{"change":"documentation","intended":"1.0.1"}}}}`;root:=releaseFixture(t,files,base);workflow,err:=buildReleaseWorkflow(root,"refine.project.json",nil);if err!=nil{t.Fatal(err)};comparison:=workflow.reports[0].Comparisons[0];if comparison.BaselinePolicySHA256==""||comparison.SnapshotPolicySHA256==""{t.Fatal("policy digest missing from report")};identity:=`{"baseline":"1.0.0","baselineSha256":"`+comparison.BaselineSHA256+`","snapshotSha256":"`+comparison.SnapshotSHA256+`","direction":"backward","reason":"reviewed"}`
    configured:=strings.Replace(base,`"intended":"1.0.1"`, `"intended":"1.0.1","overrides":[`+identity+`]`,1);if err:=os.WriteFile(filepath.Join(root,"refine.project.json"),[]byte(configured),0600);err!=nil{t.Fatal(err)};workflow,err=buildReleaseWorkflow(root,"refine.project.json",nil);if err!=nil||!workflow.reports[0].Plan.Ready{t.Fatalf("fresh policy override rejected: %v %+v",err,workflow.reports[0].Plan)}
    mutations:=[]func(string)string{func(text string)string{return strings.Replace(text,`"root":"First"`,`"wire":{"PublicationNamespace":"changed.wire"},"root":"First"`,1)},func(text string)string{return strings.Replace(text,`"root":"First"`,`"root":"Second"`,1)},func(text string)string{return strings.Replace(text,`"package":"logical.pkg"`,`"package":"changed.logical"`,1)},func(text string)string{return strings.Replace(text,`"javaPackage":"java.pkg"`,`"javaPackage":"changed.pkg"`,1)},func(text string)string{return strings.Replace(text,`["json-schema"]`,`["openapi"]`,1)}};for _,mutate:=range mutations{if err:=os.WriteFile(filepath.Join(root,"refine.project.json"),[]byte(mutate(configured)),0600);err!=nil{t.Fatal(err)};changed,err:=buildReleaseWorkflow(root,"refine.project.json",nil);if err!=nil{t.Fatal(err)};if changed.reports[0].Plan.Ready{t.Fatal("policy change did not invalidate content-bound override")}}
}

func TestReleasePromotePinsBatchAndLeavesSnapshotWithoutPendingVersion(t *testing.T){
    config:=`{"families":{"foo":{"root":"Foo","release":{"change":"feature","intended":"0.1.0"}},"bar":{"root":"Bar","release":{"change":"feature","intended":"0.1.0"}}}}`
    files:=map[string]string{"schemata/foo/SNAPSHOT.refine":"type Foo = String\n","schemata/bar/SNAPSHOT.refine":"import \"../foo/SNAPSHOT.refine\"\n\ntype Bar = { foo :: Foo }\n"};root:=releaseFixture(t,files,config);beforeFoo,_:=os.ReadFile(filepath.Join(root,"schemata/foo/SNAPSHOT.refine"));beforeBar,_:=os.ReadFile(filepath.Join(root,"schemata/bar/SNAPSHOT.refine"));var out,stderr bytes.Buffer
    if code:=releaseCommand([]string{"promote","--root",root,"--json"},&out,&stderr);code!=0{t.Fatalf("promotion %d: %s / %s",code,&out,&stderr)};var envelope map[string]any;if err:=json.Unmarshal(out.Bytes(),&envelope);err!=nil{t.Fatal(err)};if !strings.Contains(out.String(),`"generatedOutputsAtomic":true`){t.Fatal("generated-output transaction was not reported")};if _,err:=os.Stat(filepath.Join(root,".refine-generated.json"));err!=nil{t.Fatal("ownership manifest missing",err)};if _,err:=os.Stat(filepath.Join(root,"target/generated-sources/refine/foo/v0_1_0/Foo.java"));err!=nil{t.Fatal("version-qualified generated output missing",err)}
    fooRelease,err:=os.ReadFile(filepath.Join(root,"schemata/foo/v0.1.0.refine"));if err!=nil||string(fooRelease)!=string(beforeFoo){t.Fatal("foo release changed",err)};barRelease,err:=os.ReadFile(filepath.Join(root,"schemata/bar/v0.1.0.refine"));if err!=nil||!strings.Contains(string(barRelease),`import "../foo/v0.1.0.refine"`){t.Fatalf("bar import was not pinned: %v %s",err,barRelease)}
    afterFoo,_:=os.ReadFile(filepath.Join(root,"schemata/foo/SNAPSHOT.refine"));afterBar,_:=os.ReadFile(filepath.Join(root,"schemata/bar/SNAPSHOT.refine"));if !bytes.Equal(beforeFoo,afterFoo)||!bytes.Equal(beforeBar,afterBar){t.Fatal("promotion changed editable snapshots")}
    workflow,err:=buildReleaseWorkflow(root,"refine.project.json",nil);if err!=nil{t.Fatal(err)};for _,report:=range workflow.reports{if !report.Plan.NoPendingVersion||report.Plan.Suggested!=nil{t.Fatalf("pin spelling manufactured a pending version for %s: %+v",report.Family,report.Plan)}}
    if err:=os.WriteFile(filepath.Join(root,"schemata/foo/SNAPSHOT.refine"),append(beforeFoo,[]byte("-- documentation for next release\n")...),0600);err!=nil{t.Fatal(err)};secondConfig:=`{"families":{"foo":{"root":"Foo","release":{"change":"documentation","intended":"0.1.1"}},"bar":{"root":"Bar","release":{"change":"none"}}}}`;if err:=os.WriteFile(filepath.Join(root,"refine.project.json"),[]byte(secondConfig),0600);err!=nil{t.Fatal(err)};workflow,err=buildReleaseWorkflow(root,"refine.project.json",[]string{"foo"});if err!=nil{t.Fatal(err)};comparison:=workflow.reports[0].Comparisons[0];override:=`,"overrides":[{"baseline":"0.1.0","baselineSha256":"`+comparison.BaselineSHA256+`","snapshotSha256":"`+comparison.SnapshotSHA256+`","direction":"backward","reason":"native and Java compatibility reviewed"}]`;secondConfig=`{"families":{"foo":{"root":"Foo","release":{"change":"documentation","intended":"0.1.1"`+override+`}},"bar":{"root":"Bar","release":{"change":"none"}}}}`;if err:=os.WriteFile(filepath.Join(root,"refine.project.json"),[]byte(secondConfig),0600);err!=nil{t.Fatal(err)};out.Reset();stderr.Reset();if code:=releaseCommand([]string{"promote","--root",root,"--json","foo"},&out,&stderr);code!=0{t.Fatalf("second promotion %d: %s / %s",code,&out,&stderr)};if _,err:=os.Stat(filepath.Join(root,"target/generated-sources/refine/foo/v0_1_1/Foo.java"));err!=nil{t.Fatal("second generated version missing",err)};launcher,err:=os.ReadFile(filepath.Join(root,"target/generated-test-sources/refine/refine/generated/RefineGeneratedTests.java"));if err!=nil{t.Fatal(err)};for _,suite:=range []string{"foo.snapshot.ContractGeneratedProperties","foo.v0_1_0.ContractGeneratedProperties","foo.v0_1_1.ContractGeneratedProperties","bar.snapshot.ContractGeneratedProperties","bar.v0_1_0.ContractGeneratedProperties"}{if !strings.Contains(string(launcher),suite){t.Fatalf("aggregate launcher dropped %s: %s",suite,launcher)}}
}

func TestReleasePromotionRequiresSnapshotDependenciesInBatchAndIsCollisionSafe(t *testing.T){
    config:=`{"families":{"foo":{"root":"Foo","release":{"change":"feature","intended":"0.1.0"}},"bar":{"root":"Bar","release":{"change":"feature","intended":"0.1.0"}}}}`;files:=map[string]string{"schemata/foo/SNAPSHOT.refine":"type Foo = String\n","schemata/bar/SNAPSHOT.refine":"import \"../foo/SNAPSHOT.refine\"\ntype Bar = Foo\n"};root:=releaseFixture(t,files,config);var out,stderr bytes.Buffer
    if code:=releaseCommand([]string{"promote","--root",root,"bar"},&out,&stderr);code!=1||!strings.Contains(stderr.String(),"not included in the promotion batch"){t.Fatalf("partial dependency batch accepted: %d %s %s",code,&out,&stderr)}
    collision:=filepath.Join(root,"schemata/foo/v0.1.0.refine");if err:=os.WriteFile(collision,[]byte("mine"),0600);err!=nil{t.Fatal(err)};out.Reset();stderr.Reset();if code:=releaseCommand([]string{"promote","--root",root},&out,&stderr);code!=1{t.Fatal("immutable collision accepted")};data,_:=os.ReadFile(collision);if string(data)!="mine"{t.Fatal("collision was overwritten")};if _,err:=os.Stat(filepath.Join(root,"schemata/bar/v0.1.0.refine"));!os.IsNotExist(err){t.Fatal("batch partially promoted")}
}

func TestReleasePromotionRechecksDependencyAndConfigInputsUnderLock(t *testing.T){
    config:=`{"families":{"foo":{"root":"Foo","release":{"change":"feature","intended":"0.1.0"}},"bar":{"root":"Bar","release":{"change":"feature","intended":"0.1.0"}}}}`;files:=map[string]string{"schemata/foo/SNAPSHOT.refine":"type Foo = String\n","schemata/bar/SNAPSHOT.refine":"import \"../foo/SNAPSHOT.refine\"\ntype Bar = Foo\n"}
    for _,changed:=range []string{"dependency","config"}{root:=releaseFixture(t,files,config);workflow,err:=buildReleaseWorkflow(root,"refine.project.json",nil);if err!=nil{t.Fatal(err)};if changed=="dependency"{if err=os.WriteFile(filepath.Join(root,"schemata/foo/SNAPSHOT.refine"),[]byte("-- raced\ntype Foo = String\n"),0600);err!=nil{t.Fatal(err)}}else{if err=os.WriteFile(filepath.Join(root,"refine.project.json"),[]byte(config+"\n"),0600);err!=nil{t.Fatal(err)}};if _,err=promoteReleaseWorkflow(workflow);err==nil||!strings.Contains(err.Error(),"changed after planning"){t.Fatalf("%s race accepted: %v",changed,err)};for _,name:=range []string{"schemata/foo/v0.1.0.refine","schemata/bar/v0.1.0.refine",".refine-generated.json"}{if _,err=os.Stat(filepath.Join(root,name));!os.IsNotExist(err){t.Fatalf("%s race wrote %s",changed,name)}}}
}

func TestReleaseProspectiveNoCodegenVersionIsAllowedAndRemovesNoCurrentOutput(t *testing.T){
    config:=`{"families":{"foo":{"root":"Foo","noCodegen":["v0.1.0"],"release":{"change":"feature","intended":"0.1.0"}}}}`;root:=releaseFixture(t,map[string]string{"schemata/foo/SNAPSHOT.refine":"type Foo = String\n"},config);var out,stderr bytes.Buffer;if code:=releaseCommand([]string{"promote","--root",root,"--json"},&out,&stderr);code!=0{t.Fatalf("prospective no-codegen failed: %d %s %s",code,&out,&stderr)};if _,err:=os.Stat(filepath.Join(root,"target/generated-sources/refine/foo/v0_1_0/Foo.java"));!os.IsNotExist(err){t.Fatal("no-codegen version emitted Java")};if _,err:=os.Stat(filepath.Join(root,"target/generated-resources/refine/refine/foo/v0_1_0/contract.refine"));err!=nil{t.Fatal("no-codegen removed version resources",err)}
}

func TestReleaseNoCodegenRemovalRequiresAndAppliesMavenArtifactPlan(t *testing.T){
    files:=map[string]string{"schemata/foo/v1.0.0.refine":"type Foo = String\n","schemata/foo/SNAPSHOT.refine":"-- next docs\ntype Foo = String\n"};initial:=`{"families":{"foo":{"root":"Foo"}}}`;root:=releaseFixture(t,files,initial);var out,stderr bytes.Buffer;if code:=projectCommand([]string{"generate","--root",root},&out,&stderr);code!=0{t.Fatalf("initial generation: %d %s %s",code,&out,&stderr)};oldJava:=filepath.Join(root,"target/generated-sources/refine/foo/v1_0_0/Foo.java");if _,err:=os.Stat(oldJava);err!=nil{t.Fatal(err)}
    policy:=`{"families":{"foo":{"root":"Foo","noCodegen":["v1.0.0"],"release":{"change":"documentation","intended":"1.0.1"}}}}`;if err:=os.WriteFile(filepath.Join(root,"refine.project.json"),[]byte(policy),0600);err!=nil{t.Fatal(err)};workflow,err:=buildReleaseWorkflow(root,"refine.project.json",nil);if err!=nil{t.Fatal(err)};comparison:=workflow.reports[0].Comparisons[0];override:=`"overrides":[{"baseline":"1.0.0","baselineSha256":"`+comparison.BaselineSHA256+`","snapshotSha256":"`+comparison.SnapshotSHA256+`","direction":"backward","reason":"reviewed"}]`;policy=`{"release":{"maven":{"current":"1.0.0","intended":"1.1.0"}},"families":{"foo":{"root":"Foo","noCodegen":["v1.0.0"],"release":{"change":"documentation","intended":"1.0.1",`+override+`}}}}`;if err=os.WriteFile(filepath.Join(root,"refine.project.json"),[]byte(policy),0600);err!=nil{t.Fatal(err)};inventory:=generatedSourceInventory(t,root,"target/generated-sources/refine/foo/v1_0_0");writePublicationRecord(t,root,"foo","1.0.0",release.PublicationPublished,inventory);workflow,err=buildReleaseWorkflow(root,"refine.project.json",nil);if err!=nil{t.Fatal(err)};workflow.effectiveMaven=release.MavenCoordinates{GroupID:"dev.example",ArtifactID:"models",Version:"1.1.0"};if err=checkWorkflowPublication(&workflow,project.OwnedAddition{});err!=nil||workflow.maven==nil||!workflow.maven.Ready||workflow.maven.RequiredChange!=release.ArtifactFeatureChange{t.Fatalf("publication Maven removal plan: %v %+v",err,workflow.maven)};out.Reset();stderr.Reset();if code:=releaseCommand([]string{"promote","--root",root,"--json","--maven-group-id","dev.example","--maven-artifact-id","models","--maven-version","1.1.0"},&out,&stderr);code!=0{t.Fatalf("no-codegen promotion: %d %s %s",code,&out,&stderr)};if _,err=os.Stat(oldJava);!os.IsNotExist(err){t.Fatal("obsolete generated class was retained")};if _,err=os.Stat(filepath.Join(root,"target/generated-sources/refine/foo/v1_0_1/Foo.java"));err!=nil{t.Fatal("new generated version missing",err)}
}

func TestReleaseNativeBundlePlanningUsesExactBundleIdentity(t *testing.T){
    files:=map[string]string{"schemata/foo/v1.0.0.refined.json":nativeBundleFixture(t,"published.one"),"schemata/foo/SNAPSHOT.refined.json":nativeBundleFixture(t,"published.two")};config:=`{"families":{"foo":{"formats":["json-schema"],"release":{"change":"feature","intended":"1.1.0"}}}}`;root:=releaseFixture(t,files,config)
    workflow,err:=buildReleaseWorkflow(root,"refine.project.json",nil);if err!=nil{t.Fatal(err)};if len(workflow.reports)!=1||len(workflow.reports[0].Comparisons)!=2{t.Fatalf("native family was not compared in both directions: %+v",workflow.reports)};report:=workflow.reports[0];if report.Plan.Ready{t.Fatal("native wire/ABI unknown was silently accepted")};comparison:=report.Comparisons[0];if comparison.Native.Outcome!=analysis.Unknown||comparison.JavaABI.Outcome!=analysis.Unknown{t.Fatalf("native unknown dimensions not reported: %+v",comparison)}
    override:=`{"families":{"foo":{"formats":["json-schema"],"release":{"change":"feature","intended":"1.1.0","overrides":[{"baseline":"1.0.0","baselineSha256":"`+comparison.BaselineSHA256+`","snapshotSha256":"`+comparison.SnapshotSHA256+`","direction":"backward","reason":"native wire and Java ABI reviewed from the exact bundle"}]}}}}`;if err=os.WriteFile(filepath.Join(root,"refine.project.json"),[]byte(override),0600);err!=nil{t.Fatal(err)};workflow,err=buildReleaseWorkflow(root,"refine.project.json",nil);if err!=nil||!workflow.reports[0].Plan.Ready{t.Fatalf("exact native override rejected: %v %+v",err,workflow.reports[0].Plan)}
    snapshot:=filepath.Join(root,"schemata/foo/SNAPSHOT.refined.json");raw,err:=os.ReadFile(snapshot);if err!=nil{t.Fatal(err)};if err=os.WriteFile(snapshot,append(raw,'\n'),0600);err!=nil{t.Fatal(err)};changed,err:=buildReleaseWorkflow(root,"refine.project.json",nil);if err!=nil{t.Fatal(err)};if changed.reports[0].Plan.Ready||changed.reports[0].Comparisons[0].SnapshotSHA256==comparison.SnapshotSHA256{t.Fatal("an exact native bundle input change reused its override identity")}
}

func TestReleasePromotesNativeBundleVerbatimAndRechecksSnapshot(t *testing.T){
    snapshot:=nativeBundleFixture(t,"published.contracts");config:=`{"families":{"foo":{"formats":["json-schema"],"release":{"change":"feature","intended":"0.1.0"}}}}`;root:=releaseFixture(t,map[string]string{"schemata/foo/SNAPSHOT.refined.json":snapshot},config);workflow,err:=buildReleaseWorkflow(root,"refine.project.json",nil);if err!=nil{t.Fatal(err)};if !workflow.reports[0].Plan.Ready{t.Fatalf("initial native release not ready: %+v",workflow.reports[0].Plan)}
    raced:=snapshot+"\n";if err=os.WriteFile(filepath.Join(root,"schemata/foo/SNAPSHOT.refined.json"),[]byte(raced),0600);err!=nil{t.Fatal(err)};if _,err=promoteReleaseWorkflow(workflow);err==nil||!strings.Contains(err.Error(),"changed after planning"){t.Fatalf("native snapshot race accepted: %v",err)};if _,err=os.Stat(filepath.Join(root,"schemata/foo/v0.1.0.refined.json"));!os.IsNotExist(err){t.Fatal("failed native transaction wrote release")}
    if err=os.WriteFile(filepath.Join(root,"schemata/foo/SNAPSHOT.refined.json"),[]byte(snapshot),0600);err!=nil{t.Fatal(err)};var out,stderr bytes.Buffer;if code:=releaseCommand([]string{"promote","--root",root,"--json"},&out,&stderr);code!=0{t.Fatalf("native promotion %d: %s / %s",code,&out,&stderr)};released,err:=os.ReadFile(filepath.Join(root,"schemata/foo/v0.1.0.refined.json"));if err!=nil||string(released)!=snapshot{t.Fatalf("native bundle was rewritten: %v",err)};editable,err:=os.ReadFile(filepath.Join(root,"schemata/foo/SNAPSHOT.refined.json"));if err!=nil||string(editable)!=snapshot{t.Fatal("native snapshot changed")}
}

func TestReleaseNativeEmbeddedCatalogDependencyFailsClosed(t *testing.T){
    base,err:=native.IngestProject(native.JSONSchema,[]byte(`{"$id":"https://example.test/thing.json","title":"Thing","type":"string"}`),native.ProjectOptions{ResourceID:"https://example.test/thing.json",Root:native.ResourceSelector{TypeName:"Thing"}});if err!=nil{t.Fatal(err)};sources:=map[string]string{"schemata/native/main.refine":"import \"../dep/v1.0.0.refine\"\ntype Thing = Dep\n","schemata/dep/v1.0.0.refine":"type Dep = String\n"};edited,err:=base.WithEditedSources("schemata/native/main.refine",sources);if err!=nil{t.Fatal(err)};bundle,err:=edited.Bundle();if err!=nil{t.Fatal(err)}
    config:=`{"families":{"native":{"formats":["json-schema"],"release":{"change":"feature","intended":"0.1.0"}},"dep":{"root":"Dep"}}}`;root:=releaseFixture(t,map[string]string{"schemata/native/SNAPSHOT.refined.json":string(bundle),"schemata/dep/v1.0.0.refine":sources["schemata/dep/v1.0.0.refine"]},config);if _,err=buildReleaseWorkflow(root,"refine.project.json",[]string{"native"});err==nil||!strings.Contains(err.Error(),"exact semantic release pin cannot be proven"){t.Fatalf("opaque native dependency pin accepted: %v",err)}
}

func TestReleaseNativeAndRefineVersionCollisionIsRejected(t *testing.T){
    files:=map[string]string{"schemata/foo/SNAPSHOT.refined.json":nativeBundleFixture(t,"native.published"),"schemata/foo/SNAPSHOT.refine":"type Thing = String\n"};config:=`{"families":{"foo":{"formats":["json-schema"],"release":{"change":"feature","intended":"0.1.0"}}}}`;root:=releaseFixture(t,files,config);if _,err:=buildReleaseWorkflow(root,"refine.project.json",nil);err==nil||!strings.Contains(err.Error(),"defined by both"){t.Fatalf("release catalog accepted ambiguous extension: %v",err)}
}
