// Code generated by goplus from maven_integration_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package project_test

import (
	"bytes"
	"crypto/sha256"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"goforge.dev/refine/native"
	"goforge.dev/refine/project"
)

func TestMavenRegenerationAndReproducibleArtifact(t *testing.T) {
	mavenHome := os.Getenv("REFINE_MAVEN_HOME")
	if mavenHome == "" {
		if os.Getenv("REFINE_REQUIRE_MAVEN") == "1" {
			t.Fatal("REFINE_MAVEN_HOME is required")
		}
		t.Skip("set REFINE_MAVEN_HOME for the unsigned Maven integration gate")
	}
	maven := filepath.Join(mavenHome, "bin", "mvn")
	if _, err := os.Stat(maven); err != nil {
		t.Fatal(err)
	}
	root := t.TempDir()
	executable := filepath.Join(root, "refine")
	build := exec.Command("go", "build", "-o", executable, "./cmd/refine")
	build.Dir = ".."
	if output, err := build.CombinedOutput(); err != nil {
		t.Fatalf("CLI build: %v\n%s", err, output)
	}
	snippet := project.MavenSnippet(project.MavenOptions{CLIExecutable: executable})
	pom := `<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><groupId>example.test</groupId><artifactId>refine-fixture</artifactId><version>0.0.1</version>` + snippet + `</project>`
	if err := os.WriteFile(filepath.Join(root, "pom.xml"), []byte(pom), 0600); err != nil {
		t.Fatal(err)
	}
	schemaDir := filepath.Join(root, "schemata", "greeting")
	if err := os.MkdirAll(schemaDir, 0755); err != nil {
		t.Fatal(err)
	}
	schema := []byte("package example.test\ntype Greeting = {text :: String where length it > 0}\n")
	for _, version := range []string{"v1.0.0", "SNAPSHOT"} {
		if err := os.WriteFile(filepath.Join(schemaDir, version+".refine"), schema, 0600); err != nil {
			t.Fatal(err)
		}
	}
	// One native bundle exercises the independent native oracle and candidate
	// filter in the same four lifecycle builds, not a second Maven campaign.
	nativeProject, err := native.IngestProject(native.JSONSchema, []byte(`{"type":"integer","multipleOf":3}`), native.ProjectOptions{Root: native.ResourceSelector{TypeName: "Multiple"}})
	if err != nil {
		t.Fatal(err)
	}
	nativeProject, err = nativeProject.WithMetadata(native.WireMetadata{PublicationNamespace: "example.test"})
	if err != nil {
		t.Fatal(err)
	}
	nativeBundle, err := nativeProject.Bundle()
	if err != nil {
		t.Fatal(err)
	}
	nativeDir := filepath.Join(root, "schemata", "multiple")
	if err = os.MkdirAll(nativeDir, 0755); err != nil {
		t.Fatal(err)
	}
	if err = os.WriteFile(filepath.Join(nativeDir, "SNAPSHOT.refined.json"), nativeBundle, 0600); err != nil {
		t.Fatal(err)
	}
	if err = os.WriteFile(filepath.Join(root, "refine.project.json"), []byte(`{"families":{"multiple":{"formats":["json-schema"]}}}`), 0600); err != nil {
		t.Fatal(err)
	}
	run := func() {
		t.Helper()
		command := exec.Command(maven, "--batch-mode", "--no-transfer-progress", "package")
		command.Dir = root
		command.Env = os.Environ()
		if javaHome := os.Getenv("REFINE_JAVA_HOME"); javaHome != "" {
			command.Env = append(command.Env, "JAVA_HOME="+javaHome)
		}
		if output, err := command.CombinedOutput(); err != nil {
			t.Fatalf("unsigned Maven build: %v\n%s", err, output)
		}
	}
	run()
	jar := filepath.Join(root, "target", "refine-fixture-0.0.1.jar")
	first, err := os.ReadFile(jar)
	if err != nil {
		t.Fatal(err)
	}
	run()
	second, err := os.ReadFile(jar)
	if err != nil {
		t.Fatal(err)
	}
	if sha256.Sum256(first) != sha256.Sum256(second) {
		t.Fatal("unchanged unsigned artifact is not reproducible")
	}
	generated := filepath.Join(root, "target", "generated-sources", "refine", "example", "test", "greeting", "snapshot", "Greeting.java")
	before, err := os.ReadFile(generated)
	if err != nil {
		t.Fatal(err)
	}
	changed := []byte("package example.test\ntype Greeting = {text :: String where length it > 0, label :: String}\n")
	if err := os.WriteFile(filepath.Join(schemaDir, "SNAPSHOT.refine"), changed, 0600); err != nil {
		t.Fatal(err)
	}
	run()
	after, err := os.ReadFile(generated)
	if err != nil || bytes.Equal(before, after) {
		t.Fatal("Maven did not automatically regenerate changed schema", err)
	}
	released, err := os.ReadFile(filepath.Join(schemaDir, "v1.0.0.refine"))
	if err != nil || !bytes.Equal(released, schema) {
		t.Fatal("build mutated released schema")
	}
	launcher, err := os.ReadFile(filepath.Join(root, "target", "generated-test-sources", "refine", "refine", "generated", "RefineGeneratedTests.java"))
	if err != nil || !strings.Contains(string(launcher), "greeting.v1_0_0.ContractGeneratedProperties.main") || !strings.Contains(string(launcher), "greeting.snapshot.ContractGeneratedProperties.main") {
		t.Fatal("all schema versions must execute generated properties", err)
	}
	impossible := []byte("package example.test\ntype Greeting = {text :: String where length it > 100}\n")
	if err := os.WriteFile(filepath.Join(schemaDir, "SNAPSHOT.refine"), impossible, 0600); err != nil {
		t.Fatal(err)
	}
	command := exec.Command(maven, "--batch-mode", "--no-transfer-progress", "package")
	command.Dir = root
	command.Env = os.Environ()
	if javaHome := os.Getenv("REFINE_JAVA_HOME"); javaHome != "" {
		command.Env = append(command.Env, "JAVA_HOME="+javaHome)
	}
	output, err := command.CombinedOutput()
	if err == nil || !strings.Contains(string(output), "property generation exhausted: valid Greeting") {
		t.Fatalf("Maven must run generated properties and fail on exhaustion: %v\n%s", err, output)
	}
}
