// Code generated by goplus from functions_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package java

import (
	"bytes"
	"context"
	"fmt"
	"goforge.dev/refine/language"
	"goforge.dev/refine/validation"
	"goforge.dev/refine/value"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

const functionContract = baseFunctionContract + inlineContract

const baseFunctionContract = `
id :: a -> a
id x = x
positive :: Int -> Bool
positive n = n > 0
add :: Int -> Int -> Int
add a b = a + b
sum :: [Int] -> Int
sum [] = 0
sum (x : xs) = x + sum xs
choose :: [Int] -> Int
choose [] = 0
choose [x, y] = x + y
choose _ = -1
unknown :: Int -> Bool
unknown _ = 1 / 0 > 0.0
loop :: Int -> Bool
loop n = loop n
grow :: a -> Bool
grow x = grow [x]
nested :: Int -> Bool
nested n = satisfiesAll [unknown, positive] n
reason :: Int -> String
reason n = if n < 0 then "negative" else "zero"
pick :: Int -> Int -> Bool
pick 0 _ = False
pick 1 _ = True
pick _ n = unknown n
ignore :: Real -> Bool
ignore _ = True
field :: { text :: String, number :: Int } -> Int
field r = r.number
show :: Int -> Bool
show n = positive n
doubleSmall :: Int8 -> Int8
doubleSmall n = n + n
data Tree a = Leaf a | Branch (Tree a) (Tree a)
total :: Tree Int -> Int
total (Leaf n) = n
total (Branch a b) = total a + total b
start :: Int
start = 1
type Direct = Int where positive it @message (reason it)
type Sum = Int where sum [it, 1, -1] == it
type Mapped = Int where map (add it) [1, 2] == [it + 1, it + 2]
type Filter = Int where filter positive [it, -1] == (if it > 0 then [it] else [])
type Fold = Int where foldl add it [1, 2] == it + 3
type Higher = Int where (id positive) it
type Partial = Int where (let f = add it in f 1 == it + 1)
type Choice = Int where choose [it, 1] == it + 1
type Constructors = Int where total (Branch (Leaf it) (Leaf 1)) == it + 1
type Patterns = Int where (case Just (NonNull it) of { Nothing -> False; Just Null -> False; Just (NonNull n) -> n >= 0 })
type Literals = Int where (case it of { -1 -> False; 0 -> True; _ -> positive it })
type CaseList = Int where (case [it, 1] of { [] -> False; [a, b] -> a + b == it + 1; _ -> False })
type All = Int where all positive [it, 1]
type Any = Int where any positive [it, 1]
type Nested = Int where satisfiesOneOf [nested, positive] it
type Exactly = Int where satisfiesOnlyOneOf [unknown, positive, positive] it
type AtLeast = Int where satisfiesAtLeastOneOf [unknown, positive] it
type Nontermination = Int where loop it
type SurvivesDepth = Int where satisfiesOneOf [loop, positive] it
type PolymorphicRecursion = Int where grow it
type PolyRecovery = Int where satisfiesOneOf [grow, positive] it
type Eager = Int where (let f = add (sum [it]) in f 1 == it + 1)
type Membership = Int where oneOf it [0, 1] && elem it [0, 1]
type Unique = Int where unique [it, 0]
type Reverse = Int where reverse [it, 0] == [0, it]
type TextLength = Int where length "😀" == 2 && length [it] == 1
type Whole = Int where isInteger (it / 1)
type Negation = Int where not (positive it)
type Constant = Int where start == 1
type Wrapped a = { item :: a } where length [id it.item] == 1
type Concrete = Wrapped (Maybe Int)
type RecordArgument = Int where field {number = it, text = "x"} == it
type EagerFailure = Int where ignore (it / 0)
type PartialConstructor = Int where (let wrap = Just in (case wrap it of { Nothing -> False; Just n -> n == it }))
type Annotated = Int where (let x :: Int = it in x >= 0)
type BuiltinShadow = Int where show it
type Small = Int8 where doubleSmall it >= it
type CombineAll = [Int] where satisfiesAll (map pick it) 0
type CombineAny = [Int] where satisfiesOneOf (map pick it) 0
type CombineExactly = [Int] where satisfiesOnlyOneOf (map pick it) 0
type CombineAtLeast = [Int] where satisfiesAtLeastOneOf (map pick it) 0
`

func TestGeneratedFunctionExecution(t *testing.T) {
	compiler, vm := javaTools(t)
	dependencies := jetCheckClasspath(t)
	program, err := language.Compile(functionContract)
	if err != nil {
		t.Fatal(err)
	}
	files, err := GenerateValidator(program, "example.functions", "Contract")
	if err != nil {
		t.Fatal(err)
	}
	root := t.TempDir()
	sources := []string{}
	for _, file := range files {
		target := filepath.Join(root, filepath.FromSlash(file.Path))
		if err := os.MkdirAll(filepath.Dir(target), 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(target, []byte(file.Source), 0644); err != nil {
			t.Fatal(err)
		}
		sources = append(sources, target)
	}
	harness := filepath.Join(root, "FunctionConformance.java")
	if err := os.WriteFile(harness, []byte(functionHarnessJava), 0644); err != nil {
		t.Fatal(err)
	}
	sources = append(sources, harness)
	classes := filepath.Join(root, "classes")
	args := append([]string{"--release", "25", "-encoding", "UTF-8", "-Xlint:all", "-Werror", "-cp", dependencies, "-d", classes}, sources...)
	if output, err := exec.Command(compiler, args...).CombinedOutput(); err != nil {
		t.Fatalf("javac: %v\n%s", err, output)
	}
	vectors := []vector{}
	add := func(name, n string, total, clause uint64) {
		data := testNumber(n)
		if name == "Concrete" {
			data = testRecord(value.DataField{Name: "item", Value: testVariant("Just", data)})
		}
		if name == "InlineEnvelope" {
			data = testRecord(value.DataField{Name: "item", Value: data}, value.DataField{Name: "marker", Value: testNumber("0")})
		}
		limits := validation.Limits{Total: total, Clause: clause}
		for _, bypass := range []bool{false, true} {
			report := program.ValidateData(name, data, limits)
			if bypass {
				report = program.ValidateDataWithoutRefinements(name, data, limits)
			}
			vectors = append(vectors, vector{fmt.Sprintf("%s\t%s\t%d\t%d\t%v", name, n, total, clause, bypass), reportLine(report)})
		}
	}
	names := []string{"Direct", "Sum", "Mapped", "Filter", "Fold", "Higher", "Partial", "Choice", "Constructors", "Patterns", "Literals", "CaseList", "All", "Any", "Nested", "Exactly", "AtLeast", "Nontermination", "SurvivesDepth", "PolymorphicRecursion", "PolyRecovery", "Eager", "Membership", "Unique", "Reverse", "TextLength", "Whole", "Negation", "Constant", "Concrete", "RecordArgument", "EagerFailure", "PartialConstructor", "Annotated", "BuiltinShadow"}
	names = append(names, inlineNames...)
	for _, name := range names {
		for _, n := range []string{"-1", "0", "1"} {
			for limit := uint64(1); limit < 180; limit++ {
				add(name, n, limit, 0)
				add(name, n, 0, limit)
			}
			add(name, n, 0, 0)
		}
	}
	for _, n := range []string{"-129", "-128", "-1", "0", "1", "127", "128"} {
		for limit := uint64(1); limit < 100; limit++ {
			add("Small", n, limit, 0)
			add("Small", n, 0, limit)
		}
		add("Small", n, 0, 0)
	}
	for _, name := range []string{"CombineAll", "CombineAny", "CombineExactly", "CombineAtLeast"} {
		for length := 0; length <= 4; length++ {
			count := 1
			for i := 0; i < length; i++ {
				count *= 3
			}
			for encoded := 0; encoded < count; encoded++ {
				digits := ""
				items := []value.Data{}
				n := encoded
				for i := 0; i < length; i++ {
					digit := n % 3
					n /= 3
					digits += fmt.Sprint(digit)
					items = append(items, testNumber(fmt.Sprint(digit)))
				}
				for _, limit := range []uint64{0, 30, 100, 300} {
					for _, limits := range []validation.Limits{{Total: limit}, {Clause: limit}} {
						report := program.ValidateData(name, value.List(items), limits)
						vectors = append(vectors, vector{fmt.Sprintf("%s\t%s\t%d\t%d\tfalse", name, digits, limits.Total, limits.Clause), reportLine(report)})
					}
				}
			}
		}
	}
	var input strings.Builder
	for _, v := range vectors {
		input.WriteString(v.input)
		input.WriteByte('\n')
	}
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()
	command := exec.CommandContext(ctx, vm, "-Xss256k", "-cp", classes+string(os.PathListSeparator)+dependencies, "FunctionConformance")
	command.Stdin = strings.NewReader(input.String())
	var stderr bytes.Buffer
	command.Stderr = &stderr
	output, err := command.Output()
	if err != nil {
		t.Fatalf("Java functions: %v\n%s", err, stderr.String())
	}
	lines := strings.Split(strings.TrimSuffix(string(output), "\n"), "\n")
	if len(lines) != len(vectors) {
		t.Fatalf("expected %d results, got %d", len(vectors), len(lines))
	}
	for i, v := range vectors {
		if lines[i] != v.expected {
			t.Fatalf("case %s\nJava %s\nGo   %s", v.input, lines[i], v.expected)
		}
	}
	t.Logf("%d full-report Go/Java function comparisons plus 3000 jetCheck cases passed", len(vectors))
}

const functionHarnessJava = `
import example.functions.*;
import java.util.List;
import java.util.HexFormat;
import java.nio.charset.StandardCharsets;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import org.jetbrains.jetCheck.Generator;
import org.jetbrains.jetCheck.PropertyChecker;
public final class FunctionConformance {
    static String hex(String text) { return HexFormat.of().formatHex(text.getBytes(StandardCharsets.UTF_8)); }
    public static void main(String[] args) throws Exception {
        var input = new BufferedReader(new InputStreamReader(System.in, StandardCharsets.UTF_8)); String line;
        while ((line = input.readLine()) != null) {
            String[] f = line.split("\t", -1); Data data;
            if (f[0].startsWith("Combine")) {
                var items = new java.util.ArrayList<Data>(); for (int i = 0; i < f[1].length(); i++) items.add(new Data.Number(Rational.of(f[1].charAt(i) - '0')));
                data = new Data.Sequence(items);
            } else data = new Data.Number(Rational.parse(f[1]));
            if (f[0].equals("Concrete")) data = new Data.Struct(List.of(new Data.Field("item", new Data.Variant("Just", List.of(data)))));
            if (f[0].equals("InlineEnvelope")) data = new Data.Struct(List.of(new Data.Field("item", data), new Data.Field("marker", new Data.Number(Rational.ZERO))));
            var limits = new Budget.Limits(Long.parseLong(f[2]), Long.parseLong(f[3]));
            var outcome = Boolean.parseBoolean(f[4]) ? Contract.validateStructure(f[0], data, limits) : Contract.validate(f[0], data, limits);
            var report = new StringBuilder(outcome.state().name().toLowerCase(java.util.Locale.ROOT)).append('|').append(outcome.incomplete());
            for (var d : outcome.diagnostics()) report.append('|').append(hex(d.code())).append(',').append(hex(String.join(";", d.paths()))).append(',').append(hex(d.predicate())).append(',').append(hex(d.message()));
            System.out.println(report);
        }
        PropertyChecker.customized().withIterationCount(3000).forAll(Generator.integers(), n -> {
            Data value = new Data.Number(Rational.of(n));
            if (Contract.validate("Sum", value).state() != Validation.State.VALID) throw new AssertionError("recursive sum");
            var expected = n > 0 ? Validation.State.VALID : Validation.State.INVALID;
            if (Contract.validate("Higher", value).state() != expected || Contract.validate("Nested", value).state() != expected) throw new AssertionError("higher-order/unknown composition");
            var asserted = n > 0 ? Validation.State.VALID : Validation.State.INDETERMINATE;
            for (String root : List.of("InlineLocal", "InlinePre", "InlinePost", "InlinePartial", "InlineHigherPre", "InlineHigherPost", "InlineReturned", "InlineLocalFunction", "InlineNestedGuards", "InlineList", "InlineRecord", "InlineMaybe", "InlineNullable", "InlineOk", "InlineErr", "InlineParcel", "InlineMessage", "InlineBadMessage")) {
                if (Contract.validate(root, value).state() != asserted) throw new AssertionError("lost inline contract: " + root);
                if (Contract.validateStructure(root, value, Budget.Limits.defaults()).state() != Validation.State.VALID) throw new AssertionError("inline bypass: " + root);
            }
            for (String root : List.of("InlineAllRules", "InlineRulesReversed")) {
                var outcome = Contract.validate(root, value);
                String failure = n > 0 ? "evaluation.refinement_unknown:" : "evaluation.refinement:";
                if (outcome.state() != Validation.State.INDETERMINATE || !outcome.diagnostics().getFirst().message().contains(failure)) throw new AssertionError("inline rule aggregation: " + root);
            }
            return true;
        });
    }
}
`
