// Code generated by goplus from model_unions.gp. DO NOT EDIT.
//goplus:v v0.28.0

package java

import (
	"fmt"
	"strings"

	"goforge.dev/refine/language"
)

func (m *modelEmitter) unionNames(root string) map[string]string {
	if names, ok := m.alternatives[root]; ok {
		return names
	}
	names := map[string]string{}
	used := map[string]bool{}
	for name := range m.declarations {
		used[sourceNameKey(name)] = true
	}
	used[sourceNameKey(m.contract)] = true
	for _, name := range []string{"Draft", "ModelSupport", "ModelMaybe", "ModelNullable", "ModelResult", "Evidence", m.modelFactoryName()} {
		used[sourceNameKey(name)] = true
	}
	used[sourceNameKey(m.modelDraftName())] = true
	view := "Variant"
	for used[sourceNameKey(view)] {
		view += "_"
	}
	used[sourceNameKey(view)] = true
	m.unionViews[root] = view
	for _, variant := range m.declarations[root].Variants {
		name := fieldIdentifier(variant.Name)
		for used[sourceNameKey(name)] || javaClassName(name) != nil {
			name += "_"
		}
		used[sourceNameKey(name)] = true
		names[variant.Name] = name
		for _, arg := range variant.Arguments {
			m.javaType(arg)
		}
	}
	m.alternatives[root] = names
	return names
}

func (m *modelEmitter) unionModel(decl language.TypeDecl) string {
	name, parent, root := decl.Name, m.parents[decl.Name], decl.Name
	for m.parents[root] != "" {
		root = m.parents[root]
	}
	variants := m.declarations[root].Variants
	names := m.unionNames(root)
	view := m.unionViews[root]
	permits := []string{}
	if parent == "" {
		permits = append(permits, name+"."+view)
	} else {
		for _, variant := range variants {
			permits = append(permits, name+"."+names[variant.Name])
		}
	}
	permits = append(permits, m.children[name]...)
	inheritance := ""
	if parent != "" {
		inheritance = " extends " + m.qualified(parent)
	}
	var out strings.Builder
	fmt.Fprintf(&out, "public sealed interface %s%s permits %s {\n", name, inheritance, strings.Join(permits, ", "))
	if parent == "" {
		cases := []string{}
		for _, variant := range variants {
			cases = append(cases, name+"."+names[variant.Name])
		}
		fmt.Fprintf(&out, "    sealed interface %s extends %s permits %s {}\n    %s variant();\n", view, name, strings.Join(cases, ", "), view)
		out.WriteString("    Data rawData();\n    Validation.Outcome validate();\n    Validation.Outcome validate(Budget.Limits caller);\n")
		out.WriteString("    default String showWithoutValidation() { return showWithoutValidation(Budget.Limits.defaults()); }\n")
		fmt.Fprintf(&out, "    default String showWithoutValidation(Budget.Limits caller) { return %s.showWithoutValidation(rawData(),caller); }\n", m.contract)
	}
	fmt.Fprintf(&out, "    private static %s fromEvidence(ModelSupport.Evidence evidence) {\n        var raw = (Data.Variant)evidence.dataFor(%s);\n        %s result;\n", name, javaQuote(name), name)
	for i := 0; i < len(variants); i += 64 {
		fmt.Fprintf(&out, "        if ((result = alternative%d(evidence,raw.name())) != null) return result;\n", i/64)
	}
	out.WriteString("        throw new AssertionError(\"unknown validated constructor\");\n    }\n")
	for start := 0; start < len(variants); start += 64 {
		fmt.Fprintf(&out, "    private static %s alternative%d(ModelSupport.Evidence evidence, String constructor) {\n        return switch (constructor) {\n", name, start/64)
		for _, variant := range variants[start:min(start+64, len(variants))] {
			fmt.Fprintf(&out, "            case %s -> new %s.%s(evidence);\n", javaQuote(variant.Name), name, names[variant.Name])
		}
		out.WriteString("            default -> null;\n        };\n    }\n")
	}
	for _, bypass := range []bool{false, true} {
		suffix, method := "", "validate"
		if bypass {
			suffix, method = "WithoutValidation", "withoutValidation"
		}
		fmt.Fprintf(&out, "    static %s fromData%s(Data raw) { return fromData%s(raw,Budget.Limits.defaults()); }\n", name, suffix, suffix)
		fmt.Fprintf(&out, "    static %s fromData%s(Data raw, Budget.Limits caller) { return fromEvidence(ModelSupport.%s(%s,ModelSupport.nonNull(raw,\"\"),caller)); }\n", name, suffix, method, javaQuote(name))
	}
	fmt.Fprintf(&out, "    static %s read(String text) { return read(text,Budget.Limits.defaults()); }\n    static %s read(String text, Budget.Limits caller) { return fromEvidence(ModelSupport.read(%s,text,caller)); }\n", name, name, javaQuote(name))
	out.WriteString("    static Validation.Outcome validateData(Data raw) { return validateData(raw,Budget.Limits.defaults()); }\n")
	fmt.Fprintf(&out, "    static Validation.Outcome validateData(Data raw, Budget.Limits caller) { return %s.validate(%s,raw,caller); }\n", m.contract, javaQuote(name))
	for _, variant := range variants {
		out.WriteString(m.unionAlternative(name, parent, root, variant, names[variant.Name]))
	}
	out.WriteString("}\n")
	return out.String()
}

func (m *modelEmitter) unionAlternative(owner, parent, root string, variant language.Variant, name string) string {
	full := owner + "." + name
	mod := "final"
	permits := ""
	if len(m.children[owner]) > 0 {
		mod = "sealed"
		children := []string{}
		for _, child := range m.children[owner] {
			children = append(children, child+"."+name)
		}
		permits = " permits " + strings.Join(children, ", ")
	}
	inheritance := ""
	if parent != "" {
		inheritance = " extends " + m.qualified(parent) + "." + name
	}
	implemented := m.qualified(owner)
	if parent == "" {
		implemented += "." + m.unionViews[root]
	}
	var out strings.Builder
	fmt.Fprintf(&out, "    public static %s class %s%s implements %s%s {\n", mod, name, inheritance, implemented, permits)
	if parent == "" {
		out.WriteString("        private final Data raw;\n")
	}
	fmt.Fprintf(&out, "        protected %s(ModelSupport.Evidence evidence) {\n", name)
	if parent != "" {
		fmt.Fprintf(&out, "            super(evidence);\n            evidence.dataFor(%s);\n", javaQuote(owner))
	} else {
		fmt.Fprintf(&out, "            this.raw = ModelSupport.alternative(evidence.dataFor(%s),%s,%d);\n", javaQuote(owner), javaQuote(variant.Name), len(variant.Arguments))
	}
	out.WriteString("        }\n")
	parameters, arguments, values := []string{}, []string{}, []string{}
	for i, arg := range variant.Arguments {
		field := "value"
		if len(variant.Arguments) > 1 {
			field = fmt.Sprintf("value%d", i+1)
		}
		parameters = append(parameters, m.javaType(arg)+" "+field)
		arguments = append(arguments, field)
		values = append(values, m.encode(arg, field, javaQuote(fmt.Sprintf("/%d", i))))
	}
	raw := "new Data.Variant(" + javaQuote(variant.Name) + "," + javaList(values) + ")"
	withCaller := append(append([]string(nil), parameters...), "Budget.Limits caller")
	withDefault := append(append([]string(nil), arguments...), "Budget.Limits.defaults()")
	// The JVM limits method parameters to 255 slots, including this. Wide
	// constructors use the same typed draft API instead of invalid bytecode.
	if len(variant.Arguments) <= 253 {
		fmt.Fprintf(&out, "        public %s(%s) { this(%s); }\n", name, strings.Join(parameters, ", "), strings.Join(withDefault, ", "))
		fmt.Fprintf(&out, "        public %s(%s) { this(ModelSupport.validate(%s,%s,caller)); }\n", name, strings.Join(withCaller, ", "), javaQuote(owner), raw)
		fmt.Fprintf(&out, "        public static %s createWithoutValidation(%s) { return createWithoutValidation(%s); }\n", full, strings.Join(parameters, ", "), strings.Join(withDefault, ", "))
		fmt.Fprintf(&out, "        public static %s createWithoutValidation(%s) { return new %s(ModelSupport.withoutValidation(%s,%s,caller)); }\n", full, strings.Join(withCaller, ", "), full, javaQuote(owner), raw)
	}
	checked := "ModelSupport.alternative(ModelSupport.nonNull(raw,\"\")," + javaQuote(variant.Name) + "," + fmt.Sprint(len(variant.Arguments)) + ")"
	for _, bypass := range []bool{false, true} {
		suffix, method := "", "validate"
		if bypass {
			suffix, method = "WithoutValidation", "withoutValidation"
		}
		fmt.Fprintf(&out, "        public static %s fromData%s(Data raw) { return fromData%s(raw,Budget.Limits.defaults()); }\n", full, suffix, suffix)
		fmt.Fprintf(&out, "        public static %s fromData%s(Data raw, Budget.Limits caller) { return new %s(ModelSupport.%s(%s,%s,caller)); }\n", full, suffix, full, method, javaQuote(owner), checked)
	}
	fmt.Fprintf(&out, "        public static %s read(String text) { return read(text,Budget.Limits.defaults()); }\n        public static %s read(String text, Budget.Limits caller) { return new %s(ModelSupport.read(%s,text,caller)); }\n", full, full, full, javaQuote(owner))
	out.WriteString("        public static Validation.Outcome validateData(Data raw) { return validateData(raw,Budget.Limits.defaults()); }\n")
	fmt.Fprintf(&out, "        public static Validation.Outcome validateData(Data raw, Budget.Limits caller) { var shape = ModelSupport.alternativeShape(raw,%s,%d); return shape.state() == Validation.State.VALID ? %s.validate(%s,raw,caller) : shape; }\n", javaQuote(variant.Name), len(variant.Arguments), m.contract, javaQuote(owner))
	fmt.Fprintf(&out, "        public Validation.Outcome validate() { return validate(Budget.Limits.defaults()); }\n        public Validation.Outcome validate(Budget.Limits caller) { return %s.validate(%s,rawData(),caller); }\n", m.contract, javaQuote(owner))
	if parent == "" {
		out.WriteString("        public final Data rawData() { return raw; }\n")
		fmt.Fprintf(&out, "        public final %s.%s variant() { return this; }\n", m.qualified(root), m.unionViews[root])
		for i, arg := range variant.Arguments {
			fmt.Fprintf(&out, "        public final %s %s() { return %s; }\n", m.javaType(arg), arguments[i], m.decode(arg, fmt.Sprintf("ModelSupport.argument(rawData(),%d)", i)))
		}
	}
	draftName := m.modelDraftName()
	draftType := root + "." + name + "." + draftName
	for _, bypass := range []bool{false, true} {
		suffix := ""
		if bypass {
			suffix = "WithoutValidation"
		}
		fmt.Fprintf(&out, "        public static %s create%s(java.util.function.Consumer<%s> initialize) { return create%s(initialize,Budget.Limits.defaults()); }\n", full, suffix, draftType, suffix)
		fmt.Fprintf(&out, "        public static %s create%s(java.util.function.Consumer<%s> initialize, Budget.Limits caller) { %s draft = newDraft(); initialize.accept(draft); return fromData%s(draft.freeze(),caller); }\n", full, suffix, draftType, draftType, suffix)
		fmt.Fprintf(&out, "        public %s update%s(java.util.function.Consumer<%s> change) { return update%s(change,Budget.Limits.defaults()); }\n", full, suffix, draftType, suffix)
		fmt.Fprintf(&out, "        public %s update%s(java.util.function.Consumer<%s> change, Budget.Limits caller) { %s draft = draft(); change.accept(draft); return fromData%s(draft.freeze(),caller); }\n", full, suffix, draftType, draftType, suffix)
	}
	if parent == "" {
		fmt.Fprintf(&out, "        protected final %s draft() { return new %s(this); }\n        protected static %s newDraft() { return new %s(); }\n        public static final class %s {\n            private final Data raw;\n            private %s() { this.raw = null; }\n            private %s(%s source) { this.raw = source.rawData(); }\n", draftName, draftName, draftName, draftName, draftName, draftName, draftName, full)
		for i, arg := range variant.Arguments {
			fmt.Fprintf(&out, "            private %s %s;\n            private boolean changed%d;\n", m.javaType(arg), arguments[i], i)
		}
		for i, arg := range variant.Arguments {
			fmt.Fprintf(&out, "            public void set%s(%s value) { this.%s = value; changed%d = true; }\n", upperFirst(arguments[i]), m.javaType(arg), arguments[i], i)
		}
		out.WriteString("            Data freeze() {\n                var changes = new java.util.LinkedHashMap<Integer, Data>();\n")
		for i := 0; i < len(variant.Arguments); i += 64 {
			fmt.Fprintf(&out, "                arguments%d(changes);\n", i/64)
		}
		fmt.Fprintf(&out, "                return raw == null ? ModelSupport.constructVariant(%s,%d,changes) : ModelSupport.applyArgumentChanges(raw,changes);\n            }\n", javaQuote(variant.Name), len(variant.Arguments))
		for start := 0; start < len(variant.Arguments); start += 64 {
			fmt.Fprintf(&out, "            private void arguments%d(java.util.Map<Integer,Data> changes) {\n", start/64)
			for i := start; i < min(start+64, len(variant.Arguments)); i++ {
				arg := variant.Arguments[i]
				fmt.Fprintf(&out, "                if (changed%d) changes.put(%d,%s);\n", i, i, m.encode(arg, "this."+arguments[i], javaQuote(fmt.Sprintf("/%d", i))))
			}
			out.WriteString("            }\n")
		}
		out.WriteString("        }\n")
	}
	out.WriteString("    }\n")
	return out.String()
}
