// Code generated by goplus from native_validation_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package java

import (
	"crypto/sha256"
	"encoding/hex"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"goforge.dev/refine/native"
)

func networkntClasspath(t *testing.T) string {
	t.Helper()
	dir := os.Getenv("REFINE_NETWORKNT_DIR")
	if dir == "" {
		if os.Getenv("REFINE_REQUIRE_JAVA") == "1" {
			t.Fatal("REFINE_NETWORKNT_DIR is required by the Java release gate")
		}
		t.Skip("set REFINE_NETWORKNT_DIR to pinned networknt/Jackson 3 test jars")
	}
	jars := []struct{ name, sum string }{
		{"json-schema-validator-3.0.7.jar", "27b90bce60845f353b203b735cda2e0cb9a32c4962550e249141a2b065b9be5c"}, {"jackson-databind-3.2.1.jar", "8d005c5626b1839e2eea6bd33a437287e7a24d54e1bb3746b8f861193262b519"}, {"jackson-core-3.2.1.jar", "2688aaa60b207403287e16a71fb5644bf2f9cfc464cc601ae95c6c86a5af1f94"}, {"jackson-annotations-2.22.jar", "21ddb598807d3a51a876704eb979d9296e1c6a6f47ab1826ff88c6d6a127a2d0"}, {"jackson-dataformat-yaml-3.2.1.jar", "b6a748ca9aab640f647079b6bfa53f16a5b65b815a19581c4afe0601e754854e"}, {"itu-1.14.0.jar", "5cf40ab0cc77828ab2b875b1f3ecd71c8295d7721933476abc2e08fddcea164a"}, {"slf4j-api-2.0.17.jar", "7b751d952061954d5abfed7181c1f645d336091b679891591d63329c622eb832"},
	}
	parts := []string{}
	for _, jar := range jars {
		item := filepath.Join(dir, jar.name)
		data, err := os.ReadFile(item)
		if err != nil {
			t.Fatalf("networknt test dependency: %v", err)
		}
		sum := sha256.Sum256(data)
		if hex.EncodeToString(sum[:]) != jar.sum {
			t.Fatalf("networknt test dependency %s has an unexpected SHA-256", jar.name)
		}
		parts = append(parts, item)
	}
	return strings.Join(parts, string(os.PathListSeparator))
}

func TestProjectJSONSerdeIncludesNativeRegexComposition(t *testing.T) {
	schema := `{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"string","pattern":"^[a-z]+$"}`
	project, err := native.IngestProject(native.JSONSchema, []byte(schema), native.ProjectOptions{Root: native.ResourceSelector{TypeName: "Value"}})
	if err != nil {
		t.Fatal(err)
	}
	files, err := GenerateProjectJSONSerde(project, "Contract", "Module")
	if err != nil {
		t.Fatal(err)
	}
	found := false
	for _, file := range files {
		if strings.Contains(file.Source, "regularExpressionFactory(new BoundedRegexFactory())") {
			found = true
		}
	}
	if !found {
		t.Fatal("project JSON serde omitted its native ECMA-262 adapter")
	}
}

func TestJSONSerdeOptionsFromMetadataIsCopiedAndFailClosed(t *testing.T) {
	metadata := native.WireMetadata{ExtraFields: map[string]native.ExtraFieldMode{"Root": native.PreserveExtraFields}, Scalars: map[string]native.ScalarEncoding{"Root": {Kind: native.DecimalString}}, Discriminators: map[string]native.Discriminator{"Choice": {Field: "kind", Values: map[string]string{"A": "a"}, Arguments: map[string][]string{"A": {"value"}}}}}
	options, err := JSONSerdeOptionsFromMetadata("Root", metadata)
	if err != nil {
		t.Fatal(err)
	}
	if !options.PreserveExtraFields || !options.PreserveExtraFieldsFor["Root"] || options.Integers != JSONIntegerString || options.Discriminators["Choice"].Arguments["A"][0] != "value" {
		t.Fatalf("metadata conversion lost policy: %+v", options)
	}
	metadata.Discriminators["Choice"].Arguments["A"][0] = "changed"
	if options.Discriminators["Choice"].Arguments["A"][0] != "value" {
		t.Fatal("metadata conversion retained mutable input")
	}
	nested, err := JSONSerdeOptionsFromMetadata("Root", native.WireMetadata{Scalars: map[string]native.ScalarEncoding{"Nested": {Kind: native.DecimalString}}})
	if err != nil || nested.Scalars["Nested"].Kind != native.DecimalString {
		t.Fatalf("nested scalar policy lost: %v", err)
	}
	metadata.Scalars["Root"] = native.ScalarEncoding{Kind: native.JSONNumber}
	if options.Scalars["Root"].Kind != native.DecimalString {
		t.Fatal("scalar metadata retained mutable input")
	}
	if _, err := JSONSerdeOptionsFromMetadata("Root", native.WireMetadata{Scalars: map[string]native.ScalarEncoding{"Root": {Kind: native.AvroBytesDecimal}}}); err == nil {
		t.Fatal("Avro-only scalar accepted by JSON adapter")
	}
}

func TestNativeJSONGeneratorHandlesPatternsAndGatesUnsupportedFormats(t *testing.T) {
	pattern := `{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"string","pattern":"^[a-z]+$"}`
	project, err := native.IngestProject(native.JSONSchema, []byte(pattern), native.ProjectOptions{})
	if err != nil {
		t.Fatal(err)
	}
	files, err := GenerateProjectNativeJSONValidator(project, "NativeCheck")
	if err != nil || len(files) != 1 || !strings.Contains(files[0].Source, "BoundedRegexFactory") {
		t.Fatalf("bounded pattern adapter was not generated: %v", err)
	}
	innocent := `{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"pattern":{"type":"string"},"patternProperties":{"type":"string"}},"examples":[{"pattern":"not a keyword","patternProperties":{"also":"data"}}]}`
	project, err = native.IngestProject(native.JSONSchema, []byte(innocent), native.ProjectOptions{})
	if err != nil {
		t.Fatal(err)
	}
	if files, err = GenerateProjectNativeJSONValidator(project, "NativeCheck"); err != nil || len(files) != 1 {
		t.Fatalf("schema-irrelevant keyword lookalikes were gated: %v", err)
	}
	avro, err := native.IngestProject(native.Avro, []byte(`"string"`), native.ProjectOptions{})
	if err != nil {
		t.Fatal(err)
	}
	if files, err = GenerateProjectNativeJSONValidator(avro, "NativeCheck"); err == nil || files != nil {
		t.Fatal("Avro emitted a JSON Schema validator")
	}
}

func TestNativeJSONGeneratorUsesOpenAPI30ExactAdapter(t *testing.T) {
	source := "openapi: 3.0.4\ninfo: {title: Old, version: '1'}\npaths: {}\ncomponents:\n  schemas:\n    Value: {type: number, minimum: 90071992547409931234567890, exclusiveMinimum: true, nullable: true}\n"
	project, err := native.IngestProject(native.OpenAPI, []byte(source), native.ProjectOptions{Root: native.ResourceSelector{Pointer: "/components/schemas/Value", TypeName: "Value"}})
	if err != nil {
		t.Fatal(err)
	}
	files, err := GenerateProjectNativeJSONValidator(project, "NativeCheck")
	if err != nil || len(files) != 1 {
		t.Fatalf("OAS 3.0 adapter was not generated: %v", err)
	}
	generated := files[0].Source
	if strings.Contains(generated, `\"nullable\"`) || !strings.Contains(generated, `\"exclusiveMinimum\":90071992547409931234567890`) {
		t.Fatal("generated helper did not embed exact adapted OAS 3.0 schema")
	}
}

func TestGeneratedNativeJSONValidatorExactOfflineAndBounded(t *testing.T) {
	compiler, vm := javaTools(t)
	classpath := networkntClasspath(t)
	resources := []native.Resource{
		{URI: "https://example.test/root.json", Source: `{"$schema":"https://json-schema.org/draft/2020-12/schema","$ref":"classpath:/shadow.json"}`},
		{URI: "classpath:/shadow.json", Source: `{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"integer","multipleOf":3,"maximum":100000000000000000000000000000000000000000000000000}`},
	}
	project, err := native.IngestProjectResources(native.JSONSchema, resources, native.ProjectOptions{Root: native.ResourceSelector{Resource: "https://example.test/root.json", TypeName: "Root"}, Metadata: native.WireMetadata{PublicationNamespace: "example.nativecheck"}})
	if err != nil {
		t.Fatal(err)
	}
	files, err := GenerateProjectNativeJSONValidator(project, "NativeCheck")
	if err != nil {
		t.Fatal(err)
	}
	unicodeProject, err := native.IngestProject(native.JSONSchema, []byte(`{"type":"object","additionalProperties":true}`), native.ProjectOptions{Root: native.ResourceSelector{TypeName: "UnicodeRoot"}, Metadata: native.WireMetadata{PublicationNamespace: "example.nativecheck"}})
	if err != nil {
		t.Fatal(err)
	}
	unicodeFiles, err := GenerateProjectNativeJSONValidator(unicodeProject, "UnicodeCheck")
	if err != nil {
		t.Fatal(err)
	}
	files = append(files, unicodeFiles...)
	dir := t.TempDir()
	sources := []string{}
	for _, file := range files {
		target := filepath.Join(dir, filepath.FromSlash(file.Path))
		if err := os.MkdirAll(filepath.Dir(target), 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(target, []byte(file.Source), 0644); err != nil {
			t.Fatal(err)
		}
		sources = append(sources, target)
	}
	harness := filepath.Join(dir, "NativeHarness.java")
	if err := os.WriteFile(harness, []byte(nativeValidationHarnessJava), 0644); err != nil {
		t.Fatal(err)
	}
	sources = append(sources, harness)
	classes := filepath.Join(dir, "classes")
	args := append([]string{"--release", "25", "-encoding", "UTF-8", "-Xlint:all", "-Werror", "-cp", classpath, "-d", classes}, sources...)
	if output, err := exec.Command(compiler, args...).CombinedOutput(); err != nil {
		t.Fatalf("native validator javac: %v\n%s", err, output)
	}
	shadow := filepath.Join(classes, "shadow.json")
	if err := os.WriteFile(shadow, []byte(`{"type":"string"}`), 0644); err != nil {
		t.Fatal(err)
	}
	if output, err := exec.Command(vm, "-cp", classes+string(os.PathListSeparator)+classpath, "NativeHarness").CombinedOutput(); err != nil {
		t.Fatalf("native validator runtime: %v\n%s", err, output)
	}
}

func TestGeneratedProjectJSONSerdeComposesNativeAndRefinements(t *testing.T) {
	compiler, vm := javaTools(t)
	classpath := networkntClasspath(t)
	schema := `{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"integer","multipleOf":3}`
	project, err := native.IngestProject(native.JSONSchema, []byte(schema), native.ProjectOptions{Root: native.ResourceSelector{TypeName: "Value"}})
	if err != nil {
		t.Fatal(err)
	}
	editedSource := strings.Replace(project.EditableSource(), "type Value = Int", "type Value = Int where it > 0 @code \"value.positive\"", 1)
	project, err = project.WithEditedSource(editedSource)
	if err != nil {
		t.Fatal(err)
	}
	project, err = project.WithMetadata(native.WireMetadata{PublicationNamespace: "example.composed"})
	if err != nil {
		t.Fatal(err)
	}
	files, err := GenerateProjectJSONSerde(project, "Contract", "ValueModule")
	if err != nil {
		t.Fatal(err)
	}
	dir := t.TempDir()
	sources := []string{}
	for _, file := range files {
		target := filepath.Join(dir, filepath.FromSlash(file.Path))
		if err := os.MkdirAll(filepath.Dir(target), 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(target, []byte(file.Source), 0644); err != nil {
			t.Fatal(err)
		}
		sources = append(sources, target)
	}
	harness := filepath.Join(dir, "ComposedHarness.java")
	if err := os.WriteFile(harness, []byte(composedValidationHarnessJava), 0644); err != nil {
		t.Fatal(err)
	}
	sources = append(sources, harness)
	classes := filepath.Join(dir, "classes")
	args := append([]string{"--release", "25", "-encoding", "UTF-8", "-Xlint:all", "-Werror", "-cp", classpath, "-d", classes}, sources...)
	if output, err := exec.Command(compiler, args...).CombinedOutput(); err != nil {
		t.Fatalf("composed serde javac: %v\n%s", err, output)
	}
	if output, err := exec.Command(vm, "-cp", classes+string(os.PathListSeparator)+classpath, "ComposedHarness").CombinedOutput(); err != nil {
		t.Fatalf("composed serde runtime: %v\n%s", err, output)
	}
}

const nativeValidationHarnessJava = `
import example.nativecheck.*;
public final class NativeHarness {
 static void invalid(Runnable action){try{action.run();throw new AssertionError("accepted");}catch(NativeCheck.NativeValidationException expected){if(expected.getCause()!=null||expected.isResourceLimit()||expected.isIndeterminate()||expected.code()!=NativeCheck.Code.INVALID)throw new AssertionError("invalid classification");}}
 static void unicode(Runnable action){try{action.run();throw new AssertionError("accepted");}catch(UnicodeCheck.NativeValidationException expected){if(expected.getCause()!=null||expected.isIndeterminate())throw new AssertionError("escaped unpaired Unicode classification");}}
 static void resource(Runnable action){try{action.run();throw new AssertionError("accepted");}catch(NativeCheck.NativeValidationException expected){if(expected.getCause()!=null||!expected.isResourceLimit()||!expected.isIndeterminate()||expected.code()!=NativeCheck.Code.RESOURCE_LIMIT)throw new AssertionError("resource classification");}}
 public static void main(String[] args){var check=new NativeCheck();check.validate("99999999999999999999999999999999999999999999999999");invalid(()->check.validate("99999999999999999999999999999999999999999999999998"));invalid(()->check.validate("{\"n\":3,\"n\":3}"));invalid(()->check.validate("3 null"));invalid(()->check.validate("-".repeat(70000)));invalid(()->check.validate("1e+"));resource(()->check.validate("1e1000000000"));invalid(()->check.validate("\ud800"));var unicode=new UnicodeCheck();unicode(()->unicode.validate("{\"\\ud800\":3}"));unicode(()->unicode.validate("{\"value\":\"\\ud800\"}"));var tiny=new NativeCheck(new NativeCheck.Limits(100,2,10,10,10,10,8));resource(()->tiny.validate("[[[0]]]"));resource(()->tiny.validate("[1e2,1e2]"));try{new NativeCheck(new NativeCheck.Limits((1<<20)+1,128,10000,10000,1<<20,10000,65536));throw new AssertionError("relaxed hard limit accepted");}catch(IllegalArgumentException expected){}try{new NativeCheck(new NativeCheck.Limits(1<<20,128,10000,10000,1<<20,10000,65537));throw new AssertionError("relaxed generated numeric limit accepted");}catch(IllegalArgumentException expected){}}
}
`

const composedValidationHarnessJava = `
import example.composed.*;
public final class ComposedHarness {
 static void reject(Runnable action){try{action.run();throw new AssertionError("accepted");}catch(RuntimeException expected){}}
 public static void main(String[] args)throws Exception{var mapper=tools.jackson.databind.json.JsonMapper.builder().addModule(new ValueModule()).build();for(String raw:java.util.List.of("6","6.0","6e0"))if(!mapper.readValue(raw,Value.class).value().equals(java.math.BigInteger.valueOf(6)))throw new AssertionError(raw);reject(()->{try{mapper.readValue("6.5",Value.class);}catch(tools.jackson.core.JacksonException failure){throw new RuntimeException(failure);}});reject(()->{try{mapper.readValue("4",Value.class);}catch(tools.jackson.core.JacksonException failure){throw new RuntimeException(failure);}});reject(()->{try{mapper.readValue("-3",Value.class);}catch(tools.jackson.core.JacksonException failure){throw new RuntimeException(failure);}});var unsafe=Value.createWithoutValidation(java.math.BigInteger.valueOf(4));var sink=new java.io.StringWriter();reject(()->{try{mapper.writeValue(sink,unsafe);}catch(tools.jackson.core.JacksonException failure){throw new RuntimeException(failure);}});if(!sink.toString().isEmpty())throw new AssertionError("native-invalid bytes escaped");new ValueModule(new ValueModuleNativeSidecar.Limits(100,8,20,20,20,20,65536));}
}
`
