package java

import "fmt"

const nativeRegexArtifactSHA256="ee1ff0212d3a3bd28a72f00033f51dad747c8b36e9302edbbbd35cf6a58bfe8f"
const nativeRegexArtifactDirectory="refine/ecmaregex/"+nativeRegexArtifactSHA256
const nativeRegexArtifactPath=nativeRegexArtifactDirectory+"/refine-ecma262.wasm"

// nativeRegexJavaParts keeps every Chicory/WASM reference out of validators
// whose schemas do not contain pattern or patternProperties. Regex-enabled
// helpers bind NetworkNT callbacks to an instance-local request scope. Schema
// construction, lazy reference compilation, and matching therefore share one
// aggregate budget without a process-global or thread-local active request.
type nativeRegexJavaParts struct{
    hardLimits string
    nestedTypes string
    fieldsAndConstructors string
    validationOpen string
    validationCheck string
    validationClose string
    compileSignature string
    configFactory string
}

func nativeRegexParts(enabled bool,className string)nativeRegexJavaParts{
    if !enabled{return nativeRegexJavaParts{fieldsAndConstructors:fmt.Sprintf("    private final Limits limits;private final tools.jackson.databind.ObjectMapper instanceMapper;private final com.networknt.schema.Schema schema;\n    public %s(){this(Limits.defaults());}public %s(Limits limits){this.limits=java.util.Objects.requireNonNull(limits);this.instanceMapper=mapper(limits);this.schema=compile();}",className,className),validationOpen:"var result=",compileSignature:"()"}}
    runtime:=fmt.Sprintf(nativeRegexRuntimeJava,nativeRegexArtifactPath,nativeRegexArtifactSHA256)
    return nativeRegexJavaParts{
        hardLimits:",HARD_MAX_REGEX_PATTERN_UNITS=16384,HARD_MAX_REGEX_INPUT_UNITS=1<<20,HARD_MAX_REGEX_HANDLES=1024,HARD_MAX_REGEX_POLLS=1000000,HARD_MAX_REGEX_COMPILATION_POLLS=1000000,HARD_MAX_REGEX_INITIALIZATION_POLLS=1000000,HARD_MAX_REGEX_MILLIS=1000,HARD_MAX_REGEX_COMPILATION_MILLIS=10000,HARD_MAX_REGEX_INITIALIZATION_MILLIS=10000;private static final long HARD_MAX_REGEX_EVALUATIONS=10000,HARD_MAX_REGEX_WORK_UNITS=8L<<20",
        nestedTypes:runtime,
        fieldsAndConstructors:fmt.Sprintf("    private final Limits limits;private final RegexLimits regexLimits;private final RegexScope regexScope;private final tools.jackson.databind.ObjectMapper instanceMapper;private final com.networknt.schema.Schema schema;\n    public %s(){this(Limits.defaults(),RegexLimits.defaults());}public %s(Limits limits){this(limits,RegexLimits.defaults());}public %s(Limits limits,RegexLimits regexLimits){this.limits=java.util.Objects.requireNonNull(limits);this.regexLimits=java.util.Objects.requireNonNull(regexLimits);this.regexScope=new RegexScope();this.instanceMapper=mapper(limits);this.schema=regexScope.construct(RegexLimits.defaults(),()->compile(regexScope));}",className,className,className),
        validationOpen:"var result=regexScope.run(regexLimits,()->",
        validationClose:")",
        compileSignature:"(RegexScope regexScope)",
        configFactory:".regularExpressionFactory(new BoundedRegexFactory(regexScope))",
    }
}

const nativeRegexRuntimeJava=`
    public record RegexLimits(int maxPatternUnits,int maxInputUnits,long maxEvaluations,long maxWorkUnits,int maxMillis,int maxCompilationPolls,int maxCompilationMillis){public RegexLimits(int maxPatternUnits,int maxInputUnits,long maxEvaluations,long maxWorkUnits,int maxMillis){this(maxPatternUnits,maxInputUnits,maxEvaluations,maxWorkUnits,maxMillis,HARD_MAX_REGEX_COMPILATION_POLLS,HARD_MAX_REGEX_COMPILATION_MILLIS);}public RegexLimits{if(maxPatternUnits<=0||maxInputUnits<=0||maxEvaluations<=0||maxWorkUnits<=0||maxMillis<=0||maxCompilationPolls<=0||maxCompilationMillis<=0)throw new IllegalArgumentException("Native regex limits must be positive.");if(maxPatternUnits>HARD_MAX_REGEX_PATTERN_UNITS||maxInputUnits>HARD_MAX_REGEX_INPUT_UNITS||maxEvaluations>HARD_MAX_REGEX_EVALUATIONS||maxWorkUnits>HARD_MAX_REGEX_WORK_UNITS||maxMillis>HARD_MAX_REGEX_MILLIS||maxCompilationPolls>HARD_MAX_REGEX_COMPILATION_POLLS||maxCompilationMillis>HARD_MAX_REGEX_COMPILATION_MILLIS)throw new IllegalArgumentException("Native regex limits may only tighten generated hard limits.");}public static RegexLimits defaults(){return new RegexLimits(HARD_MAX_REGEX_PATTERN_UNITS,HARD_MAX_REGEX_INPUT_UNITS,HARD_MAX_REGEX_EVALUATIONS,HARD_MAX_REGEX_WORK_UNITS,HARD_MAX_REGEX_MILLIS,HARD_MAX_REGEX_COMPILATION_POLLS,HARD_MAX_REGEX_COMPILATION_MILLIS);}}
    private static final String REGEX_ARTIFACT="/%s",REGEX_ARTIFACT_SHA256="%s";
    private static final com.dylibso.chicory.wasm.WasmModule REGEX_MODULE=loadRegexModule();
    private static com.dylibso.chicory.wasm.WasmModule loadRegexModule(){try(var input=RegexScope.class.getResourceAsStream(REGEX_ARTIFACT)){if(input==null)throw new IllegalStateException("Checked native regex WebAssembly resource is absent.");byte[] bytes=input.readNBytes(1202262);if(bytes.length!=1202261||input.read()!=-1)throw new IllegalStateException("Checked native regex WebAssembly resource size mismatch.");var digest=java.security.MessageDigest.getInstance("SHA-256").digest(bytes);if(!java.util.HexFormat.of().formatHex(digest).equals(REGEX_ARTIFACT_SHA256))throw new IllegalStateException("Checked native regex WebAssembly resource digest mismatch.");return com.dylibso.chicory.wasm.Parser.parse(bytes);}catch(java.io.IOException|java.security.NoSuchAlgorithmException failure){throw new ExceptionInInitializerError(failure);}}
    private static final class BoundedRegexFactory implements com.networknt.schema.regex.RegularExpressionFactory{private final RegexScope scope;BoundedRegexFactory(RegexScope scope){this.scope=java.util.Objects.requireNonNull(scope);}@Override public com.networknt.schema.regex.RegularExpression getRegularExpression(String pattern){return new BoundedRegularExpression(scope,pattern);}@Override public com.networknt.schema.regex.RegularExpression getRegularExpression(String pattern,com.networknt.schema.SchemaContext context){return new BoundedRegularExpression(scope,pattern);}}
    private static final class BoundedRegularExpression implements com.networknt.schema.regex.RegularExpression{private final RegexScope scope;private final String pattern;private BoundedRegularExpression(RegexScope scope,String pattern){this.scope=scope;this.pattern=java.util.Objects.requireNonNull(pattern);scope.current().compile(pattern);}@Override public boolean matches(String input){return scope.current().matches(pattern,java.util.Objects.requireNonNull(input));}}
    private static final class RegexScope{
        private final java.util.concurrent.locks.ReentrantLock lock=new java.util.concurrent.locks.ReentrantLock(true);private RegexSession session;private RegexRequest active;private Thread owner;
        private <T>T construct(RegexLimits limits,java.util.function.Supplier<T> action){return execute(limits,limits.maxCompilationMillis(),true,action);}
        private <T>T run(RegexLimits limits,java.util.function.Supplier<T> action){return execute(limits,limits.maxMillis(),false,action);}
        private <T>T execute(RegexLimits limits,int waitMillis,boolean construction,java.util.function.Supplier<T> action){long acquisitionDeadline=System.nanoTime()+java.util.concurrent.TimeUnit.MILLISECONDS.toNanos(waitMillis);boolean acquired;try{acquired=lock.tryLock(waitMillis,java.util.concurrent.TimeUnit.MILLISECONDS);}catch(InterruptedException failure){Thread.currentThread().interrupt();throw RegexRequest.resource("Native regex request acquisition was interrupted.");}if(!acquired)throw RegexRequest.resource("Native regex request acquisition limit exceeded.");RegexSession used=null;RegexRequest request=null;Throwable primary=null;try{long remaining=acquisitionDeadline-System.nanoTime();if(remaining<=0)throw RegexRequest.resource("Native regex request acquisition limit exceeded.");if(session==null)session=RegexSession.open();used=session;request=used.begin(limits,remaining,construction);active=request;owner=Thread.currentThread();return action.get();}catch(RuntimeException failure){primary=RegexRequest.propagate(failure);throw (RuntimeException)primary;}catch(Error failure){primary=failure;if(request!=null)request.poison();throw failure;}finally{active=null;owner=null;Throwable cleanup=null;boolean reusable=false;if(request!=null)try{reusable=request.finish();}catch(RuntimeException|Error failure){cleanup=failure;}if(used!=null&&!reusable){if(session==used)session=null;Throwable destroyFailure=used.destroyFailure();if(cleanup==null)cleanup=destroyFailure;else if(destroyFailure!=null)cleanup.addSuppressed(destroyFailure);}lock.unlock();if(cleanup!=null){if(primary!=null)primary.addSuppressed(cleanup);else if(cleanup instanceof RuntimeException runtime)throw runtime;else throw (Error)cleanup;}}}
        private RegexRequest current(){if(!lock.isHeldByCurrentThread()||active==null||owner!=Thread.currentThread())throw new NativeValidationException(Code.ENFORCEMENT,"Native regex execution escaped its validation request.");return active;}
    }
    private static final class RegexSession{
        private com.dylibso.chicory.runtime.Instance instance;private com.dylibso.chicory.runtime.Memory memory;private com.dylibso.chicory.runtime.ExportFunction alloc,free,compile,test,release,reset,destroy;private RegexRequest request;private boolean initializing=true,initializationInterrupted,destroyed;private long initializationDeadline,initializationPolls;
        private RegexSession(){initializationDeadline=System.nanoTime()+java.util.concurrent.TimeUnit.MILLISECONDS.toNanos(HARD_MAX_REGEX_INITIALIZATION_MILLIS);var interrupt=new com.dylibso.chicory.runtime.HostFunction("refine","should_interrupt",com.dylibso.chicory.wasm.types.FunctionType.of(new com.dylibso.chicory.wasm.types.ValType[]{com.dylibso.chicory.wasm.types.ValType.I32},new com.dylibso.chicory.wasm.types.ValType[]{com.dylibso.chicory.wasm.types.ValType.I32}),(ignored,args)->new long[]{shouldInterrupt(Math.toIntExact(args[0]))?1:0});try{instance=com.dylibso.chicory.runtime.Instance.builder(REGEX_MODULE).withImportValues(com.dylibso.chicory.runtime.ImportValues.builder().addFunction(interrupt).build()).withMemoryLimits(new com.dylibso.chicory.wasm.types.MemoryLimits(5,512)).withStart(false).build();memory=instance.exports().memory("memory");if(memory==null||memory.initialPages()!=5||memory.maximumPages()!=512)throw new IllegalStateException("Checked native regex WebAssembly memory invariant changed.");alloc=required("regex_alloc");free=required("regex_free");compile=required("regex_compile");test=required("regex_test");release=required("regex_release");reset=required("regex_reset");destroy=required("regex_destroy");long[] version=required("regex_abi_version").apply();if(version.length!=1||version[0]!=2)throw new IllegalStateException("Checked native regex WebAssembly ABI changed.");long[] initialized=required("regex_init").apply();if(initialized.length!=1||initialized[0]!=0)throw RegexRequest.initializationFailure();if(initializationInterrupted||RegexRequest.expired(initializationDeadline))throw RegexRequest.initializationFailure();}catch(NativeValidationException failure){destroyFailure();throw failure;}catch(RuntimeException failure){destroyFailure();if(initializationInterrupted||RegexRequest.expired(initializationDeadline))throw RegexRequest.initializationFailure();throw new NativeValidationException(Code.ENFORCEMENT,"Native ECMA-262 regex initialization could not complete.");}catch(Error failure){var cleanup=destroyFailure();if(cleanup!=null)failure.addSuppressed(cleanup);throw failure;}initializing=false;}
        private static RegexSession open(){return new RegexSession();}
        private com.dylibso.chicory.runtime.ExportFunction required(String name){var result=instance.exports().function(name);if(result==null)throw new IllegalStateException("Checked native regex WebAssembly export is absent.");return result;}
        private boolean shouldInterrupt(int phase){if(initializing){initializationPolls++;if(initializationPolls>HARD_MAX_REGEX_INITIALIZATION_POLLS||RegexRequest.expired(initializationDeadline)){initializationInterrupted=true;return true;}return false;}var current=request;return current==null||current.shouldInterrupt(phase);}
        private RegexRequest begin(RegexLimits limits,long matchBudgetNanos,boolean construction){if(request!=null||destroyed)throw new NativeValidationException(Code.ENFORCEMENT,"Native regex session was not clean at request start.");var next=new RegexRequest(this,limits,matchBudgetNanos,construction);request=next;return next;}
        private void detach(RegexRequest completed){if(request!=completed)throw new NativeValidationException(Code.ENFORCEMENT,"Native regex request ownership changed during cleanup.");request=null;}
        private Throwable destroyFailure(){if(destroyed)return null;destroyed=true;request=null;if(destroy==null)return null;try{destroy.apply();return null;}catch(RuntimeException failure){return new NativeValidationException(Code.ENFORCEMENT,"Native ECMA-262 regex session discard could not complete.");}catch(Error failure){return failure;}}
    }
    private static final class RegexRequest{
        private static final int STATUS_FALSE=0,STATUS_TRUE=1,STATUS_SYNTAX=2,STATUS_RESOURCE=3,STATUS_INTERNAL=4,STATUS_DISCARD=5;
        private final RegexSession session;private final RegexLimits limits;private final java.util.Map<String,Long> handles=new java.util.HashMap<>();private final long matchBudgetNanos,compilationDeadline;private long matchDeadline,polls,compilationPolls,evaluations,work;private boolean poisoned,closed;
        private RegexRequest(RegexSession session,RegexLimits limits,long matchBudgetNanos,boolean construction){this.session=session;this.limits=java.util.Objects.requireNonNull(limits);this.matchBudgetNanos=matchBudgetNanos;long compileNanos=java.util.concurrent.TimeUnit.MILLISECONDS.toNanos(limits.maxCompilationMillis());if(construction&&matchBudgetNanos<compileNanos)compileNanos=matchBudgetNanos;compilationDeadline=System.nanoTime()+compileNanos;}
        private boolean shouldInterrupt(int phase){if(phase==3){polls++;return polls>HARD_MAX_REGEX_POLLS||matchDeadline!=0&&expired(matchDeadline);}compilationPolls++;return compilationPolls>limits.maxCompilationPolls()||expired(compilationDeadline);}
        private static boolean expired(long deadline){return System.nanoTime()-deadline>=0;}
        private long remainingPolls(boolean compiling){return Math.max(0,compiling?(long)limits.maxCompilationPolls()-compilationPolls:HARD_MAX_REGEX_POLLS-polls);}
        private long compile(String pattern){var existing=handles.get(pattern);if(existing!=null)return existing;if(pattern.length()>limits.maxPatternUnits())throw resource("Native regex pattern limit exceeded.");charge(pattern.length(),false);if(handles.size()>=HARD_MAX_REGEX_HANDLES)throw resource("Native regex handle limit exceeded.");byte[] encoded=utf16(pattern);long pointer=copy(encoded,true),output=0;RuntimeException primary=null;try{output=allocate(4,true);long status=call(true,session.compile,pointer,pattern.length(),remainingPolls(true),output);if(status!=STATUS_TRUE)throw status(status,true);long handle=Integer.toUnsignedLong(session.memory.readInt(Math.toIntExact(output)));if(handle==0||handles.containsValue(handle))throw internal("Native regex guest returned an invalid handle.");handles.put(pattern,handle);return handle;}catch(RuntimeException failure){primary=failure;throw failure;}finally{cleanup(primary,output,pointer);}}
        private boolean matches(String pattern,String input){long handle=compile(pattern);if(input.length()>limits.maxInputUnits())throw resource("Native regex input limit exceeded.");if(matchDeadline==0)matchDeadline=System.nanoTime()+matchBudgetNanos;charge((long)pattern.length()+input.length(),true);byte[] encoded=utf16(input);long pointer=copy(encoded,false);RuntimeException primary=null;try{long status=call(false,session.test,handle,pointer,input.length(),remainingPolls(false));if(status==STATUS_TRUE)return true;if(status==STATUS_FALSE)return false;throw status(status,false);}catch(RuntimeException failure){primary=failure;throw failure;}finally{cleanup(primary,pointer);}}
        private void charge(long units,boolean evaluation){if(units<0||units>limits.maxWorkUnits()-work)throw resource("Native regex aggregate work limit exceeded.");if(evaluation&&evaluations>=limits.maxEvaluations())throw resource("Native regex evaluation limit exceeded.");if(evaluation)evaluations++;work+=units;if(evaluation)complete(false);else complete(true);}
        private long call(boolean compiling,com.dylibso.chicory.runtime.ExportFunction function,long...arguments){try{long[] result=function.apply(arguments);if(result.length!=1)throw internal("Native regex guest returned an invalid status.");complete(compiling);return result[0];}catch(NativeValidationException failure){throw failure;}catch(RuntimeException failure){poisoned=true;if(expired(compiling?compilationDeadline:matchDeadline))throw resource("Native regex resource limit exceeded.");throw new NativeValidationException(Code.ENFORCEMENT,"Native ECMA-262 regex execution could not complete.");}catch(Error failure){poisoned=true;throw failure;}}
        private long allocate(int size,boolean compiling){long pointer=call(compiling,session.alloc,size);if(pointer==0){poisoned=true;throw resource("Native regex memory limit exceeded.");}return pointer;}
        private long copy(byte[] value,boolean compiling){long pointer=allocate(value.length,compiling);try{session.memory.write(Math.toIntExact(pointer),value,0,value.length);return pointer;}catch(RuntimeException failure){var wrapped=internal("Native regex guest memory write failed.");cleanup(wrapped,pointer);throw wrapped;}}
        private void cleanup(RuntimeException primary,long...pointers){RuntimeException cleanup=null;for(long pointer:pointers){if(pointer==0||poisoned)continue;try{session.free.apply(pointer);}catch(RuntimeException failure){poisoned=true;var wrapped=new NativeValidationException(Code.ENFORCEMENT,"Native ECMA-262 regex memory cleanup could not complete.");if(cleanup==null)cleanup=wrapped;else cleanup.addSuppressed(wrapped);}}if(cleanup!=null){if(primary!=null)primary.addSuppressed(cleanup);else throw cleanup;}}
        private static byte[] utf16(String value){byte[] out=new byte[Math.multiplyExact(value.length(),2)];for(int i=0;i<value.length();i++){char unit=value.charAt(i);out[i*2]=(byte)unit;out[i*2+1]=(byte)(unit>>>8);}return out;}
        private NativeValidationException status(long status,boolean compiling){if(status==STATUS_SYNTAX)return new NativeValidationException(Code.ENFORCEMENT,"Checked native schema contains an invalid ECMA-262 regular expression.");if(status==STATUS_RESOURCE){poisoned=true;return resource("Native regex resource limit exceeded.");}if(status==STATUS_INTERNAL)return internal("Native ECMA-262 regex guest reported an internal failure.");return internal(compiling?"Native regex compilation returned an invalid status.":"Native regex matching returned an invalid status.");}
        private static NativeValidationException resource(String message){return new NativeValidationException(Code.RESOURCE_LIMIT,message);}
        private static RuntimeException propagate(RuntimeException failure){for(Throwable cause=failure;cause!=null;cause=cause.getCause())if(cause instanceof NativeValidationException nativeFailure)return nativeFailure;return failure;}
        private void poison(){poisoned=true;}
        private NativeValidationException internal(String message){poisoned=true;return new NativeValidationException(Code.ENFORCEMENT,message);}
        private static NativeValidationException initializationFailure(){return new NativeValidationException(Code.RESOURCE_LIMIT,"Native ECMA-262 regex initialization exceeded its deployment limit.");}
        private void complete(boolean compiling){long deadline=compiling?compilationDeadline:matchDeadline;if(deadline!=0&&expired(deadline)){poisoned=true;throw resource("Native regex resource limit exceeded.");}}
        private boolean finish(){if(closed)return !poisoned;closed=true;RuntimeException cleanup=null;boolean reusable=!poisoned;try{if(!poisoned){for(long handle:new java.util.ArrayList<>(handles.values())){long[] result=session.release.apply(handle);if(result.length!=1||result[0]!=STATUS_TRUE)throw internal("Native regex guest rejected a live handle during cleanup.");}long[] result=session.reset.apply();if(result.length!=1)throw internal("Native regex guest reset returned no status.");if(result[0]==STATUS_DISCARD)reusable=false;else if(result[0]!=STATUS_TRUE)throw internal("Native regex guest reset did not restore a clean session.");}}catch(RuntimeException failure){poisoned=true;reusable=false;cleanup=new NativeValidationException(Code.ENFORCEMENT,"Native ECMA-262 regex request cleanup could not complete.");}catch(Error failure){poisoned=true;throw failure;}finally{handles.clear();try{session.detach(this);}catch(RuntimeException failure){poisoned=true;reusable=false;if(cleanup==null)cleanup=failure;else cleanup.addSuppressed(failure);}}if(cleanup!=null)throw cleanup;return reusable&&!poisoned;}
    }
`
