// Code generated by goplus from openapi_native.gp. DO NOT EDIT.
//goplus:v v0.28.0

package java

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"path"
	"sort"
	"strings"

	"goforge.dev/refine/language"
	"goforge.dev/refine/native"
)

// GenerateProjectOpenAPIContext composes checked native operation-part Schema
// Objects with structural JSON decoding and the complete Refine request,
// response, and context predicates. Inputs are semantic JSON values, never HTTP
// syntax. Schema locations come only from Project.OpenAPIOperationIndex.
func GenerateProjectOpenAPIContext(project *native.Project, contractName, className string) (files []File, failure error) {
	defer func() {
		if caught := recover(); caught != nil {
			if err, ok := caught.(*GenerationError); ok {
				files = nil
				failure = err
			} else {
				panic(caught)
			}
		}
	}()
	if project == nil || !project.HasOpenAPINativeBindings() {
		return nil, &GenerationError{Message: "checked native OpenAPI operation bindings are required"}
	}
	if err := javaClassName(contractName); err != nil {
		return nil, err
	}
	if err := javaClassName(className); err != nil {
		return nil, err
	}
	if strings.EqualFold(contractName, className) {
		return nil, &GenerationError{Message: "OpenAPI facade and contract class names must differ"}
	}
	catalog, err := project.OpenAPIOperationIndex()
	if err != nil {
		return nil, err
	}
	if len(catalog.Operations) == 0 || len(catalog.Operations) > 256 {
		return nil, &GenerationError{Message: "generated native OpenAPI facade supports between 1 and 256 operations"}
	}
	program, err := language.Compile(project.EditableSource())
	if err != nil {
		return nil, err
	}
	metadata := project.Metadata()
	namespace := metadata.PublicationNamespace
	usedNames := map[string]bool{sourceNameKey(contractName): true, sourceNameKey(className): true}
	for _, decl := range program.Syntax().Types {
		usedNames[sourceNameKey(decl.Name)] = true
	}
	uniqueName := func(base string) string {
		name := base
		for usedNames[sourceNameKey(name)] {
			name += "_"
		}
		usedNames[sourceNameKey(name)] = true
		return name
	}
	sidecarName := uniqueName(className + "NativeParts")
	responseSidecarName := sidecarName

	targets := map[string]native.OpenAPISchemaTarget{}
	requestTargets := map[string]native.OpenAPISchemaTarget{}
	responseTargets := map[string]native.OpenAPISchemaTarget{}
	types := map[string]bool{}
	totalParts, totalResponses := 0, 0
	addTarget := func(direction map[string]native.OpenAPISchemaTarget, target native.OpenAPISchemaTarget) error {
		if old, ok := targets[target.ID]; ok && (old.Resource != target.Resource || old.Pointer != target.Pointer) {
			return &GenerationError{Message: "native OpenAPI part ID collision"}
		}
		targets[target.ID] = target
		direction[target.ID] = target
		return nil
	}
	for _, operation := range catalog.Operations {
		types[operation.RequestType] = true
		for _, target := range operation.RequestParts {
			totalParts++
			if err := addTarget(requestTargets, target); err != nil {
				return nil, err
			}
		}
		for _, response := range operation.Responses {
			totalResponses++
			types[response.TypeExpression] = true
			for _, target := range response.Parts {
				totalParts++
				if err := addTarget(responseTargets, target); err != nil {
					return nil, err
				}
			}
		}
	}
	if totalParts == 0 || totalParts > 1024 || totalResponses > 256 {
		return nil, &GenerationError{Message: "generated native OpenAPI facade exceeds its part or response binding limit"}
	}
	for _, target := range targets {
		if target.ID == "" || target.Resource == "" || len(target.FieldPath) == 0 || len(target.FieldPath) > 128 {
			return nil, &GenerationError{Message: "native OpenAPI target is incomplete or exceeds the field-path depth limit"}
		}
	}

	requestResources, err := project.OpenAPIValidationResources(native.OpenAPIRequest)
	if err != nil {
		return nil, err
	}
	responseResources, err := project.OpenAPIValidationResources(native.OpenAPIResponse)
	if err != nil {
		return nil, err
	}
	sharedNative := nativeResourceSlicesEqual(requestResources, responseResources)
	var nativeFiles, responseNativeFiles []File
	if sharedNative {
		selector, wrapper, wrapErr := nativeOpenAPIWrapper("", targets, catalog.Resources)
		if wrapErr != nil {
			return nil, wrapErr
		}
		nativeFiles, err = generateProjectNativeJSONValidatorWithBaseResources(project, sidecarName, selector, requestResources, wrapper)
		if err != nil {
			return nil, err
		}
	} else {
		responseSidecarName = uniqueName(className + "NativeResponseParts")
		requestSelector, requestWrapper, wrapErr := nativeOpenAPIWrapper("request", requestTargets, catalog.Resources)
		if wrapErr != nil {
			return nil, wrapErr
		}
		responseSelector, responseWrapper, wrapErr := nativeOpenAPIWrapper("response", responseTargets, catalog.Resources)
		if wrapErr != nil {
			return nil, wrapErr
		}
		nativeFiles, err = generateProjectNativeJSONValidatorWithBaseResources(project, sidecarName, requestSelector, requestResources, requestWrapper)
		if err != nil {
			return nil, err
		}
		responseNativeFiles, err = generateProjectNativeJSONValidatorWithBaseResources(project, responseSidecarName, responseSelector, responseResources, responseWrapper)
		if err != nil {
			return nil, err
		}
	}

	typeNames := make([]string, 0, len(types))
	for name := range types {
		typeNames = append(typeNames, name)
	}
	sort.Strings(typeNames)
	codecNames := map[string]string{}
	all := []File{}
	seen := map[string]string{}
	merge := func(next []File) error {
		for _, file := range next {
			if previous, ok := seen[file.Path]; ok {
				if previous != file.Source {
					return &GenerationError{Message: "native OpenAPI generated sources disagree at " + file.Path}
				}
				continue
			}
			seen[file.Path] = file.Source
			all = append(all, file)
		}
		return nil
	}
	if err := merge(nativeFiles); err != nil {
		return nil, err
	}
	if err := merge(responseNativeFiles); err != nil {
		return nil, err
	}
	for _, name := range typeNames {
		if _, err := program.PayloadType(name); err != nil {
			return nil, &GenerationError{Message: "native OpenAPI target type is not a closed checked payload: " + name}
		}
		codec := uniqueName(className + "JSON" + fmt.Sprint(len(codecNames)))
		codecNames[name] = codec
		options, err := JSONSerdeOptionsFromMetadata(name, metadata)
		if err != nil {
			return nil, err
		}
		if options.Reals == JSONRealUnspecified {
			options.Reals = JSONRealExactDecimal
		}
		generated, err := GenerateJSONSerde(program, namespace, contractName, codec, options)
		if err != nil {
			return nil, err
		}
		if err := merge(generated); err != nil {
			return nil, err
		}
	}

	entries := []string{}
	descriptors := []string{}
	for _, operation := range catalog.Operations {
		requestParts := nativeOpenAPIParts(operation.RequestParts)
		responses := []string{}
		for _, response := range operation.Responses {
			responses = append(responses, "new ResponseBinding("+javaQuote(response.Status)+","+javaQuote(response.TypeExpression)+","+javaQuote(response.ContextType)+",java.util.List.of("+strings.Join(nativeOpenAPIParts(response.Parts), ",")+"))")
		}
		entries = append(entries, "java.util.Map.entry("+javaQuote(operation.OperationID)+",new Binding("+javaQuote(operation.RequestType)+",java.util.List.of("+strings.Join(requestParts, ",")+"),java.util.List.of("+strings.Join(responses, ",")+")))")
		descriptors = append(descriptors, "new Operation("+javaQuote(operation.OperationID)+","+javaQuote(operation.Method)+","+javaQuote(operation.Path)+")")
	}
	codecFields := []string{}
	decodeCases := []string{}
	for _, name := range typeNames {
		codec := codecNames[name]
		field := "codec" + fmt.Sprint(len(codecFields))
		codecFields = append(codecFields, "    private final "+codec+" "+field+"=new "+codec+"();")
		decodeCases = append(decodeCases, "case "+javaQuote(name)+"->"+field+".readDataWithoutRefinements(input,budget)")
	}
	nativeFields := "private final " + sidecarName + " nativeValidator;"
	nativeValidation := "nativeValidator.validate(input);"
	responseLimits := ""
	regexLocations, err := project.JSONSchemaKeywordLocations("pattern", "patternProperties")
	if err != nil {
		return nil, err
	}
	constructors := "    public " + className + "(){this(Limits.defaults()," + sidecarName + ".Limits.defaults());}\n    public " + className + "(Limits limits," + sidecarName + ".Limits nativeLimits){this.limits=java.util.Objects.requireNonNull(limits);this.nativeLimits=java.util.Objects.requireNonNull(nativeLimits);this.nativeValidator=new " + sidecarName + "(this.nativeLimits);}"
	if !sharedNative {
		nativeFields = "private final " + sidecarName + " requestNativeValidator;private final " + responseSidecarName + " responseNativeValidator;"
		nativeValidation = "if(request){requestNativeValidator.validate(input);return;}try{responseNativeValidator.validate(input);}catch(" + responseSidecarName + ".NativeValidationException failure){throw responseFailure(failure);}"
		responseLimits = "    private static " + responseSidecarName + ".Limits responseLimits(" + sidecarName + ".Limits value){return new " + responseSidecarName + ".Limits(value.maxBytes(),value.maxDepth(),value.maxNodes(),value.maxNumberLength(),value.maxStringLength(),value.maxNameLength(),value.maxNumericExpansion());}\n    private static " + sidecarName + ".NativeValidationException responseFailure(" + responseSidecarName + ".NativeValidationException value){var failure=new " + sidecarName + ".NativeValidationException(" + sidecarName + ".Code.valueOf(value.code().name()),value.getMessage());failure.initCause(value);return failure;}\n"
		constructors = "    public " + className + "(){this(Limits.defaults()," + sidecarName + ".Limits.defaults());}\n    public " + className + "(Limits limits," + sidecarName + ".Limits nativeLimits){this.limits=java.util.Objects.requireNonNull(limits);this.nativeLimits=java.util.Objects.requireNonNull(nativeLimits);this.requestNativeValidator=new " + sidecarName + "(this.nativeLimits);this.responseNativeValidator=new " + responseSidecarName + "(responseLimits(this.nativeLimits));}"
	}
	if len(regexLocations) > 0 {
		if sharedNative {
			constructors = "    public " + className + "(){this(Limits.defaults()," + sidecarName + ".Limits.defaults()," + sidecarName + ".RegexLimits.defaults());}\n    public " + className + "(Limits limits," + sidecarName + ".Limits nativeLimits," + sidecarName + ".RegexLimits regexLimits){this.limits=java.util.Objects.requireNonNull(limits);this.nativeLimits=java.util.Objects.requireNonNull(nativeLimits);this.nativeValidator=new " + sidecarName + "(this.nativeLimits,java.util.Objects.requireNonNull(regexLimits));}"
		} else {
			responseLimits += "    private static " + responseSidecarName + ".RegexLimits responseRegexLimits(" + sidecarName + ".RegexLimits value){return new " + responseSidecarName + ".RegexLimits(value.maxPatternUnits(),value.maxInputUnits(),value.maxEvaluations(),value.maxWorkUnits(),value.maxMillis());}\n"
			constructors = "    public " + className + "(){this(Limits.defaults()," + sidecarName + ".Limits.defaults()," + sidecarName + ".RegexLimits.defaults());}\n    public " + className + "(Limits limits," + sidecarName + ".Limits nativeLimits," + sidecarName + ".RegexLimits regexLimits){this.limits=java.util.Objects.requireNonNull(limits);this.nativeLimits=java.util.Objects.requireNonNull(nativeLimits);var checkedRegex=java.util.Objects.requireNonNull(regexLimits);this.requestNativeValidator=new " + sidecarName + "(this.nativeLimits,checkedRegex);this.responseNativeValidator=new " + responseSidecarName + "(responseLimits(this.nativeLimits),responseRegexLimits(checkedRegex));}"
		}
	}
	identity, err := json.Marshal(struct {
		Source   string                         `json:"source"`
		Catalog  native.OpenAPIOperationCatalog `json:"catalog"`
		Metadata native.WireMetadata            `json:"metadata"`
	}{project.EditableSource(), catalog, metadata})
	if err != nil {
		return nil, err
	}
	projectHash := sha256.Sum256(identity)
	replacements := map[string]string{"@@CLASS@@": className, "@@CONTRACT@@": contractName, "@@SIDECAR@@": sidecarName, "@@RESPONSE_SIDECAR@@": responseSidecarName, "@@ENTRIES@@": strings.Join(entries, ","), "@@DESCRIPTORS@@": strings.Join(descriptors, ","), "@@CODEC_FIELDS@@": strings.Join(codecFields, "\n"), "@@DECODE_CASES@@": strings.Join(decodeCases, ";"), "@@NATIVE_FIELDS@@": nativeFields, "@@VALIDATE_NATIVE@@": nativeValidation, "@@CONSTRUCTORS@@": responseLimits + constructors, "@@PROJECT_ID@@": hex.EncodeToString(projectHash[:])}
	source := nativeOpenAPIJava
	keys := make([]string, 0, len(replacements))
	for key := range replacements {
		keys = append(keys, key)
	}
	sort.Slice(keys, func(i, j int) bool { return len(keys[i]) > len(keys[j]) })
	for _, key := range keys {
		source = strings.ReplaceAll(source, key, replacements[key])
	}
	header := "// Generated by Refine: composed native OpenAPI operation validation. MIT licensed.\n"
	if namespace != "" {
		header += "package " + namespace + ";\n"
	}
	facade := File{Path: path.Join(strings.ReplaceAll(namespace, ".", "/"), className+".java"), Source: header + source}
	if err := merge([]File{facade}); err != nil {
		return nil, err
	}
	return all, nil
}

func nativeResourceSlicesEqual(left, right []native.Resource) bool {
	if len(left) != len(right) {
		return false
	}
	for i, item := range left {
		if item != right[i] {
			return false
		}
	}
	return true
}

func nativeOpenAPIWrapper(direction string, targets map[string]native.OpenAPISchemaTarget, resources []native.Resource) (native.ResourceSelector, []native.Resource, error) {
	properties := map[string]any{}
	ids := make([]string, 0, len(targets))
	for id, target := range targets {
		ids = append(ids, id)
		location := target.Resource
		if target.Pointer != "" {
			location += "#" + target.Pointer
		}
		properties[id] = map[string]any{"$ref": location}
	}
	sort.Strings(ids)
	wrapper := map[string]any{"$schema": "https://json-schema.org/draft/2020-12/schema", "type": "object", "properties": properties, "additionalProperties": false}
	wrapperBytes, err := json.Marshal(wrapper)
	if err != nil {
		return native.ResourceSelector{}, nil, err
	}
	hashInput := wrapperBytes
	prefix := "urn:refine:openapi-parts:"
	if direction != "" {
		hashInput = append([]byte(direction+"\x00"), wrapperBytes...)
		prefix += direction + ":"
	}
	wrapperHash := sha256.Sum256(hashInput)
	uri := prefix + hex.EncodeToString(wrapperHash[:16])
	for _, resource := range resources {
		if resource.URI == uri {
			return native.ResourceSelector{}, nil, &GenerationError{Message: "generated native OpenAPI wrapper URI collides with a project resource"}
		}
	}
	return native.ResourceSelector{Resource: uri}, []native.Resource{{URI: uri, Source: string(wrapperBytes)}}, nil
}

func nativeOpenAPIParts(parts []native.OpenAPISchemaTarget) []string {
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		pathParts := []string{}
		for _, name := range part.FieldPath {
			pathParts = append(pathParts, javaQuote(name))
		}
		out = append(out, "new Part("+javaQuote(part.ID)+","+javaQuote(part.In)+","+javaQuote(part.Name)+",java.util.List.of("+strings.Join(pathParts, ",")+"),"+fmt.Sprint(part.Required)+","+javaQuote(part.MediaType)+")")
	}
	return out
}

const nativeOpenAPIJava = `
public final class @@CLASS@@ {
    private static final String PROJECT_ID="@@PROJECT_ID@@";
    public record Limits(int maxBytes,int maxParts){public Limits{if(maxBytes<=0||maxParts<=0)throw new IllegalArgumentException("OpenAPI limits must be positive.");if(maxBytes>(1<<20)||maxParts>1024)throw new IllegalArgumentException("OpenAPI limits may only tighten generated hard limits.");}public static Limits defaults(){return new Limits(1<<20,1024);}}
    public record ParameterJSON(String in,String name,byte[] value){public ParameterJSON{java.util.Objects.requireNonNull(in);java.util.Objects.requireNonNull(name);value=checkedInput(value);}public byte[] value(){return value.clone();}private byte[] raw(){return value;}}
    public record HeaderJSON(String name,byte[] value){public HeaderJSON{java.util.Objects.requireNonNull(name);value=checkedInput(value);}public byte[] value(){return value.clone();}private byte[] raw(){return value;}}
    public record MediaJSON(String mediaType,byte[] value){public MediaJSON{java.util.Objects.requireNonNull(mediaType);value=checkedInput(value);}public byte[] value(){return value.clone();}private byte[] raw(){return value;}}
    public record RequestJSON(java.util.List<ParameterJSON> parameters,java.util.List<HeaderJSON> headers,MediaJSON body){public RequestJSON{parameters=checkedList(parameters);headers=checkedList(headers);}}
    public record ResponseJSON(String status,java.util.List<HeaderJSON> headers,MediaJSON body){public ResponseJSON{java.util.Objects.requireNonNull(status);headers=checkedList(headers);}}
    public record Operation(String operationId,String method,String path){public Operation{java.util.Objects.requireNonNull(operationId);java.util.Objects.requireNonNull(method);java.util.Objects.requireNonNull(path);}}
    public static final class ValidatedRequest{private final Object owner;private final String projectId;private final String operationId;private final Data data;private ValidatedRequest(Object owner,String operationId,Data data){this.owner=owner;this.projectId=PROJECT_ID;this.operationId=operationId;this.data=data;}public String operationId(){return operationId;}public Data data(){return data;}}
    public static final class OpenAPILimitException extends IllegalArgumentException{private static final long serialVersionUID=1L;private OpenAPILimitException(String message){super(message);}public boolean isIndeterminate(){return true;}}
    private record Part(String id,String in,String name,java.util.List<String> fieldPath,boolean required,String mediaType){Part{fieldPath=java.util.List.copyOf(fieldPath);}}
    private record ResponseBinding(String status,String responseType,String contextType,java.util.List<Part> parts){ResponseBinding{parts=java.util.List.copyOf(parts);}}
    private record Binding(String requestType,java.util.List<Part> requestParts,java.util.List<ResponseBinding> responses){Binding{requestParts=java.util.List.copyOf(requestParts);responses=java.util.List.copyOf(responses);}}
    private record Supplied(byte[] raw,String media){Supplied{raw=raw.clone();}public byte[] raw(){return raw.clone();}}
    private sealed interface JSON permits ObjectJSON,RawJSON{}
    private static final class ObjectJSON implements JSON{final java.util.LinkedHashMap<String,JSON> members=new java.util.LinkedHashMap<>();}
    private record RawJSON(byte[] value)implements JSON{RawJSON{value=value.clone();}public byte[] value(){return value.clone();}}
    private final Object owner=new Object();
    private static final java.util.Map<String,Binding> BINDINGS=java.util.Map.ofEntries(@@ENTRIES@@);
    private static final java.util.List<Operation> OPERATIONS=java.util.List.of(@@DESCRIPTORS@@);
    private final Limits limits;private final @@SIDECAR@@.Limits nativeLimits;@@NATIVE_FIELDS@@
@@CODEC_FIELDS@@
@@CONSTRUCTORS@@
    public static java.util.List<Operation> operations(){return OPERATIONS;}
    private static Binding operation(String operationId){var result=operationId==null?null:BINDINGS.get(operationId);if(result==null)throw new IllegalArgumentException("unknown OpenAPI operationId");return result;}
    private static boolean runtimeStatus(String status){return status!=null&&status.length()==3&&status.charAt(0)>='1'&&status.charAt(0)<='5'&&status.charAt(1)>='0'&&status.charAt(1)<='9'&&status.charAt(2)>='0'&&status.charAt(2)<='9';}
    private static ResponseBinding response(Binding binding,String status){if(!runtimeStatus(status))throw new IllegalArgumentException("response status must be 100-599");String family=status.substring(0,1)+"XX";ResponseBinding classMatch=null,defaultMatch=null;for(var candidate:binding.responses()){if(candidate.status().equals(status))return candidate;if(candidate.status().equals(family))classMatch=candidate;else if(candidate.status().equals("default"))defaultMatch=candidate;}if(classMatch!=null)return classMatch;if(defaultMatch!=null)return defaultMatch;throw new IllegalArgumentException("response status has no binding");}
    private static byte[] checkedInput(byte[] value){java.util.Objects.requireNonNull(value);if(value.length>1<<20)throw limit("OpenAPI semantic part byte limit exceeded.");return value.clone();}
    private static <T> java.util.List<T> checkedList(java.util.List<T> value){java.util.Objects.requireNonNull(value);if(value.size()>1024)throw limit("OpenAPI semantic part count limit exceeded.");return java.util.List.copyOf(value);}
    private static String key(String in,String name){return in.toLowerCase(java.util.Locale.ROOT)+"\u0000"+(in.equalsIgnoreCase("header")?name.toLowerCase(java.util.Locale.ROOT):name);}
    private void supplied(java.util.Map<String,Supplied> out,String key,byte[] raw,String media,String duplicate){if(out.size()>=limits.maxParts())throw limit("OpenAPI aggregate semantic part limit exceeded.");long bytes=raw.length;for(var item:out.values())bytes+=item.raw.length;if(bytes>limits.maxBytes())throw limit("OpenAPI aggregate semantic byte limit exceeded.");preflight(raw);if(out.putIfAbsent(key,new Supplied(raw,media))!=null)throw new IllegalArgumentException(duplicate);}
    private java.util.Map<String,Supplied> requestParts(RequestJSON input){var out=new java.util.LinkedHashMap<String,Supplied>();for(var item:input.parameters()){String in=item.in().toLowerCase(java.util.Locale.ROOT);if(!in.equals("path")&&!in.equals("query")&&!in.equals("cookie"))throw new IllegalArgumentException("parameters require path, query, or cookie location");supplied(out,key(in,item.name()),item.raw(),"","duplicate semantic parameter");}for(var item:input.headers())supplied(out,key("header",item.name()),item.raw(),"","duplicate semantic header");if(input.body()!=null)supplied(out,"body",input.body().raw(),input.body().mediaType(),"duplicate semantic body");return out;}
    private java.util.Map<String,Supplied> responseParts(ResponseJSON input){var out=new java.util.LinkedHashMap<String,Supplied>();for(var item:input.headers())supplied(out,key("header",item.name()),item.raw(),"","duplicate semantic response header");if(input.body()!=null)supplied(out,"body",input.body().raw(),input.body().mediaType(),"duplicate semantic response body");return out;}
    private java.util.List<java.util.Map.Entry<Part,Supplied>> select(java.util.List<Part> expected,java.util.Map<String,Supplied> provided){var selected=new java.util.ArrayList<java.util.Map.Entry<Part,Supplied>>();var used=new java.util.HashSet<String>();for(var part:expected){String lookup=part.in().equals("body")?"body":key(part.in(),part.name());var supplied=provided.get(lookup);if(supplied==null){if(part.required())throw new IllegalArgumentException("required semantic part is absent: "+part.id());continue;}used.add(lookup);if(part.in().equals("body")&&!supplied.media().equalsIgnoreCase(part.mediaType()))throw new IllegalArgumentException("body media type does not match the checked binding");selected.add(java.util.Map.entry(part,supplied));}for(var key:provided.keySet())if(!used.contains(key))throw new IllegalArgumentException("semantic part is not declared by the checked operation");return selected;}
    private void validateNative(java.util.List<java.util.Map.Entry<Part,Supplied>> selected,boolean request){var root=new ObjectJSON();for(var item:selected)root.members.put(item.getKey().id(),new RawJSON(item.getValue().raw()));byte[] input=encode(root,limits.maxBytes());@@VALIDATE_NATIVE@@}
    private Data decode(String type,byte[] input,Budget.Limits budget){return switch(type){@@DECODE_CASES@@;default->throw new AssertionError("missing checked OpenAPI codec");};}
    private Data decodeParts(String type,java.util.List<java.util.Map.Entry<Part,Supplied>> selected,boolean request,Budget.Limits budget){validateNative(selected,request);var root=new ObjectJSON();if(request){root.members.put("parameters",new ObjectJSON());root.members.put("headers",new ObjectJSON());}else root.members.put("headers",new ObjectJSON());for(var item:selected)put(root,item.getKey().fieldPath(),new RawJSON(item.getValue().raw()));return decode(type,encode(root,limits.maxBytes()),budget);}
    public ValidatedRequest validateRequest(String operationId,RequestJSON input){return validateRequest(operationId,input,Budget.Limits.defaults());}
    public ValidatedRequest validateRequest(String operationId,RequestJSON input,Budget.Limits budget){java.util.Objects.requireNonNull(input);java.util.Objects.requireNonNull(budget);var binding=operation(operationId);Data data=decodeParts(binding.requestType(),select(binding.requestParts(),requestParts(input)),true,budget);@@CONTRACT@@.validate(binding.requestType(),data,budget).orThrow();return new ValidatedRequest(owner,operationId,data);}
    public Validation.Outcome validateResponse(String operationId,ResponseJSON input,ValidatedRequest original){return validateResponse(operationId,input,original,Budget.Limits.defaults());}
    public Validation.Outcome validateResponse(String operationId,ResponseJSON input,ValidatedRequest original,Budget.Limits budget){java.util.Objects.requireNonNull(input);java.util.Objects.requireNonNull(budget);var binding=operation(operationId);var selected=response(binding,input.status());Data data=decodeParts(selected.responseType(),select(selected.parts(),responseParts(input)),false,budget);if(selected.contextType().isEmpty())return @@CONTRACT@@.validate(selected.responseType(),data,budget);if(original==null)return merge(@@CONTRACT@@.validate(selected.responseType(),data,budget),missingRequest());if(original.owner!=owner||!original.projectId.equals(PROJECT_ID)||!original.operationId.equals(operationId))throw new IllegalArgumentException("original request token belongs to a different operation or project");var context=new Data.Struct(java.util.List.of(new Data.Field("request",original.data),new Data.Field("response",data)));return @@CONTRACT@@.validate(selected.contextType(),context,budget);}
    private static Validation.Outcome missingRequest(){return new Validation.Indeterminate(java.util.List.of(new Validation.Diagnostic("openapi.request_context.missing",java.util.List.of("request"),"","Original request context is required for response validation.")));}
    private static Validation.Outcome merge(Validation.Outcome first,Validation.Outcome second){var details=new java.util.ArrayList<Validation.Diagnostic>();details.addAll(first.diagnostics());details.addAll(second.diagnostics());boolean invalid=first.state()==Validation.State.INVALID||second.state()==Validation.State.INVALID;boolean incomplete=first.incomplete()||second.incomplete();return invalid?new Validation.Invalid(details,incomplete):incomplete?new Validation.Indeterminate(details):new Validation.Valid();}
    private void preflight(byte[] raw){var constraints=tools.jackson.core.StreamReadConstraints.builder().maxDocumentLength(Math.min((long)limits.maxBytes(),nativeLimits.maxBytes())).maxNestingDepth(nativeLimits.maxDepth()).maxTokenCount(nativeLimits.maxNodes()).maxNumberLength(nativeLimits.maxNumberLength()).maxStringLength(nativeLimits.maxStringLength()).maxNameLength(nativeLimits.maxNameLength()).build();var factory=tools.jackson.core.json.JsonFactory.builder().streamReadConstraints(constraints).enable(tools.jackson.core.StreamReadFeature.STRICT_DUPLICATE_DETECTION).build();try(var parser=factory.createParser(tools.jackson.core.ObjectReadContext.empty(),raw)){var token=parser.nextToken();if(token==null)throw new @@SIDECAR@@.NativeValidationException("Expected one JSON value.");int containers=token==tools.jackson.core.JsonToken.START_OBJECT||token==tools.jackson.core.JsonToken.START_ARRAY?1:0;if(containers>0)while(containers>0){token=parser.nextToken();if(token==null)throw new @@SIDECAR@@.NativeValidationException("Expected one complete JSON value.");if(token==tools.jackson.core.JsonToken.START_OBJECT||token==tools.jackson.core.JsonToken.START_ARRAY)containers++;else if(token==tools.jackson.core.JsonToken.END_OBJECT||token==tools.jackson.core.JsonToken.END_ARRAY)containers--;}if(parser.nextToken()!=null)throw new @@SIDECAR@@.NativeValidationException("Expected exactly one JSON value.");}catch(@@SIDECAR@@.NativeValidationException failure){throw failure;}catch(tools.jackson.core.exc.StreamConstraintsException failure){throw new @@SIDECAR@@.NativeValidationException(@@SIDECAR@@.Code.RESOURCE_LIMIT,"OpenAPI semantic JSON parser resource limit exceeded.");}catch(tools.jackson.core.JacksonException failure){throw new @@SIDECAR@@.NativeValidationException("Invalid OpenAPI semantic JSON value.");}}
    private static void put(ObjectJSON root,java.util.List<String> path,JSON value){ObjectJSON current=root;for(int index=0;index<path.size();index++){String name=path.get(index);if(index==path.size()-1){if(current.members.putIfAbsent(name,value)!=null)throw new IllegalStateException("checked OpenAPI field paths overlap");return;}JSON next=current.members.get(name);if(next==null){var created=new ObjectJSON();current.members.put(name,created);current=created;}else if(next instanceof ObjectJSON object)current=object;else throw new IllegalStateException("checked OpenAPI field paths overlap");}}
    private static byte[] encode(JSON root,int maximum){var sink=new CappedOutput(maximum);write(root,sink);return sink.bytes();}
    private static void write(JSON value,CappedOutput sink){switch(value){case RawJSON raw->sink.write(raw.value());case ObjectJSON object->{sink.write('{');boolean first=true;for(var member:object.members.entrySet()){if(!first)sink.write(',');first=false;quote(member.getKey(),sink);sink.write(':');write(member.getValue(),sink);}sink.write('}');}}}
    private static void quote(String value,CappedOutput sink){sink.write('"');for(int index=0;index<value.length();index++){char unit=value.charAt(index);switch(unit){case '"'->sink.writeAscii("\\\"");case '\\'->sink.writeAscii("\\\\");case '\b'->sink.writeAscii("\\b");case '\f'->sink.writeAscii("\\f");case '\n'->sink.writeAscii("\\n");case '\r'->sink.writeAscii("\\r");case '\t'->sink.writeAscii("\\t");default->{if(unit<0x20)sink.writeAscii(String.format(java.util.Locale.ROOT,"\\u%04x",(int)unit));else{if(Character.isHighSurrogate(unit)){if(index+1>=value.length()||!Character.isLowSurrogate(value.charAt(index+1)))throw new IllegalStateException("generated OpenAPI name is not Unicode scalar text");sink.write(new String(new char[]{unit,value.charAt(++index)}).getBytes(java.nio.charset.StandardCharsets.UTF_8));}else if(Character.isLowSurrogate(unit))throw new IllegalStateException("generated OpenAPI name is not Unicode scalar text");else sink.write(String.valueOf(unit).getBytes(java.nio.charset.StandardCharsets.UTF_8));}}}}sink.write('"');}
    private static OpenAPILimitException limit(String message){return new OpenAPILimitException(message);}
    private static final class CappedOutput{private final java.io.ByteArrayOutputStream sink=new java.io.ByteArrayOutputStream();private final int maximum;private int written;CappedOutput(int maximum){this.maximum=maximum;}void write(int value){claim(1);sink.write(value);}void write(byte[] value){claim(value.length);sink.write(value,0,value.length);}void writeAscii(String value){write(value.getBytes(java.nio.charset.StandardCharsets.US_ASCII));}void claim(int count){if(count<0||count>maximum-written)throw limit("OpenAPI assembled JSON byte limit exceeded.");written+=count;}byte[] bytes(){return sink.toByteArray();}}
}
`
