package java

import (
    "fmt"
    "path"
    "sort"
    "strings"

    "goforge.dev/refine/language"
    "goforge.dev/refine/native"
)

type openAPIPropertyExample struct { label string; target string; source string; expected PropertyOutcome; nativeExpected PropertyNativeOutcome; codes []string }
type openAPIResponseProperty struct { index int; operation int; target string; requestGenerator string }
type openAPIPropertyRule struct { rule propertyRule; role string }

const openAPIReplayPrefix="@refine-openapi-property/v1/"
// OpenAPIPropertyElementPathSegment is the reserved affected-path segment for
// one runtime list element or map key in an occurrence replay selector. It is
// not a JSON Pointer escape and cannot collide with an authored field name.
const OpenAPIPropertyElementPathSegment="~2"

func openAPIReplayTarget(role,operationID,status string)string{return fmt.Sprintf("%s%s/%d:%s/%d:%s",openAPIReplayPrefix,role,len(operationID),operationID,len(status),status)}
func openAPIOccurrenceReplayTarget(base string,paths []string,offset int)string{var out strings.Builder;fmt.Fprintf(&out,"%s/occurrence/%d/%d",base,offset,len(paths));for _,item:=range paths{fmt.Fprintf(&out,"/%d:%s",len(item),item)};return out.String()}

// OpenAPIRequestReplayTarget returns the opaque replay selector for one
// operation's request property. The generator still verifies that the selector
// names exactly one authoritative catalog property.
func OpenAPIRequestReplayTarget(operationID string)string{return openAPIReplayTarget("request",operationID,"")}

// OpenAPIRequestOccurrenceReplayTarget selects one repeated request clause by
// its checked affected paths and source offset. Prefer the shorter request
// selector when a diagnostic code occurs only once in the request.
func OpenAPIRequestOccurrenceReplayTarget(operationID string,paths []string,offset int)string{return openAPIOccurrenceReplayTarget(OpenAPIRequestReplayTarget(operationID),paths,offset)}

// OpenAPIResponseReplayTarget selects response-origin invalid predicates,
// including those evaluated within a context. It also selects valid response
// pairs when the binding has no additional context type.
func OpenAPIResponseReplayTarget(operationID,status string)string{return openAPIReplayTarget("response",operationID,status)}

// OpenAPIResponseOccurrenceReplayTarget selects one repeated response-origin
// clause, including a response clause evaluated through a context binding.
func OpenAPIResponseOccurrenceReplayTarget(operationID,status string,paths []string,offset int)string{return openAPIOccurrenceReplayTarget(OpenAPIResponseReplayTarget(operationID,status),paths,offset)}

// OpenAPIContextReplayTarget returns the opaque replay selector for a response
// pair validated through an additional checked context type.
func OpenAPIContextReplayTarget(operationID,status string)string{return openAPIReplayTarget("context",operationID,status)}

// OpenAPIContextOccurrenceReplayTarget selects one repeated additional context
// clause by its checked affected paths and source offset.
func OpenAPIContextOccurrenceReplayTarget(operationID,status string,paths []string,offset int)string{return openAPIOccurrenceReplayTarget(OpenAPIContextReplayTarget(operationID,status),paths,offset)}

func propertyRuleArguments(rule propertyRule)string{parts:=[]string{javaQuote(rule.code),javaQuote(rule.predicate),javaQuote(rule.enclosing),fmt.Sprint(rule.offset),fmt.Sprint(rule.automatic)};for _,item:=range rule.paths{parts=append(parts,javaQuote(item))};return strings.Join(parts,",")}
func propertyRuleReplayCounts(rules []openAPIPropertyRule,bases []string)map[string]int{out:=map[string]int{};for i,item:=range rules{out[bases[i]+"\x00"+item.rule.code]++};return out}
func propertyRuleReplaySelector(base string,rule propertyRule,counts map[string]int,replays map[string]string,seen map[string]bool)(string,error){key:=base+"\x00"+rule.code;if counts[key]==1{return base,nil};legacy:=replayKey(base,ReplayInvalid,rule.code);if _,supplied:=replays[legacy];supplied{return "",fmt.Errorf("operation replay selector %s is ambiguous for repeated diagnostic %s; use an occurrence selector",base,rule.code)};diagnostic:=base+"\x00"+rule.code+"\x00"+rule.predicate;for _,item:=range rule.paths{diagnostic+=fmt.Sprintf("\x00%d:%s",len(item),item)};if seen[diagnostic]{return "",fmt.Errorf("operation property occurrences for diagnostic %s cannot be distinguished by their emitted diagnostics",rule.code)};seen[diagnostic]=true;return openAPIOccurrenceReplayTarget(base,rule.paths,rule.offset),nil}

func propertyPathsPrefixed(paths []string,prefix string)[]string{out:=make([]string,len(paths));for i,item:=range paths{if item==""{out[i]=prefix}else{out[i]=prefix+item}};return out}
func samePropertyPaths(left,right []string)bool{if len(left)!=len(right){return false};for i:=range left{if left[i]!=right[i]{return false}};return true}
func embeddedPropertyRule(outer,inner propertyRule,prefix string)bool{return outer.predicate==inner.predicate&&outer.offset==inner.offset&&samePropertyPaths(outer.paths,propertyPathsPrefixed(inner.paths,prefix))}
func classifyOpenAPIContextRules(context,request,response []propertyRule)[]openAPIPropertyRule{usedRequest:=make([]bool,len(request));usedResponse:=make([]bool,len(response));out:=[]openAPIPropertyRule{};for _,rule:=range context{inherited:=false;for i,candidate:=range request{if !usedRequest[i]&&embeddedPropertyRule(rule,candidate,"/request"){usedRequest[i]=true;inherited=true;break}};if inherited{continue};for i,candidate:=range response{if !usedResponse[i]&&embeddedPropertyRule(rule,candidate,"/response"){usedResponse[i]=true;out=append(out,openAPIPropertyRule{rule:candidate,role:"response"});inherited=true;break}};if !inherited{out=append(out,openAPIPropertyRule{rule:rule,role:"context"})}};return out}

func openAPIPropertyRules(emitter *propertyEmitter,declarations map[string]language.TypeDecl,name string)([]propertyRule,error){decl,ok:=declarations[name];if !ok||len(decl.Parameters)>0{return nil,fmt.Errorf("operation property target %s must be a closed declaration",name)};typ:=decl.Body;if typ==nil{typ=&language.Type{Form:language.NamedType(name),At:decl.At}};return emitter.rules(name,"",typ)}

func openAPIPropertyStatus(operation native.OpenAPIOperation,response native.OpenAPIResponseOperation)(string,error){
    raw:=response.Status;if len(raw)==3&&raw[0]>='1'&&raw[0]<='5'&&raw[1]>='0'&&raw[1]<='9'&&raw[2]>='0'&&raw[2]<='9'{return raw,nil};exact:=map[string]bool{};classes:=map[string]bool{};for _,item:=range operation.Responses{if len(item.Status)==3&&item.Status[1:]!="XX"{exact[item.Status]=true}else if len(item.Status)==3&&item.Status[1:]=="XX"{classes[item.Status[:1]]=true}}
    if len(raw)==3&&raw[1:]=="XX"{for code:=100;code<=599;code++{candidate:=fmt.Sprint(code);if candidate[:1]==raw[:1]&&!exact[candidate]{return candidate,nil}};return "",fmt.Errorf("response class %s has no representative status",raw)}
    if raw=="default"{for code:=100;code<=599;code++{candidate:=fmt.Sprint(code);if !exact[candidate]&&!classes[candidate[:1]]{return candidate,nil}};return "",fmt.Errorf("default response has no representative status")};return "",fmt.Errorf("unsupported response status binding %s",raw)
}

func openAPIPropertyPart(root string,target native.OpenAPISchemaTarget)string{parts:=[]string{root};for _,item:=range target.FieldPath{parts=append(parts,javaQuote(item))};return "part("+strings.Join(parts,",")+")"}

type openAPIEnvelopeType struct { typ *language.Type; bindings map[string]openAPIEnvelopeType }
type openAPIEnvelopeField struct { name string; typ openAPIEnvelopeType }
type openAPIEnvelopeAudit struct { declarations map[string]language.TypeDecl; remaining int }

func (a *openAPIEnvelopeAudit)take(units int)error{if units<0||units>a.remaining{return fmt.Errorf("transport envelope structural work limit exceeded")};a.remaining-=units;return nil}
func (a *openAPIEnvelopeAudit)application(value openAPIEnvelopeType)(string,[]openAPIEnvelopeType,error){arguments:=[]openAPIEnvelopeType{};current:=value;for{if current.typ==nil{return "",nil,fmt.Errorf("transport envelope application contains an absent type")};if err:=a.take(1);err!=nil{return "",nil,err};match current.typ.Form{case language.AppliedType(fn,arg):arguments=append(arguments,openAPIEnvelopeType{typ:arg,bindings:current.bindings});current=openAPIEnvelopeType{typ:fn,bindings:current.bindings};case language.NamedType(name):if replacement,ok:=current.bindings[name];ok{current=replacement;continue};for left,right:=0,len(arguments)-1;left<right;left,right=left+1,right-1{arguments[left],arguments[right]=arguments[right],arguments[left]};return name,arguments,nil;case _:return "",nil,fmt.Errorf("transport envelope application has no named constructor")}}}
func (a *openAPIEnvelopeAudit)record(value openAPIEnvelopeType,active map[string]bool,depth int)([]openAPIEnvelopeField,error){if value.typ==nil||depth>128{return nil,fmt.Errorf("transport envelope type resolution limit exceeded")};if err:=a.take(1);err!=nil{return nil,err};match value.typ.Form{case language.RefinedType(base,_):return a.record(openAPIEnvelopeType{typ:base,bindings:value.bindings},active,depth+1);case language.RecordType(fields):if err:=a.take(len(fields));err!=nil{return nil,err};out:=make([]openAPIEnvelopeField,len(fields));for i,field:=range fields{out[i]=openAPIEnvelopeField{name:field.Name,typ:openAPIEnvelopeType{typ:field.Type,bindings:value.bindings}}};return out,nil;case language.NamedType(name):if replacement,ok:=value.bindings[name];ok{return a.record(replacement,active,depth+1)};if active[name]{return nil,fmt.Errorf("cyclic transport envelope alias")};decl,ok:=a.declarations[name];if !ok||len(decl.Parameters)>0||decl.Body==nil{return nil,fmt.Errorf("transport envelope is not a closed record")};active[name]=true;defer delete(active,name);return a.record(openAPIEnvelopeType{typ:decl.Body},active,depth+1);case language.AppliedType(_,_):name,args,err:=a.application(value);if err!=nil{return nil,err};decl,ok:=a.declarations[name];if !ok||decl.Body==nil||len(args)!=len(decl.Parameters){return nil,fmt.Errorf("transport envelope is not a closed record")};if err:=a.take(len(args));err!=nil{return nil,err};bindings:=make(map[string]openAPIEnvelopeType,len(args));for i,param:=range decl.Parameters{bindings[param]=args[i]};return a.record(openAPIEnvelopeType{typ:decl.Body,bindings:bindings},active,depth+1);case _:};return nil,fmt.Errorf("transport envelope is not a record")}
func (a *openAPIEnvelopeAudit)absent(value openAPIEnvelopeType,active map[string]bool,depth int)(bool,error){if value.typ==nil||depth>128{return false,fmt.Errorf("transport optional type resolution limit exceeded")};if err:=a.take(1);err!=nil{return false,err};match value.typ.Form{case language.RefinedType(base,_):return a.absent(openAPIEnvelopeType{typ:base,bindings:value.bindings},active,depth+1);case language.NamedType(name):if replacement,ok:=value.bindings[name];ok{return a.absent(replacement,active,depth+1)};if active[name]{return false,fmt.Errorf("cyclic transport optional alias")};if decl,ok:=a.declarations[name];ok&&len(decl.Parameters)==0&&decl.Body!=nil{active[name]=true;defer delete(active,name);return a.absent(openAPIEnvelopeType{typ:decl.Body},active,depth+1)};case language.AppliedType(_,_):name,args,err:=a.application(value);if err!=nil{return false,err};if name=="Maybe"&&len(args)==1{return true,nil};if decl,ok:=a.declarations[name];ok&&decl.Body!=nil&&len(args)==len(decl.Parameters){if err:=a.take(len(args));err!=nil{return false,err};bindings:=make(map[string]openAPIEnvelopeType,len(args));for i,param:=range decl.Parameters{bindings[param]=args[i]};return a.absent(openAPIEnvelopeType{typ:decl.Body,bindings:bindings},active,depth+1)};case _:};return false,nil}

func openAPITransportEnvelopeBounded(declarations map[string]language.TypeDecl,name string,request bool,work int)error{decl,ok:=declarations[name];if !ok||len(decl.Parameters)>0{return fmt.Errorf("zero-part transport target %s must be a closed declaration",name)};audit:=&openAPIEnvelopeAudit{declarations:declarations,remaining:work};typ:=decl.Body;if typ==nil{typ=&language.Type{Form:language.NamedType(name),At:decl.At}};fields,err:=audit.record(openAPIEnvelopeType{typ:typ},map[string]bool{},0);if err!=nil{return fmt.Errorf("zero-part transport target %s: %w",name,err)};foundParameters,foundHeaders,foundBody:=false,false,false;for _,field:=range fields{switch field.name{case "parameters":if !request{return fmt.Errorf("zero-part response target %s cannot declare parameters",name)};foundParameters=true;nested,nestedErr:=audit.record(field.typ,map[string]bool{},0);if nestedErr!=nil{return fmt.Errorf("zero-part request target %s parameters: %w",name,nestedErr)};for _,item:=range nested{optional,optionalErr:=audit.absent(item.typ,map[string]bool{},0);if optionalErr!=nil{return optionalErr};if !optional{return fmt.Errorf("zero-part request target %s has required unmapped parameter field %s",name,item.name)}};case "headers":foundHeaders=true;nested,nestedErr:=audit.record(field.typ,map[string]bool{},0);if nestedErr!=nil{return fmt.Errorf("zero-part transport target %s headers: %w",name,nestedErr)};for _,item:=range nested{optional,optionalErr:=audit.absent(item.typ,map[string]bool{},0);if optionalErr!=nil{return optionalErr};if !optional{return fmt.Errorf("zero-part transport target %s has required unmapped header field %s",name,item.name)}};case "body":foundBody=true;optional,optionalErr:=audit.absent(field.typ,map[string]bool{},0);if optionalErr!=nil{return optionalErr};if !optional{return fmt.Errorf("zero-part transport target %s has a required unmapped body",name)};default:optional,optionalErr:=audit.absent(field.typ,map[string]bool{},0);if optionalErr!=nil{return optionalErr};if !optional{return fmt.Errorf("zero-part transport target %s has required unmapped field %s",name,field.name)}}};if request&&!foundParameters{return fmt.Errorf("zero-part request target %s lacks parameters",name)};if !foundHeaders{return fmt.Errorf("zero-part transport target %s lacks headers",name)};if !foundBody{return fmt.Errorf("zero-part transport target %s lacks body",name)};return nil}
func openAPITransportEnvelope(declarations map[string]language.TypeDecl,name string,request bool)error{return openAPITransportEnvelopeBounded(declarations,name,request,language.DefaultSubstitutionNodes)}

func openAPITransportData(codec string,request bool)string{raw:=`{"headers":{}}`;if request{raw=`{"parameters":{},"headers":{}}`};return codec+".readDataWithoutRefinements("+javaQuote(raw)+".getBytes(java.nio.charset.StandardCharsets.UTF_8))"}
func openAPITransportGenerator(codec string,request bool)string{return "org.jetbrains.jetCheck.Generator.<Data>constant("+openAPITransportData(codec,request)+")"}

// GenerateProjectOpenAPIPropertyTests emits one executable JetCheck launcher
// which exercises every checked request and response binding through the real
// native-first OpenAPI facade. Targets cannot narrow the authoritative catalog.
// Examples cover valid, invalid, indeterminate, and native-invalid outcomes.
// Replay selectors bind request values or request/response pairs to one exact
// catalog property. Standalone wire-adapter overrides reject the complete
// generation request instead of being skipped.
func GenerateProjectOpenAPIPropertyTests(project *native.Project,namespace,contractName,facadeName string,options PropertyTestOptions)([]File,error){
    if project==nil||!project.HasOpenAPINativeBindings(){return nil,&GenerationError{Message:"checked native OpenAPI operation bindings are required for operation properties"}};if err:=packageName(namespace);err!=nil{return nil,err};if err:=javaClassName(contractName);err!=nil{return nil,err};if err:=javaClassName(facadeName);err!=nil{return nil,err};if namespace!=project.Metadata().PublicationNamespace{return nil,&GenerationError{Message:"operation property namespace must equal the checked project publication namespace"}};if len(options.Targets)>0{return nil,&GenerationError{Message:"operation property targets are authoritative and cannot be narrowed"}};if options.JSONModule!=""||options.AvroSerde!=""||options.NativeJSONValidator!=""{return nil,&GenerationError{Message:"operation properties use the generated OpenAPI facade; standalone wire adapters are not accepted"}}
    cases:=options.CaseCount;if cases==0{cases=100};attempts:=options.AttemptBudget;if attempts==0{attempts=10000};if cases<1||attempts<1{return nil,&GenerationError{Message:"property case count and attempt budget must be positive"}}
    program,err:=language.Compile(project.EditableSource());if err!=nil{return nil,err};catalog,err:=project.OpenAPIOperationIndex();if err!=nil{return nil,err};if len(catalog.Operations)==0{return nil,&GenerationError{Message:"operation properties require at least one checked operation"}}
    declarations:=map[string]language.TypeDecl{};for _,decl:=range program.Syntax().Types{declarations[decl.Name]=decl};types:=map[string]bool{};generatedTypes:=map[string]bool{};contextTypes:=map[string]bool{};responses:=0;for _,operation:=range catalog.Operations{types[operation.RequestType]=true;if len(operation.RequestParts)>0{generatedTypes[operation.RequestType]=true};for _,response:=range operation.Responses{types[response.TypeExpression]=true;if len(response.Parts)>0{generatedTypes[response.TypeExpression]=true};if response.ContextType!=""{contextTypes[response.ContextType]=true};responses++}};if responses==0{return nil,&GenerationError{Message:"operation properties require at least one response binding"}}
    typeNames:=make([]string,0,len(types));for name:=range types{typeNames=append(typeNames,name)};sort.Strings(typeNames);requestResources,err:=project.OpenAPIValidationResources(native.OpenAPIRequest);if err!=nil{return nil,err};responseResources,err:=project.OpenAPIValidationResources(native.OpenAPIResponse);if err!=nil{return nil,err};names:=openAPINames(program,contractName,facadeName,nativeResourceSlicesEqual(requestResources,responseResources),typeNames)
    seeds:=map[string][]string{};examples:=[]openAPIPropertyExample{};addExample:=func(label,target string,dataSource string,expected PropertyOutcome,nativeExpected PropertyNativeOutcome,codes []string)error{if !types[target]&&!contextTypes[target]{return fmt.Errorf("%s targets %s, which is not an operation request, response, or context type",label,target)};if expected!=ExampleValid&&expected!=ExampleInvalid&&expected!=ExampleIndeterminate{return fmt.Errorf("%s has an invalid expected outcome",label)};if nativeExpected!=ExampleNativeValid&&nativeExpected!=ExampleNativeInvalid{return fmt.Errorf("%s has an invalid native expected outcome",label)};if expected==ExampleValid&&len(codes)>0{return fmt.Errorf("valid %s cannot require diagnostics",label)};if expected==ExampleInvalid&&len(codes)!=1{return fmt.Errorf("invalid %s must require exactly one diagnostic code",label)};for _,code:=range codes{if code==""{return fmt.Errorf("%s has an empty diagnostic code",label)}};if nativeExpected==ExampleNativeInvalid&&(expected!=ExampleValid||len(codes)>0){return fmt.Errorf("native-invalid %s must be Refine-valid and cannot claim refinement diagnostics",label)};if expected==ExampleValid&&nativeExpected==ExampleNativeValid&&types[target]{seeds[target]=append(seeds[target],dataSource)};examples=append(examples,openAPIPropertyExample{label:label,target:target,source:dataSource,expected:expected,nativeExpected:nativeExpected,codes:append([]string(nil),codes...)});return nil};checked,err:=native.CheckExamples(program,project.Metadata().Examples);if err!=nil{return nil,err};for _,example:=range checked{source,sourceErr:=exampleDataJava(example.Value);if sourceErr!=nil{return nil,sourceErr};expected:=ExampleValid;if example.Expected==native.ExpectedInvalid{expected=ExampleInvalid};nativeExpected:=ExampleNativeValid;if example.NativeExpected==native.NativeExpectedInvalid{nativeExpected=ExampleNativeInvalid};if err:=addExample("embedded example "+example.Name,example.Target,source,expected,nativeExpected,example.DiagnosticCodes);err!=nil{return nil,err}};for index,example:=range options.Examples{source,sourceErr:=exampleDataJava(example.Value);if sourceErr!=nil{return nil,sourceErr};if err:=addExample(fmt.Sprintf("caller example %d",index),example.Target,source,example.Expected,example.NativeExpected,example.DiagnosticCodes);err!=nil{return nil,err}}
    replayValues:=map[string]string{};for i,replay:=range options.Replays{if replay.Target==""||replay.SerializedData==""{return nil,fmt.Errorf("operation replay %d requires a target and serialized data",i)};if replay.Kind!=ReplayValid&&replay.Kind!=ReplayInvalid{return nil,fmt.Errorf("operation replay %d has invalid kind",i)};if replay.Kind==ReplayValid&&replay.DiagnosticCode!=""{return nil,fmt.Errorf("valid operation replay %d must not name a diagnostic",i)};if replay.Kind==ReplayInvalid&&replay.DiagnosticCode==""{return nil,fmt.Errorf("invalid operation replay %d requires a diagnostic code",i)};key:=replayKey(replay.Target,replay.Kind,replay.DiagnosticCode);if _,exists:=replayValues[key];exists{return nil,fmt.Errorf("duplicate operation replay selector %s",replay.Target)};replayValues[key]=replay.SerializedData};emittedReplays:=map[string]bool{};usedReplays:=map[string]bool{};propertyReplay:=func(target string,kind ReplayKind,code string)(string,error){key:=replayKey(target,kind,code);if emittedReplays[key]{return "",fmt.Errorf("operation property selector %s is ambiguous for diagnostic %s",target,code)};emittedReplays[key]=true;if value,ok:=replayValues[key];ok{usedReplays[key]=true;return value,nil};return "",nil}
    emitter:=&propertyEmitter{declarations:declarations,visiting:map[string]bool{}};generators:=map[string]string{};for _,name:=range typeNames{decl,ok:=declarations[name];if !ok||len(decl.Parameters)>0{return nil,&GenerationError{Message:"operation property target must be a closed declaration: "+name}};if !generatedTypes[name]{continue};typ:=decl.Body;if typ==nil{typ=&language.Type{Form:language.NamedType(name),At:decl.At}};raw,genErr:=emitter.boundedGenerator(typ);if genErr!=nil{return nil,fmt.Errorf("operation property target %s: %w",name,genErr)};generators[name]=seededPropertyGenerator(raw,seeds[name])}
    codecFields:=[]string{};codecField:=map[string]string{};for _,name:=range typeNames{field:="CODEC"+fmt.Sprint(len(codecFields));codecField[name]=field;codecFields=append(codecFields,"    private static final "+names.codecs[name]+" "+field+"=new "+names.codecs[name]+"();")}
    var methods strings.Builder;calls:=[]string{};pairIndex:=0;requestOccurrences:=map[string][]int{};responseOccurrences:=map[string][]openAPIResponseProperty{};contextOccurrences:=map[string][]openAPIResponseProperty{}
    for opIndex,operation:=range catalog.Operations{
        requestOccurrences[operation.RequestType]=append(requestOccurrences[operation.RequestType],opIndex);requestMethod:=fmt.Sprintf("request%d",opIndex);requestGenerator:=generators[operation.RequestType];if len(operation.RequestParts)==0{if auditErr:=openAPITransportEnvelope(declarations,operation.RequestType,true);auditErr!=nil{return nil,&GenerationError{Message:auditErr.Error()}};requestGenerator=openAPITransportGenerator(codecField[operation.RequestType],true)}
        fmt.Fprintf(&methods,"    private static %s.RequestJSON %s(Data data){var root=parse(%s.writeDataWithoutRefinements(data));var parameters=new java.util.ArrayList<%s.ParameterJSON>();var headers=new java.util.ArrayList<%s.HeaderJSON>();%s.MediaJSON body=null;\n",facadeName,requestMethod,codecField[operation.RequestType],facadeName,facadeName,facadeName)
        for partIndex,target:=range operation.RequestParts{variable:=fmt.Sprintf("part%d",partIndex);fmt.Fprintf(&methods,"        var %s=%s;",variable,openAPIPropertyPart("root",target));switch target.In{case "body":fmt.Fprintf(&methods,"if(%s!=null)body=new %s.MediaJSON(%s,%s);",variable,facadeName,javaQuote(target.MediaType),variable);case "header":fmt.Fprintf(&methods,"if(%s!=null)headers.add(new %s.HeaderJSON(%s,%s));",variable,facadeName,javaQuote(target.Name),variable);default:fmt.Fprintf(&methods,"if(%s!=null)parameters.add(new %s.ParameterJSON(%s,%s,%s));",variable,facadeName,javaQuote(target.In),javaQuote(target.Name),variable)}}
        fmt.Fprintf(&methods,"return new %s.RequestJSON(parameters,headers,body);}\n",facadeName)
        fmt.Fprintf(&methods,"    private static boolean requestCandidate%d(Data data){try{var token=FACADE.validateRequest(%s,%s(data));return token.data().equals(data);}catch(%s.OpenAPILimitException failure){throw failure;}catch(%s.NativeValidationException failure){if(failure.isIndeterminate())throw failure;return false;}catch(ValidationException failure){if(failure.outcome().incomplete())throw failure;return false;}}\n",opIndex,javaQuote(operation.OperationID),requestMethod,facadeName,names.sidecar)
        fmt.Fprintf(&methods,"    private static boolean requestInvalidCandidate%d(Data data,String code,String predicate,String enclosing,int offset,boolean automatic,String... paths){if(!targeted(%s.validate(%s,data),code,predicate,enclosing,offset,automatic,paths))return false;try{FACADE.validateRequest(%s,%s(data));return false;}catch(%s.OpenAPILimitException failure){throw failure;}catch(%s.NativeValidationException failure){if(failure.isIndeterminate()||failure.code()!=%s.Code.INVALID)throw failure;return true;}catch(ValidationException failure){return rejected(failure.outcome());}}\n",opIndex,contractName,javaQuote(operation.RequestType),javaQuote(operation.OperationID),requestMethod,facadeName,names.sidecar,names.sidecar)
        fmt.Fprintf(&methods,"    private static boolean requestExample%d(Data data,Validation.State expected,boolean nativeInvalid,String... codes){try{var token=FACADE.validateRequest(%s,%s(data));return !nativeInvalid&&expected==Validation.State.VALID&&token.data().equals(data);}catch(%s.OpenAPILimitException failure){throw failure;}catch(%s.NativeValidationException failure){if(failure.isIndeterminate())throw failure;return nativeInvalid&&failure.code()==%s.Code.INVALID;}catch(ValidationException failure){return !nativeInvalid&&matchesOutcome(failure.outcome(),expected,codes);}}\n",opIndex,javaQuote(operation.OperationID),requestMethod,facadeName,names.sidecar,names.sidecar)
        requestRules,ruleErr:=openAPIPropertyRules(emitter,declarations,operation.RequestType);if ruleErr!=nil{return nil,ruleErr};requestSelector:=OpenAPIRequestReplayTarget(operation.OperationID);validReplay,replayErr:=propertyReplay(requestSelector,ReplayValid,"");if replayErr!=nil{return nil,replayErr};requestItems:=[]openAPIPropertyRule{};requestBases:=[]string{};for _,rule:=range requestRules{requestItems=append(requestItems,openAPIPropertyRule{rule:rule,role:"request"});requestBases=append(requestBases,requestSelector)};requestCounts:=propertyRuleReplayCounts(requestItems,requestBases);requestSeen:=map[string]bool{};var invalid strings.Builder;for ruleIndex,rule:=range requestRules{selector,selectorErr:=propertyRuleReplaySelector(requestSelector,rule,requestCounts,replayValues,requestSeen);if selectorErr!=nil{return nil,selectorErr};replay,replayErr:=propertyReplay(selector,ReplayInvalid,rule.code);if replayErr!=nil{return nil,replayErr};arguments:=propertyRuleArguments(rule);fmt.Fprintf(&invalid,"var invalid%d=requiring(raw,d->requestInvalidCandidate%d(d,%s),ATTEMPTS,%s);check(invalid%d,d->requestInvalidCandidate%d(d,%s),%s);",ruleIndex,opIndex,arguments,javaQuote("invalid request "+operation.OperationID+" "+rule.code+" "+strings.Join(rule.paths,",")),ruleIndex,opIndex,arguments,javaQuote(replay))}
        fmt.Fprintf(&methods,"    private static void requestProperty%d(){var raw=%s;var valid=requiring(raw,%sGeneratedProperties::requestCandidate%d,ATTEMPTS,%s);check(valid,data->{var token=FACADE.validateRequest(%s,%s(data));return token.operationId().equals(%s)&&token.data().equals(data);},%s);%s}\n",opIndex,requestGenerator,contractName,opIndex,javaQuote("request "+operation.OperationID),javaQuote(operation.OperationID),requestMethod,javaQuote(operation.OperationID),javaQuote(validReplay),invalid.String());calls=append(calls,fmt.Sprintf("requestProperty%d();",opIndex))
        for _,response:=range operation.Responses{
            status,statusErr:=openAPIPropertyStatus(operation,response);if statusErr!=nil{return nil,statusErr};responseGenerator:=generators[response.TypeExpression];responseExact:="";if len(response.Parts)==0{if auditErr:=openAPITransportEnvelope(declarations,response.TypeExpression,false);auditErr!=nil{return nil,&GenerationError{Message:auditErr.Error()}};responseGenerator=openAPITransportGenerator(codecField[response.TypeExpression],false);responseExact="if(!pair.response().equals("+openAPITransportData(codecField[response.TypeExpression],false)+"))return false;"};occurrence:=openAPIResponseProperty{index:pairIndex,operation:opIndex,target:response.TypeExpression,requestGenerator:requestGenerator};responseOccurrences[response.TypeExpression]=append(responseOccurrences[response.TypeExpression],occurrence);if response.ContextType!=""{contextOccurrences[response.ContextType]=append(contextOccurrences[response.ContextType],occurrence)};responseMethod:=fmt.Sprintf("response%d",pairIndex)
            fmt.Fprintf(&methods,"    private static %s.ResponseJSON %s(Data data){var root=parse(%s.writeDataWithoutRefinements(data));var headers=new java.util.ArrayList<%s.HeaderJSON>();%s.MediaJSON body=null;\n",facadeName,responseMethod,codecField[response.TypeExpression],facadeName,facadeName);for partIndex,target:=range response.Parts{variable:=fmt.Sprintf("part%d",partIndex);fmt.Fprintf(&methods,"        var %s=%s;",variable,openAPIPropertyPart("root",target));if target.In=="body"{fmt.Fprintf(&methods,"if(%s!=null)body=new %s.MediaJSON(%s,%s);",variable,facadeName,javaQuote(target.MediaType),variable)}else{fmt.Fprintf(&methods,"if(%s!=null)headers.add(new %s.HeaderJSON(%s,%s));",variable,facadeName,javaQuote(target.Name),variable)}};fmt.Fprintf(&methods,"return new %s.ResponseJSON(%s,headers,body);}\n",facadeName,javaQuote(status));fmt.Fprintf(&methods,"    private record Pair%d(Data request,Data response){}\n",pairIndex)
            fmt.Fprintf(&methods,"    private static boolean responseCandidate%d(Pair%d pair){try{var token=FACADE.validateRequest(%s,%s(pair.request()));var outcome=FACADE.validateResponse(%s,%s(pair.response()),token);if(outcome.incomplete())throw new AssertionError(\"operation response validation was indeterminate\");return outcome.state()==Validation.State.VALID;}catch(%s.OpenAPILimitException failure){throw failure;}catch(%s.NativeValidationException failure){if(failure.isIndeterminate())throw failure;return false;}catch(ValidationException failure){if(failure.outcome().incomplete())throw failure;return false;}}\n",pairIndex,pairIndex,javaQuote(operation.OperationID),requestMethod,javaQuote(operation.OperationID),responseMethod,facadeName,names.sidecar)
            fmt.Fprintf(&methods,"    private static boolean responseInvalidCandidate%d(Pair%d pair,String target,Data logical,String code,String predicate,String enclosing,int offset,boolean automatic,String... paths){if(!targeted(%s.validate(target,logical),code,predicate,enclosing,offset,automatic,paths))return false;%s.ValidatedRequest token;try{token=FACADE.validateRequest(%s,%s(pair.request()));}catch(%s.OpenAPILimitException failure){throw failure;}catch(%s.NativeValidationException failure){if(failure.isIndeterminate())throw failure;return false;}catch(ValidationException failure){if(failure.outcome().incomplete())throw failure;return false;}try{return rejected(FACADE.validateResponse(%s,%s(pair.response()),token));}catch(%s.OpenAPILimitException failure){throw failure;}catch(%s.NativeValidationException failure){if(failure.isIndeterminate()||failure.code()!=%s.Code.INVALID)throw failure;return true;}catch(ValidationException failure){return rejected(failure.outcome());}}\n",pairIndex,pairIndex,contractName,facadeName,javaQuote(operation.OperationID),requestMethod,facadeName,names.sidecar,javaQuote(operation.OperationID),responseMethod,facadeName,names.sidecar,names.sidecar)
            fmt.Fprintf(&methods,"    private static boolean responseExample%d(Pair%d pair,Validation.State expected,boolean nativeInvalid,String... codes){%s%s.ValidatedRequest token;try{token=FACADE.validateRequest(%s,%s(pair.request()));}catch(%s.OpenAPILimitException failure){throw failure;}catch(%s.NativeValidationException failure){if(failure.isIndeterminate())throw failure;return false;}catch(ValidationException failure){if(failure.outcome().incomplete())throw failure;return false;}try{var outcome=FACADE.validateResponse(%s,%s(pair.response()),token);return !nativeInvalid&&matchesOutcome(outcome,expected,codes);}catch(%s.OpenAPILimitException failure){throw failure;}catch(%s.NativeValidationException failure){if(failure.isIndeterminate())throw failure;return nativeInvalid&&failure.code()==%s.Code.INVALID;}}\n",pairIndex,pairIndex,responseExact,facadeName,javaQuote(operation.OperationID),requestMethod,facadeName,names.sidecar,javaQuote(operation.OperationID),responseMethod,facadeName,names.sidecar,names.sidecar)
            fmt.Fprintf(&methods,"    private static boolean contextExample%d(Pair%d pair,Validation.State expected,boolean nativeInvalid,String... codes){%s%s.ValidatedRequest token;try{token=FACADE.validateRequest(%s,%s(pair.request()));}catch(%s.OpenAPILimitException failure){throw failure;}catch(%s.NativeValidationException failure){if(failure.isIndeterminate())throw failure;return nativeInvalid&&failure.code()==%s.Code.INVALID;}catch(ValidationException failure){if(failure.outcome().incomplete())throw failure;return false;}try{var outcome=FACADE.validateResponse(%s,%s(pair.response()),token);return !nativeInvalid&&matchesOutcome(outcome,expected,codes);}catch(%s.OpenAPILimitException failure){throw failure;}catch(%s.NativeValidationException failure){if(failure.isIndeterminate())throw failure;return nativeInvalid&&failure.code()==%s.Code.INVALID;}}\n",pairIndex,pairIndex,responseExact,facadeName,javaQuote(operation.OperationID),requestMethod,facadeName,names.sidecar,names.sidecar,javaQuote(operation.OperationID),responseMethod,facadeName,names.sidecar,names.sidecar)
            responseRules,ruleErr:=openAPIPropertyRules(emitter,declarations,response.TypeExpression);if ruleErr!=nil{return nil,ruleErr};rules:=[]openAPIPropertyRule{};for _,rule:=range responseRules{rules=append(rules,openAPIPropertyRule{rule:rule,role:"response"})};if response.ContextType!=""{contextRules,contextErr:=openAPIPropertyRules(emitter,declarations,response.ContextType);if contextErr!=nil{return nil,contextErr};rules=classifyOpenAPIContextRules(contextRules,requestRules,responseRules)};validSelector:=OpenAPIResponseReplayTarget(operation.OperationID,response.Status);if response.ContextType!=""{validSelector=OpenAPIContextReplayTarget(operation.OperationID,response.Status)};validReplay,replayErr:=propertyReplay(validSelector,ReplayValid,"");if replayErr!=nil{return nil,replayErr};bases:=make([]string,len(rules));for i,item:=range rules{bases[i]=OpenAPIResponseReplayTarget(operation.OperationID,response.Status);if item.role=="context"{bases[i]=OpenAPIContextReplayTarget(operation.OperationID,response.Status)}};counts:=propertyRuleReplayCounts(rules,bases);seen:=map[string]bool{};var responseInvalid strings.Builder;for ruleIndex,item:=range rules{selector,selectorErr:=propertyRuleReplaySelector(bases[ruleIndex],item.rule,counts,replayValues,seen);if selectorErr!=nil{return nil,selectorErr};replay,replayErr:=propertyReplay(selector,ReplayInvalid,item.rule.code);if replayErr!=nil{return nil,replayErr};logicalType:=response.TypeExpression;logicalValue:="p.response()";if item.role=="context"{logicalType=response.ContextType;logicalValue="new Data.Struct(java.util.List.of(new Data.Field(\"request\",p.request()),new Data.Field(\"response\",p.response())))"};arguments:=javaQuote(logicalType)+","+logicalValue+","+propertyRuleArguments(item.rule);fmt.Fprintf(&responseInvalid,"var invalid%d=requiring(raw,p->responseInvalidCandidate%d(p,%s),ATTEMPTS,%s);check(invalid%d,p->responseInvalidCandidate%d(p,%s),%s);",ruleIndex,pairIndex,arguments,javaQuote("invalid "+item.role+" "+operation.OperationID+" "+response.Status+" "+item.rule.code+" "+strings.Join(item.rule.paths,",")),ruleIndex,pairIndex,arguments,javaQuote(replay))}
            label:="response "+operation.OperationID+" "+response.Status;if response.ContextType!=""{label="context "+operation.OperationID+" "+response.Status};fmt.Fprintf(&methods,"    private static void responseProperty%d(){var raw=org.jetbrains.jetCheck.Generator.zipWith(%s,%s,Pair%d::new);var valid=requiring(raw,%sGeneratedProperties::responseCandidate%d,ATTEMPTS,%s);check(valid,pair->{var token=FACADE.validateRequest(%s,%s(pair.request()));return FACADE.validateResponse(%s,%s(pair.response()),token).state()==Validation.State.VALID;},%s);%s}\n",pairIndex,requestGenerator,responseGenerator,pairIndex,contractName,pairIndex,javaQuote(label),javaQuote(operation.OperationID),requestMethod,javaQuote(operation.OperationID),responseMethod,javaQuote(validReplay),responseInvalid.String());calls=append(calls,fmt.Sprintf("responseProperty%d();",pairIndex));pairIndex++
        }
    }
    for exampleIndex,example:=range examples{method:=fmt.Sprintf("example%d",exampleIndex);state:="VALID";if example.expected==ExampleInvalid{state="INVALID"}else if example.expected==ExampleIndeterminate{state="INDETERMINATE"};args:="Validation.State."+state+","+fmt.Sprint(example.nativeExpected==ExampleNativeInvalid);for _,code:=range example.codes{args+=","+javaQuote(code)};fmt.Fprintf(&methods,"    private static void %s(){var data=%s;",method,example.source);if example.nativeExpected==ExampleNativeInvalid{fmt.Fprintf(&methods,"if(!matchesOutcome(%s.validate(%s,data),Validation.State.VALID))throw new AssertionError(%s);",contractName,javaQuote(example.target),javaQuote(example.label+" declared Refine-valid outcome"))};covered:=0;for _,operationIndex:=range requestOccurrences[example.target]{fmt.Fprintf(&methods,"if(!requestExample%d(data,%s))throw new AssertionError(%s);",operationIndex,args,javaQuote(example.label+" request boundary"));covered++};for _,occurrence:=range responseOccurrences[example.target]{fmt.Fprintf(&methods,"var compatible%d=requiring(%s,request->responseExample%d(new Pair%d(request,data),%s),ATTEMPTS,%s);checkExample(compatible%d,request->responseExample%d(new Pair%d(request,data),%s));",covered,occurrence.requestGenerator,occurrence.index,occurrence.index,args,javaQuote(example.label+" compatible request context"),covered,occurrence.index,occurrence.index,args);covered++};for _,occurrence:=range contextOccurrences[example.target]{fmt.Fprintf(&methods,"var pair%d=new Pair%d(contextField(data,\"request\"),contextField(data,\"response\"));if(!contextExample%d(pair%d,%s))throw new AssertionError(%s);",covered,occurrence.index,occurrence.index,covered,args,javaQuote(example.label+" context boundary"));covered++};if covered==0{return nil,&GenerationError{Message:example.label+" has no checked operation occurrence"}};methods.WriteString("}\n");calls=append(calls,method+"();")}
    for key:=range replayValues{if !usedReplays[key]{return nil,&GenerationError{Message:"operation replay does not match exactly one generated catalog property"}}}
    class:=contractName+"GeneratedProperties";header:="// Generated by Refine: OpenAPI JetCheck 0.3.0 operation properties.\n";if namespace!=""{header+="package "+namespace+";\n"};source:=header+fmt.Sprintf(`@SuppressWarnings("deprecation")
public final class %s {
    private static final int CASES=%d,ATTEMPTS=%d;private static final long SEED=%dL;
    private static final %s FACADE=new %s();
%s
    private static final tools.jackson.databind.json.JsonMapper TREE=tools.jackson.databind.json.JsonMapper.builder().enable(tools.jackson.databind.DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS,tools.jackson.databind.DeserializationFeature.USE_BIG_INTEGER_FOR_INTS).build();
    private static tools.jackson.databind.JsonNode parse(byte[] raw){return TREE.readTree(raw);}
    private static byte[] part(tools.jackson.databind.JsonNode root,String... path){var value=root;for(var name:path){if(value==null||!value.isObject())return null;value=value.get(name);}return value==null?null:TREE.writeValueAsBytes(value);}
    private static <T> org.jetbrains.jetCheck.Generator<T> requiring(org.jetbrains.jetCheck.Generator<T> raw,java.util.function.Predicate<T> wanted,int attempts,String label){return org.jetbrains.jetCheck.Generator.from(env->{for(int i=0;i<attempts;i++){T value=env.generate(raw);if(wanted.test(value)){env.generate(org.jetbrains.jetCheck.Generator.integers());return value;}}throw new AssertionError("property generation exhausted: "+label+" after "+attempts+" attempts");});}
    private static <T> void check(org.jetbrains.jetCheck.Generator<T> generator,java.util.function.Predicate<T> property,String replay){if(replay.isEmpty())org.jetbrains.jetCheck.PropertyChecker.customized().withSeed(SEED).withIterationCount(CASES).silent().forAll(generator,property);else org.jetbrains.jetCheck.PropertyChecker.customized().rechecking(replay).silent().forAll(generator,property);}
    private static <T> void checkExample(org.jetbrains.jetCheck.Generator<T> generator,java.util.function.Predicate<T> property){org.jetbrains.jetCheck.PropertyChecker.customized().withSeed(SEED).withIterationCount(1).silent().forAll(generator,property);}
    // Invalid properties require dual evidence: the checked logical contract
    // identifies the exact clause occurrence, then the native-first facade
    // rejects the same request or response at either enforcement layer.
    private static boolean pathPattern(String actual,String pattern){var found=actual.split("/",-1);var expected=pattern.split("/",-1);if(found.length!=expected.length)return false;for(int i=0;i<found.length;i++)if(!expected[i].equals("~2")&&!found[i].equals(expected[i]))return false;return true;}
    private static boolean diagnosticPaths(java.util.List<String> actual,String... patterns){if(actual.size()!=patterns.length)return false;for(int i=0;i<patterns.length;i++)if(!pathPattern(actual.get(i),patterns[i]))return false;return true;}
    private static String concreteEnclosing(String pattern,String actual){var found=actual.split("/",-1);var expected=pattern.split("/",-1);if(found.length<expected.length)return null;var result=new String[expected.length];for(int i=0;i<expected.length;i++){if(expected[i].equals("~2"))result[i]=found[i];else if(found[i].equals(expected[i]))result[i]=expected[i];else return null;}return String.join("/",result);}
    private static String automaticCode(String path,int offset,String predicate){try{var digest=java.security.MessageDigest.getInstance("SHA-256").digest((path+":"+offset+":"+predicate).getBytes(java.nio.charset.StandardCharsets.UTF_8));return "refine."+java.util.HexFormat.of().formatHex(digest,0,8);}catch(java.security.NoSuchAlgorithmException impossible){throw new AssertionError(impossible);}}
    private static boolean targeted(Validation.Outcome outcome,String code,String predicate,String enclosing,int offset,boolean automatic,String... paths){if(outcome.incomplete()||outcome.state()==Validation.State.INDETERMINATE)throw new AssertionError("operation validation was indeterminate");return outcome.state()==Validation.State.INVALID&&outcome.diagnostics().stream().anyMatch(d->{if(!d.predicate().equals(predicate)||!diagnosticPaths(d.paths(),paths))return false;if(!automatic)return d.code().equals(code);var concrete=concreteEnclosing(enclosing,d.paths().getFirst());return concrete!=null&&d.code().equals(automaticCode(concrete,offset,predicate));});}
    private static boolean rejected(Validation.Outcome outcome){if(outcome.incomplete()||outcome.state()==Validation.State.INDETERMINATE)throw new AssertionError("operation validation was indeterminate");return outcome.state()==Validation.State.INVALID;}
    private static boolean matchesOutcome(Validation.Outcome outcome,Validation.State state,String... codes){if(outcome.state()!=state)return false;if(state!=Validation.State.INDETERMINATE&&outcome.incomplete())return false;for(var code:codes)if(outcome.diagnostics().stream().noneMatch(d->d.code().equals(code)))return false;return true;}
    private static Data contextField(Data data,String name){if(!(data instanceof Data.Struct record)||record.fields().size()!=2)throw new AssertionError("operation context example must contain exactly request and response");Data found=null;for(var field:record.fields()){if(!field.name().equals("request")&&!field.name().equals("response"))throw new AssertionError("operation context example has an unknown field");if(field.name().equals(name)){if(found!=null)throw new AssertionError("duplicate operation context field");found=field.value();}}if(found==null)throw new AssertionError("operation context example lacks "+name);return found;}
%s
    public static void main(String[] args){%s}
}
`,class,cases,attempts,options.Seed,facadeName,facadeName,strings.Join(codecFields,"\n"),methods.String(),strings.Join(calls," "));return []File{{Path:path.Join(strings.ReplaceAll(namespace,".","/"),class+".java"),Source:source}},nil
}
