package java

import (
    "fmt"
    "path"
    "sort"
    "strings"

    "goforge.dev/refine/language"
    "goforge.dev/refine/native"
)

type openAPIPropertyExample struct { label string; target string; source string }
type openAPIResponseProperty struct { index int; operation int; target string; requestGenerator string }
type openAPIPropertyRule struct { rule propertyRule; role string }

func openAPIPropertyRules(emitter *propertyEmitter,declarations map[string]language.TypeDecl,name string)([]propertyRule,error){decl,ok:=declarations[name];if !ok||len(decl.Parameters)>0{return nil,fmt.Errorf("operation property target %s must be a closed declaration",name)};typ:=decl.Body;if typ==nil{typ=&language.Type{Form:language.NamedType(name),At:decl.At}};return emitter.rules(name,"",typ)}

func openAPIPropertyStatus(operation native.OpenAPIOperation,response native.OpenAPIResponseOperation)(string,error){
    raw:=response.Status;if len(raw)==3&&raw[0]>='1'&&raw[0]<='5'&&raw[1]>='0'&&raw[1]<='9'&&raw[2]>='0'&&raw[2]<='9'{return raw,nil};exact:=map[string]bool{};classes:=map[string]bool{};for _,item:=range operation.Responses{if len(item.Status)==3&&item.Status[1:]!="XX"{exact[item.Status]=true}else if len(item.Status)==3&&item.Status[1:]=="XX"{classes[item.Status[:1]]=true}}
    if len(raw)==3&&raw[1:]=="XX"{for code:=100;code<=599;code++{candidate:=fmt.Sprint(code);if candidate[:1]==raw[:1]&&!exact[candidate]{return candidate,nil}};return "",fmt.Errorf("response class %s has no representative status",raw)}
    if raw=="default"{for code:=100;code<=599;code++{candidate:=fmt.Sprint(code);if !exact[candidate]&&!classes[candidate[:1]]{return candidate,nil}};return "",fmt.Errorf("default response has no representative status")};return "",fmt.Errorf("unsupported response status binding %s",raw)
}

func openAPIPropertyPart(root string,target native.OpenAPISchemaTarget)string{parts:=[]string{root};for _,item:=range target.FieldPath{parts=append(parts,javaQuote(item))};return "part("+strings.Join(parts,",")+")"}

// GenerateProjectOpenAPIPropertyTests emits one executable JetCheck launcher
// which exercises every checked request and response binding through the real
// native-first OpenAPI facade. Targets cannot narrow the authoritative catalog.
// This first version accepts valid examples only; invalid/indeterminate
// examples, replay pairs, and standalone wire-adapter overrides reject the
// complete generation request instead of being skipped.
func GenerateProjectOpenAPIPropertyTests(project *native.Project,namespace,contractName,facadeName string,options PropertyTestOptions)([]File,error){
    if project==nil||!project.HasOpenAPINativeBindings(){return nil,&GenerationError{Message:"checked native OpenAPI operation bindings are required for operation properties"}};if err:=packageName(namespace);err!=nil{return nil,err};if err:=javaClassName(contractName);err!=nil{return nil,err};if err:=javaClassName(facadeName);err!=nil{return nil,err};if namespace!=project.Metadata().PublicationNamespace{return nil,&GenerationError{Message:"operation property namespace must equal the checked project publication namespace"}};if len(options.Targets)>0{return nil,&GenerationError{Message:"operation property targets are authoritative and cannot be narrowed"}};if len(options.Replays)>0{return nil,&GenerationError{Message:"operation property replay pairs are not supported by this generator version"}};if options.JSONModule!=""||options.AvroSerde!=""||options.NativeJSONValidator!=""{return nil,&GenerationError{Message:"operation properties use the generated OpenAPI facade; standalone wire adapters are not accepted"}}
    cases:=options.CaseCount;if cases==0{cases=100};attempts:=options.AttemptBudget;if attempts==0{attempts=10000};if cases<1||attempts<1{return nil,&GenerationError{Message:"property case count and attempt budget must be positive"}}
    program,err:=language.Compile(project.EditableSource());if err!=nil{return nil,err};catalog,err:=project.OpenAPIOperationIndex();if err!=nil{return nil,err};if len(catalog.Operations)==0{return nil,&GenerationError{Message:"operation properties require at least one checked operation"}}
    declarations:=map[string]language.TypeDecl{};for _,decl:=range program.Syntax().Types{declarations[decl.Name]=decl};types:=map[string]bool{};parts:=0;responses:=0;for _,operation:=range catalog.Operations{types[operation.RequestType]=true;parts+=len(operation.RequestParts);for _,response:=range operation.Responses{types[response.TypeExpression]=true;parts+=len(response.Parts);responses++}};if parts==0{return nil,&GenerationError{Message:"operation properties require at least one semantic native part"}};if responses==0{return nil,&GenerationError{Message:"operation properties require at least one response binding"}}
    typeNames:=make([]string,0,len(types));for name:=range types{typeNames=append(typeNames,name)};sort.Strings(typeNames);requestResources,err:=project.OpenAPIValidationResources(native.OpenAPIRequest);if err!=nil{return nil,err};responseResources,err:=project.OpenAPIValidationResources(native.OpenAPIResponse);if err!=nil{return nil,err};names:=openAPINames(program,contractName,facadeName,nativeResourceSlicesEqual(requestResources,responseResources),typeNames)
    seeds:=map[string][]string{};examples:=[]openAPIPropertyExample{};addExample:=func(label,target string,dataSource string,expected PropertyOutcome,nativeExpected PropertyNativeOutcome,codes []string)error{if !types[target]{return fmt.Errorf("%s targets %s, which is not an operation request or response type",label,target)};if expected!=ExampleValid||nativeExpected!=ExampleNativeValid||len(codes)!=0{return fmt.Errorf("%s uses an outcome not faithfully representable by operation pair properties",label)};seeds[target]=append(seeds[target],dataSource);examples=append(examples,openAPIPropertyExample{label:label,target:target,source:dataSource});return nil};checked,err:=native.CheckExamples(program,project.Metadata().Examples);if err!=nil{return nil,err};for _,example:=range checked{source,sourceErr:=exampleDataJava(example.Value);if sourceErr!=nil{return nil,sourceErr};expected:=ExampleValid;if example.Expected==native.ExpectedInvalid{expected=ExampleInvalid};nativeExpected:=ExampleNativeValid;if example.NativeExpected==native.NativeExpectedInvalid{nativeExpected=ExampleNativeInvalid};if err:=addExample("embedded example "+example.Name,example.Target,source,expected,nativeExpected,example.DiagnosticCodes);err!=nil{return nil,err}};for index,example:=range options.Examples{source,sourceErr:=exampleDataJava(example.Value);if sourceErr!=nil{return nil,sourceErr};if err:=addExample(fmt.Sprintf("caller example %d",index),example.Target,source,example.Expected,example.NativeExpected,example.DiagnosticCodes);err!=nil{return nil,err}}
    emitter:=&propertyEmitter{declarations:declarations,visiting:map[string]bool{}};generators:=map[string]string{};for _,name:=range typeNames{decl,ok:=declarations[name];if !ok||len(decl.Parameters)>0{return nil,&GenerationError{Message:"operation property target must be a closed declaration: "+name}};typ:=decl.Body;if typ==nil{typ=&language.Type{Form:language.NamedType(name),At:decl.At}};raw,genErr:=emitter.boundedGenerator(typ);if genErr!=nil{return nil,fmt.Errorf("operation property target %s: %w",name,genErr)};generators[name]=seededPropertyGenerator(raw,seeds[name])}
    codecFields:=[]string{};codecField:=map[string]string{};for _,name:=range typeNames{field:="CODEC"+fmt.Sprint(len(codecFields));codecField[name]=field;codecFields=append(codecFields,"    private static final "+names.codecs[name]+" "+field+"=new "+names.codecs[name]+"();")}
    var methods strings.Builder;calls:=[]string{};pairIndex:=0;requestOccurrences:=map[string][]int{};responseOccurrences:=map[string][]openAPIResponseProperty{}
    for opIndex,operation:=range catalog.Operations{
        requestOccurrences[operation.RequestType]=append(requestOccurrences[operation.RequestType],opIndex);requestMethod:=fmt.Sprintf("request%d",opIndex)
        fmt.Fprintf(&methods,"    private static %s.RequestJSON %s(Data data){var root=parse(%s.writeDataWithoutRefinements(data));var parameters=new java.util.ArrayList<%s.ParameterJSON>();var headers=new java.util.ArrayList<%s.HeaderJSON>();%s.MediaJSON body=null;\n",facadeName,requestMethod,codecField[operation.RequestType],facadeName,facadeName,facadeName)
        for partIndex,target:=range operation.RequestParts{variable:=fmt.Sprintf("part%d",partIndex);fmt.Fprintf(&methods,"        var %s=%s;",variable,openAPIPropertyPart("root",target));switch target.In{case "body":fmt.Fprintf(&methods,"if(%s!=null)body=new %s.MediaJSON(%s,%s);",variable,facadeName,javaQuote(target.MediaType),variable);case "header":fmt.Fprintf(&methods,"if(%s!=null)headers.add(new %s.HeaderJSON(%s,%s));",variable,facadeName,javaQuote(target.Name),variable);default:fmt.Fprintf(&methods,"if(%s!=null)parameters.add(new %s.ParameterJSON(%s,%s,%s));",variable,facadeName,javaQuote(target.In),javaQuote(target.Name),variable)}}
        fmt.Fprintf(&methods,"return new %s.RequestJSON(parameters,headers,body);}\n",facadeName)
        fmt.Fprintf(&methods,"    private static boolean requestCandidate%d(Data data){try{var token=FACADE.validateRequest(%s,%s(data));return token.data().equals(data);}catch(%s.OpenAPILimitException failure){throw failure;}catch(%s.NativeValidationException failure){if(failure.isIndeterminate())throw failure;return false;}catch(ValidationException failure){if(failure.outcome().incomplete())throw failure;return false;}}\n",opIndex,javaQuote(operation.OperationID),requestMethod,facadeName,names.sidecar)
        fmt.Fprintf(&methods,"    private static boolean requestInvalidCandidate%d(Data data,String code){try{FACADE.validateRequest(%s,%s(data));return false;}catch(%s.OpenAPILimitException failure){throw failure;}catch(%s.NativeValidationException failure){if(failure.isIndeterminate())throw failure;return false;}catch(ValidationException failure){return targeted(failure.outcome(),code);}}\n",opIndex,javaQuote(operation.OperationID),requestMethod,facadeName,names.sidecar)
        requestRules,ruleErr:=openAPIPropertyRules(emitter,declarations,operation.RequestType);if ruleErr!=nil{return nil,ruleErr};var invalid strings.Builder;for ruleIndex,rule:=range requestRules{fmt.Fprintf(&invalid,"var invalid%d=requiring(raw,d->requestInvalidCandidate%d(d,%s),ATTEMPTS,%s);check(invalid%d,d->requestInvalidCandidate%d(d,%s));",ruleIndex,opIndex,javaQuote(rule.code),javaQuote("invalid request "+operation.OperationID+" "+rule.code),ruleIndex,opIndex,javaQuote(rule.code))}
        fmt.Fprintf(&methods,"    private static void requestProperty%d(){var raw=%s;var valid=requiring(raw,%sGeneratedProperties::requestCandidate%d,ATTEMPTS,%s);check(valid,data->{var token=FACADE.validateRequest(%s,%s(data));return token.operationId().equals(%s)&&token.data().equals(data);});%s}\n",opIndex,generators[operation.RequestType],contractName,opIndex,javaQuote("request "+operation.OperationID),javaQuote(operation.OperationID),requestMethod,javaQuote(operation.OperationID),invalid.String());calls=append(calls,fmt.Sprintf("requestProperty%d();",opIndex))
        for _,response:=range operation.Responses{
            status,statusErr:=openAPIPropertyStatus(operation,response);if statusErr!=nil{return nil,statusErr};responseOccurrences[response.TypeExpression]=append(responseOccurrences[response.TypeExpression],openAPIResponseProperty{index:pairIndex,operation:opIndex,target:response.TypeExpression,requestGenerator:generators[operation.RequestType]});responseMethod:=fmt.Sprintf("response%d",pairIndex)
            fmt.Fprintf(&methods,"    private static %s.ResponseJSON %s(Data data){var root=parse(%s.writeDataWithoutRefinements(data));var headers=new java.util.ArrayList<%s.HeaderJSON>();%s.MediaJSON body=null;\n",facadeName,responseMethod,codecField[response.TypeExpression],facadeName,facadeName);for partIndex,target:=range response.Parts{variable:=fmt.Sprintf("part%d",partIndex);fmt.Fprintf(&methods,"        var %s=%s;",variable,openAPIPropertyPart("root",target));if target.In=="body"{fmt.Fprintf(&methods,"if(%s!=null)body=new %s.MediaJSON(%s,%s);",variable,facadeName,javaQuote(target.MediaType),variable)}else{fmt.Fprintf(&methods,"if(%s!=null)headers.add(new %s.HeaderJSON(%s,%s));",variable,facadeName,javaQuote(target.Name),variable)}};fmt.Fprintf(&methods,"return new %s.ResponseJSON(%s,headers,body);}\n",facadeName,javaQuote(status));fmt.Fprintf(&methods,"    private record Pair%d(Data request,Data response){}\n",pairIndex)
            fmt.Fprintf(&methods,"    private static boolean responseCandidate%d(Pair%d pair){try{var token=FACADE.validateRequest(%s,%s(pair.request()));var outcome=FACADE.validateResponse(%s,%s(pair.response()),token);if(outcome.incomplete())throw new AssertionError(\"operation response validation was indeterminate\");return outcome.state()==Validation.State.VALID;}catch(%s.OpenAPILimitException failure){throw failure;}catch(%s.NativeValidationException failure){if(failure.isIndeterminate())throw failure;return false;}catch(ValidationException failure){if(failure.outcome().incomplete())throw failure;return false;}}\n",pairIndex,pairIndex,javaQuote(operation.OperationID),requestMethod,javaQuote(operation.OperationID),responseMethod,facadeName,names.sidecar)
            fmt.Fprintf(&methods,"    private static boolean responseInvalidCandidate%d(Pair%d pair,String code){try{var token=FACADE.validateRequest(%s,%s(pair.request()));return targeted(FACADE.validateResponse(%s,%s(pair.response()),token),code);}catch(%s.OpenAPILimitException failure){throw failure;}catch(%s.NativeValidationException failure){if(failure.isIndeterminate())throw failure;return false;}catch(ValidationException failure){if(failure.outcome().incomplete())throw failure;return false;}}\n",pairIndex,pairIndex,javaQuote(operation.OperationID),requestMethod,javaQuote(operation.OperationID),responseMethod,facadeName,names.sidecar)
            responseRules,ruleErr:=openAPIPropertyRules(emitter,declarations,response.TypeExpression);if ruleErr!=nil{return nil,ruleErr};rules:=[]openAPIPropertyRule{};for _,rule:=range responseRules{rules=append(rules,openAPIPropertyRule{rule:rule,role:"response"})};if response.ContextType!=""{contextRules,contextErr:=openAPIPropertyRules(emitter,declarations,response.ContextType);if contextErr!=nil{return nil,contextErr};requestOffsets,responseOffsets:=map[int]int{},map[int]bool{};for _,rule:=range requestRules{requestOffsets[rule.offset]++};for _,rule:=range responseRules{responseOffsets[rule.offset]=true};rules=nil;for _,rule:=range contextRules{if requestOffsets[rule.offset]>0{requestOffsets[rule.offset]--;continue};role:="context";if responseOffsets[rule.offset]{role="response"};rules=append(rules,openAPIPropertyRule{rule:rule,role:role})}};var responseInvalid strings.Builder;for ruleIndex,item:=range rules{fmt.Fprintf(&responseInvalid,"var invalid%d=requiring(raw,p->responseInvalidCandidate%d(p,%s),ATTEMPTS,%s);check(invalid%d,p->responseInvalidCandidate%d(p,%s));",ruleIndex,pairIndex,javaQuote(item.rule.code),javaQuote("invalid "+item.role+" "+operation.OperationID+" "+response.Status+" "+item.rule.code),ruleIndex,pairIndex,javaQuote(item.rule.code))}
            label:="response "+operation.OperationID+" "+response.Status;if response.ContextType!=""{label="context "+operation.OperationID+" "+response.Status};fmt.Fprintf(&methods,"    private static void responseProperty%d(){var raw=org.jetbrains.jetCheck.Generator.zipWith(%s,%s,Pair%d::new);var valid=requiring(raw,%sGeneratedProperties::responseCandidate%d,ATTEMPTS,%s);check(valid,pair->{var token=FACADE.validateRequest(%s,%s(pair.request()));return FACADE.validateResponse(%s,%s(pair.response()),token).state()==Validation.State.VALID;});%s}\n",pairIndex,generators[operation.RequestType],generators[response.TypeExpression],pairIndex,contractName,pairIndex,javaQuote(label),javaQuote(operation.OperationID),requestMethod,javaQuote(operation.OperationID),responseMethod,responseInvalid.String());calls=append(calls,fmt.Sprintf("responseProperty%d();",pairIndex));pairIndex++
        }
    }
    for exampleIndex,example:=range examples{method:=fmt.Sprintf("example%d",exampleIndex);fmt.Fprintf(&methods,"    private static void %s(){var data=%s;",method,example.source);covered:=0;for _,operationIndex:=range requestOccurrences[example.target]{fmt.Fprintf(&methods,"if(!requestCandidate%d(data))throw new AssertionError(%s);",operationIndex,javaQuote(example.label+" request boundary"));covered++};for _,occurrence:=range responseOccurrences[example.target]{fmt.Fprintf(&methods,"var compatible%d=requiring(%s,request->responseCandidate%d(new Pair%d(request,data)),ATTEMPTS,%s);checkExample(compatible%d,request->responseCandidate%d(new Pair%d(request,data)));",covered,occurrence.requestGenerator,occurrence.index,occurrence.index,javaQuote(example.label+" compatible request context"),covered,occurrence.index,occurrence.index);covered++};if covered==0{return nil,&GenerationError{Message:example.label+" has no checked operation occurrence"}};methods.WriteString("}\n");calls=append(calls,method+"();")}
    class:=contractName+"GeneratedProperties";header:="// Generated by Refine: OpenAPI JetCheck 0.3.0 operation properties.\n";if namespace!=""{header+="package "+namespace+";\n"};source:=header+fmt.Sprintf(`@SuppressWarnings("deprecation")
public final class %s {
    private static final int CASES=%d,ATTEMPTS=%d;private static final long SEED=%dL;
    private static final %s FACADE=new %s();
%s
    private static final tools.jackson.databind.json.JsonMapper TREE=tools.jackson.databind.json.JsonMapper.builder().enable(tools.jackson.databind.DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS,tools.jackson.databind.DeserializationFeature.USE_BIG_INTEGER_FOR_INTS).build();
    private static tools.jackson.databind.JsonNode parse(byte[] raw){return TREE.readTree(raw);}
    private static byte[] part(tools.jackson.databind.JsonNode root,String... path){var value=root;for(var name:path){if(value==null||!value.isObject())return null;value=value.get(name);}return value==null?null:TREE.writeValueAsBytes(value);}
    private static <T> org.jetbrains.jetCheck.Generator<T> requiring(org.jetbrains.jetCheck.Generator<T> raw,java.util.function.Predicate<T> wanted,int attempts,String label){return org.jetbrains.jetCheck.Generator.from(env->{for(int i=0;i<attempts;i++){T value=env.generate(raw);if(wanted.test(value)){env.generate(org.jetbrains.jetCheck.Generator.integers());return value;}}throw new AssertionError("property generation exhausted: "+label+" after "+attempts+" attempts");});}
    private static <T> void check(org.jetbrains.jetCheck.Generator<T> generator,java.util.function.Predicate<T> property){org.jetbrains.jetCheck.PropertyChecker.customized().withSeed(SEED).withIterationCount(CASES).silent().forAll(generator,property);}
    private static <T> void checkExample(org.jetbrains.jetCheck.Generator<T> generator,java.util.function.Predicate<T> property){org.jetbrains.jetCheck.PropertyChecker.customized().withSeed(SEED).withIterationCount(1).silent().forAll(generator,property);}
    private static boolean targeted(Validation.Outcome outcome,String code){if(outcome.incomplete()||outcome.state()==Validation.State.INDETERMINATE)throw new AssertionError("operation validation was indeterminate");return outcome.state()==Validation.State.INVALID&&outcome.diagnostics().stream().anyMatch(d->d.code().equals(code));}
%s
    public static void main(String[] args){%s}
}
`,class,cases,attempts,options.Seed,facadeName,facadeName,strings.Join(codecFields,"\n"),methods.String(),strings.Join(calls," "));return []File{{Path:path.Join(strings.ReplaceAll(namespace,".","/"),class+".java"),Source:source}},nil
}
