// Code generated by goplus from property_evidence_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package java

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"goforge.dev/refine/language"
	"goforge.dev/refine/native"
)

func compileEvidenceFiles(t *testing.T, files []File, dependencies string) (string, string) {
	t.Helper()
	compiler, vm := javaTools(t)
	root := t.TempDir()
	sources := []string{}
	for _, file := range files {
		name := filepath.Join(root, filepath.FromSlash(file.Path))
		if err := os.MkdirAll(filepath.Dir(name), 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(name, []byte(file.Source), 0600); err != nil {
			t.Fatal(err)
		}
		sources = append(sources, name)
	}
	classes := filepath.Join(root, "classes")
	args := append([]string{"--release", "25", "-encoding", "UTF-8", "-Xlint:all", "-Werror", "-cp", dependencies, "-d", classes}, sources...)
	if output, err := exec.Command(compiler, args...).CombinedOutput(); err != nil {
		t.Fatalf("evidence javac: %v\n%s", err, output)
	}
	return vm, classes + string(os.PathListSeparator) + dependencies
}

func mutateEvidence(t *testing.T, files []File, suffix, before, after string) {
	t.Helper()
	changed := 0
	for i := range files {
		if strings.HasSuffix(files[i].Path, suffix) {
			count := strings.Count(files[i].Source, before)
			if count != 1 {
				t.Fatalf("mutation %s matched %d sites", suffix, count)
			}
			files[i].Source = strings.Replace(files[i].Source, before, after, 1)
			changed++
		}
	}
	if changed != 1 {
		t.Fatalf("mutation %s changed %d files", suffix, changed)
	}
}

func requireEvidenceMutationsFail(t *testing.T, vm, classpath, class string, mutations []string) {
	t.Helper()
	baseline, err := exec.Command(vm, "-cp", classpath, class).CombinedOutput()
	if err != nil {
		t.Fatalf("healthy suite failed: %v\n%s", err, baseline)
	}
	if !strings.Contains(string(baseline), "REFINE_SUITE PASS") || !strings.Contains(string(baseline), "REFINE_PROPERTY PASS invalid Age age.min") {
		t.Fatalf("healthy suite did not execute negative property: %s", baseline)
	}
	for _, mutation := range mutations {
		t.Run(mutation, func(t *testing.T) {
			output, err := exec.Command(vm, "-Drefine.mutation."+mutation+"=true", "-cp", classpath, class).CombinedOutput()
			if err == nil {
				t.Fatalf("broken implementation passed: %s", output)
			}
			if !strings.Contains(string(output), "REFINE_PROPERTY FAIL") || strings.Contains(string(output), "REFINE_SUITE PASS") {
				t.Fatalf("mutation was not an executed property failure: %v\n%s", err, output)
			}
			t.Logf("killed implementation mutation %s", mutation)
		})
	}
}

func TestGeneratedPropertiesDetectBrokenModelsAndJSONCodecs(t *testing.T) {
	program, err := language.Compile(`type Age = Int where it >= 0 @code "age.min"`)
	if err != nil {
		t.Fatal(err)
	}
	files, err := GenerateJSONSerde(program, "example.evidence", "Contract", "AgeModule", JSONSerdeOptions{Root: "Age"})
	if err != nil {
		t.Fatal(err)
	}
	properties, err := GeneratePropertyTests(program, "example.evidence", "Contract", PropertyTestOptions{Targets: []PropertyTarget{{Name: "Age"}}, CaseCount: 12, Seed: 13, JSONModule: "AgeModule"})
	if err != nil {
		t.Fatal(err)
	}
	// Mutate the generated implementations, never the generated assertions.
	mutateEvidence(t, files, "/Contract.java", `return ContractRuntime.validate(DEFINITIONS, FUNCTIONS, root, input, SCHEMA_LIMITS, caller);`, `if(Boolean.getBoolean("refine.mutation.contract-validator"))return new Validation.Valid();return ContractRuntime.validate(DEFINITIONS, FUNCTIONS, root, input, SCHEMA_LIMITS, caller);`)
	mutateEvidence(t, files, "/Age.java", `return Contract.validate("Age",rawData(),caller);`, `if(Boolean.getBoolean("refine.mutation.model-validator"))return new Validation.Valid();return Contract.validate("Age",rawData(),caller);`)
	mutateEvidence(t, files, "/ModelSupport.java", `Contract.validate(root, raw, caller).orThrow();`, `if(!Boolean.getBoolean("refine.mutation.model-constructor"))Contract.validate(root, raw, caller).orThrow();`)
	mutateEvidence(t, files, "/AgeModule.java", `value.validate().orThrow();J wire;`, `if(!Boolean.getBoolean("refine.mutation.json-validation"))value.validate().orThrow();J wire;`)
	mutateEvidence(t, files, "/AgeModule.java", `wire=toWire(ROOT,value.rawData(),0,new WireGuard(limits));`, `wire=toWire(ROOT,Boolean.getBoolean("refine.mutation.json-data-loss")?new Data.Number(Rational.ZERO):value.rawData(),0,new WireGuard(limits));`)
	files = append(files, properties...)
	vm, classpath := compileEvidenceFiles(t, files, jetCheckClasspath(t)+string(os.PathListSeparator)+jacksonClasspath(t))
	requireEvidenceMutationsFail(t, vm, classpath, "example.evidence.ContractGeneratedProperties", []string{"contract-validator", "model-validator", "model-constructor", "json-validation", "json-data-loss"})
}

func TestGeneratedPropertiesDetectBrokenAvroCodecs(t *testing.T) {
	imported, err := native.IngestProject(native.Avro, []byte(`"long"`), native.ProjectOptions{Root: native.ResourceSelector{TypeName: "Age"}, Metadata: native.WireMetadata{PublicationNamespace: "example.avroevidence"}})
	if err != nil {
		t.Fatal(err)
	}
	imported, err = imported.WithEditedSource(`type Age = Int64 where fromInt64 it >= 0 @code "age.min"`)
	if err != nil {
		t.Fatal(err)
	}
	files, err := GenerateProjectAvroSerde(imported, "Contract", "AgeSerde")
	if err != nil {
		t.Fatal(err)
	}
	properties, err := GenerateProjectPropertyTests(imported, "example.avroevidence", "Contract", PropertyTestOptions{Targets: []PropertyTarget{{Name: "Age"}}, CaseCount: 12, Seed: 13, AvroSerde: "AgeSerde"})
	if err != nil {
		t.Fatal(err)
	}
	mutateEvidence(t, files, "/AgeSerde.java", `value.validate(validationLimits).orThrow();return value;`, `if(!Boolean.getBoolean("refine.mutation.avro-validation"))value.validate(validationLimits).orThrow();return value;`)
	mutateEvidence(t, files, "/AgeSerde.java", `public byte[] writeBinary(Age value)throws java.io.IOException{`, `public byte[] writeBinary(Age value)throws java.io.IOException{if(Boolean.getBoolean("refine.mutation.avro-binary-loss"))return new byte[]{0};`)
	mutateEvidence(t, files, "/AgeSerde.java", `public String writeJson(Age value)throws java.io.IOException{var checked=checked(value);`, `public String writeJson(Age value)throws java.io.IOException{if(Boolean.getBoolean("refine.mutation.avro-json-loss"))return "0";var checked=Boolean.getBoolean("refine.mutation.avro-json-validation")?value:checked(value);`)
	files = append(files, properties...)
	vm, classpath := compileEvidenceFiles(t, files, jetCheckClasspath(t)+string(os.PathListSeparator)+avroClasspath(t))
	requireEvidenceMutationsFail(t, vm, classpath, "example.avroevidence.ContractGeneratedProperties", []string{"avro-validation", "avro-binary-loss", "avro-json-loss", "avro-json-validation"})
}

func TestGeneratedPropertyReportsAndInapplicableChecks(t *testing.T) {
	program, err := language.Compile(`type Name = String`)
	if err != nil {
		t.Fatal(err)
	}
	options := PropertyTestOptions{Targets: []PropertyTarget{{Name: "Name"}}, CaseCount: 7, Seed: 17, JSONModule: "NameModule"}
	files, err := GeneratePropertyTests(program, "example.properties", "Contract", options)
	if err != nil {
		t.Fatal(err)
	}
	for _, absent := range []string{"avroWireValid(", "avroWireInvalid(", "avroNativeWireInvalid(", "avroNativeCandidate(", "invalidBoundary0(", "wireInvalid(", "nativeWireInvalid("} {
		if strings.Contains(files[0].Source, absent) {
			t.Fatalf("inapplicable check emitted: %s", absent)
		}
	}
	vm, classpath := compilePropertySuite(t, `type Name = String`, options)
	output, err := exec.Command(vm, "-cp", classpath, "example.properties.ContractGeneratedProperties").CombinedOutput()
	if err != nil {
		t.Fatalf("valid-only suite: %v\n%s", err, output)
	}
	for _, want := range []string{"NOT_APPLICABLE avro-wire", "NOT_GENERATED refinement-negative target=Name", "REFINE_PROPERTY PASS valid Name cases=7 mode=generated", "REFINE_SUITE PASS properties=4 cases=28 examples=0"} {
		if !strings.Contains(string(output), want) {
			t.Fatalf("missing actual coverage report %q: %s", want, output)
		}
	}
	if strings.Contains(string(output), "REFINE_PROPERTY PASS invalid") {
		t.Fatalf("claimed an unexecuted negative property: %s", output)
	}
}

func TestGeneratedPropertyRejectsNoOpRunner(t *testing.T) {
	program, err := language.Compile(`type Name = String`)
	if err != nil {
		t.Fatal(err)
	}
	models, err := GenerateModels(program, "example.noop", "Contract")
	if err != nil {
		t.Fatal(err)
	}
	properties, err := GeneratePropertyTests(program, "example.noop", "Contract", PropertyTestOptions{CaseCount: 3})
	if err != nil {
		t.Fatal(err)
	}
	// Substitute a broken property runner that returns without evaluating anything.
	runner := File{Path: "org/jetbrains/jetCheck/PropertyChecker.java", Source: `package org.jetbrains.jetCheck; public final class PropertyChecker {
      public static PropertyChecker customized(){return new PropertyChecker();}
      public PropertyChecker withSeed(long seed){return this;}
      public PropertyChecker withIterationCount(int count){return this;}
      public PropertyChecker silent(){return this;}
      public PropertyChecker rechecking(String replay){return this;}
      public <T> void forAll(Generator<T> generator,java.util.function.Predicate<T> property){}
    }`}
	files := append(models, properties...)
	files = append(files, runner)
	vm, classpath := compileEvidenceFiles(t, files, jetCheckClasspath(t))
	output, err := exec.Command(vm, "-cp", classpath, "example.noop.ContractGeneratedProperties").CombinedOutput()
	if err == nil || !strings.Contains(string(output), "property executed zero cases") || strings.Contains(string(output), "REFINE_SUITE PASS") {
		t.Fatalf("no-op runner passed: %v\n%s", err, output)
	}
}

func TestWirePropertyEqualityPreservesPayloadDifferences(t *testing.T) {
	program, err := language.Compile(`type Amount = Int64`)
	if err != nil {
		t.Fatal(err)
	}
	models, err := GenerateModels(program, "example.wireequality", "Contract")
	if err != nil {
		t.Fatal(err)
	}
	// Exercise the actual emitted comparator independently of codecs and their
	// candidate filters. Only the unencoded numeric tag may be disregarded.
	harness := File{Path: "example/wireequality/WireEquality.java", Source: `package example.wireequality;
      public final class WireEquality {` + propertyWireEqualityJava + `
        private static void expect(boolean actual,boolean expected){if(actual!=expected)throw new AssertionError("wire equality");}
        public static void main(String[] args){
          Data typed=new Data.Number(Rational.of(7),"Int64"),plain=new Data.Number(Rational.of(7));
          expect(typed.equals(plain),false);expect(wireDataEqual(typed,plain),true);
          expect(wireDataEqual(typed,new Data.Number(Rational.of(8))),false);
          expect(wireDataEqual(typed,new Data.Number(Rational.parse("7/2"))),false);
          expect(wireDataEqual(typed,new Data.Text("7")),false);
          expect(wireDataEqual(new Data.Sequence(java.util.List.of(typed)),new Data.Sequence(java.util.List.of(plain))),true);
          expect(wireDataEqual(new Data.Sequence(java.util.List.of(typed)),new Data.Sequence(java.util.List.of())),false);
          expect(wireDataEqual(new Data.Variant("A",java.util.List.of(typed)),new Data.Variant("B",java.util.List.of(plain))),false);
          expect(wireDataEqual(new Data.Struct(java.util.List.of(new Data.Field("a",typed))),new Data.Struct(java.util.List.of(new Data.Field("b",plain)))),false);
          expect(wireDataEqual(new Data.Mapping(java.util.Map.of("a",typed)),new Data.Mapping(java.util.Map.of("a",plain))),true);
          expect(wireDataEqual(new Data.Mapping(java.util.Map.of("a",typed)),new Data.Mapping(java.util.Map.of("b",plain))),false);
          expect(wireDataEqual(new Data.Bool(true),new Data.Bool(false)),false);
        }
      }`}
	vm, classpath := compileEvidenceFiles(t, append(models, harness), jetCheckClasspath(t))
	if output, err := exec.Command(vm, "-cp", classpath, "example.wireequality.WireEquality").CombinedOutput(); err != nil {
		t.Fatalf("wire equality: %v\n%s", err, output)
	}
}

func TestGeneratedNegativePropertyExhaustionFailsHard(t *testing.T) {
	vm, classpath := compilePropertySuite(t, `type Age = Int where it == it @code "always"`, PropertyTestOptions{CaseCount: 2, AttemptBudget: 8, Seed: 3})
	output, err := exec.Command(vm, "-cp", classpath, "example.properties.ContractGeneratedProperties").CombinedOutput()
	if err == nil || !strings.Contains(string(output), "property generation exhausted: invalid Age always") || !strings.Contains(string(output), "REFINE_PROPERTY FAIL invalid Age always evaluations=0") || strings.Contains(string(output), "REFINE_SUITE PASS") {
		t.Fatalf("required negative property silently passed without cases: %v\n%s", err, output)
	}
}

// Native-invalid expectations come from the Go native oracle at generation time,
// never from the Java sidecar whose enforcement is being tested.
func TestGeneratedPropertiesDetectNativeLimitsAndAccessors(t *testing.T) {
	project, err := native.IngestProject(native.JSONSchema, []byte(`{"type":"object","properties":{"countryCode":{"type":"string"},"name":{"type":"string"}},"required":["countryCode","name"]}`), native.ProjectOptions{Root: native.ResourceSelector{TypeName: "Country"}, Metadata: native.WireMetadata{PublicationNamespace: "example.boundaries"}})
	if err != nil {
		t.Fatal(err)
	}
	files, err := GenerateProjectJSONSerde(project, "Contract", "CountryModule")
	if err != nil {
		t.Fatal(err)
	}
	properties, err := GenerateProjectPropertyTests(project, "example.boundaries", "Contract", PropertyTestOptions{Targets: []PropertyTarget{{Name: "Country"}}, CaseCount: 12, Seed: 13, JSONModule: "CountryModule", NativeJSONValidator: "CountryModuleNativeSidecar"})
	if err != nil {
		t.Fatal(err)
	}
	mutateEvidence(t, files, "/Country.java", `return ((Data.Text)ModelSupport.field(rawData(),"countryCode")).value();`, `return Boolean.getBoolean("refine.mutation.getter")?"":((Data.Text)ModelSupport.field(rawData(),"countryCode")).value();`)
	mutateEvidence(t, files, "/CountryModule.java", `if(depth>limits.maxDepth()||++nodes>limits.maxNodes())`, `if(!Boolean.getBoolean("refine.mutation.limits")&&(depth>limits.maxDepth()||++nodes>limits.maxNodes()))`)
	mutateEvidence(t, files, "/CountryModuleNativeSidecar.java", `if(!result.isValid())`, `if(!Boolean.getBoolean("refine.mutation.native")&&!result.isValid())`)
	vm, classpath := compileEvidenceFiles(t, append(files, properties...), jetCheckClasspath(t)+string(os.PathListSeparator)+networkntClasspath(t))
	class := "example.boundaries.ContractGeneratedProperties"
	output, err := exec.Command(vm, "-cp", classpath, class).CombinedOutput()
	if err != nil {
		t.Fatalf("healthy boundaries: %v\n%s", err, output)
	}
	for _, label := range []string{"model-accessors Country", "json-node-limit", "json-depth-limit", "native-json-rejection"} {
		if !strings.Contains(string(output), "REFINE_PROPERTY PASS "+label) {
			t.Fatalf("missing boundary check %s: %s", label, output)
		}
	}
	for _, mutation := range []string{"getter", "limits", "native"} {
		t.Run(mutation, func(t *testing.T) {
			out, err := exec.Command(vm, "-Drefine.mutation."+mutation+"=true", "-cp", classpath, class).CombinedOutput()
			if err == nil || !strings.Contains(string(out), "REFINE_PROPERTY FAIL") || strings.Contains(string(out), "REFINE_SUITE PASS") {
				t.Fatalf("mutation not killed by generated checks: %v\n%s", err, out)
			}
			t.Logf("killed %s", mutation)
		})
	}
}
