// Code generated by goplus from regex_compile_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package java

import (
	"bytes"
	"context"
	"crypto/sha256"
	"fmt"
	"math/rand"
	"os"
	"os/exec"
	"path/filepath"
	"regexp/syntax"
	"strings"
	"testing"
	"time"

	"goforge.dev/refine/pattern"
	"goforge.dev/refine/validation"
	"goforge.dev/refine/value"
)

func regexTreeLine(id int, root *syntax.Regexp) string {
	nodes := []*syntax.Regexp{}
	indices := map[*syntax.Regexp]int{}
	var visit func(*syntax.Regexp) int
	visit = func(node *syntax.Regexp) int {
		if id, ok := indices[node]; ok {
			return id
		}
		for _, child := range node.Sub {
			visit(child)
		}
		id := len(nodes)
		indices[node] = id
		nodes = append(nodes, node)
		return id
	}
	rootID := visit(root)
	var out strings.Builder
	fmt.Fprintf(&out, "tree\t%d\t%d\t", id, rootID)
	for i, node := range nodes {
		if i > 0 {
			out.WriteByte(';')
		}
		fmt.Fprintf(&out, "%d:%d:%d:%d:%d:", node.Op, node.Flags, node.Min, node.Max, node.Cap)
		for j, r := range node.Rune {
			if j > 0 {
				out.WriteByte(',')
			}
			fmt.Fprint(&out, r)
		}
		out.WriteByte(':')
		for j, child := range node.Sub {
			if j > 0 {
				out.WriteByte(',')
			}
			fmt.Fprint(&out, indices[child])
		}
	}
	return out.String()
}
func regexInstructionDigest(start int, instructions []pattern.Instruction) string {
	var out strings.Builder
	fmt.Fprintf(&out, "%d;", start)
	for _, inst := range instructions {
		fmt.Fprintf(&out, "%s:%d:%d:", pattern.OpcodeName(inst.Opcode), inst.Out, inst.Arg)
		for _, r := range inst.Runes {
			fmt.Fprintf(&out, "%d,", r)
		}
		out.WriteByte(';')
	}
	sum := sha256.Sum256([]byte(out.String()))
	return fmt.Sprintf("%x", sum)
}
func syntaxInstructionDigest(program *syntax.Prog) string {
	var out strings.Builder
	fmt.Fprintf(&out, "%d;", program.Start)
	names := []string{"ALT", "ALT_MATCH", "CAPTURE", "EMPTY_WIDTH", "MATCH", "FAIL", "NOP", "RUNE", "RUNE1", "RUNE_ANY", "RUNE_ANY_NOT_NL"}
	for _, inst := range program.Inst {
		fmt.Fprintf(&out, "%s:%d:%d:", names[int(inst.Op)], inst.Out, inst.Arg)
		for _, r := range inst.Rune {
			fmt.Fprintf(&out, "%d,", r)
		}
		out.WriteByte(';')
	}
	sum := sha256.Sum256([]byte(out.String()))
	return fmt.Sprintf("%x", sum)
}

func TestGeneratedRegexCompiler(t *testing.T) {
	compiler, vm := javaTools(t)
	dependencies := jetCheckClasspath(t)
	files, err := GenerateRuntime("example.regexcompile")
	if err != nil {
		t.Fatal(err)
	}
	root := t.TempDir()
	sources := []string{}
	for _, file := range files {
		target := filepath.Join(root, filepath.FromSlash(file.Path))
		if err := os.MkdirAll(filepath.Dir(target), 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(target, []byte(file.Source), 0644); err != nil {
			t.Fatal(err)
		}
		sources = append(sources, target)
	}
	harness := filepath.Join(root, "RegexCompileConformance.java")
	if err := os.WriteFile(harness, []byte(regexCompileHarnessJava), 0644); err != nil {
		t.Fatal(err)
	}
	sources = append(sources, harness)
	classes := filepath.Join(root, "classes")
	args := append([]string{"--release", "25", "-encoding", "UTF-8", "-Xlint:all", "-Werror", "-cp", dependencies, "-d", classes}, sources...)
	if output, err := exec.Command(compiler, args...).CombinedOutput(); err != nil {
		t.Fatalf("javac: %v\n%s", err, output)
	}
	patterns := []string{"", "a", "a|ab", "[a-z]", "(?i)k", "(?i)σ", "(?i)[a-z]", "(?s).", ".", "(?m)^a$", `\A\bcat\B\z`, "(a)(?P<name>b)", `\p{Greek}+`, `\p{Cs}`, "(?:a?)*", "(?:a*)*", "(?:a*)+", "(?:a+)+", "(?:a+?)+", "(?:a{0}){2}", "(a){2,5}", "(a){2,5}?", "(?:a{2,5})?", "(a|aa)*b", "(?U)(a|aa)*b", "(?:a|ab){0,3}", "[^\\x{0}-\\x{10ffff}]"}
	atoms := []string{"a", "(?:)", ".", "[a-z]", "(?i:k)", "(a)", "(?:a|ab)", "(?:a?)", "(?m:^)", `\p{Greek}`, "(?i:ß)", "(?i:𐐀)"}
	quantifiers := []string{"", "?", "*", "+", "{0}", "{1}", "{2}", "{0,3}", "{2,5}", "{0,}", "{1,}", "{4,}", "??", "*?", "+?", "{2,5}?", "{4,}?"}
	for _, atom := range atoms {
		for _, q := range quantifiers {
			patterns = append(patterns, atom+q)
		}
	}
	rng := rand.New(rand.NewSource(110919))
	for i := 0; i < 2000; i++ {
		a, b := atoms[rng.Intn(len(atoms))], atoms[rng.Intn(len(atoms))]
		patterns = append(patterns, "(?:"+a+"|"+b+")"+quantifiers[rng.Intn(len(quantifiers))]+a+quantifiers[rng.Intn(len(quantifiers))])
	}
	patterns = append(patterns, "a{0,1000}", "(a?){0,1000}", "(a*){1,1000}?", "(?:a{100}){10}", strings.Repeat("x", 6000), strings.Repeat("(?:a?)", 1000))
	for _, depth := range []int{250, 510, 511, 512, 513, 600} {
		patterns = append(patterns, strings.Repeat("(", depth)+"a"+strings.Repeat(")", depth))
	}
	vectors := []vector{}
	text := func(raw string) value.Text {
		v, err := value.TextFromUTF8(raw)
		if err != nil {
			t.Fatal(err)
		}
		return v
	}
	add := func(index int, source string, total, clause uint64, nested int, precharge uint64) {
		budget := validation.NewBudget(validation.Limits{Total: total, Clause: clause}, validation.Limits{})
		outer := budget.BeginClause(0)
		_ = outer.Step(precharge)
		meter := outer
		if nested >= 0 {
			meter = outer.Nested(uint64(nested))
		}
		program, err := pattern.Compile(text(source), meter)
		result := ""
		if err != nil {
			result = "error:" + err.Error()
		} else {
			plan, err := program.Program()
			if err != nil {
				t.Fatal(err)
			}
			result = regexInstructionDigest(plan.Start, plan.Instructions)
		}
		result += fmt.Sprintf("|%d|%d|%d", budget.Used(), outer.Used(), meter.Used())
		recovered := outer.Step(1) == nil
		zero := meter.Step(0) == nil
		result += fmt.Sprintf("|%v|%v|%d", recovered, zero, budget.Used())
		prefix := uint64(text(source).Length())
		prefix = prefix*prefix + 1
		vectors = append(vectors, vector{fmt.Sprintf("compile\t%d\t%d\t%d\t%d\t%d\t%d", index, prefix, total, clause, nested, precharge), result})
	}
	for i, source := range patterns {
		tree, err := syntax.Parse(source, syntax.Perl)
		if err != nil {
			t.Fatalf("invalid fixture %s: %v", source, err)
		}
		vectors = append(vectors, vector{regexTreeLine(i, tree), "tree:ok"})
		add(i, source, 1000000000, 1000000000, -1, 0)
		if i < 27 {
			for limit := uint64(1); limit < 260; limit++ {
				add(i, source, limit, 0, -1, 0)
				add(i, source, 0, limit, 0, 7)
			}
		} else if i < len(patterns)-12 {
			add(i, source, uint64(rng.Intn(500)+1), uint64(rng.Intn(500)+1), rng.Intn(100), uint64(rng.Intn(20)))
		}
	}
	// Already-parsed backend trees also cover shapes erased by parser factoring.
	synthetic := []*syntax.Regexp{}
	literal := func(r rune) *syntax.Regexp { return &syntax.Regexp{Op: syntax.OpLiteral, Rune: []rune{r}} }
	for _, op := range []syntax.Op{syntax.OpConcat, syntax.OpAlternate, syntax.OpStar, syntax.OpPlus, syntax.OpQuest, syntax.OpCapture} {
		for _, child := range []*syntax.Regexp{{Op: syntax.OpNoMatch}, {Op: syntax.OpEmptyMatch}, literal('a')} {
			sub := []*syntax.Regexp{child}
			if op == syntax.OpConcat || op == syntax.OpAlternate {
				sub = append(sub, literal('b'))
			}
			synthetic = append(synthetic, &syntax.Regexp{Op: op, Sub: sub, Cap: 1, Flags: syntax.NonGreedy})
		}
	}
	alternatives := []*syntax.Regexp{}
	for i := 0; i < 30; i++ {
		alternatives = append(alternatives, literal(rune('a'+i)))
	}
	synthetic = append(synthetic, &syntax.Regexp{Op: syntax.OpConcat, Sub: []*syntax.Regexp{{Op: syntax.OpAlternate, Sub: alternatives}, {Op: syntax.OpNoMatch}}}, &syntax.Regexp{Op: syntax.OpAlternate}, &syntax.Regexp{Op: syntax.OpConcat})
	// Differential law over raw trees, including dead fragments and nested
	// repetitions which the source parser normally factors or rejects.
	var randomTree func(int) *syntax.Regexp
	randomTree = func(depth int) *syntax.Regexp {
		op := syntax.Op(rng.Intn(19) + 1)
		if depth == 0 {
			op = syntax.Op(rng.Intn(12) + 1)
		}
		node := &syntax.Regexp{Op: op, Flags: syntax.Flags(rng.Intn(2) * 32)}
		switch op {
		case syntax.OpLiteral:
			for n := rng.Intn(4); n > 0; n-- {
				node.Rune = append(node.Rune, []rune{'a', 'K', 'σ', 0xd800, 0x10400}[rng.Intn(5)])
			}
			node.Flags |= syntax.Flags(rng.Intn(2))
		case syntax.OpCharClass:
			node.Rune = []rune{'a', 'f', 'k', 'z'}
		case syntax.OpCapture, syntax.OpStar, syntax.OpPlus, syntax.OpQuest, syntax.OpRepeat:
			node.Sub = []*syntax.Regexp{randomTree(depth - 1)}
			node.Cap = rng.Intn(5)
			if op == syntax.OpRepeat {
				node.Min = rng.Intn(4)
				node.Max = node.Min + rng.Intn(4)
				if rng.Intn(4) == 0 {
					node.Max = -1
				}
			}
		case syntax.OpConcat, syntax.OpAlternate:
			for n := rng.Intn(4); n > 0; n-- {
				node.Sub = append(node.Sub, randomTree(depth-1))
			}
		}
		return node
	}
	for i := 0; i < 2000; i++ {
		synthetic = append(synthetic, randomTree(6))
	}
	for i, tree := range synthetic {
		id := len(patterns) + i
		vectors = append(vectors, vector{regexTreeLine(id, tree), "tree:ok"})
		program, err := syntax.Compile(tree.Simplify())
		if err != nil {
			t.Fatal(err)
		}
		vectors = append(vectors, vector{fmt.Sprintf("raw\t%d", id), syntaxInstructionDigest(program)})
	}
	var input strings.Builder
	for _, v := range vectors {
		input.WriteString(v.input)
		input.WriteByte('\n')
	}
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()
	command := exec.CommandContext(ctx, vm, "-Xss256k", "-cp", classes+string(os.PathListSeparator)+dependencies, "RegexCompileConformance")
	command.Stdin = strings.NewReader(input.String())
	var stderr bytes.Buffer
	command.Stderr = &stderr
	output, err := command.Output()
	if err != nil {
		t.Fatalf("Java regex compiler: %v\n%s", err, stderr.String())
	}
	lines := strings.Split(strings.TrimSuffix(string(output), "\n"), "\n")
	if len(lines) != len(vectors) {
		t.Fatalf("expected %d outputs, got %d", len(vectors), len(lines))
	}
	for i, v := range vectors {
		if lines[i] != v.expected {
			t.Fatalf("case %s\nJava %s\nGo   %s", v.input, lines[i], v.expected)
		}
	}
	t.Logf("%d parsed patterns, %d synthetic trees, %d instruction/budget comparisons and 6000 jetCheck cases passed", len(patterns), len(synthetic), len(vectors)-len(patterns)-len(synthetic))
}

const regexCompileHarnessJava = `
import example.regexcompile.*;
import java.util.List;
import java.util.ArrayList;
import java.util.HashMap;
import java.nio.charset.StandardCharsets;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import org.jetbrains.jetCheck.Generator;
import org.jetbrains.jetCheck.PropertyChecker;
public final class RegexCompileConformance {
    static void require(boolean condition){if(!condition)throw new AssertionError();}
    static RegexProgram.Tree node(RegexProgram.TreeOp op,int flags,List<Integer> runes,List<RegexProgram.Tree> children,int min,int max,int capture){return new RegexProgram.Tree(op,flags,runes,children,min,max,capture,"");}
    static RegexProgram.Tree simple(RegexProgram.TreeOp op,RegexProgram.Tree...children){return node(op,0,List.of(),List.of(children),0,0,0);}
    static Budget.Meter meter(long steps){return new Budget(new Budget.Limits(steps,steps),Budget.Limits.defaults()).beginClause(0);}
    static RegexProgram.Tree tree(String[] f){
        var trees=new ArrayList<RegexProgram.Tree>();
        for(String part:f[3].split(";")){
            String[] values=part.split(":",-1);var runes=new ArrayList<Integer>();var children=new ArrayList<RegexProgram.Tree>();
            if(!values[5].isEmpty())for(String r:values[5].split(","))runes.add(Integer.parseInt(r));
            if(!values[6].isEmpty())for(String c:values[6].split(","))children.add(trees.get(Integer.parseInt(c)));
            trees.add(node(RegexProgram.TreeOp.values()[Integer.parseInt(values[0])-1],Integer.parseInt(values[1]),runes,children,Integer.parseInt(values[2]),Integer.parseInt(values[3]),Integer.parseInt(values[4])));
        }return trees.get(Integer.parseInt(f[2]));
    }
    static String digest(RegexProgram program)throws Exception{
        var source=new StringBuilder().append(program.start()).append(';');
        for(var i:program.instructions()){source.append(i.opcode()).append(':').append(i.out()).append(':').append(i.arg()).append(':');for(int r:i.runes())source.append(r).append(',');source.append(';');}
        return java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(source.toString().getBytes(StandardCharsets.UTF_8)));
    }
    static String compile(RegexProgram.Tree tree,String[] f)throws Exception{
        var budget=new Budget(new Budget.Limits(Long.parseLong(f[3]),Long.parseLong(f[4])),Budget.Limits.defaults());
        var outer=budget.beginClause(0);try{outer.step(Long.parseLong(f[6]));}catch(Budget.Exceeded ignored){}
        int nested=Integer.parseInt(f[5]);var meter=nested<0?outer:outer.nested(nested);String result;
        try{meter.step(Long.parseLong(f[2]));result=digest(RegexProgram.compileTree(tree,meter));}
        catch(Budget.Exceeded failure){result="error:regex.budget: regular expression step budget exhausted";}
        catch(RegexProgram.Error failure){result="error:"+failure.code()+": "+failure.getMessage();}
        result+="|"+budget.used()+"|"+outer.used()+"|"+meter.used();boolean recovery=true,zero=true;
        try{outer.step(1);}catch(Budget.Exceeded ignored){recovery=false;}try{meter.step(0);}catch(Budget.Exceeded ignored){zero=false;}
        return result+"|"+recovery+"|"+zero+"|"+budget.used();
    }
    static void rejects(Runnable action){try{action.run();throw new AssertionError("invalid tree accepted");}catch(IllegalArgumentException expected){}}
    public static void main(String[] args)throws Exception{
        var trees=new HashMap<Integer,RegexProgram.Tree>();var input=new BufferedReader(new InputStreamReader(System.in,StandardCharsets.UTF_8));String line;
        while((line=input.readLine())!=null){String[] f=line.split("\t",-1);switch(f[0]){
            case "tree"->{trees.put(Integer.parseInt(f[1]),tree(f));System.out.println("tree:ok");}
            case "compile"->System.out.println(compile(trees.get(Integer.parseInt(f[1])),f));
            case "raw"->System.out.println(digest(RegexProgram.compileTree(trees.get(Integer.parseInt(f[1])),meter(1000000))));
            default->throw new AssertionError();
        }}
        var literal=node(RegexProgram.TreeOp.LITERAL,0,List.of(97),List.of(),0,0,0);
        rejects(()->simple(RegexProgram.TreeOp.STAR));
        rejects(()->simple(RegexProgram.TreeOp.EMPTY,literal));
        rejects(()->node(RegexProgram.TreeOp.CLASS,0,List.of(2,1),List.of(),0,0,0));
        rejects(()->node(RegexProgram.TreeOp.REPEAT,0,List.of(),List.of(literal),5,2,0));
        rejects(()->node(RegexProgram.TreeOp.LITERAL,0,List.of(-1),List.of(),0,0,0));
        var mutable=new ArrayList<RegexProgram.Tree>();mutable.add(literal);
        var copied=node(RegexProgram.TreeOp.STAR,0,List.of(),mutable,0,0,0);mutable.clear();require(copied.children().size()==1);
        try{copied.children().clear();throw new AssertionError();}catch(UnsupportedOperationException expected){}
        // Overflow must be detected before attempting expansion/allocation.
        var huge=literal;for(int i=0;i<10;i++)huge=node(RegexProgram.TreeOp.REPEAT,0,List.of(),List.of(huge),1000,1000,0);
        var maxBudget=new Budget(new Budget.Limits(Budget.MAX,Budget.MAX),Budget.Limits.defaults());var hugeMeter=maxBudget.beginClause(0);
        try{RegexProgram.compileTree(huge,hugeMeter);throw new AssertionError("overflow expanded");}
        catch(RegexProgram.Error expected){require(expected.code().equals("regex.limit")&&hugeMeter.used().intValueExact()==11);}
        PropertyChecker.customized().withIterationCount(2000).forAll(Generator.integers(),seed->{
            int min=Math.floorMod(seed,7),max=min+Math.floorMod(seed/7,8);boolean lazy=(seed&1)!=0;
            var tree=node(RegexProgram.TreeOp.REPEAT,lazy?32:0,List.of(),List.of(literal),min,max,0);
            var budget=meter(1000000);var program=RegexProgram.compileTree(tree,budget);long cost=budget.used().longValueExact();
            for(int length=0;length<=16;length++)require(program.match("a".repeat(length),RegexProgram.Mode.FULL,meter(1000000))==(length>=min&&length<=max));
            require(RegexProgram.compileTree(tree,meter(cost)).instructions().equals(program.instructions()));
            try{RegexProgram.compileTree(tree,meter(cost-1));throw new AssertionError("compiler budget relaxed");}catch(RegexProgram.Error expected){require(expected.code().equals("regex.budget"));}
            return true;
        });
        PropertyChecker.customized().withIterationCount(2000).forAll(Generator.integers(),seed->{
            int min=Math.floorMod(seed,20);var tree=node(RegexProgram.TreeOp.REPEAT,seed&32,List.of(),List.of(literal),min,-1,0);
            var program=RegexProgram.compileTree(tree,meter(1000000));
            for(int n=0;n<=25;n++)require(program.match("a".repeat(n),RegexProgram.Mode.FULL,meter(1000000))==(n>=min));return true;
        });
        PropertyChecker.customized().withIterationCount(2000).forAll(Generator.integers(),seed->{
            int depth=Math.floorMod(seed,600);var tree=literal;for(int i=0;i<depth;i++)tree=simple(RegexProgram.TreeOp.CAPTURE,tree);
            try{var program=RegexProgram.compileTree(tree,meter(1000000));require(depth<512&&program.match("a",RegexProgram.Mode.FULL,meter(1000000)));}
            catch(RegexProgram.Error failure){require(depth>=512&&failure.code().equals("regex.limit"));}return true;
        });
    }
}
`
