// Package java emits Java 25 source. Generation is pure: callers choose where
// to write the returned files, and no generated predicate receives I/O access.
package java

import (
    "fmt"
    "path"
    "strings"
    "unicode"
)

type File struct { Path string; Source string }

// Package names are identifiers, never filesystem paths or source fragments.
// Invisible controls/format characters are deliberately excluded even where a
// Java compiler might ignore them in an identifier.
func packageName(name string)error{
    if name==""{return nil}
    if name=="java"||strings.HasPrefix(name,"java."){return fmt.Errorf("generated types cannot use Java platform packages")}
    keywords:=" abstract assert boolean break byte case catch char class const continue default do double else enum extends final finally float for goto if implements import instanceof int interface long native new package private protected public return short static strictfp super switch synchronized this throw throws transient try void volatile while true false null _ "
    for _,segment:=range strings.Split(name,"."){
        if segment==""||strings.Contains(keywords," "+segment+" "){return fmt.Errorf("invalid Java package segment")}
        for i,r:=range segment{
            start:=unicode.IsLetter(r)||unicode.In(r,unicode.Nl,unicode.Sc,unicode.Pc)
            rest:=start||unicode.IsDigit(r)||unicode.In(r,unicode.Mn,unicode.Mc)
            if i==0&&!start||i!=0&&!rest{return fmt.Errorf("invalid Java package character")}
        }
    }
    return nil
}

// GenerateRuntime emits shared runtime sources, not schema-specific models or
// serde adapters. An empty package selects Java's unnamed package. Paths are
// package-relative; a flat-layout caller can retain only their base names.
// These development sources are intended to live in the user's single artifact;
// no separately deployed Maven runtime artifact is required.
func GenerateRuntime(namespace string)([]File,error){
    if err:=packageName(namespace);err!=nil{return nil,err}
    header:="// Generated by Refine: development Java 25 runtime. MIT licensed.\n"
    if namespace!=""{header+="package "+namespace+";\n"}
    types:=[]struct{name string;body string}{
        {"Rational",rationalJava},{"TextCodec",textJava},{"Validation",validationJava},
        {"ValidationException",validationExceptionJava},{"Budget",budgetJava},{"Timestamp",timestampJava},{"RegexProgram",regexProgramJava()},
    }
    files:=make([]File,len(types))
    for i,typ:=range types{files[i]=File{Path:path.Join(strings.ReplaceAll(namespace,".","/"),typ.name+".java"),Source:header+typ.body}}
    return files,nil
}
