// Code generated by goplus from serde_json.gp. DO NOT EDIT.
//goplus:v v0.28.0

package java

import (
	"fmt"
	"path"
	"strings"

	"goforge.dev/refine/language"
	"goforge.dev/refine/native"
)

type JSONIntegerEncoding uint8

const (
	JSONIntegerNumber JSONIntegerEncoding = iota
	JSONIntegerString
)

type JSONRealEncoding uint8

const (
	JSONRealUnspecified JSONRealEncoding = iota
	JSONRealExactDecimal
	JSONRealRationalString
)

type JSONTimestampEncoding uint8

const (
	JSONTimestampUnspecified JSONTimestampEncoding = iota
	JSONTimestampRFC3339String
)

type JSONDiscriminator struct {
	Field     string
	Values    map[string]string
	Arguments map[string][]string
}
type JSONSerdeOptions struct {
	Root                   string
	PreserveExtraFields    bool
	PreserveExtraFieldsFor map[string]bool
	Discriminators         map[string]JSONDiscriminator
	Integers               JSONIntegerEncoding
	Reals                  JSONRealEncoding
	Timestamps             JSONTimestampEncoding
}

// GenerateProjectJSONSerde consumes the checked native project's wire choices;
// it never invents a discriminator, scalar encoding, or extra-field policy.
func GenerateProjectJSONSerde(project *native.Project, contractName, moduleName string) ([]File, error) {
	if project == nil {
		return nil, &GenerationError{Message: "a checked native project is required"}
	}
	program, err := language.Compile(project.EditableSource())
	if err != nil {
		return nil, err
	}
	metadata := project.Metadata()
	root := project.Root().TypeName
	options := JSONSerdeOptions{Root: root}
	options.PreserveExtraFieldsFor = map[string]bool{}
	for name, mode := range metadata.ExtraFields {
		if mode == native.PreserveExtraFields {
			options.PreserveExtraFieldsFor[name] = true
		}
	}
	options.Discriminators = map[string]JSONDiscriminator{}
	for name, wire := range metadata.Discriminators {
		values := map[string]string{}
		arguments := map[string][]string{}
		for constructor, value := range wire.Values {
			values[constructor] = value
		}
		for constructor, names := range wire.Arguments {
			arguments[constructor] = append([]string(nil), names...)
		}
		options.Discriminators[name] = JSONDiscriminator{Field: wire.Field, Values: values, Arguments: arguments}
	}
	if metadata.ExtraFields[root] == native.PreserveExtraFields {
		options.PreserveExtraFields = true
	}
	if scalar, ok := metadata.Scalars[root]; ok {
		switch scalar.Kind {
		case native.JSONNumber:
			options.Integers = JSONIntegerNumber
			options.Reals = JSONRealExactDecimal
		case native.DecimalString:
			options.Integers = JSONIntegerString
			options.Reals = JSONRealRationalString
		case native.TimestampString:
			options.Timestamps = JSONTimestampRFC3339String
		default:
			return nil, &GenerationError{Message: "native scalar encoding is not supported by Jackson JSON serde"}
		}
	}
	return GenerateJSONSerde(program, metadata.PublicationNamespace, contractName, moduleName, options)
}

// GenerateJSONSerde emits semantic models plus a Jackson 3 module for one
// closed, non-generic record or scalar root. Wire choices that could lose exact
// values are explicit; unsupported shapes fail the whole generation.
func GenerateJSONSerde(program *language.Program, namespace, contractName, moduleName string, options JSONSerdeOptions) (files []File, failure error) {
	defer func() {
		if caught := recover(); caught != nil {
			if err, ok := caught.(*GenerationError); ok {
				files = nil
				failure = err
			} else {
				panic(caught)
			}
		}
	}()
	if err := javaClassName(moduleName); err != nil {
		unsupported(language.Span{}, err.Error())
	}
	if options.Root == "" {
		unsupported(language.Span{}, "JSON serde root is required")
	}
	files, failure = GenerateModels(program, namespace, contractName)
	if failure != nil {
		return nil, failure
	}
	module := program.Syntax()
	decls := map[string]language.TypeDecl{}
	for _, decl := range module.Types {
		decls[decl.Name] = decl
	}
	root, ok := decls[options.Root]
	if !ok {
		unsupported(language.Span{}, "unknown JSON serde root "+options.Root)
	}
	if len(root.Parameters) > 0 {
		unsupported(root.At, "JSON serde roots must be closed; register an instantiated nominal declaration")
	}
	emitter := &jsonShapeEmitter{decls: decls, options: options, definitions: map[string]string{}, building: map[string]bool{}}
	shape := ""
	if root.Body == nil {
		shape = emitter.unionDecl(root.Name, root.Name, root.Variants, nil, 0)
	} else {
		body := jsonResolve(root.Body, decls, map[string]bool{})
		switch __gp_m0 := any(body.Form).(type) {
		case language.RecordType:
			fields := __gp_m0.Fields
			shape = emitter.record(options.Root, options.Root, fields, 0)
		default:
			shape = emitter.shape(body, 0)
		}
	}
	definitionParts := []string{}
	for _, key := range emitter.order {
		definitionParts = append(definitionParts, "java.util.Map.entry("+javaQuote(key)+","+emitter.definitions[key]+")")
	}
	definitions := "java.util.Map.ofEntries(" + strings.Join(definitionParts, ",") + ")"
	construct := options.Root + ".fromData(raw)"
	if jsonGenericRoot(root, decls) {
		construct = "new " + options.Root + "." + modelFactoryNameFor(decls, contractName) + "().fromData(raw)"
	}
	source := fmt.Sprintf(jsonSerdeJava, moduleName, shape, definitions, options.Integers == JSONIntegerString, options.Reals == JSONRealRationalString, moduleName, moduleName, options.Root, options.Root, options.Root, options.Root, options.Root, options.Root, options.Root, construct)
	header := "// Generated by Refine: validated Jackson 3 JSON serde. MIT licensed.\n"
	if namespace != "" {
		header += "package " + namespace + ";\n"
	}
	prefix := strings.ReplaceAll(namespace, ".", "/")
	files = append(files, File{Path: path.Join(prefix, moduleName+".java"), Source: header + source})
	return files, nil
}

func modelFactoryNameFor(decls map[string]language.TypeDecl, contract string) string {
	used := map[string]bool{sourceNameKey(contract): true}
	for name := range decls {
		used[sourceNameKey(name)] = true
	}
	name := "Factory"
	for used[sourceNameKey(name)] {
		name += "_"
	}
	return name
}
func jsonGenericRoot(root language.TypeDecl, decls map[string]language.TypeDecl) bool {
	name := root.Name
	seen := map[string]bool{}
	for {
		if seen[name] {
			return false
		}
		seen[name] = true
		decl := decls[name]
		if len(decl.Parameters) > 0 {
			return true
		}
		if decl.Body == nil {
			return false
		}
		base := unrefined(decl.Body)
		switch __gp_m1 := any(base.Form).(type) {
		case language.NamedType:
			parent := __gp_m1.Name
			if _, ok := decls[parent]; ok {
				name = parent
				continue
			}
		case language.AppliedType:
			fn := __gp_m1.Constructor
			arg := __gp_m1.Argument
			if fn != nil && arg != nil {
				parent, args := applied(base)
				if len(args) >= 0 {
					if _, ok := decls[parent]; ok {
						name = parent
						continue
					}
				}
			}
		default:
		}
		return false
	}
}
func jsonResolve(t *language.Type, decls map[string]language.TypeDecl, seen map[string]bool) (result *language.Type) {
	t = unrefined(t)
	switch __gp_m2 := any(t.Form).(type) {
	case language.NamedType:
		name := __gp_m2.Name
		decl, ok := decls[name]
		if !ok || decl.Body == nil {
			return t
		}
		if len(decl.Parameters) > 0 {
			unsupported(t.At, "generic JSON type is missing arguments")
		}
		if seen[name] {
			unsupported(t.At, "recursive JSON alias")
		}
		next := map[string]bool{}
		for key, value := range seen {
			next[key] = value
		}
		next[name] = true
		return jsonResolve(decl.Body, decls, next)
	case language.AppliedType:
		fn := __gp_m2.Constructor
		arg := __gp_m2.Argument
		if fn == nil || arg == nil {
			return t
		}
		name, args := applied(t)
		decl, ok := decls[name]
		if !ok || decl.Body == nil {
			return t
		}
		if len(args) != len(decl.Parameters) {
			unsupported(t.At, "generic JSON type argument count mismatch")
		}
		bindings := map[string]*language.Type{}
		for i, param := range decl.Parameters {
			bindings[param] = args[i]
		}
		closed, err := language.SubstituteType(decl.Body, bindings)
		if err != nil {
			unsupported(t.At, err.Error())
		}
		next := map[string]bool{}
		for key, value := range seen {
			next[key] = value
		}
		if next[name] {
			unsupported(t.At, "recursive JSON alias")
		}
		next[name] = true
		return jsonResolve(closed, decls, next)
	default:
		result = t
	}
	return result
}

type jsonShapeEmitter struct {
	decls       map[string]language.TypeDecl
	options     JSONSerdeOptions
	definitions map[string]string
	building    map[string]bool
	order       []string
	nodes       int
}
type jsonVariantShape struct {
	name      string
	arguments []*language.Type
}

func (e *jsonShapeEmitter) visit(t *language.Type, depth int) {
	e.nodes++
	if e.nodes > language.DefaultSubstitutionNodes {
		unsupported(t.At, "JSON shape node limit exceeded")
	}
	if depth > 512 {
		unsupported(t.At, "JSON shape depth limit exceeded")
	}
}
func (e *jsonShapeEmitter) preserve(name string) bool {
	return (name == e.options.Root && e.options.PreserveExtraFields) || e.options.PreserveExtraFieldsFor[name]
}
func (e *jsonShapeEmitter) reference(key string) string {
	return "new S(\"ref\",null,null," + javaQuote(key) + ",false,null)"
}
func (e *jsonShapeEmitter) record(key, name string, fields []language.Field, depth int) string {
	if _, ok := e.definitions[key]; ok {
		return e.reference(key)
	}
	e.definitions[key] = ""
	e.building[key] = true
	e.order = append(e.order, key)
	parts := []string{}
	for _, field := range fields {
		parts = append(parts, "new F("+javaQuote(field.Name)+","+e.shape(field.Type, depth+1)+")")
	}
	e.definitions[key] = "new S(\"record\",null,java.util.List.of(" + strings.Join(parts, ",") + "),null," + fmt.Sprint(e.preserve(name)) + ",null)"
	delete(e.building, key)
	return e.reference(key)
}
func (e *jsonShapeEmitter) unionDecl(key, name string, variants []language.Variant, bindings map[string]*language.Type, depth int) string {
	shapes := []jsonVariantShape{}
	for _, variant := range variants {
		arguments := variant.Arguments
		if bindings != nil {
			arguments = []*language.Type{}
			for _, argument := range variant.Arguments {
				closed, err := language.SubstituteType(argument, bindings)
				if err != nil {
					unsupported(argument.At, err.Error())
				}
				arguments = append(arguments, closed)
			}
		}
		shapes = append(shapes, jsonVariantShape{name: variant.Name, arguments: arguments})
	}
	return e.union(key, name, shapes, depth)
}
func (e *jsonShapeEmitter) union(key, name string, variants []jsonVariantShape, depth int) string {
	if _, ok := e.definitions[key]; ok {
		return e.reference(key)
	}
	wire, ok := e.options.Discriminators[name]
	if !ok || wire.Field == "" {
		unsupported(language.Span{}, "tagged-union JSON serde requires explicit discriminator metadata for "+name)
	}
	if len(wire.Values) != len(variants) || len(wire.Arguments) != len(variants) {
		unsupported(language.Span{}, "discriminator metadata must cover every constructor of "+name)
	}
	e.definitions[key] = ""
	e.order = append(e.order, key)
	seenTags := map[string]bool{}
	parts := []string{}
	for _, variant := range variants {
		tag, ok := wire.Values[variant.name]
		if !ok || tag == "" || seenTags[tag] {
			unsupported(language.Span{}, "missing or duplicate discriminator value for "+name+"."+variant.name)
		}
		seenTags[tag] = true
		names, ok := wire.Arguments[variant.name]
		if !ok || len(names) != len(variant.arguments) {
			unsupported(language.Span{}, "constructor argument names have wrong arity for "+name+"."+variant.name)
		}
		seenNames := map[string]bool{wire.Field: true}
		nameParts := []string{}
		shapeParts := []string{}
		for i, argument := range variant.arguments {
			if names[i] == "" || seenNames[names[i]] {
				unsupported(argument.At, "duplicate or empty union JSON member name")
			}
			seenNames[names[i]] = true
			nameParts = append(nameParts, javaQuote(names[i]))
			shapeParts = append(shapeParts, e.shape(argument, depth+1))
		}
		parts = append(parts, "new V("+javaQuote(variant.name)+","+javaQuote(tag)+",java.util.List.of("+strings.Join(nameParts, ",")+"),java.util.List.of("+strings.Join(shapeParts, ",")+"))")
	}
	e.definitions[key] = "new S(\"union\",null,null,null,false,new U(" + javaQuote(wire.Field) + ",java.util.List.of(" + strings.Join(parts, ",") + ")))"
	return e.reference(key)
}
func (e *jsonShapeEmitter) shape(t *language.Type, depth int) string {
	e.visit(t, depth)
	t = unrefined(t)
	switch __gp_m3 := any(t.Form).(type) {
	case language.NamedType:
		name := __gp_m3.Name

		if integerType(name) {
			return "new S(\"integer\",null,null,null,false,null)"
		}
		switch name {
		case "String":
			return "new S(\"text\",null,null,null,false,null)"
		case "Bool":
			return "new S(\"bool\",null,null,null,false,null)"
		case "Real":
			if e.options.Reals == JSONRealUnspecified {
				unsupported(t.At, "exact Real JSON encoding policy is required")
			}
			return "new S(\"real\",null,null,null,false,null)"
		case "Timestamp":
			if e.options.Timestamps != JSONTimestampRFC3339String {
				unsupported(t.At, "Timestamp JSON encoding policy is required")
			}
			return "new S(\"timestamp\",null,null,null,false,null)"
		}
		decl, ok := e.decls[name]
		if !ok {
			unsupported(t.At, "unknown JSON field type")
		}
		if len(decl.Parameters) > 0 {
			unsupported(t.At, "generic JSON field requires type arguments")
		}
		if decl.Body == nil {
			return e.unionDecl(name, name, decl.Variants, nil, depth)
		}
		base := unrefined(decl.Body)
		switch __gp_m4 := any(base.Form).(type) {
		case language.RecordType:
			fields := __gp_m4.Fields
			return e.record(name, name, fields, depth)
		default:
			return e.shape(base, depth+1)
		}
	case language.RecordType:
		fields := __gp_m3.Fields
		return e.record("@anonymous:"+fmt.Sprint(t.At.Start.Offset), "", fields, depth)
	case language.ListType:
		element := __gp_m3.Element
		return "new S(\"list\"," + e.shape(element, depth+1) + ",null,null,false,null)"
	case language.AppliedType:
		fn := __gp_m3.Constructor
		arg := __gp_m3.Argument
		if fn == nil || arg == nil {
			unsupported(t.At, "invalid generic JSON field")
		}
		name, args := applied(t)
		if name == "Maybe" && len(args) == 1 {
			return "new S(\"maybe\"," + e.shape(args[0], depth+1) + ",null,null,false,null)"
		}
		if name == "Nullable" && len(args) == 1 {
			return "new S(\"nullable\"," + e.shape(args[0], depth+1) + ",null,null,false,null)"
		}
		key := jsonTypeKey(t, 0)
		if name == "Result" && len(args) == 2 {
			return e.union(key, "Result", []jsonVariantShape{{name: "Err", arguments: args[:1]}, {name: "Ok", arguments: args[1:]}}, depth)
		}
		decl, ok := e.decls[name]
		if !ok {
			unsupported(t.At, "unknown generic JSON field")
		}
		if len(args) != len(decl.Parameters) {
			unsupported(t.At, "generic JSON type argument count mismatch")
		}
		bindings := map[string]*language.Type{}
		for i, param := range decl.Parameters {
			bindings[param] = args[i]
		}
		if decl.Body == nil {
			return e.unionDecl(key, name, decl.Variants, bindings, depth)
		}
		closed, err := language.SubstituteType(decl.Body, bindings)
		if err != nil {
			unsupported(t.At, err.Error())
		}
		base := unrefined(closed)
		switch __gp_m5 := any(base.Form).(type) {
		case language.RecordType:
			fields := __gp_m5.Fields
			return e.record(key, name, fields, depth)
		default:
			return e.shape(base, depth+1)
		}
	default:
		unsupported(t.At, "unsupported JSON field shape")
	}
	return ""
}
func jsonTypeKey(t *language.Type, depth int) (key string) {
	if depth > 512 {
		unsupported(t.At, "JSON type key depth limit exceeded")
	}
	t = unrefined(t)
	switch __gp_m6 := any(t.Form).(type) {
	case language.NamedType:
		name := __gp_m6.Name
		return name
	case language.ListType:
		element := __gp_m6.Element
		return "[" + jsonTypeKey(element, depth+1) + "]"
	case language.AppliedType:
		fn := __gp_m6.Constructor
		arg := __gp_m6.Argument
		return jsonTypeKey(fn, depth+1) + "<" + jsonTypeKey(arg, depth+1) + ">"
	default:
		key = "@" + fmt.Sprint(t.At.Start.Offset)
	}
	return key
}

const jsonSerdeJava = `
public final class %s extends tools.jackson.databind.module.SimpleModule {
    @java.io.Serial private static final long serialVersionUID=1L;
    private sealed interface J permits O,A,N,T,B,Z {}
    private record O(java.util.List<E> fields) implements J { O { fields=java.util.List.copyOf(fields); } }
    private record E(String name,J value) {}
    private record A(java.util.List<J> values) implements J { A { values=java.util.List.copyOf(values); } }
    private record N(String value) implements J {}
    private record T(String value) implements J {}
    private record B(boolean value) implements J {}
    private record Z() implements J {}
    private record S(String kind,S argument,java.util.List<F> fields,String reference,boolean preserveExtras,U union) {}
    private record F(String name,S shape) {}
    private record U(String discriminator,java.util.List<V> variants) {}
    private record V(String constructor,String tag,java.util.List<String> names,java.util.List<S> shapes) {}
    private static final S ROOT=%s;
    private static final java.util.Map<String,S> DEFINITIONS=%s;
    private static final boolean INTEGER_STRING=%t,REAL_STRING=%t;
    public %s(){super(%q);addSerializer(%s.class,new Serializer());addDeserializer(%s.class,new Deserializer());}
    private static final class Serializer extends tools.jackson.databind.ValueSerializer<%s>{
        @Override public void serialize(%s value,tools.jackson.core.JsonGenerator output,tools.jackson.databind.SerializationContext context)throws tools.jackson.core.JacksonException{
            ModelSupport.nonNull(value,"");value.validate().orThrow();J wire;try{wire=toWire(ROOT,value.rawData(),0);}catch(ArithmeticException failure){throw structure("Value cannot be represented exactly by the configured JSON encoding.");}write(wire,output);
        }
    }
    private static final class Deserializer extends tools.jackson.databind.ValueDeserializer<%s>{
        @Override public %s getNullValue(tools.jackson.databind.DeserializationContext context){throw structure("Java null is not a language value.");}
        @Override public %s deserialize(tools.jackson.core.JsonParser input,tools.jackson.databind.DeserializationContext context)throws tools.jackson.core.JacksonException{
            J wire=read(input,new java.util.ArrayDeque<>());Data raw=fromWire(ROOT,wire,0);return %s;
        }
    }
    private static S resolve(S shape){var current=shape;var seen=new java.util.HashSet<String>();while(current.kind().equals("ref")){if(!seen.add(current.reference()))throw structure("Cyclic JSON shape reference without a record boundary.");current=DEFINITIONS.get(current.reference());if(current==null)throw new AssertionError("missing checked JSON shape");}return current;}
    private static J recordToWire(S shape,Data raw,int depth){var struct=(Data.Struct)raw;var out=new java.util.ArrayList<E>();var declared=new java.util.HashSet<String>();for(F field:shape.fields()){declared.add(field.name());Data value=null;for(var candidate:struct.fields())if(candidate.name().equals(field.name())){value=candidate.value();break;}if(value==null)continue;S fieldShape=resolve(field.shape());if(fieldShape.kind().equals("maybe")&&value instanceof Data.Variant v&&v.name().equals("Nothing"))continue;if(fieldShape.kind().equals("maybe"))value=((Data.Variant)value).values().getFirst();out.add(new E(field.name(),toWire(fieldShape.kind().equals("maybe")?fieldShape.argument():fieldShape,value,depth+1)));}if(shape.preserveExtras())for(var field:struct.fields())if(!declared.contains(field.name()))out.add(new E(field.name(),extraToWire(field.value(),depth+1)));return new O(out);}
    private static Data wireToRecord(S shape,J wire,int depth){if(!(wire instanceof O object))throw structure("Expected JSON object.");var source=new java.util.LinkedHashMap<String,J>();for(E field:object.fields())source.put(field.name(),field.value());var out=new java.util.ArrayList<Data.Field>();for(F field:shape.fields()){S fieldShape=resolve(field.shape());J value=source.remove(field.name());if(value==null){if(fieldShape.kind().equals("maybe"))out.add(new Data.Field(field.name(),new Data.Variant("Nothing",java.util.List.of())));continue;}Data decoded=fromWire(fieldShape.kind().equals("maybe")?fieldShape.argument():fieldShape,value,depth+1);if(fieldShape.kind().equals("maybe"))decoded=new Data.Variant("Just",java.util.List.of(decoded));out.add(new Data.Field(field.name(),decoded));}if(shape.preserveExtras())for(var field:source.entrySet())out.add(new Data.Field(field.getKey(),extraFromWire(field.getValue(),depth+1)));return new Data.Struct(out);}
    private static J toWire(S unresolved,Data data,int depth){if(depth>512)throw structure("JSON value nesting limit exceeded.");S shape=resolve(unresolved);return switch(shape.kind()){
        case "integer"->INTEGER_STRING?new T(((Data.Number)data).value().numerator().toString()):new N(((Data.Number)data).value().numerator().toString());
        case "real"->REAL_STRING?new T(((Data.Number)data).value().toString()):new N(((Data.Number)data).value().decimal());
        case "text"->new T(((Data.Text)data).value());case "timestamp"->new T(((Data.Text)data).value());case "bool"->new B(((Data.Bool)data).value());
        case "record"->recordToWire(shape,data,depth);case "union"->unionToWire(shape.union(),data,depth);case "list"->{var values=new java.util.ArrayList<J>();for(Data item:((Data.Sequence)data).values())values.add(toWire(shape.argument(),item,depth+1));yield new A(values);}
        case "nullable"->{var value=(Data.Variant)data;yield value.name().equals("Null")?new Z():toWire(shape.argument(),value.values().getFirst(),depth+1);}
        default->throw new AssertionError("unsupported checked JSON shape");};}
    private static Data fromWire(S unresolved,J wire,int depth){if(depth>512)throw structure("JSON value nesting limit exceeded.");S shape=resolve(unresolved);return switch(shape.kind()){
        case "integer"->integer(wire);case "real"->real(wire);
        case "text"->new Data.Text(text(wire));case "timestamp"->new Data.Text(text(wire));case "bool"->{if(!(wire instanceof B value))throw structure("Expected JSON Boolean.");yield new Data.Bool(value.value());}
        case "record"->wireToRecord(shape,wire,depth);case "union"->wireToUnion(shape.union(),wire,depth);case "list"->{if(!(wire instanceof A array))throw structure("Expected JSON array.");var values=new java.util.ArrayList<Data>();for(J item:array.values())values.add(fromWire(shape.argument(),item,depth+1));yield new Data.Sequence(values);}
        case "nullable"->wire instanceof Z?new Data.Variant("Null",java.util.List.of()):new Data.Variant("NonNull",java.util.List.of(fromWire(shape.argument(),wire,depth+1)));
        default->throw new AssertionError("unsupported checked JSON shape");};}
    private static J unionToWire(U shape,Data data,int depth){var value=(Data.Variant)data;V selected=null;for(var variant:shape.variants())if(variant.constructor().equals(value.name())){selected=variant;break;}if(selected==null||value.values().size()!=selected.shapes().size())throw structure("Unknown or malformed union constructor.");var fields=new java.util.ArrayList<E>();fields.add(new E(shape.discriminator(),new T(selected.tag())));for(int i=0;i<selected.shapes().size();i++)fields.add(new E(selected.names().get(i),toWire(selected.shapes().get(i),value.values().get(i),depth+1)));return new O(fields);}
    private static Data wireToUnion(U shape,J wire,int depth){if(!(wire instanceof O object))throw structure("Expected JSON object for tagged union.");var source=new java.util.LinkedHashMap<String,J>();for(var field:object.fields())source.put(field.name(),field.value());J tagWire=source.remove(shape.discriminator());if(tagWire==null)throw structure("Missing union discriminator: "+shape.discriminator());String tag=text(tagWire);V selected=null;for(var variant:shape.variants())if(variant.tag().equals(tag)){selected=variant;break;}if(selected==null)throw structure("Unknown union discriminator value.");var values=new java.util.ArrayList<Data>();for(int i=0;i<selected.shapes().size();i++){J argument=source.remove(selected.names().get(i));if(argument==null)throw structure("Missing union argument: "+selected.names().get(i));values.add(fromWire(selected.shapes().get(i),argument,depth+1));}return new Data.Variant(selected.constructor(),values);}
    private static String text(J wire){if(!(wire instanceof T value))throw structure("Expected JSON string.");return value.value();}private static String number(J wire){if(!(wire instanceof N value))throw structure("Expected JSON number.");return value.value();}
    private static Data integer(J wire){try{return new Data.Number(Rational.of(new java.math.BigInteger(INTEGER_STRING?text(wire):number(wire))));}catch(NumberFormatException failure){throw structure("Invalid integer wire value.");}}
    private static Data real(J wire){try{return new Data.Number(REAL_STRING?Rational.parse(text(wire)):Rational.parse(number(wire)));}catch(IllegalArgumentException failure){throw structure("Invalid exact real wire value.");}}
    private static J extraToWire(Data data,int depth){if(depth>512)throw structure("JSON value nesting limit exceeded.");return switch(data){case Data.Struct object->{var fields=new java.util.ArrayList<E>();var seen=new java.util.HashSet<String>();for(var field:object.fields()){if(!seen.add(field.name()))throw structure("Duplicate preserved object key: "+field.name());fields.add(new E(field.name(),extraToWire(field.value(),depth+1)));}yield new O(fields);}case Data.Sequence array->{var values=new java.util.ArrayList<J>();for(var item:array.values())values.add(extraToWire(item,depth+1));yield new A(values);}case Data.Number number->new N(number.value().decimal());case Data.Text value->new T(value.value());case Data.Bool value->new B(value.value());case Data.Variant value->{if(!value.name().equals("Null")||!value.values().isEmpty())throw structure("Preserved JSON extras cannot encode a language constructor.");yield new Z();}};}
    private static Data extraFromWire(J wire,int depth){if(depth>512)throw structure("JSON value nesting limit exceeded.");return switch(wire){case O object->{var fields=new java.util.ArrayList<Data.Field>();for(var field:object.fields())fields.add(new Data.Field(field.name(),extraFromWire(field.value(),depth+1)));yield new Data.Struct(fields);}case A array->{var values=new java.util.ArrayList<Data>();for(var item:array.values())values.add(extraFromWire(item,depth+1));yield new Data.Sequence(values);}case N number->{try{yield new Data.Number(Rational.parse(number.value()));}catch(IllegalArgumentException failure){throw structure("Invalid preserved JSON number.");}}case T value->new Data.Text(value.value());case B value->new Data.Bool(value.value());case Z ignored->new Data.Variant("Null",java.util.List.of());};}
    private static J read(tools.jackson.core.JsonParser input,java.util.ArrayDeque<String> path)throws tools.jackson.core.JacksonException{var token=input.currentToken();if(token==null)token=input.nextToken();return switch(token){case START_OBJECT->{var fields=new java.util.ArrayList<E>();var seen=new java.util.HashSet<String>();while(input.nextToken()!=tools.jackson.core.JsonToken.END_OBJECT){String name=input.currentName();if(!seen.add(name))throw structure("Duplicate JSON object key: "+name);input.nextToken();fields.add(new E(name,read(input,path)));}yield new O(fields);}case START_ARRAY->{var values=new java.util.ArrayList<J>();while(input.nextToken()!=tools.jackson.core.JsonToken.END_ARRAY)values.add(read(input,path));yield new A(values);}case VALUE_STRING->new T(input.getString());case VALUE_NUMBER_INT,VALUE_NUMBER_FLOAT->new N(input.getString());case VALUE_TRUE->new B(true);case VALUE_FALSE->new B(false);case VALUE_NULL->new Z();default->throw structure("Expected a JSON value.");};}
    private static void write(J value,tools.jackson.core.JsonGenerator output)throws tools.jackson.core.JacksonException{switch(value){case O object->{output.writeStartObject();for(E field:object.fields()){output.writeName(field.name());write(field.value(),output);}output.writeEndObject();}case A array->{output.writeStartArray();for(J item:array.values())write(item,output);output.writeEndArray();}case N number->output.writeNumber(number.value());case T text->output.writeString(text.value());case B bool->output.writeBoolean(bool.value());case Z ignored->output.writeNull();}}
    private static ValidationException structure(String message){return new ValidationException(new Validation.Invalid(java.util.List.of(new Validation.Diagnostic("validation.structure",java.util.List.of(""),"",message)),false));}
}
`
