package native

import (
    "encoding/binary"
    "errors"
    "fmt"
    "math"
    "math/big"
    "strconv"
    "strings"

    avro "github.com/hamba/avro/v2"
    "goforge.dev/refine/language"
    "goforge.dev/refine/schemajson"
    "goforge.dev/refine/validation"
    "goforge.dev/refine/value"
)

// AvroDefaultCheck records what compilation established about one reachable
// reader default after decoding it through the checked language field type.
// Invalid defaults reject compilation and therefore never appear here.
// Indeterminate means refinement evaluation exhausted its deterministic budget.
type AvroDefaultCheck struct { Resource string `json:"resource"`; Pointer string `json:"pointer"`; State string `json:"state"`; Code string `json:"code"`; Message string `json:"message"` }

func copyAvroDefaultChecks(in []AvroDefaultCheck)[]AvroDefaultCheck{return append([]AvroDefaultCheck(nil),in...)}
func (p *Project) AvroDefaultChecks()[]AvroDefaultCheck{if p==nil{return nil};return copyAvroDefaultChecks(p.avroDefaultChecks)}

type rawAvroDefault struct{node schemajson.Node;resource string;pointer string}
type rawAvroDefaults struct{fields map[string]map[string]rawAvroDefault;seen map[avro.Schema]bool}
func newRawAvroDefaults()*rawAvroDefaults{return &rawAvroDefaults{fields:map[string]map[string]rawAvroDefault{},seen:map[avro.Schema]bool{}}}

func collectRawAvroDefaults(resources []Resource,root ResourceSelector)(avro.Schema,*rawAvroDefaults,error){cache:=&avro.SchemaCache{};index:=newRawAvroDefaults();var selected avro.Schema
    for _,resource:=range resources{doc,err:=schemajson.Parse([]byte(resource.Source),schemajson.Limits{});if err!=nil{return nil,nil,err};schema,err:=parseAvroStructure([]byte(resource.Source),cache);if err!=nil{return nil,nil,err};index.walk(doc.Root(),schema,resource.URI,"");if resource.URI==root.Resource{selected=schema}}
    if selected==nil{return nil,nil,&Error{Code:"native.root",Format:Avro,Pointer:root.Resource,Message:"root writer schema is absent"}};return selected,index,nil
}

func (r *rawAvroDefaults) walk(node schemajson.Node,schema avro.Schema,resource,path string){schema=avroDereference(schema);if schema==nil||r.seen[schema]{return};kind:=schemajson.KindName(node.Kind());if kind=="array"&&schema.Type()==avro.Union{r.seen[schema]=true;branches:=schema.(*avro.UnionSchema).Types();for i,item:=range node.Elements(){if i<len(branches){r.walk(item,branches[i],resource,fmt.Sprintf("%s/%d",path,i))}};return};if kind!="object"{return};typ,present:=node.Lookup("type");if !present{return};if schemajson.KindName(typ.Kind())!="string"{r.walk(typ,schema,resource,path+"/type");return};r.seen[schema]=true
    switch schema.Type(){
    case avro.Record:record:=schema.(*avro.RecordSchema);byField:=r.fields[record.FullName()];if byField==nil{byField=map[string]rawAvroDefault{};r.fields[record.FullName()]=byField};rawFields,_:=node.Lookup("fields");fields:=record.Fields();for i,rawField:=range rawFields.Elements(){if i>=len(fields){break};field:=fields[i];fieldPath:=fmt.Sprintf("%s/fields/%d",path,i);if def,ok:=rawField.Lookup("default");ok{byField[field.Name()]=rawAvroDefault{node:def,resource:resource,pointer:fieldPath+"/default"}};rawType,_:=rawField.Lookup("type");r.walk(rawType,field.Type(),resource,fieldPath+"/type")}
    case avro.Array:if items,ok:=node.Lookup("items");ok{r.walk(items,schema.(*avro.ArraySchema).Items(),resource,path+"/items")}
    case avro.Map:if values,ok:=node.Lookup("values");ok{r.walk(values,schema.(*avro.MapSchema).Values(),resource,path+"/values")}
    }
}

func validateAvroRefinementDefaults(p *Project)(*Project,error){if p==nil||p.Format()!=Avro{return p,nil};resources,err:=p.EffectiveResources();if err!=nil{return nil,err};schema,index,err:=collectRawAvroDefaults(resources,p.root);if err!=nil{return nil,wrap(Avro,"native.default","",err)};target,err:=p.PayloadType();if err!=nil{return nil,err};checked:=target.CheckedSyntax();walker:=avroDefaultWalker{project:p,index:index,matcher:newAvroDefaultMatcher(index,schemajson.DefaultNodes,schemajson.DefaultBytes),declarations:map[string]language.TypeDecl{},seen:map[string]bool{},unknown:map[string]bool{}};for _,decl:=range checked.Module.Syntax.Types{walker.declarations[decl.Name]=decl};if err:=walker.walk(checked.Type,schema,nil,"",0);err!=nil{return nil,err};p.avroDefaultChecks=copyAvroDefaultChecks(walker.checks);return p,nil}

type avroDefaultWalker struct{project *Project;index *rawAvroDefaults;matcher *avroDefaultMatcher;declarations map[string]language.TypeDecl;seen map[string]bool;unknown map[string]bool;checks []AvroDefaultCheck}

func (w *avroDefaultWalker) traversalUnknown(key,message string){if w.unknown==nil{w.unknown=map[string]bool{}};if w.unknown[key]{return};w.unknown[key]=true;resource,pointer:="","";if w.project!=nil{resource=w.project.root.Resource;pointer=w.project.root.Pointer};w.checks=append(w.checks,AvroDefaultCheck{Resource:resource,Pointer:pointer,State:"indeterminate",Code:"native.limit",Message:message})}
func avroSubstitutionLimited(err error)bool{if err==nil{return false};message:=err.Error();return strings.Contains(message,"node limit exceeded")||strings.Contains(message,"depth limit exceeded")}
func (w *avroDefaultWalker) substitution(err error,key string)error{if avroSubstitutionLimited(err){w.traversalUnknown("substitution:"+key,"Avro default refinement traversal exhausted deterministic type-substitution resources.");return nil};return &Error{Code:"native.default-refinement",Format:Avro,Pointer:key,Message:"Avro default refinement traversal encountered malformed checked type substitution",Cause:err}}

func (w *avroDefaultWalker) walk(t *language.Type,schema avro.Schema,bindings map[string]*language.Type,nominal string,depth int)error{if t==nil{return &Error{Code:"native.default-refinement",Format:Avro,Pointer:nominal,Message:"Avro default refinement traversal encountered a nil checked type"}};if depth>512{w.traversalUnknown("depth:"+nominal,"Avro default refinement traversal exceeded its deterministic type-depth limit.");return nil};schema=avroDereference(schema);if schema==nil{return &Error{Code:"native.default-refinement",Format:Avro,Pointer:nominal,Message:"Avro default refinement traversal encountered a nil native schema"}};match t.Form{
    case language.RefinedType(base,_):return w.walk(base,schema,bindings,nominal,depth+1)
    case language.NamedType(name):if bound,ok:=bindings[name];ok{return w.walk(bound,schema,bindings,nominal,depth+1)};if encoding,scalar:=w.project.metadata.Scalars[name];scalar{return w.scalarCarrier(name,encoding,schema)};if name=="Bool"||name=="String"||name=="Timestamp"||name=="Real"||name=="Float32"||name=="Float64"||jsonLanguageInteger(name){return nil};decl,ok:=w.declarations[name];if !ok{return &Error{Code:"native.default-refinement",Format:Avro,Pointer:name,Message:"Avro default refinement traversal encountered an unbound checked type"}};if len(decl.Parameters)!=0{return &Error{Code:"native.default-refinement",Format:Avro,Pointer:name,Message:"Avro default refinement traversal encountered an unapplied generic type"}};if decl.Body!=nil{return w.walk(decl.Body,schema,nil,name,depth+1)};return w.union(decl.Variants,schema,nil,depth+1)
    case language.ListType(element):if schema.Type()==avro.Array{return w.walk(element,schema.(*avro.ArraySchema).Items(),bindings,"",depth+1)};return nil
    case language.RecordType(fields):return w.record(fields,schema,bindings,depth+1)
    case language.AppliedType(_,_):name,args,ok:=jsonApplied(t);if !ok{return nil};if name=="Nullable"&&len(args)==1{if schema.Type()!=avro.Union{return nil};for _,branch:=range schema.(*avro.UnionSchema).Types(){if avroDereference(branch).Type()!=avro.Null{return w.walk(args[0],branch,bindings,"",depth+1)}};return nil};if name=="Map"&&len(args)==2&&schema.Type()==avro.Map{return w.walk(args[1],schema.(*avro.MapSchema).Values(),bindings,"",depth+1)};decl,ok:=w.declarations[name];if !ok||len(args)!=len(decl.Parameters){return nil};closed:=map[string]*language.Type{};for key,item:=range bindings{closed[key]=item};for i,param:=range decl.Parameters{argument:=args[i];if bindings!=nil{resolved,subErr:=language.SubstituteType(argument,bindings);if subErr!=nil{return w.substitution(subErr,name)};argument=resolved};closed[param]=argument};if decl.Body!=nil{return w.walk(decl.Body,schema,closed,name,depth+1)};return w.union(decl.Variants,schema,closed,depth+1)
    case language.ArrowType(_,_):return nil
    };return nil}

func (w *avroDefaultWalker) union(variants []language.Variant,schema avro.Schema,bindings map[string]*language.Type,depth int)error{
    if schema.Type()==avro.Enum{symbols:=schema.(*avro.EnumSchema).Symbols();if len(symbols)!=len(variants){return &Error{Code:"native.enforcement",Format:Avro,Message:"edited checked constructors do not match the effective Avro enum symbol order"}};for i,variant:=range variants{if len(variant.Arguments)!=0||variant.Name!=safeTypeName(symbols[i]){return &Error{Code:"native.enforcement",Format:Avro,Pointer:variant.Name,Message:"edited checked constructors do not match the effective Avro enum symbol order"}}};return nil}
    if schema.Type()!=avro.Union{return nil};branches:=schema.(*avro.UnionSchema).Types();if len(branches)!=len(variants){return nil};for i,variant:=range variants{if len(variant.Arguments)!=1{continue};typ:=variant.Arguments[0];if bindings!=nil{closed,err:=language.SubstituteType(typ,bindings);if err!=nil{if handled:=w.substitution(err,variant.Name);handled!=nil{return handled};continue};typ=closed};if err:=w.walk(typ,branches[i],nil,"",depth+1);err!=nil{return err}};return nil
}

func (w *avroDefaultWalker) record(fields []language.Field,schema avro.Schema,bindings map[string]*language.Type,depth int)error{if schema.Type()!=avro.Record{return nil};record:=schema.(*avro.RecordSchema);checkedFields:=map[string]language.Field{};key:=record.FullName()+"|";for _,field:=range fields{typ:=field.Type;if bindings!=nil{closed,err:=language.SubstituteType(typ,bindings);if err!=nil{return w.substitution(err,field.Name)};typ=closed};field.Type=typ;checkedFields[field.Name]=field;key+=field.Name+":"+language.FormatType(typ)+";"};if w.seen[key]{return nil};w.seen[key]=true;rawFields:=w.index.fields[record.FullName()]
    for _,nativeField:=range record.Fields(){field,ok:=checkedFields[nativeField.Name()];if !ok{continue};typ:=field.Type;if def,hasDefault:=rawFields[nativeField.Name()];hasDefault{if err:=w.check(def,typ,nativeField.Type());err!=nil{return err}};if err:=w.walk(typ,nativeField.Type(),nil,"",depth+1);err!=nil{return err}}
    return nil
}

func avroDefaultComponentBytes(def rawAvroDefault)([]byte,error){text,ok:=def.node.Text();if !ok{return nil,errors.New("rational-record component default is not Avro bytes text")};units:=text.Units();raw:=make([]byte,len(units));for i,unit:=range units{if unit>255{return nil,errors.New("rational-record component default is outside byte range")};raw[i]=byte(unit)};return raw,nil}
func (w *avroDefaultWalker) carrierError(def rawAvroDefault,message string,cause error)error{return &Error{Code:"native.default-refinement",Format:Avro,Pointer:def.resource+"#"+def.pointer,Message:message,Cause:cause}}
func (w *avroDefaultWalker) carrierUnknown(name string,def rawAvroDefault,message string,code string){key:="carrier:"+name+":"+def.resource+"#"+def.pointer;if w.unknown==nil{w.unknown=map[string]bool{}};if w.unknown[key]{return};w.unknown[key]=true;w.checks=append(w.checks,AvroDefaultCheck{Resource:def.resource,Pointer:def.pointer,State:"indeterminate",Code:code,Message:message})}
func (w *avroDefaultWalker) scalarCarrier(name string,encoding ScalarEncoding,schema avro.Schema)error{if encoding.Kind!=RationalRecord{return nil};schema=avroDereference(schema);if schema.Type()!=avro.Record{return &Error{Code:"native.enforcement",Format:Avro,Pointer:name,Message:"rational-record scalar requires an Avro record carrier"}};record:=schema.(*avro.RecordSchema);fields:=record.Fields();if len(fields)!=2||fields[0].Name()!="numerator"||fields[1].Name()!="denominator"||avroDereference(fields[0].Type()).Type()!=avro.Bytes||avroDereference(fields[1].Type()).Type()!=avro.Bytes{return &Error{Code:"native.enforcement",Format:Avro,Pointer:name,Message:"rational-record scalar carrier must contain ordered bytes fields numerator and denominator"}};defaults:=w.index.fields[record.FullName()];raw:=map[string][]byte{};present:=map[string]rawAvroDefault{}
    for _,field:=range fields{def,ok:=defaults[field.Name()];if !ok{continue};component,err:=avroDefaultComponentBytes(def);if err!=nil{return w.carrierError(def,"rational-record component default is not structurally representable",err)};if !minimalSignedAvroInteger(component){return w.carrierError(def,"rational-record component default is not minimal signed two's-complement",nil)};if field.Name()=="denominator"&&(len(component)==1&&component[0]==0||component[0]&0x80!=0){return w.carrierError(def,"rational-record denominator default is not positive",nil)};raw[field.Name()]=component;present[field.Name()]=def}
    numerator,nok:=raw["numerator"];denominator,dok:=raw["denominator"];if nok&&dok{digits:=0;for _,component:=range [][]byte{numerator,denominator}{if len(component)>math.MaxInt/8{digits=w.project.metadata.NumericExpansionLimit()+1;break};digits+=(len(component)*8*30103)/100000+1};if digits>w.project.metadata.NumericExpansionLimit(){for _,field:=range fields{if def,ok:=present[field.Name()];ok{w.carrierUnknown(name,def,"Rational-record component default exceeded deterministic exact-number resources.","native.limit")}};return nil};n:=signedAvroInteger(numerator);d:=signedAvroInteger(denominator);if new(big.Int).GCD(nil,nil,new(big.Int).Abs(new(big.Int).Set(n)),d).Cmp(big.NewInt(1))!=0{return w.carrierError(present["denominator"],"rational-record component defaults do not form a reduced exact rational",nil)};number,err:=value.ParseNumber(n.String()+"/"+d.String());if err!=nil{return w.carrierError(present["denominator"],"rational-record component defaults could not form an exact rational",err)};target,err:=w.project.program.PayloadType(name);if err!=nil{return w.carrierError(present["denominator"],"rational-record scalar type is not a checked payload",err)};report:=target.ValidateData(value.OfNumber(number),validation.Limits{});if validation.StateName(report.State())=="invalid"{return w.carrierError(present["denominator"],"complete rational-record defaults conclusively fail the checked scalar refinements",nil)}}
    for _,field:=range fields{if def,ok:=present[field.Name()];ok{w.carrierUnknown(name,def,"Rational-record component default is encoding-valid; its checked scalar result depends on the resolved reader fields.","native.default.unknown")}};return nil}

func (w *avroDefaultWalker) check(def rawAvroDefault,typ *language.Type,schema avro.Schema)error{encoder:=avroDefaultEncoder{limits:AvroPayloadLimits{Bytes:schemajson.DefaultBytes,Depth:schemajson.DefaultDepth,Values:schemajson.DefaultNodes,StringBytes:1<<20},index:w.index,matcher:w.matcher};if err:=encoder.value(schema,def.node,0,"$");err!=nil{var limited *avroPayloadLimitError;if errors.As(err,&limited){w.checks=append(w.checks,AvroDefaultCheck{Resource:def.resource,Pointer:def.pointer,State:"indeterminate",Code:"native.limit",Message:"Avro default refinement validation exceeded deterministic decode resources."});return nil};return &Error{Code:"native.default-refinement",Format:Avro,Pointer:def.resource+"#"+def.pointer,Message:"Avro field default could not be decoded through its checked field type",Cause:err}}
    decoder:=avroValueDecoder{cursor:avroBinaryCursor{input:encoder.output,limits:encoder.limits},metadata:w.project.Metadata(),declarations:w.declarations};data,err:=decoder.decode(typ,schema,nil,"$",0,"");if err!=nil{return &Error{Code:"native.default-refinement",Format:Avro,Pointer:def.resource+"#"+def.pointer,Message:"Avro field default does not match its checked field type",Cause:err}};target,err:=w.project.program.PayloadType(language.FormatType(typ));if err!=nil{return wrap(Avro,"native.default-refinement",def.resource+"#"+def.pointer,err)};report:=target.ValidateData(data,validation.Limits{});state:=validation.StateName(report.State());if state=="invalid"{return &Error{Code:"native.default-refinement",Format:Avro,Pointer:def.resource+"#"+def.pointer,Message:"Avro field default conclusively fails its checked refinements"}};code,message:="native.default.valid","Avro field default satisfies its checked field contract.";if state=="indeterminate"{code="native.default.unknown";message="Avro field default refinement result is unknown within deterministic evaluation resources."};w.checks=append(w.checks,AvroDefaultCheck{Resource:def.resource,Pointer:def.pointer,State:state,Code:code,Message:message});return nil}

type avroDefaultEncoder struct{output []byte;limits AvroPayloadLimits;nodes int;index *rawAvroDefaults;matcher *avroDefaultMatcher}
func (e *avroDefaultEncoder) fail(path,message string)error{return fmt.Errorf("%s: %s",path,message)}
func (e *avroDefaultEncoder) enter(depth int,path string)error{if depth>e.limits.Depth{return &avroPayloadLimitError{path:path,message:"default nesting exceeds limit"}};if e.nodes>=e.limits.Values{return &avroPayloadLimitError{path:path,message:"default value count exceeds limit"}};e.nodes++;return nil}
func (e *avroDefaultEncoder) append(raw []byte,path string)error{if len(raw)>e.limits.Bytes-len(e.output){return &avroPayloadLimitError{path:path,message:"encoded default byte size exceeds limit"}};e.output=append(e.output,raw...);return nil}
func (e *avroDefaultEncoder) long(number int64,path string)error{encoded:=uint64(number<<1)^uint64(number>>63);raw:=[]byte{};for encoded>=0x80{raw=append(raw,byte(encoded)|0x80);encoded>>=7};raw=append(raw,byte(encoded));return e.append(raw,path)}
func (e *avroDefaultEncoder) bytes(raw []byte,path string)error{if len(raw)>e.limits.StringBytes{return &avroPayloadLimitError{path:path,message:"default string/bytes exceeds limit"}};if err:=e.long(int64(len(raw)),path);err!=nil{return err};return e.append(raw,path)}

func (e *avroDefaultEncoder) value(schema avro.Schema,node schemajson.Node,depth int,path string)error{schema=avroDereference(schema);if err:=e.enter(depth,path);err!=nil{return err};switch schema.Type(){
    case avro.Null:return nil
    case avro.Boolean:if node.Raw()=="true"{return e.append([]byte{1},path)};return e.append([]byte{0},path)
    case avro.Int,avro.Long:number,err:=value.ParseNumber(node.Raw());if err!=nil||!number.IsInteger(){return e.fail(path,"default is not an integer")};parsed,err:=strconv.ParseInt(number.Show(),10,64);if err!=nil{return e.fail(path,"integer default is outside int64")};return e.long(parsed,path)
    case avro.Float, avro.Double:bits:=64;size:=8;if schema.Type()==avro.Float{bits=32;size=4};number,err:=strconv.ParseFloat(node.Raw(),bits);if err!=nil&&!math.IsInf(number,0){return e.fail(path,"floating default is not representable")};raw:=make([]byte,size);if size==4{binary.LittleEndian.PutUint32(raw,math.Float32bits(float32(number)))}else{binary.LittleEndian.PutUint64(raw,math.Float64bits(number))};return e.append(raw,path)
    case avro.String:text,ok:=node.Text();if !ok{return e.fail(path,"string default is not text")};raw,err:=text.UTF8();if err!=nil{return e.fail(path,"string default is not Unicode scalar text")};return e.bytes([]byte(raw),path)
    case avro.Bytes,avro.Fixed:text,ok:=node.Text();if !ok{return e.fail(path,"bytes default is not text")};units:=text.Units();raw:=make([]byte,len(units));for i,unit:=range units{if unit>255{return e.fail(path,"bytes default code point is outside 0-255")};raw[i]=byte(unit)};if schema.Type()==avro.Fixed{return e.append(raw,path)};return e.bytes(raw,path)
    case avro.Enum:text,ok:=nodeString(node);if !ok{return e.fail(path,"enum default is not text")};for index,symbol:=range schema.(*avro.EnumSchema).Symbols(){if text==symbol{return e.long(int64(index),path)}};return e.fail(path,"enum default is not a symbol")
    case avro.Array:items:=node.Elements();if len(items)>e.limits.Values-e.nodes{return &avroPayloadLimitError{path:path,message:"default array exceeds value count limit"}};if len(items)>0{if err:=e.long(int64(len(items)),path);err!=nil{return err};for i,item:=range items{if err:=e.value(schema.(*avro.ArraySchema).Items(),item,depth+1,fmt.Sprintf("%s[%d]",path,i));err!=nil{return err}}};return e.long(0,path)
    case avro.Map:members:=node.Members();if len(members)>e.limits.Values-e.nodes{return &avroPayloadLimitError{path:path,message:"default map exceeds value count limit"}};if len(members)>0{if err:=e.long(int64(len(members)),path);err!=nil{return err};for _,member:=range members{name,err:=member.Key.UTF8();if err!=nil{return e.fail(path,"default map key is not Unicode scalar text")};if err:=e.bytes([]byte(name),path);err!=nil{return err};if err:=e.value(schema.(*avro.MapSchema).Values(),member.Value,depth+1,path+"."+name);err!=nil{return err}}};return e.long(0,path)
    case avro.Record:record:=schema.(*avro.RecordSchema);defaults:=e.index.fields[record.FullName()];if e.matcher==nil{e.matcher=newAvroDefaultMatcher(e.index,schemajson.DefaultNodes,schemajson.DefaultBytes)};members:=node.Members();if err:=e.matcher.chargeWork(len(members));err!=nil{return err};byName:=make(map[string]schemajson.Node,len(members));for _,member:=range members{if err:=e.matcher.chargeUnits(member.Key.Length()+1);err!=nil{return err};name,keyErr:=member.Key.UTF8();if keyErr==nil{byName[name]=member.Value}};for _,field:=range record.Fields(){child,ok:=byName[field.Name()];if !ok{fallback,exists:=defaults[field.Name()];if !exists{return e.fail(path,"record default omits a required field")};child=fallback.node};if err:=e.value(field.Type(),child,depth+1,path+"."+field.Name());err!=nil{return err}};return nil
    case avro.Union:branches:=schema.(*avro.UnionSchema).Types();if e.matcher==nil{e.matcher=newAvroDefaultMatcher(e.index,schemajson.DefaultNodes,schemajson.DefaultBytes)};for index,branch:=range branches{matched,err:=e.matcher.match(branch,node,0);if err!=nil{return err};if matched{if err:=e.long(int64(index),path);err!=nil{return err};return e.value(branch,node,depth+1,path+"<default>")}};return e.fail(path,"union default matches no branch")
    };return e.fail(path,"unsupported Avro default schema type")}
