// Code generated by goplus from bundle.gp. DO NOT EDIT.
//goplus:v v0.28.0

package native

import (
	"bytes"
	"encoding/json"

	"goforge.dev/refine/language"
	_ "goforge.dev/refine/schemajson"
)

type bundleTarget struct {
	Kind     ProjectKind `json:"kind"`
	Resource string      `json:"resource"`
}
type bundleFile struct {
	Version                 int                     `json:"version"`
	Format                  Format                  `json:"format"`
	Root                    *ResourceSelector       `json:"root,omitempty"`
	Target                  *bundleTarget           `json:"target,omitempty"`
	Resources               []Resource              `json:"resources"`
	EditableSource          string                  `json:"editableSource"`
	LanguageEntry           string                  `json:"languageEntry,omitempty"`
	LanguageFiles           []language.SourceFile   `json:"languageFiles,omitempty"`
	NativeConstraintSources []Resource              `json:"nativeConstraintSources,omitempty"`
	Metadata                WireMetadata            `json:"metadata"`
	ReleasePolicy           *language.ReleasePolicy `json:"releasePolicy,omitempty"`
}

// Bundle returns one self-contained JSON distribution. Native resources remain
// byte-for-byte strings and retain their URI identities for offline resolution.
func (p *Project) Bundle() ([]byte, error) {
	if p == nil || p.program == nil || p.document == nil {
		return nil, &Error{Code: "native.project", Message: "a checked project is required"}
	}
	wire := bundleFile{Version: 1, Format: p.Format(), Resources: p.Resources(), EditableSource: p.source, LanguageEntry: p.LanguageEntry(), LanguageFiles: p.LanguageFiles(), NativeConstraintSources: p.NativeConstraintSources(), Metadata: p.Metadata(), ReleasePolicy: p.ReleasePolicy()}
	switch p.Kind() {
	case PayloadProject:
		if !p.HasPayloadRoot() {
			return nil, &Error{Code: "native.project", Format: p.Format(), Message: "payload project target is invalid"}
		}
		root := p.root
		wire.Root = &root
	case OpenAPIOperationsProject:
		if p.target.Kind != OpenAPIOperationsProject || p.root != (ResourceSelector{}) || p.EntryResource() == "" || p.openAPIOperations == nil {
			return nil, &Error{Code: "native.project", Format: p.Format(), Message: "OpenAPI operations project target is invalid or unchecked"}
		}
		wire.Version = 2
		wire.Target = &bundleTarget{Kind: OpenAPIOperationsProject, Resource: p.EntryResource()}
	default:
		return nil, &Error{Code: "native.project", Format: p.Format(), Message: "project target kind is invalid"}
	}
	data, err := json.MarshalIndent(wire, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(data, '\n'), nil
}

func ParseBundle(input []byte) (*Project, error) {
	_, checkedPolicy, err := ReleaseComparisonBundle(input)
	if err != nil {
		return nil, err
	}
	var wire bundleFile
	decoder := json.NewDecoder(bytes.NewReader(input))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&wire); err != nil {
		return nil, wrap("", "native.bundle", "", err)
	}
	if wire.Version == 1 {
		if wire.Root == nil || wire.Target != nil {
			return nil, &Error{Code: "native.bundle", Format: wire.Format, Message: "version 1 bundle requires root and forbids target"}
		}
		project, err := IngestProjectResources(wire.Format, wire.Resources, ProjectOptions{ResourceID: wire.Root.Resource, Root: *wire.Root})
		if err != nil {
			return nil, err
		}
		project, err = applyBundledSourceAndNativeConstraintSources(project, wire)
		if err != nil {
			return nil, err
		}
		project, err = project.WithMetadata(wire.Metadata)
		if err != nil {
			return nil, err
		}
		project.releasePolicy = copyNativeReleasePolicy(checkedPolicy)
		return project, nil
	}
	if wire.Version != 2 {
		return nil, &Error{Code: "native.bundle", Format: wire.Format, Message: "unsupported bundle version"}
	}
	if wire.Format != OpenAPI || wire.Root != nil || wire.Target == nil || wire.Target.Kind != OpenAPIOperationsProject || wire.Target.Resource == "" {
		return nil, &Error{Code: "native.bundle", Format: wire.Format, Message: "version 2 operations bundle requires an OpenAPI target resource and forbids root"}
	}
	bundled, err := compileBundledOperationSource(wire)
	if err != nil {
		return nil, err
	}
	project, err := ingestOpenAPIOperationResources(wire.Resources, OpenAPIOperationIngestOptions{EntryResource: wire.Target.Resource, Metadata: wire.Metadata}, bundled)
	if err != nil {
		return nil, err
	}
	project, err = applyBundledNativeConstraintSources(project, wire)
	if err != nil {
		return nil, err
	}
	project.releasePolicy = copyNativeReleasePolicy(checkedPolicy)
	return project, nil
}

func applyBundledNativeConstraintSources(project *Project, wire bundleFile) (*Project, error) {
	seen := map[string]bool{}
	for _, unit := range wire.NativeConstraintSources {
		if seen[unit.URI] {
			return nil, &Error{Code: "native.bundle", Format: wire.Format, Pointer: unit.URI, Message: "duplicate native constraint source resource"}
		}
		seen[unit.URI] = true
	}
	return project.withEditedNativeConstraintSources(wire.NativeConstraintSources)
}

func applyBundledSourceAndNativeConstraintSources(project *Project, wire bundleFile) (*Project, error) {
	seen := map[string]bool{}
	for _, unit := range wire.NativeConstraintSources {
		if seen[unit.URI] {
			return nil, &Error{Code: "native.bundle", Format: wire.Format, Pointer: unit.URI, Message: "duplicate native constraint source resource"}
		}
		seen[unit.URI] = true
	}
	if wire.LanguageEntry == "" {
		return project.WithEditedSourceAndNativeConstraintSources(wire.EditableSource, wire.NativeConstraintSources)
	}
	sources := make(map[string]string)
	for _, file := range wire.LanguageFiles {
		if _, duplicate := sources[file.ID]; duplicate {
			return nil, &Error{Code: "native.bundle", Format: wire.Format, Message: "duplicate language source ID"}
		}
		sources[file.ID] = file.Source
	}
	bundle, err := language.CompileSources(wire.LanguageEntry, sources)
	if err != nil {
		return nil, wrap(wire.Format, "native.refinement", "", err)
	}
	if bundle.Program().Source() != wire.EditableSource {
		return nil, &Error{Code: "native.bundle", Format: wire.Format, Message: "editableSource does not match the bundled language import graph"}
	}
	return project.withEditedProgramAndNativeConstraintSources(wire.EditableSource, bundle.Program(), bundle.Entry(), bundle.Files(), wire.NativeConstraintSources)
}

func compileBundledOperationSource(wire bundleFile) (*openAPIOperationSource, error) {
	if wire.LanguageEntry == "" {
		program, err := language.Compile(wire.EditableSource)
		if err != nil {
			return nil, wrap(OpenAPI, "native.refinement", "", err)
		}
		return &openAPIOperationSource{source: wire.EditableSource, program: program}, nil
	}
	sources := map[string]string{}
	for _, file := range wire.LanguageFiles {
		if _, duplicate := sources[file.ID]; duplicate {
			return nil, &Error{Code: "native.bundle", Format: wire.Format, Message: "duplicate language source ID"}
		}
		sources[file.ID] = file.Source
	}
	bundle, err := language.CompileSources(wire.LanguageEntry, sources)
	if err != nil {
		return nil, wrap(OpenAPI, "native.refinement", "", err)
	}
	if bundle.Program().Source() != wire.EditableSource {
		return nil, &Error{Code: "native.bundle", Format: wire.Format, Message: "editableSource does not match the bundled language import graph"}
	}
	return &openAPIOperationSource{source: wire.EditableSource, program: bundle.Program(), entry: bundle.Entry(), files: bundle.Files()}, nil
}
