package native

import (
    "fmt"
    "strconv"
    "strings"
    "testing"
)

func TestJSONProjectionResolvesNestedExternalRecursiveReferences(t *testing.T){
    rootURI:="https://example.test/root.json";nodeURI:="https://example.test/node.json";root:=`{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"head":{"$ref":"node.json#/$defs/Node"}},"required":["head"]}`;node:=`{"$schema":"https://json-schema.org/draft/2020-12/schema","$defs":{"Node":{"type":"object","properties":{"value":{"type":"integer"},"next":{"$ref":"#/$defs/Node"}},"required":["value"]}}}`
    project,err:=IngestProjectResources(JSONSchema,[]Resource{{URI:rootURI,Source:root},{URI:nodeURI,Source:node}},ProjectOptions{ResourceID:rootURI,Root:ResourceSelector{Resource:rootURI,TypeName:"Root"},Metadata:WireMetadata{PublicationNamespace:"example.external"}});if err!=nil{t.Fatal(err)};source:=project.EditableSource();if strings.Count(source,"type Node_")!=1||!strings.Contains(source,"next :: Maybe (Node_")||!strings.Contains(source,"head :: Node_"){t.Fatalf("external recursion was not projected once:\n%s",source)};if project.Metadata().PublicationNamespace!="example.external"{t.Fatal("metadata was lost")};if _,err:=project.PayloadType();err!=nil{t.Fatal(err)};if resources,err:=project.CanonicalJSONResources();err!=nil||len(resources)!=2{t.Fatalf("canonical runtime closure unavailable: %v",err)};if err:=project.ValidateJSON([]byte(`{"head":{"value":1,"next":{"value":2}}}`));err!=nil{t.Fatalf("valid recursive external value rejected: %v",err)};if err:=project.ValidateJSON([]byte(`{"head":{"value":"bad"}}`));problemCode(err)!="native.payload"{t.Fatalf("invalid recursive external value accepted: %v",err)}
}

func TestJSONProjectionResolvesCanonicalNestedIDAnchorAndPointer(t *testing.T){
    rootURI:="https://example.test/root.json";defsURI:="https://cdn.test/defs.json";root:=`{"$schema":"https://json-schema.org/draft/2020-12/schema","$ref":"https://schemas.test/tree#node"}`;defs:=`{"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://schemas.test/base","$anchor":"catalog","$defs":{"Node":{"$id":"tree","$anchor":"node","type":"object","properties":{"next":{"$ref":"#node"},"leaf":{"$ref":"#/$defs/Leaf"}},"required":["leaf"],"$defs":{"Leaf":{"type":"string"}}}}}`
    resources:=[]Resource{{URI:rootURI,Source:root},{URI:defsURI,Source:defs}};project,err:=IngestProjectResources(JSONSchema,resources,ProjectOptions{ResourceID:rootURI,Root:ResourceSelector{Resource:rootURI,TypeName:"Tree"}});if err!=nil{t.Fatal(err)};source:=project.EditableSource();if !strings.Contains(source,"next :: Maybe (")||!strings.Contains(source,"leaf :: Leaf_")||!strings.Contains(source,"type Leaf_")||!strings.Contains(source," = String")||!strings.Contains(source,"type Tree = "){t.Fatalf("logical ID/anchor projection incomplete:\n%s",source)};if _,err:=project.PayloadType();err!=nil{t.Fatal(err)};catalog,err:=newJSONProjectionCatalog(resources);if err!=nil{t.Fatal(err)};rootContext,err:=catalog.at(ResourceSelector{Resource:rootURI});if err!=nil{t.Fatal(err)};physicalAlias,err:=catalog.resolve(rootContext,defsURI+"#catalog");if err!=nil||physicalAlias.resource!=defsURI||physicalAlias.pointer!=""{t.Fatalf("physical resource alias did not resolve through canonical root base: %+v %v",physicalAlias,err)};aliases,err:=project.JSONSchemaResourceAliases();if err!=nil{t.Fatal(err)};if len(aliases)!=2||aliases[0].URI!="https://schemas.test/base"||aliases[1].URI!="https://schemas.test/tree"||!strings.Contains(aliases[0].Source,`"$id":"https://schemas.test/base"`)||!strings.Contains(aliases[1].Source,`"$id":"https://schemas.test/tree"`)||!strings.Contains(aliases[1].Source,`"$schema":"https://json-schema.org/draft/2020-12/schema"`){t.Fatalf("canonical alias inventory was incomplete or unstable: %+v",aliases)};aliases[0].Source="changed";again,err:=project.JSONSchemaResourceAliases();if err!=nil||again[0].Source=="changed"{t.Fatalf("alias inventory was not defensive: %v %+v",err,again)};if err:=project.ValidateJSON([]byte(`{"leaf":"ok"}`));err!=nil{t.Fatalf("valid logical-ID value rejected: %v",err)};if err:=project.ValidateJSON([]byte(`{"leaf":1}`));problemCode(err)!="native.payload"{t.Fatalf("invalid logical-ID value accepted: %v",err)}
    locations,err:=project.JSONSchemaKeywordLocations("type");if err!=nil{t.Fatal(err)};if len(locations)!=2||locations[0]!=defsURI+"#/$defs/Node/$defs/Leaf/type"||locations[1]!=defsURI+"#/$defs/Node/type"{t.Fatalf("schema-location integration lost stable physical identities: %v",locations)}
}

func TestJSONProjectionNamesExternalCollisionsDeterministically(t *testing.T){
    rootURI:="https://example.test/root.json";aURI:="https://example.test/a.json";bURI:="https://example.test/b.json";root:=`{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"a":{"$ref":"a.json"},"b":{"$ref":"b.json"}},"required":["a","b"]}`;a:=`{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"value":{"type":"string"}}}`;b:=`{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"value":{"type":"integer"}}}`;options:=ProjectOptions{ResourceID:rootURI,Root:ResourceSelector{Resource:rootURI,TypeName:"Pair"}}
    first,err:=IngestProjectResources(JSONSchema,[]Resource{{URI:rootURI,Source:root},{URI:aURI,Source:a},{URI:bURI,Source:b}},options);if err!=nil{t.Fatal(err)};second,err:=IngestProjectResources(JSONSchema,[]Resource{{URI:bURI,Source:b},{URI:rootURI,Source:root},{URI:aURI,Source:a}},options);if err!=nil{t.Fatal(err)};if first.EditableSource()!=second.EditableSource(){t.Fatalf("resource order changed generated names:\n%s\n---\n%s",first.EditableSource(),second.EditableSource())};if strings.Count(first.EditableSource(),"type External_")!=2{t.Fatalf("colliding external labels were not uniquely framed:\n%s",first.EditableSource())}
}

func TestJSONProjectionCatalogRejectsAmbiguousAndNonSchemaTargets(t *testing.T){
    duplicate:=[]Resource{{URI:"https://example.test/a.json",Source:`{"$id":"https://schemas.test/same","type":"string"}`},{URI:"https://example.test/b.json",Source:`{"$id":"https://schemas.test/same","type":"integer"}`}};if _,err:=newJSONProjectionCatalog(duplicate);err==nil||problemCode(err)!="native.projection"{t.Fatalf("duplicate logical ID accepted: %v",err)}
    lookalike:=[]Resource{{URI:"https://example.test/root.json",Source:`{"type":"object","examples":[{"$anchor":"fake","type":"string"}]}`}};catalog,err:=newJSONProjectionCatalog(lookalike);if err!=nil{t.Fatal(err)};root,err:=catalog.at(ResourceSelector{Resource:"https://example.test/root.json"});if err!=nil{t.Fatal(err)};if _,err:=catalog.resolve(root,"#fake");err==nil{t.Fatal("anchor lookalike in examples was indexed")};if _,err:=catalog.resolve(root,"missing.json");err==nil||problemCode(err)!="native.resource"{t.Fatalf("missing explicit resource accepted: %v",err)}
    dynamic:=[]Resource{{URI:"https://example.test/dynamic.json",Source:`{"$dynamicRef":"#node","$defs":{"Node":{"$dynamicAnchor":"node","type":"string"}}}`}};if _,err:=projectJSONResources(dynamic,ResourceSelector{Resource:"https://example.test/dynamic.json",TypeName:"Dynamic"});err==nil||problemCode(err)!="native.projection"{t.Fatalf("dynamic reference projected statically: %v",err)}
}

func TestJSONProjectionSelectedDefinitionRetainsSiblingLocalNameAndMetadata(t *testing.T){
    resource:="https://example.test/local.json";source:=`{"$schema":"https://json-schema.org/draft/2020-12/schema","$defs":{"Child":{"type":"object","properties":{"value":{"type":"string"}},"required":["value"]},"Root":{"type":"object","properties":{"child":{"$ref":"#/$defs/Child"}},"required":["child"]}}}`
    project,err:=IngestProjectResources(JSONSchema,[]Resource{{URI:resource,Source:source}},ProjectOptions{ResourceID:resource,Root:ResourceSelector{Resource:resource,Pointer:"/$defs/Root",TypeName:"Selected"},Metadata:WireMetadata{ExtraFields:map[string]ExtraFieldMode{"Child":RejectExtraFields}}});if err!=nil{t.Fatal(err)};editable:=project.EditableSource();if !strings.Contains(editable,"type Child = {value :: String}")||!strings.Contains(editable,"type Selected = {child :: Child}"){t.Fatalf("selected nested root renamed its sibling local definition:\n%s",editable)};metadata:=project.Metadata();if metadata.ExtraFields["Child"]!=RejectExtraFields||len(metadata.ExtraFields)!=1{t.Fatalf("local-name metadata identity changed: %+v",metadata.ExtraFields)}
}

func TestJSONProjectionCatalogPreflightsRetainedLocationAmplification(t *testing.T){
    longKey:=strings.Repeat("x",1<<20);children:=make([]string,20);for i:=range children{children[i]=fmt.Sprintf("%s:true",strconv.Quote(fmt.Sprintf("N%d",i)))};source:=`{"properties":{`+strconv.Quote(longKey)+`:{"$defs":{`+strings.Join(children,",")+`}}}}`;_,err:=newJSONProjectionCatalog([]Resource{{URI:"https://example.test/amplified.json",Source:source}});if problemCode(err)!="native.limit"{t.Fatalf("retained path amplification was not rejected before storage: %v",err)}
}
