package native

import (
    "strings"
    "testing"

    "goforge.dev/refine/validation"
)

const dynamicItemsSchema=`{"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://schemas.test/items","type":"object","properties":{"items":{"type":"array","items":{"$dynamicRef":"#item"}}},"required":["items"],"additionalProperties":false,"$defs":{"Item":{"$dynamicAnchor":"item","type":"string","minLength":2}}}`

func dynamicItemsProject(t *testing.T)*Project{t.Helper();resource:="https://cdn.test/items.json";project,err:=IngestProjectResources(JSONSchema,[]Resource{{URI:resource,Source:dynamicItemsSchema}},ProjectOptions{ResourceID:resource,Root:ResourceSelector{Resource:resource,TypeName:"DynamicItems"}});if err!=nil{t.Fatal(err)};want:="type DynamicItems = {items :: [JSON]}";if !strings.Contains(project.EditableSource(),want){t.Fatalf("dynamic item was projected statically:\n%s",project.EditableSource())};edited:=strings.Replace(project.EditableSource(),want,want+` where length it.items < 3 @code "items.short"`,1);project,err=project.WithEditedSource(edited);if err!=nil{t.Fatal(err)};return project}

func requireDynamicOutcome(t *testing.T,project *Project,input,want string){t.Helper();_,report,err:=project.DecodeAndValidateJSON([]byte(input),validation.Limits{});if want=="native"{if problemCode(err)!="native.payload"{t.Fatalf("native-invalid dynamic value was not rejected first: %v",err)};return};if err!=nil{t.Fatal(err)};if validation.StateName(report.State())!=want{t.Fatalf("dynamic value state=%s want=%s: %+v",validation.StateName(report.State()),want,report)}}

func TestJSONDynamicReferenceCarrierPreservesNativeFirstValidationAndExport(t *testing.T){project:=dynamicItemsProject(t);valid:=`{"items":["aa","bb"]}`;nativeInvalid:=`{"items":["x"]}`;refineInvalid:=`{"items":["aa","bb","cc"]}`;requireDynamicOutcome(t,project,valid,"valid");requireDynamicOutcome(t,project,nativeInvalid,"native");requireDynamicOutcome(t,project,refineInvalid,"invalid")
    for _,mode:=range []ExportMode{Ordinary,Refined}{exported,err:=project.Export(LowerOptions{Mode:mode,AllowDocumentedLoss:true});if err!=nil{t.Fatal(err)};resources:=exported.Resources();if len(resources)!=1||!strings.Contains(resources[0].Source,`"$dynamicRef": "#item"`){t.Fatalf("%s export lost dynamic native authority: %+v",mode,resources)};again,err:=IngestProjectResources(JSONSchema,resources,ProjectOptions{ResourceID:exported.Root().Resource,Root:exported.Root(),Metadata:exported.Metadata()});if err!=nil{t.Fatalf("%s dynamic export did not reingest: %v",mode,err)};requireDynamicOutcome(t,again,valid,"valid");requireDynamicOutcome(t,again,nativeInvalid,"native");if mode==Refined{requireDynamicOutcome(t,again,refineInvalid,"invalid")}}
}

func TestJSONDynamicReferenceCanonicalScopesRemainNativeAuthority(t *testing.T){physical:="https://cdn.test/dynamic.json";source:=`{"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://schemas.test/root","$dynamicAnchor":"meta","type":"object","properties":{"foo":{"const":"pass"}},"$ref":"extended","$defs":{"Extended":{"$id":"extended","$dynamicAnchor":"meta","type":"object","properties":{"bar":{"$ref":"bar"}}},"Bar":{"$id":"bar","type":"object","properties":{"baz":{"$dynamicRef":"extended#meta"}}}}}`;project,err:=IngestProjectResources(JSONSchema,[]Resource{{URI:physical,Source:source}},ProjectOptions{ResourceID:physical,Root:ResourceSelector{Resource:physical,TypeName:"Scoped"}});if err!=nil{t.Fatal(err)};if !strings.Contains(project.EditableSource(),"type Scoped = JSON"){t.Fatalf("dynamic scope acquired a fictitious static type:\n%s",project.EditableSource())};aliases,err:=project.JSONSchemaResourceAliases();if err!=nil||len(aliases)!=3{t.Fatalf("dynamic canonical resources were not exposed offline: %v %+v",err,aliases)};valid:=`{"foo":"pass","bar":{"baz":{"foo":"pass"}}}`;invalid:=`{"foo":"pass","bar":{"baz":{"foo":"fail"}}}`;if err:=project.ValidateJSON([]byte(valid));err!=nil{t.Fatalf("valid dynamic scope rejected: %v",err)};if err:=project.ValidateJSON([]byte(invalid));problemCode(err)!="native.payload"{t.Fatalf("dynamic scope override was not enforced: %v",err)}}
