// Code generated by goplus from lower_cardinality.gp. DO NOT EDIT.
//goplus:v v0.28.0

package native

import (
	"encoding/json"
	"goforge.dev/refine/language"
	"strings"
)

// cardinalityRule recognizes the canonical collection-size comparison only.
// Native string length is intentionally excluded; it is not UTF-16 length.
func (l *lowerer) cardinalityRule(schema any, rule language.Where) bool {
	object, ok := schema.(map[string]any)
	if !ok {
		return false
	}
	switch __gp_m0 := any(rule.Predicate.Form).(type) {
	case language.Binary:
		operator := __gp_m0.Operator
		left := __gp_m0.Left
		right := __gp_m0.Right

		if operator != ">=" && operator != "<=" {
			return false
		}
		raw, ok := loweringNumberLiteral(right)
		if !ok || strings.ContainsAny(raw, "-.eE/") {
			return false
		}
		builtin := ""
		switch __gp_m1 := any(left.Form).(type) {
		case language.Apply:
			fn := __gp_m1.Function
			subject := __gp_m1.Argument
			if !isIt(subject) {
				return false
			}
			switch __gp_m2 := any(fn.Form).(type) {
			case language.Variable:
				name := __gp_m2.Name
				builtin = name
			default:
				return false
			}
		default:
			return false
		}
		if lowererHasFunction(l, builtin) {
			return false
		}
		keyword := ""
		if builtin == "length" && object["type"] == "array" {
			if operator == ">=" {
				keyword = "minItems"
			} else {
				keyword = "maxItems"
			}
		}
		if builtin == "size" && object["type"] == "object" {
			if operator == ">=" {
				keyword = "minProperties"
			} else {
				keyword = "maxProperties"
			}
		}
		if keyword == "" {
			return false
		}
		putConstraint(object, keyword, json.Number(raw))
		return true
	default:
		return false
	}
}
