// Code generated by goplus from lower.gp. DO NOT EDIT.
//goplus:v v0.28.0

package native

import (
	"encoding/json"
	"fmt"
	"math/big"
	"strings"

	"goforge.dev/refine/explain"
	"goforge.dev/refine/language"
	"goforge.dev/refine/value"
)

type ExportMode string

const (
	Ordinary ExportMode = "ordinary"
	Refined  ExportMode = "refined"
)

type LowerOptions struct {
	Mode           ExportMode
	OpenAPIVersion string
	// AllowDocumentedLoss is required before an ordinary export may replace a
	// checked rule with embedded and companion English. The returned Losses
	// enumerate every such rule. Wire-unrepresentable base types always error.
	AllowDocumentedLoss bool
	// MaxGenericSpecializations bounds distinct closed generic applications.
	// Zero selects DefaultLowerGenericSpecializations; values above the hard
	// package maximum are rejected before lowering.
	MaxGenericSpecializations int
}
type Loss struct {
	Owner       string
	Location    string
	Predicate   string
	Explanation string
}
type Export struct {
	format    Format
	version   string
	data      []byte
	companion string
	losses    []Loss
}

func (e *Export) Format() Format {
	if e == nil {
		return ""
	}
	return e.format
}
func (e *Export) Version() string {
	if e == nil {
		return ""
	}
	return e.version
}
func (e *Export) Bytes() []byte {
	if e == nil {
		return nil
	}
	return append([]byte(nil), e.data...)
}
func (e *Export) String() string {
	if e == nil {
		return ""
	}
	return string(e.data)
}
func (e *Export) CompanionMarkdown() string {
	if e == nil {
		return ""
	}
	return e.companion
}
func (e *Export) Losses() []Loss {
	if e == nil {
		return nil
	}
	return append([]Loss(nil), e.losses...)
}

type lowerer struct {
	format              Format
	mode                ExportMode
	allowLoss           bool
	module              *language.Module
	rootSource          string
	declarations        map[string]language.TypeDecl
	definitions         map[string]any
	building            map[string]bool
	avroDefined         map[string]bool
	losses              []Loss
	explanation         explain.Document
	companion           string
	explanationUsed     map[int]bool
	encodings           map[string]ScalarEncoding
	extraFields         map[string]ExtraFieldMode
	discriminators      map[string]Discriminator
	owner               string
	specializationNames map[string]string
	nativeNames         map[string]string
	specializationCount int
	maxSpecializations  int
}

// LowerPayload lowers one immutable checked payload type. It validates the
// generated native document through Parse before returning it.
func LowerPayload(format Format, payload *language.PayloadType, options LowerOptions) (*Export, error) {
	return lowerPayload(format, payload, WireMetadata{}, options)
}

// LowerPayloadWithMetadata applies checked, explicit wire encodings. Metadata
// never weakens the source type; codecs must reject values outside the chosen
// lossless representation.
func LowerPayloadWithMetadata(format Format, payload *language.PayloadType, metadata WireMetadata, options LowerOptions) (*Export, error) {
	return lowerPayload(format, payload, metadata, options)
}

func lowerPayload(format Format, payload *language.PayloadType, metadata WireMetadata, options LowerOptions) (*Export, error) {
	if payload == nil {
		return nil, &Error{Code: "native.lower", Format: format, Message: "a checked payload type is required"}
	}
	mode := options.Mode
	if mode == "" {
		mode = Ordinary
	}
	if mode != Ordinary && mode != Refined {
		return nil, &Error{Code: "native.lower", Format: format, Message: "mode must be ordinary or refined"}
	}
	maxSpecializations := options.MaxGenericSpecializations
	if maxSpecializations == 0 {
		maxSpecializations = DefaultLowerGenericSpecializations
	}
	if maxSpecializations < 1 || maxSpecializations > MaximumLowerGenericSpecializations {
		return nil, &Error{Code: "native.lower", Format: format, Message: fmt.Sprintf("MaxGenericSpecializations must be between 1 and %d, or zero for the default", MaximumLowerGenericSpecializations)}
	}
	checked := payload.CheckedSyntax()
	if checked.Type == nil || checked.Module.Syntax == nil {
		return nil, &Error{Code: "native.lower", Format: format, Message: "invalid checked payload type"}
	}
	program, err := language.Compile(checked.Module.Syntax.Source)
	if err != nil {
		return nil, wrap(format, "native.lower", "", err)
	}
	if err := validateMetadata(program, metadata); err != nil {
		return nil, wrap(format, "native.metadata", "", err)
	}
	explained, err := explain.GeneratePayload(payload)
	if err != nil {
		return nil, wrap(format, "native.lower", "", err)
	}
	copiedMetadata := copyMetadata(metadata)
	if format == Avro && (len(copiedMetadata.ExtraFields) > 0 || len(copiedMetadata.Discriminators) > 0) {
		return nil, &Error{Code: "native.unrepresentable", Format: Avro, Message: "JSON extra-field and discriminator policies cannot be represented by Avro lowering"}
	}
	l := &lowerer{format: format, mode: mode, allowLoss: options.AllowDocumentedLoss, module: checked.Module.Syntax, rootSource: payload.Source(), declarations: make(map[string]language.TypeDecl), definitions: make(map[string]any), building: make(map[string]bool), avroDefined: make(map[string]bool), explanation: explained, companion: explained.Markdown(), explanationUsed: make(map[int]bool), encodings: copiedMetadata.Scalars, extraFields: copiedMetadata.ExtraFields, discriminators: copiedMetadata.Discriminators, owner: "$payload", specializationNames: make(map[string]string), nativeNames: make(map[string]string), maxSpecializations: maxSpecializations}
	l.nativeNames["Anonymous"] = "reserved anonymous Avro record"
	for _, decl := range l.module.Types {
		l.declarations[decl.Name] = decl
		l.nativeNames[decl.Name] = "declaration " + decl.Name
	}
	for name, encoding := range l.encodings {
		if encoding.Kind == RationalRecord {
			l.nativeNames[name+"Wire"] = "scalar wire " + name
		}
	}
	schema, err := l.typ(checked.Type, false)
	if err != nil {
		return nil, err
	}
	l.finishCompanion()
	if mode == Ordinary && len(l.losses) > 0 && !options.AllowDocumentedLoss {
		return nil, &Error{Code: "native.unrepresentable", Format: format, Message: fmt.Sprintf("%d refinement rule(s) have no exact native representation; set AllowDocumentedLoss to embed explanations and receive the loss list", len(l.losses))}
	}
	if len(l.losses) > 0 {
		l.addDocumentation(schema)
	}
	var root any
	version := ""
	switch format {
	case JSONSchema:
		object, ok := schema.(map[string]any)
		if !ok {
			object = map[string]any{"allOf": []any{schema}}
		}
		object["$schema"] = "https://json-schema.org/draft/2020-12/schema"
		if len(l.definitions) > 0 {
			object["$defs"] = l.definitions
		}
		root = object
		version = "2020-12"
	case OpenAPI:
		version = options.OpenAPIVersion
		if version == "" {
			version = "3.2.0"
		}
		if version != "3.1.0" && version != "3.1.1" && version != "3.1.2" && version != "3.2.0" {
			return nil, &Error{Code: "native.unrepresentable", Format: OpenAPI, Message: "lowering currently requires OpenAPI 3.1.x or 3.2.0; 3.0 ingestion remains supported"}
		}
		rootName := "RefineRoot"
		for {
			if _, collision := l.definitions[rootName]; !collision {
				break
			}
			rootName += "_"
		}
		components := map[string]any{rootName: schema}
		for name, definition := range l.definitions {
			components[name] = definition
		}
		root = map[string]any{"openapi": version, "info": map[string]any{"title": "Refine generated contract", "version": "SNAPSHOT"}, "paths": map[string]any{}, "components": map[string]any{"schemas": components}}
	case Avro:
		root = schema
		version = "1.12.0"
	default:
		return nil, &Error{Code: "native.format", Format: format, Message: "supported lowering formats are json-schema, avro, and openapi"}
	}
	if mode == Refined {
		object, ok := root.(map[string]any)
		if !ok {
			if format != Avro {
				return nil, &Error{Code: "native.unrepresentable", Format: format, Message: "the native root cannot carry a Refine annotation"}
			}
			object = map[string]any{"type": root}
			root = object
		}
		object["x-refine"] = map[string]any{"source": l.module.Source, "root": l.rootSource}
	}
	data, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return nil, wrap(format, "native.lower", "", err)
	}
	data = append(data, '\n')
	if _, err := Parse(format, data, Options{}); err != nil {
		return nil, &Error{Code: "native.lower-invalid", Format: format, Message: "generated document failed native validation: " + err.Error(), Cause: err}
	}
	return &Export{format: format, version: version, data: data, companion: l.companion, losses: append([]Loss(nil), l.losses...)}, nil
}

func (l *lowerer) addDocumentation(schema any) {
	object, ok := schema.(map[string]any)
	if !ok {
		return
	}
	summary := "Additional Refine rules are not machine-enforced by this ordinary schema. The complete executable contract in English follows.\n\n" + l.companion
	if existing, ok := object["description"].(string); ok && existing != "" {
		summary = existing + "\n\n" + summary
	}
	if l.format == Avro {
		object["doc"] = summary
	} else {
		object["description"] = summary
	}
}

func (l *lowerer) finishCompanion() {
	if len(l.losses) == 0 {
		return
	}
	var b strings.Builder
	b.WriteString(l.companion)
	if b.Len() > 0 && !strings.HasSuffix(l.companion, "\n") {
		b.WriteByte('\n')
	}
	b.WriteString("\n## Ordinary-schema lowering losses\n\n")
	for _, loss := range l.losses {
		b.WriteString("- At `" + loss.Location + "`, the native schema does not machine-enforce `" + loss.Predicate + "`. " + loss.Explanation + "\n")
	}
	l.companion = b.String()
}

func (l *lowerer) lose(rule language.Where, location string) {
	predicate := language.FormatExpression(rule.Predicate)
	explanation := "Evaluate the Refine predicate " + predicate + "."
	owner := ""
	for index, r := range l.explanation.Rules() {
		if !l.explanationUsed[index] && r.Owner == l.owner && r.Offset == rule.At.Start.Offset && r.Predicate == predicate {
			l.explanationUsed[index] = true
			owner = r.Owner
			location = r.Location
			explanation = "Apply rule " + r.Owner + " at " + r.Location + ": " + predicate
			if r.Message != "" {
				explanation += ". On failure, evaluate the author-defined message " + r.Message
			}
			break
		}
	}
	l.losses = append(l.losses, Loss{Owner: owner, Location: location, Predicate: predicate, Explanation: explanation})
}

func (l *lowerer) typ(t *language.Type, field bool) (any, error) {
	switch __gp_m0 := any(t.Form).(type) {
	case language.NamedType:
		name := __gp_m0.Name
		return l.named(name)
	case language.ListType:
		element := __gp_m0.Element
		item, err := l.typ(element, false)
		if err != nil {
			return nil, err
		}
		if l.format == Avro {
			return map[string]any{"type": "array", "items": item}, nil
		}
		return map[string]any{"type": "array", "items": item}, nil
	case language.RecordType:
		fields := __gp_m0.Fields

		if l.format == Avro {
			return l.avroRecord("Anonymous", fields)
		}
		properties := make(map[string]any)
		required := []string{}
		for _, f := range fields {
			optional, inner := unwrap(f.Type, "Maybe")
			value, err := l.typ(inner, true)
			if err != nil {
				return nil, atLower(err, "field "+f.Name)
			}
			properties[f.Name] = value
			if !optional {
				required = append(required, f.Name)
			}
		}
		additional := true
		if mode, ok := l.extraFields[l.owner]; ok {
			additional = mode == PreserveExtraFields
		}
		result := map[string]any{"type": "object", "properties": properties, "additionalProperties": additional}
		if len(required) > 0 {
			result["required"] = required
		}
		return result, nil
	case language.AppliedType:

		if ok, inner := unwrap(t, "Nullable"); ok {
			value, err := l.typ(inner, field)
			if err != nil {
				return nil, err
			}
			if l.format == Avro {
				return []any{"null", value}, nil
			}
			return map[string]any{"anyOf": []any{map[string]any{"type": "null"}, value}}, nil
		}
		if ok, _ := unwrap(t, "Maybe"); ok {
			return nil, &Error{Code: "native.unrepresentable", Format: l.format, Message: "Maybe represents field absence and is supported only directly on record fields"}
		}
		return l.generic(t)
	case language.RefinedType:
		base := __gp_m0.Base
		rules := __gp_m0.Rules

		result, err := l.typ(base, field)
		if err != nil {
			return nil, err
		}
		for _, rule := range rules {
			represented := false
			if l.format != Avro {
				represented = l.numericRule(result, rule)
			}
			if !represented {
				if l.mode == Refined || l.allowLoss {
					l.lose(rule, language.FormatType(base))
				} else {
					l.lose(rule, language.FormatType(base))
				}
			}
		}
		return result, nil
	case language.ArrowType:
		return nil, &Error{Code: "native.unrepresentable", Format: l.format, Message: "function types are not wire payloads"}
	}
	panic("unreachable type")
}

func unwrap(t *language.Type, name string) (bool, *language.Type) {
	switch __gp_m1 := any(t.Form).(type) {
	case language.AppliedType:
		constructor := __gp_m1.Constructor
		arg := __gp_m1.Argument
		switch __gp_m2 := any(constructor.Form).(type) {
		case language.NamedType:
			n := __gp_m2.Name
			if n == name {
				return true, arg
			}
		default:
		}
	default:
	}
	return false, t
}

func (l *lowerer) named(name string) (any, error) {
	switch name {
	case "String":
		return map[string]any{"type": "string"}, nil
	case "Bool":
		return map[string]any{"type": "boolean"}, nil
	case "Int":
		if l.format == Avro {
			return nil, l.unrepresentable(name, "arbitrary-precision integers need an explicit lossless Avro wire encoding")
		}
		return map[string]any{"type": "integer"}, nil
	case "Real":
		return nil, l.unrepresentable(name, "exact rationals such as 1/3 need an explicit lossless wire encoding")
	case "Timestamp":
		return nil, l.unrepresentable(name, "Timestamp preserves exact RFC 3339 value semantics and needs an explicit wire encoding policy")
	case "Int32":
		if l.format == Avro {
			return "int", nil
		}
		return map[string]any{"type": "integer", "minimum": json.Number("-2147483648"), "maximum": json.Number("2147483647")}, nil
	case "Int64":
		if l.format == Avro {
			return "long", nil
		}
		return map[string]any{"type": "integer", "minimum": json.Number("-9223372036854775808"), "maximum": json.Number("9223372036854775807")}, nil
	}
	if strings.HasPrefix(name, "Int") || strings.HasPrefix(name, "UInt") {
		return l.fixedInteger(name)
	}
	decl, ok := l.declarations[name]
	if !ok {
		return nil, l.unrepresentable(name, "unknown native payload primitive")
	}
	if len(decl.Parameters) > 0 {
		return nil, l.unrepresentable(name, "generic declarations require concrete substitution")
	}
	if decl.Body == nil {
		wire, ok := l.discriminators[name]
		if !ok {
			return nil, l.unrepresentable(name, "tagged alternatives require explicit wire discriminator metadata")
		}
		if l.format == Avro {
			return nil, l.unrepresentable(name, "tagged discriminator objects cannot be represented as Avro unions")
		}
		return l.tagged(name, decl, wire)
	}
	if encoding, ok := l.encodings[name]; ok {
		return l.scalarEncoding(name, encoding)
	}
	if l.format == Avro {
		if !genericRecordBody(decl.Body) {
			return l.avroNamed(name, decl.Body)
		}
		if l.avroDefined[name] {
			return name, nil
		}
		l.avroDefined[name] = true
		result, err := l.avroNamed(name, decl.Body)
		if err != nil {
			delete(l.avroDefined, name)
			return nil, err
		}
		return result, nil
	}
	refPrefix := "#/$defs/"
	if l.format == OpenAPI {
		refPrefix = "#/components/schemas/"
	}
	if _, exists := l.definitions[name]; !exists {
		if l.building[name] {
			return map[string]any{"$ref": refPrefix + name}, nil
		}
		l.building[name] = true
		l.definitions[name] = map[string]any{}
		oldOwner := l.owner
		l.owner = name
		definition, err := l.typ(decl.Body, false)
		l.owner = oldOwner
		delete(l.building, name)
		if err != nil {
			return nil, err
		}
		l.definitions[name] = definition
	}
	return map[string]any{"$ref": refPrefix + name}, nil
}

func (l *lowerer) tagged(name string, decl language.TypeDecl, wire Discriminator) (any, error) {
	refPrefix := "#/$defs/"
	if l.format == OpenAPI {
		refPrefix = "#/components/schemas/"
	}
	if _, exists := l.definitions[name]; !exists {
		if l.building[name] {
			return map[string]any{"$ref": refPrefix + name}, nil
		}
		l.building[name] = true
		l.definitions[name] = map[string]any{}
		oldOwner := l.owner
		l.owner = name
		variants := []any{}
		for _, variant := range decl.Variants {
			properties := map[string]any{wire.Field: map[string]any{"const": wire.Values[variant.Name]}}
			required := []string{wire.Field}
			for i, arg := range variant.Arguments {
				member := wire.Arguments[variant.Name][i]
				schema, err := l.typ(arg, true)
				if err != nil {
					l.owner = oldOwner
					delete(l.building, name)
					return nil, atLower(err, name+"."+variant.Name+"."+member)
				}
				properties[member] = schema
				required = append(required, member)
			}
			variants = append(variants, map[string]any{"type": "object", "properties": properties, "additionalProperties": false, "required": required})
		}
		l.owner = oldOwner
		definition := map[string]any{"oneOf": variants}
		if l.format == OpenAPI {
			definition["discriminator"] = map[string]any{"propertyName": wire.Field}
		}
		l.definitions[name] = definition
		delete(l.building, name)
	}
	return map[string]any{"$ref": refPrefix + name}, nil
}

func (l *lowerer) scalarEncoding(name string, encoding ScalarEncoding) (any, error) {
	switch encoding.Kind {
	case JSONNumber:
		if l.format == Avro {
			return nil, l.unrepresentable(name, "Avro numbers require int/long or an explicit string/bytes representation")
		}
		return map[string]any{"type": "integer"}, nil
	case DecimalString:
		description := "A canonical base-10 integer string: zero is 0; nonzero values have no leading zero; negative zero is forbidden; no rounding occurs."
		if l.format == Avro {
			return map[string]any{"type": "string", "doc": description, "refineEncoding": "decimal-integer-string"}, nil
		}
		return map[string]any{"type": "string", "pattern": "^(?:0|-?[1-9][0-9]*)$", "description": description}, nil
	case TimestampString:
		description := "An RFC 3339 timestamp string; the exact source spelling and offset are preserved."
		if l.format == Avro {
			return map[string]any{"type": "string", "doc": description, "refineEncoding": "rfc3339-preserve"}, nil
		}
		return map[string]any{"type": "string", "format": "date-time", "description": description}, nil
	case RationalRecord:
		if l.format == Avro {
			wireName := name + "Wire"
			if l.avroDefined[wireName] {
				return wireName, nil
			}
			l.avroDefined[wireName] = true
			return map[string]any{"type": "record", "name": wireName, "doc": "An exact reduced rational. numerator and positive denominator are minimal signed two's-complement big-endian byte sequences; zero is one 0x00 byte.", "fields": []any{map[string]any{"name": "numerator", "type": "bytes", "refineEncoding": "signed-twos-complement-big-endian"}, map[string]any{"name": "denominator", "type": "bytes", "refineEncoding": "positive-signed-twos-complement-big-endian"}}}, nil
		}
		return map[string]any{"type": "object", "description": "An exact reduced rational with a positive denominator.", "properties": map[string]any{"numerator": map[string]any{"type": "integer"}, "denominator": map[string]any{"type": "integer", "exclusiveMinimum": 0}}, "required": []string{"numerator", "denominator"}, "additionalProperties": false}, nil
	case AvroBytesDecimal:
		if l.format != Avro {
			return nil, l.unrepresentable(name, "avro-bytes-decimal applies only to Avro")
		}
		return map[string]any{"type": "bytes", "logicalType": "decimal", "precision": encoding.Precision, "scale": encoding.Scale}, nil
	}
	return nil, l.unrepresentable(name, "unknown scalar encoding")
}

func (l *lowerer) avroNamed(name string, t *language.Type) (any, error) {
	oldOwner := l.owner
	l.owner = name
	defer func() { l.owner = oldOwner }()
	switch __gp_m3 := any(t.Form).(type) {
	case language.RecordType:
		fields := __gp_m3.Fields
		return l.avroRecord(name, fields)
	case language.RefinedType:
		base := __gp_m3.Base
		rules := __gp_m3.Rules
		result, err := l.avroNamed(name, base)
		if err != nil {
			return nil, err
		}
		for _, rule := range rules {
			l.lose(rule, language.FormatType(base))
		}
		return result, nil
	default:
		return l.typ(t, false)
	}
}

func (l *lowerer) avroRecord(name string, fields []language.Field) (any, error) {
	result := map[string]any{"type": "record", "name": name}
	nativeFields := []any{}
	for _, f := range fields {
		if ok, _ := unwrap(f.Type, "Maybe"); ok {
			return nil, l.unrepresentable(f.Name, "Avro records encode every field; Maybe absence is not an Avro default")
		}
		value, err := l.typ(f.Type, true)
		if err != nil {
			return nil, atLower(err, "field "+f.Name)
		}
		nativeFields = append(nativeFields, map[string]any{"name": f.Name, "type": value})
	}
	result["fields"] = nativeFields
	return result, nil
}

func (l *lowerer) fixedInteger(name string) (any, error) {
	unsigned := strings.HasPrefix(name, "UInt")
	digits := strings.TrimPrefix(name, "Int")
	if unsigned {
		digits = strings.TrimPrefix(name, "UInt")
	}
	bits, ok := new(big.Int).SetString(digits, 10)
	if !ok || !bits.IsInt64() || bits.Int64() < 1 {
		return nil, l.unrepresentable(name, "invalid fixed integer width")
	}
	if bits.Int64() > 65536 {
		return nil, l.unrepresentable(name, "fixed integer width exceeds the native schema generation limit of 65536 bits")
	}
	if l.format == Avro {
		return nil, l.unrepresentable(name, "Avro int/long do not retain this fixed-width integer domain exactly")
	}
	var min, max big.Int
	if unsigned {
		min.SetInt64(0)
		max.Exp(big.NewInt(2), bits, nil)
		max.Sub(&max, big.NewInt(1))
	} else {
		power := new(big.Int).Sub(bits, big.NewInt(1))
		max.Exp(big.NewInt(2), power, nil)
		min.Neg(&max)
		max.Sub(&max, big.NewInt(1))
	}
	return map[string]any{"type": "integer", "minimum": json.Number(min.String()), "maximum": json.Number(max.String())}, nil
}

func (l *lowerer) unrepresentable(name, message string) *Error {
	return &Error{Code: "native.unrepresentable", Format: l.format, Pointer: name, Message: message}
}
func atLower(err error, where string) error {
	if problem, ok := err.(*Error); ok {
		copy := *problem
		if copy.Pointer == "" {
			copy.Pointer = where
		} else {
			copy.Pointer = where + " / " + copy.Pointer
		}
		return &copy
	}
	return err
}

func (l *lowerer) numericRule(schema any, rule language.Where) bool {
	object, ok := schema.(map[string]any)
	if !ok {
		return false
	}
	op, raw, ok := comparison(rule.Predicate)
	key := ""
	if ok {
		switch op {
		case ">=":
			key = "minimum"
		case ">":
			key = "exclusiveMinimum"
		case "<=":
			key = "maximum"
		case "<":
			key = "exclusiveMaximum"
		}
	}
	if key == "" {
		raw, ok = multiple(rule.Predicate)
		if ok {
			key = "multipleOf"
		}
	}
	if key == "" || !ok {
		return false
	}
	putConstraint(object, key, json.Number(raw))
	return true
}

func putConstraint(object map[string]any, key string, value any) {
	if _, exists := object[key]; !exists {
		object[key] = value
		return
	}
	clause := map[string]any{key: value}
	if prior, ok := object["allOf"].([]any); ok {
		object["allOf"] = append(prior, clause)
	} else {
		object["allOf"] = []any{clause}
	}
}

func comparison(expr *language.Expr) (string, string, bool) {
	switch __gp_m4 := any(expr.Form).(type) {
	case language.Binary:
		op := __gp_m4.Operator
		left := __gp_m4.Left
		right := __gp_m4.Right

		if isIt(left) {
			if raw, ok := loweringNumberLiteral(right); ok {
				return op, raw, true
			}
		}
		if isIt(right) {
			if raw, ok := loweringNumberLiteral(left); ok {
				reverse := map[string]string{"<": ">", ">": "<", "<=": ">=", ">=": "<="}
				if flipped, exists := reverse[op]; exists {
					return flipped, raw, true
				}
			}
		}
	default:
	}
	return "", "", false
}
func isIt(expr *language.Expr) bool {
	switch __gp_m5 := any(expr.Form).(type) {
	case language.Variable:
		name := __gp_m5.Name
		return name == "it"
	default:
		return false
	}
}
func numberLiteral(expr *language.Expr) (string, bool) {
	switch __gp_m6 := any(expr.Form).(type) {
	case language.NumberLiteral:
		raw := __gp_m6.Text
		return raw, true
	case language.Unary:
		op := __gp_m6.Operator
		operand := __gp_m6.Operand
		if op == "-" {
			if raw, ok := numberLiteral(operand); ok {
				return "-" + raw, true
			}
		}
	default:
	}
	return "", false
}

func multiple(expr *language.Expr) (string, bool) {
	switch __gp_m7 := any(expr.Form).(type) {
	case language.Apply:
		fn := __gp_m7.Function
		arg := __gp_m7.Argument

		switch __gp_m8 := any(fn.Form).(type) {
		case language.Variable:
			name := __gp_m8.Name
			if name != "isInteger" {
				return "", false
			}
		default:
			return "", false
		}
		switch __gp_m9 := any(arg.Form).(type) {
		case language.Binary:
			op := __gp_m9.Operator
			numerator := __gp_m9.Left
			divisor := __gp_m9.Right
			if op != "/" {
				return "", false
			}
			if !isIt(numerator) {
				switch __gp_m10 := any(numerator.Form).(type) {
				case language.Binary:
					castOp := __gp_m10.Operator
					castValue := __gp_m10.Left
					one := __gp_m10.Right
					if castOp != "/" || !isIt(castValue) {
						return "", false
					}
					oneRaw, ok := numberLiteral(one)
					if !ok || oneRaw != "1" {
						return "", false
					}
				default:
					return "", false
				}
			}
			raw, ok := jsonNumberExpression(divisor)
			if !ok {
				return "", false
			}
			number, err := value.ParseNumber(raw)
			if err != nil || number.Sign() <= 0 {
				return "", false
			}
			return raw, true
		default:
			return "", false
		}
	default:
	}
	return "", false
}

func jsonNumberExpression(expr *language.Expr) (string, bool) {
	if raw, ok := loweringNumberLiteral(expr); ok {
		return raw, true
	}
	switch __gp_m11 := any(expr.Form).(type) {
	case language.Binary:
		op := __gp_m11.Operator
		left := __gp_m11.Left
		right := __gp_m11.Right
		if op == "/" {
			a, okA := loweringNumberLiteral(left)
			b, okB := loweringNumberLiteral(right)
			if okA && okB && b == "1" {
				return a, true
			}
		}
	default:
	}
	return "", false
}
