package native

import (
    "encoding/json"
    "fmt"
    "net/url"
    "sort"
    "strings"
    "unicode/utf8"

    "goforge.dev/refine/explain"
    "goforge.dev/refine/language"
    refineopenapi "goforge.dev/refine/openapi"
)

const defaultAuthoredOpenAPIResource="urn:refine:openapi:authored"

// AuthorOpenAPIOptions supplies non-operation wire policy and the stable URI
// of the generated OpenAPI resource. OpenAPI operation metadata is always
// derived from the checked source declaration and cannot be supplied twice.
type AuthorOpenAPIOptions struct { EntryResource string; Metadata WireMetadata }

type authoredOpenAPILowerer struct { lower *lowerer; resolver *authoredOpenAPITypeResolver; gotchas []string }
type authoredOpenAPITypeView struct { typ *language.Type; bindings map[string]*authoredOpenAPITypeView }
type authoredOpenAPITypeResolver struct { declarations map[string]language.TypeDecl; remaining int; paths map[string]*authoredOpenAPITypeView }

// AuthorOpenAPIProject lowers a checked standalone OpenAPI declaration into a
// rootless native project. The generated document contains no synthetic
// payload root. Its top-level x-refine annotation retains the exact checked
// source and authoritative operation bindings for subsequent bundle/export
// and generated-runtime composition.
func AuthorOpenAPIProject(program *language.Program,options AuthorOpenAPIOptions)(*Project,error){
    if program==nil{return nil,&Error{Code:"native.project",Format:OpenAPI,Message:"a checked Refine program is required"}}
    declaration:=program.OpenAPI();if declaration==nil{return nil,&Error{Code:"native.metadata",Format:OpenAPI,Message:"the checked program has no standalone OpenAPI declaration"}}
    if options.Metadata.OpenAPI!=nil{return nil,&Error{Code:"native.metadata",Format:OpenAPI,Message:"AuthorOpenAPIProject derives operation authority from source and will not merge competing OpenAPI metadata"}}
    entry:=options.EntryResource;if entry==""{entry=defaultAuthoredOpenAPIResource};parsed,err:=url.Parse(entry);if err!=nil||!parsed.IsAbs()||parsed.Fragment!=""{return nil,&Error{Code:"native.resource",Format:OpenAPI,Pointer:entry,Message:"EntryResource must be an absolute URI without a fragment"}}
    metadata:=copyMetadata(options.Metadata);if err:=validateMetadata(program,metadata);err!=nil{return nil,wrap(OpenAPI,"native.metadata","",err)}
    generated,derived,err:=authorOpenAPIDocument(program,declaration,metadata);if err!=nil{return nil,err};metadata.OpenAPI=derived
    generated["x-refine"]=map[string]any{"source":program.Source(),"metadata":metadata}
    data,err:=json.MarshalIndent(generated,"","  ");if err!=nil{return nil,wrap(OpenAPI,"native.lower","",err)};data=append(data,'\n');if len(data)>64<<20{return nil,&Error{Code:"native.limit",Format:OpenAPI,Pointer:entry,Message:"generated OpenAPI resource exceeds 64 MiB"}}
    project,err:=IngestOpenAPIOperations(data,OpenAPIOperationIngestOptions{EntryResource:entry});if err!=nil{return nil,&Error{Code:"native.lower-invalid",Format:OpenAPI,Pointer:entry,Message:"generated standalone OpenAPI document failed checked ingestion: "+err.Error(),Cause:err}}
    // A source release footer remains part of EditableSource. Authoring does
    // not copy it into the native bundle's independent outer release policy.
    return project,nil
}

func authorOpenAPIDocument(program *language.Program,declaration *language.OpenAPIDeclaration,metadata WireMetadata)(map[string]any,*refineopenapi.Schema,error){
    if declaration==nil{return nil,nil,&Error{Code:"native.metadata",Format:OpenAPI,Message:"standalone OpenAPI declaration is absent"}}
    if declaration.Version!="3.1.0"&&declaration.Version!="3.1.1"&&declaration.Version!="3.1.2"&&declaration.Version!="3.2.0"&&declaration.Version!="3.2.1"{return nil,nil,&Error{Code:"native.unrepresentable",Format:OpenAPI,Pointer:"openapi.version",Message:"standalone authoring requires a published OpenAPI 3.1.x or 3.2.x patch"}}
    if declaration.Title==""||declaration.APIVersion==""||!utf8.ValidString(declaration.Title)||!utf8.ValidString(declaration.APIVersion){return nil,nil,&Error{Code:"native.metadata",Format:OpenAPI,Pointer:"openapi.info",Message:"title and API version must be nonempty UTF-8 text"}}
    if len(declaration.Operations)==0||len(declaration.Operations)>4096{return nil,nil,&Error{Code:"native.metadata",Format:OpenAPI,Message:"standalone OpenAPI declaration must contain between 1 and 4,096 operations"}}
    lowering,err:=newAuthoredOpenAPILowerer(program,metadata);if err!=nil{return nil,nil,err}
    paths:=map[string]any{};refined:=[]refineopenapi.OperationBinding{};nativeBindings:=[]refineopenapi.NativeOperationBinding{};operationIDs:=map[string]bool{};locations:=map[string]bool{}
    for _,operation:=range declaration.Operations{
        operationObject,refinedBinding,nativeBinding,err:=lowering.operation(program,operation);if err!=nil{return nil,nil,err};if operationIDs[refinedBinding.OperationID]{return nil,nil,authorOpenAPIError(operation.OperationID,"duplicate operationId")};operationIDs[refinedBinding.OperationID]=true;location:=refinedBinding.Method+"\x00"+refinedBinding.Path;if locations[location]{return nil,nil,authorOpenAPIError(operation.OperationID,"duplicate method and path")};locations[location]=true
        pathObject,ok:=paths[refinedBinding.Path].(map[string]any);if !ok{pathObject=map[string]any{};paths[refinedBinding.Path]=pathObject};pathObject[strings.ToLower(refinedBinding.Method)]=operationObject;refined=append(refined,refinedBinding);nativeBindings=append(nativeBindings,nativeBinding)
    }
    lowering.lower.finishCompanion();description:="Refine standalone OpenAPI contract. The checked source embedded in x-refine is authoritative for operation assembly and refinements.\n\n"+lowering.lower.companion
    if len(lowering.gotchas)>0{description+="\n\n## OpenAPI presence gotchas\n\n- "+strings.Join(lowering.gotchas,"\n- ")}
    document:=map[string]any{"openapi":declaration.Version,"info":map[string]any{"title":declaration.Title,"version":declaration.APIVersion,"description":description},"paths":paths}
    if len(lowering.lower.definitions)>0{document["components"]=map[string]any{"schemas":lowering.lower.definitions}}
    schema:=&refineopenapi.Schema{Version:refineopenapi.SchemaVersion,Operations:refined,Native:&refineopenapi.NativeBindings{Version:refineopenapi.NativeBindingsVersion,Operations:nativeBindings}}
    metadata.OpenAPI=schema;if err:=validateMetadata(program,metadata);err!=nil{return nil,nil,wrap(OpenAPI,"native.metadata","",err)}
    return document,schema,nil
}

func newAuthoredOpenAPILowerer(program *language.Program,metadata WireMetadata)(*authoredOpenAPILowerer,error){
    checked:=program.CheckedSyntax();module:=checked.Syntax;explained,err:=explain.Generate(program);if err!=nil{return nil,wrap(OpenAPI,"native.lower","",err)};copied:=copyMetadata(metadata)
    lower:=&lowerer{format:OpenAPI,mode:Refined,allowLoss:true,module:module,declarations:map[string]language.TypeDecl{},definitions:map[string]any{},building:map[string]bool{},avroDefined:map[string]bool{},explanation:explained,companion:explained.Markdown(),explanationUsed:map[int]bool{},encodings:copied.Scalars,extraFields:copied.ExtraFields,discriminators:copied.Discriminators,owner:"$payload",specializationNames:map[string]string{},nativeNames:map[string]string{},maxSpecializations:DefaultLowerGenericSpecializations,nativeJSONNumbers:true}
    lower.extraFieldWork.remaining=language.DefaultSubstitutionNodes;lower.nativeNames["Anonymous"]="reserved anonymous Avro record";declarations:=map[string]language.TypeDecl{};for _,item:=range module.Types{lower.declarations[item.Name]=item;declarations[item.Name]=item;lower.nativeNames[item.Name]="declaration "+item.Name};for name,encoding:=range lower.encodings{if encoding.Kind==RationalRecord{lower.nativeNames[name+"Wire"]="scalar wire "+name}}
    return &authoredOpenAPILowerer{lower:lower,resolver:&authoredOpenAPITypeResolver{declarations:declarations,remaining:language.DefaultSubstitutionNodes,paths:map[string]*authoredOpenAPITypeView{}}},nil
}

func (a *authoredOpenAPILowerer)operation(program *language.Program,operation language.OpenAPIOperationDeclaration)(map[string]any,refineopenapi.OperationBinding,refineopenapi.NativeOperationBinding,error){
    method:=strings.ToUpper(operation.Method);allowed:=map[string]bool{"GET":true,"PUT":true,"POST":true,"DELETE":true,"OPTIONS":true,"HEAD":true,"PATCH":true,"TRACE":true};if operation.OperationID==""||!utf8.ValidString(operation.OperationID){return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"operationId must be nonempty UTF-8 text")};if !allowed[method]||method!=operation.Method{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"method must use a canonical uppercase OpenAPI path-item method")};if operation.Path==""||!utf8.ValidString(operation.Path){return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"path must be nonempty UTF-8 text")}
    if err:=a.resolver.closedRoot(operation.Request.TypeName);err!=nil{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"request type: "+err.Error())}
    object:=map[string]any{"operationId":operation.OperationID};parameters:=[]any{};nativeParameters:=[]refineopenapi.NativeParameterBinding{};requestPaths:=map[string]bool{};coverage:=map[string][][]string{"parameters":{},"headers":{}}
    for _,parameter:=range operation.Request.Parameters{location:=strings.ToLower(parameter.In);if location!="path"&&location!="query"&&location!="header"&&location!="cookie"{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"parameter location must be path, query, header, or cookie")};if parameter.Name==""||!utf8.ValidString(parameter.Name){return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"parameter name must be nonempty UTF-8 text")};top:="parameters";if location=="header"{top="headers"};relative,err:=authorOpenAPIFieldPath(parameter.FieldPath,top);if err!=nil{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"parameter "+parameter.Name+": "+err.Error())};wireKey:=openAPIParameterKey(location,parameter.Name);if requestPaths[wireKey]{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"duplicate parameter "+location+"/"+parameter.Name)};requestPaths[wireKey]=true
        required,schema,err:=a.part(program,operation.Request.TypeName,parameter.FieldPath,parameter.Required,operation.OperationID+" request parameter "+parameter.Name);if err!=nil{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},err};if location=="path"&&!required{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"path parameter "+parameter.Name+" must be required")};parameters=append(parameters,map[string]any{"name":parameter.Name,"in":location,"required":required,"schema":schema});nativeParameters=append(nativeParameters,refineopenapi.NativeParameterBinding{In:location,Name:parameter.Name,FieldPath:relative});coverage[top]=append(coverage[top],relative)
    }
    for _,top:=range []string{"parameters","headers"}{if err:=a.coverage(program,operation.Request.TypeName,top,coverage[top]);err!=nil{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"request "+top+": "+err.Error())}}
    if len(parameters)>0{object["parameters"]=parameters};var nativeBody *refineopenapi.NativeMediaBinding
    if operation.Request.Body!=nil{body:=operation.Request.Body;if err:=authorOpenAPIBodyPath(body.FieldPath);err!=nil{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"request body: "+err.Error())};required,schema,err:=a.part(program,operation.Request.TypeName,body.FieldPath,body.Required,operation.OperationID+" request body");if err!=nil{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},err};media,err:=authorOpenAPIMedia(body.MediaType);if err!=nil{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"request body: "+err.Error())};object["requestBody"]=map[string]any{"required":required,"content":map[string]any{media:map[string]any{"schema":schema}}};nativeBody=&refineopenapi.NativeMediaBinding{MediaType:media}
    }else if err:=a.absentBody(program,operation.Request.TypeName);err!=nil{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"request body: "+err.Error())}
    if len(operation.Responses)==0{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"at least one response is required")};responsesObject:=map[string]any{};responses:=[]refineopenapi.ResponseBinding{};nativeResponses:=[]refineopenapi.NativeResponseBinding{};seenStatuses:=map[string]bool{}
    for _,response:=range operation.Responses{if seenStatuses[response.Status]{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"duplicate response status "+response.Status)};seenStatuses[response.Status]=true;if err:=a.resolver.closedRoot(response.TypeName);err!=nil{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"response "+response.Status+" type: "+err.Error())};if response.Description==""||!utf8.ValidString(response.Description){return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"response "+response.Status+" description must be nonempty UTF-8 text")};responseObject:=map[string]any{"description":response.Description};headers:=map[string]any{};nativeHeaders:=[]refineopenapi.NativeHeaderBinding{};headerNames:=map[string]bool{};headerCoverage:=[][]string{}
        for _,header:=range response.Headers{if header.Name==""||!utf8.ValidString(header.Name){return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"response header name must be nonempty UTF-8 text")};folded:=strings.ToLower(header.Name);if headerNames[folded]{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"duplicate response header "+header.Name)};headerNames[folded]=true;relative,err:=authorOpenAPIFieldPath(header.FieldPath,"headers");if err!=nil{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"response header "+header.Name+": "+err.Error())};required,schema,err:=a.part(program,response.TypeName,header.FieldPath,header.Required,operation.OperationID+" response "+response.Status+" header "+header.Name);if err!=nil{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},err};headers[header.Name]=map[string]any{"schema":schema};nativeHeaders=append(nativeHeaders,refineopenapi.NativeHeaderBinding{Name:header.Name,FieldPath:relative});headerCoverage=append(headerCoverage,relative);if required{a.gotchas=append(a.gotchas,"Refine requires response "+response.Status+" header `"+header.Name+"` for operation `"+operation.OperationID+"`; an OpenAPI Header Object does not require response-header presence, so the checked facade enforces this additional condition.")}}
        if err:=a.coverage(program,response.TypeName,"headers",headerCoverage);err!=nil{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"response "+response.Status+" headers: "+err.Error())};if len(headers)>0{responseObject["headers"]=headers};var nativeResponseBody *refineopenapi.NativeMediaBinding
        if response.Body!=nil{body:=response.Body;if err:=authorOpenAPIBodyPath(body.FieldPath);err!=nil{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"response "+response.Status+" body: "+err.Error())};required,schema,err:=a.part(program,response.TypeName,body.FieldPath,body.Required,operation.OperationID+" response "+response.Status+" body");if err!=nil{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},err};media,err:=authorOpenAPIMedia(body.MediaType);if err!=nil{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"response "+response.Status+" body: "+err.Error())};responseObject["content"]=map[string]any{media:map[string]any{"schema":schema}};nativeResponseBody=&refineopenapi.NativeMediaBinding{MediaType:media};if required{a.gotchas=append(a.gotchas,"Refine requires response "+response.Status+" body for operation `"+operation.OperationID+"`; OpenAPI response content describes a supplied body but does not require its presence, so the checked facade enforces this additional condition.")}
        }else if err:=a.absentBody(program,response.TypeName);err!=nil{return nil,refineopenapi.OperationBinding{},refineopenapi.NativeOperationBinding{},authorOpenAPIError(operation.OperationID,"response "+response.Status+" body: "+err.Error())}
        responsesObject[response.Status]=responseObject;responses=append(responses,refineopenapi.ResponseBinding{Status:response.Status,ResponseType:response.TypeName,ContextType:response.ContextType});nativeResponses=append(nativeResponses,refineopenapi.NativeResponseBinding{Status:response.Status,Headers:nativeHeaders,Body:nativeResponseBody})
    }
    object["responses"]=responsesObject;refined:=refineopenapi.OperationBinding{OperationID:operation.OperationID,Method:method,Path:operation.Path,RequestType:operation.Request.TypeName,Responses:responses};native:=refineopenapi.NativeOperationBinding{OperationID:operation.OperationID,Parameters:nativeParameters,RequestBody:nativeBody,Responses:nativeResponses};return object,refined,native,nil
}

func (a *authoredOpenAPILowerer)part(program *language.Program,root string,path []string,explicit *bool,owner string)(bool,any,error){
    typ,err:=a.resolver.fieldPath(root,path);if err!=nil{return false,nil,&Error{Code:"native.metadata",Format:OpenAPI,Pointer:owner,Message:err.Error(),Cause:err}}
    optional,schemaView,err:=a.resolver.optionalType(typ,map[string]bool{},0);if err!=nil{return false,nil,&Error{Code:"native.limit",Format:OpenAPI,Pointer:owner,Message:err.Error(),Cause:err}}
    required:=!optional;if explicit!=nil&&*explicit!=required{state:="required";if optional{state="optional"};return false,nil,&Error{Code:"native.metadata",Format:OpenAPI,Pointer:owner,Message:fmt.Sprintf("explicit required=%t conflicts with the checked field type, which is %s",*explicit,state)}}
    schemaType,err:=a.resolver.materialize(schemaView,0);if err!=nil{return false,nil,&Error{Code:"native.limit",Format:OpenAPI,Pointer:owner,Message:err.Error(),Cause:err}}
    oldOwner:=a.lower.owner;a.lower.owner=root;schema,err:=a.lower.typ(schemaType,false);a.lower.owner=oldOwner;if err!=nil{return false,nil,atLower(err,owner)};return required,schema,nil
}

func (r *authoredOpenAPITypeResolver)closedRoot(name string)error{decl,ok:=r.declarations[name];if name==""||!ok||len(decl.Parameters)!=0{return fmt.Errorf("must name a declared closed type")};return nil}
func (r *authoredOpenAPITypeResolver)step(count int)error{if count<0||count>r.remaining{return fmt.Errorf("standalone OpenAPI checked-type work limit exceeded")};r.remaining-=count;return nil}
func (r *authoredOpenAPITypeResolver)view(typ *language.Type,bindings map[string]*authoredOpenAPITypeView)*authoredOpenAPITypeView{return &authoredOpenAPITypeView{typ:typ,bindings:bindings}}
func (r *authoredOpenAPITypeResolver)named(view *authoredOpenAPITypeView)(string,bool){if view==nil||view.typ==nil{return "",false};match view.typ.Form{case language.NamedType(name):return name,true;case _:return "",false}}
func (r *authoredOpenAPITypeResolver)bound(view *authoredOpenAPITypeView)(*authoredOpenAPITypeView,bool){name,ok:=r.named(view);if !ok||view.bindings==nil{return nil,false};bound,ok:=view.bindings[name];return bound,ok}
func (r *authoredOpenAPITypeResolver)application(view *authoredOpenAPITypeView)(string,[]*authoredOpenAPITypeView,bool,error){current:=view;args:=[]*authoredOpenAPITypeView{};for{if current==nil||current.typ==nil{return "",nil,false,fmt.Errorf("checked type contains a nil child")};match current.typ.Form{case language.AppliedType(fn,arg):if err:=r.step(1);err!=nil{return "",nil,false,err};args=append([]*authoredOpenAPITypeView{r.view(arg,current.bindings)},args...);current=r.view(fn,current.bindings);case language.NamedType(name):if bound,ok:=r.bound(current);ok{current=bound;continue};return name,args,true,nil;case _:return "",nil,false,nil}}}
func (r *authoredOpenAPITypeResolver)genericBody(name string,args []*authoredOpenAPITypeView)(*authoredOpenAPITypeView,error){decl,ok:=r.declarations[name];if !ok||decl.Body==nil||len(decl.Parameters)!=len(args){return nil,fmt.Errorf("checked type does not resolve through alias %s",name)};if err:=r.step(len(args)+1);err!=nil{return nil,err};bindings:=make(map[string]*authoredOpenAPITypeView,len(args));for i,param:=range decl.Parameters{bindings[param]=args[i]};return r.view(decl.Body,bindings),nil}
func (r *authoredOpenAPITypeResolver)optionalType(view *authoredOpenAPITypeView,active map[string]bool,depth int)(bool,*authoredOpenAPITypeView,error){
    if view==nil||view.typ==nil||depth>128{return false,nil,fmt.Errorf("optional type resolution limit exceeded")};if err:=r.step(1);err!=nil{return false,nil,err};if bound,ok:=r.bound(view);ok{return r.optionalType(bound,active,depth+1)};match view.typ.Form{case language.RefinedType(base,_):optional,inner,err:=r.optionalType(r.view(base,view.bindings),active,depth+1);if optional{return true,inner,err};return false,view,err;case language.NamedType(name):decl,ok:=r.declarations[name];if !ok||decl.Body==nil||len(decl.Parameters)>0{return false,view,nil};if active[name]{return false,nil,fmt.Errorf("cyclic optional alias")};active[name]=true;optional,inner,err:=r.optionalType(r.view(decl.Body,nil),active,depth+1);delete(active,name);if optional{return true,inner,err};return false,view,err;case language.AppliedType(_,_):name,args,ok,err:=r.application(view);if err!=nil{return false,nil,err};if !ok{return false,view,nil};if name=="Maybe"&&len(args)==1{return true,args[0],nil};if name=="Nullable"||name=="Map"{return false,view,nil};decl,found:=r.declarations[name];if !found||decl.Body==nil||len(decl.Parameters)!=len(args){return false,view,nil};body,err:=r.genericBody(name,args);if err!=nil{return false,nil,err};optional,inner,err:=r.optionalType(body,active,depth+1);if optional{return true,inner,err};return false,view,err;case _:return false,view,nil}}

func (r *authoredOpenAPITypeResolver)fieldPath(root string,path []string)(*authoredOpenAPITypeView,error){key:=root+"\x00"+strings.Join(path,"\x00");if cached:=r.paths[key];cached!=nil{return cached,nil};if err:=r.closedRoot(root);err!=nil{return nil,err};current:=r.view(&language.Type{Form:language.NamedType{Name:root}},nil);for _,name:=range path{if name==""{return nil,fmt.Errorf("field path contains an empty member")};fields,err:=r.recordFields(current,map[string]bool{},0);if err!=nil{return nil,err};next:=fields[name];if next==nil{return nil,fmt.Errorf("field path %s does not exist",strings.Join(path,"."))};current=next};r.paths[key]=current;return current,nil}
func (r *authoredOpenAPITypeResolver)recordFields(view *authoredOpenAPITypeView,active map[string]bool,depth int)(map[string]*authoredOpenAPITypeView,error){
    if view==nil||view.typ==nil||depth>128{return nil,fmt.Errorf("field path type resolution limit exceeded")};if err:=r.step(1);err!=nil{return nil,err};if bound,ok:=r.bound(view);ok{return r.recordFields(bound,active,depth+1)};match view.typ.Form{case language.RefinedType(base,_):return r.recordFields(r.view(base,view.bindings),active,depth+1);case language.RecordType(fields):if err:=r.step(len(fields));err!=nil{return nil,err};out:=map[string]*authoredOpenAPITypeView{};for _,field:=range fields{out[field.Name]=r.view(field.Type,view.bindings)};return out,nil;case language.NamedType(name):decl,ok:=r.declarations[name];if !ok||decl.Body==nil||len(decl.Parameters)>0{return nil,fmt.Errorf("field path traverses a non-record type")};if active[name]{return nil,fmt.Errorf("cyclic record alias")};active[name]=true;out,err:=r.recordFields(r.view(decl.Body,nil),active,depth+1);delete(active,name);return out,err;case language.AppliedType(_,_):name,args,ok,err:=r.application(view);if err!=nil{return nil,err};if !ok{return nil,fmt.Errorf("field path traverses a non-record type")};if (name=="Maybe"||name=="Nullable")&&len(args)==1{return r.recordFields(args[0],active,depth+1)};body,err:=r.genericBody(name,args);if err!=nil{return nil,err};return r.recordFields(body,active,depth+1);case _:return nil,fmt.Errorf("field path traverses a non-record type")}}

func (r *authoredOpenAPITypeResolver)materialize(view *authoredOpenAPITypeView,depth int)(*language.Type,error){
    if view==nil||view.typ==nil||depth>512{return nil,fmt.Errorf("selected field type materialization limit exceeded")};if err:=r.step(1);err!=nil{return nil,err};if bound,ok:=r.bound(view);ok{return r.materialize(bound,depth+1)};current:=view.typ;match current.Form{case language.NamedType(_):copy:=*current;return &copy,nil;case language.ListType(element):next,err:=r.materialize(r.view(element,view.bindings),depth+1);if err!=nil{return nil,err};return &language.Type{Form:language.ListType{Element:next},At:current.At},nil;case language.AppliedType(fn,arg):left,err:=r.materialize(r.view(fn,view.bindings),depth+1);if err!=nil{return nil,err};right,err:=r.materialize(r.view(arg,view.bindings),depth+1);if err!=nil{return nil,err};return &language.Type{Form:language.AppliedType{Constructor:left,Argument:right},At:current.At},nil;case language.ArrowType(arg,result):left,err:=r.materialize(r.view(arg,view.bindings),depth+1);if err!=nil{return nil,err};right,err:=r.materialize(r.view(result,view.bindings),depth+1);if err!=nil{return nil,err};return &language.Type{Form:language.ArrowType{Argument:left,Result:right},At:current.At},nil;case language.RecordType(fields):if err:=r.step(len(fields));err!=nil{return nil,err};next:=make([]language.Field,len(fields));for i,field:=range fields{typ,err:=r.materialize(r.view(field.Type,view.bindings),depth+1);if err!=nil{return nil,err};next[i]=field;next[i].Type=typ};return &language.Type{Form:language.RecordType{Fields:next},At:current.At},nil;case language.RefinedType(base,rules):next,err:=r.materialize(r.view(base,view.bindings),depth+1);if err!=nil{return nil,err};return &language.Type{Form:language.RefinedType{Base:next,Rules:append([]language.Where(nil),rules...)},At:current.At},nil};return nil,fmt.Errorf("unknown selected field type")}

func authorOpenAPIFieldPath(path []string,top string)([]string,error){if len(path)<2||path[0]!=top{return nil,fmt.Errorf("field path must begin %s and select a nested field",top)};for _,part:=range path{if part==""{return nil,fmt.Errorf("field path contains an empty member")}};return append([]string(nil),path[1:]...),nil}
func authorOpenAPIBodyPath(path []string)error{if len(path)!=1||path[0]!="body"{return fmt.Errorf("field path must be exactly body")};return nil}
func authorOpenAPIMedia(media string)(string,error){if !utf8.ValidString(media){return "",fmt.Errorf("media type must be UTF-8 text")};lower:=strings.ToLower(media);if lower!="application/json"&&!strings.HasSuffix(lower,"+json"){return "",fmt.Errorf("semantic body media type must be application/json or end in +json")};return media,nil}

func (a *authoredOpenAPILowerer)coverage(program *language.Program,root,top string,paths [][]string)error{typ,err:=a.resolver.fieldPath(root,[]string{top});if err!=nil{return err};return a.coverType(typ,nil,paths,0)}
func (a *authoredOpenAPILowerer)coverType(typ *authoredOpenAPITypeView,prefix []string,paths [][]string,depth int)error{
    if depth>128{return fmt.Errorf("field coverage resolution limit exceeded")};if err:=a.resolver.step(len(paths)+1);err!=nil{return err};exact:=false;descendants:=[][]string{};for _,path:=range paths{if stringSliceEqual(path,prefix){exact=true}else if authorPathPrefix(prefix,path){descendants=append(descendants,path)}};if exact{if len(descendants)>0{return fmt.Errorf("field mappings overlap at %s",strings.Join(prefix,"."))};return nil};fields,err:=a.resolver.recordFields(typ,map[string]bool{},depth);if err!=nil{if len(prefix)==0{return fmt.Errorf("mapped collection must resolve to a record")};return fmt.Errorf("checked field %s is not represented by any native operation part",strings.Join(prefix,"."))};if len(fields)==0{if len(descendants)>0{return fmt.Errorf("field mapping descends through empty record %s",strings.Join(prefix,"."))};return nil};names:=make([]string,0,len(fields));for name:=range fields{names=append(names,name)};sort.Strings(names);for _,name:=range names{next:=append(append([]string(nil),prefix...),name);if err:=a.coverType(fields[name],next,paths,depth+1);err!=nil{return err}};for _,path:=range paths{if !authorPathPrefix(prefix,path){continue};if len(path)>len(prefix){if fields[path[len(prefix)]]==nil{return fmt.Errorf("field mapping %s does not exist",strings.Join(path,"."))}}};return nil
}
func authorPathPrefix(prefix,path []string)bool{if len(prefix)>len(path){return false};for i:=range prefix{if prefix[i]!=path[i]{return false}};return true}

func (a *authoredOpenAPILowerer)absentBody(program *language.Program,root string)error{typ,err:=a.resolver.fieldPath(root,[]string{"body"});if err!=nil{return err};optional,inner,err:=a.resolver.optionalType(typ,map[string]bool{},0);if err!=nil{return err};if !optional{return fmt.Errorf("undeclared body must be optional")};fields,err:=a.resolver.recordFields(inner,map[string]bool{},0);if err!=nil||len(fields)!=0{return fmt.Errorf("undeclared body must have the transport-empty type Maybe ({})")};return nil}
func authorOpenAPIError(operation,message string)error{return &Error{Code:"native.metadata",Format:OpenAPI,Pointer:operation,Message:message}}
