package native

import (
    "fmt"
    "testing"
    "testing/quick"
)

func TestOpenAPI31ExactJSONSchemaPayloadValidation(t *testing.T){
    source:="openapi: 3.1.2\ninfo: {title: Exact, version: '1'}\npaths: {}\ncomponents:\n  schemas:\n    Exact:\n      $schema: https://spec.openapis.org/oas/3.1/dialect/base\n      type: integer\n      minimum: 9007199254740993\n      multipleOf: 2\n"
    project,err:=IngestProject(OpenAPI,[]byte(source),ProjectOptions{ResourceID:"https://example.test/api.yaml",Root:ResourceSelector{Pointer:"/components/schemas/Exact",TypeName:"Exact"}});if err!=nil{t.Fatal(err)}
    for payload,valid:=range map[string]bool{"9007199254740994":true,"9007199254740993":false,"9007199254740992":false,"9007199254740994.0":true}{err:=project.ValidateJSON([]byte(payload));if (err==nil)!=valid{t.Fatalf("payload %s valid=%t: %v",payload,valid,err)}}
    if err:=project.ValidateJSON([]byte(`{"x":1,"x":1}`));problemCode(err)!="native.payload"{t.Fatalf("duplicate payload key accepted: %v",err)}
}

func TestOpenAPI321ResourceIngestionAndNativePayload(t *testing.T){source:="openapi: 3.2.1\ninfo: {title: Current, version: '1'}\npaths: {}\ncomponents:\n  schemas:\n    Count: {type: integer, minimum: 2}\n";resources:=[]Resource{{URI:"https://example.test/current.yaml",Source:source}};project,err:=IngestProjectResources(OpenAPI,resources,ProjectOptions{Root:ResourceSelector{Resource:"https://example.test/current.yaml",Pointer:"/components/schemas/Count",TypeName:"Count"}});if err!=nil{t.Fatal(err)};if project.Version()!="3.2.1"||project.NativeDocument().Original()!=source{t.Fatalf("3.2.1 identity changed: %s %q",project.Version(),project.NativeDocument().Original())};if err:=project.ValidateJSON([]byte(`2`));err!=nil{t.Fatal(err)};if err:=project.ValidateJSON([]byte(`1`));problemCode(err)!="native.payload"{t.Fatalf("3.2.1 scalar constraint not enforced: %v",err)}}

func TestOpenAPIExactYAMLNumbersAndExternalResources(t *testing.T){
    hexadecimal:="openapi: 3.2.0\ninfo: {title: Hex, version: '1'}\npaths: {}\ncomponents:\n  schemas:\n    Value: {type: integer, minimum: 0x10}\n";project,err:=IngestProject(OpenAPI,[]byte(hexadecimal),ProjectOptions{Root:ResourceSelector{Pointer:"/components/schemas/Value",TypeName:"Value"}});if err!=nil{t.Fatal(err)};if err:=project.ValidateJSON([]byte(`16`));err!=nil{t.Fatal(err)};if err:=project.ValidateJSON([]byte(`15`));problemCode(err)!="native.payload"{t.Fatalf("exact YAML integer lost: %v",err)}
    resources:=[]Resource{{URI:"https://example.test/api.yaml",Source:"openapi: 3.1.2\ninfo: {title: External, version: '1'}\npaths: {}\ncomponents:\n  schemas:\n    Code: {$ref: './code.yaml'}\n"},{URI:"https://example.test/code.yaml",Source:"type: string\nminLength: 2\n"}};external,err:=IngestProjectResources(OpenAPI,resources,ProjectOptions{Root:ResourceSelector{Resource:"https://example.test/api.yaml",Pointer:"/components/schemas/Code",TypeName:"Code"}});if err!=nil{t.Fatal(err)};if err:=external.ValidateJSON([]byte(`"ok"`));err!=nil{t.Fatal(err)};if err:=external.ValidateJSON([]byte(`"x"`));problemCode(err)!="native.payload"{t.Fatalf("external constraint not enforced: %v",err)}
}

func TestOpenAPIPayloadDialectGates(t *testing.T){
    custom:="openapi: 3.1.2\njsonSchemaDialect: https://example.test/custom-dialect\ninfo: {title: Custom, version: '1'}\npaths: {}\ncomponents:\n  schemas:\n    Text: {type: string}\n";project,err:=IngestProject(OpenAPI,[]byte(custom),ProjectOptions{Root:ResourceSelector{Pointer:"/components/schemas/Text",TypeName:"Text"}});if err!=nil{t.Fatal(err)};if err:=project.ValidateJSON([]byte(`"x"`));problemCode(err)!="native.enforcement"{t.Fatalf("custom dialect silently ignored: %v",err)}
    nested:="openapi: 3.1.2\ninfo: {title: Nested, version: '1'}\npaths: {}\ncomponents:\n  schemas:\n    Text: {$schema: 'https://example.test/custom-dialect', type: string}\n";project,err=IngestProject(OpenAPI,[]byte(nested),ProjectOptions{Root:ResourceSelector{Pointer:"/components/schemas/Text",TypeName:"Text"}});if err!=nil{t.Fatal(err)};if err:=project.ValidateJSON([]byte(`"x"`));problemCode(err)!="native.enforcement"{t.Fatalf("Schema Object custom dialect silently ignored: %v",err)}
}

func TestOpenAPI30ExactAdapterNullableExclusiveAndRefs(t *testing.T){
    for _,version:=range []string{"3.0.0","3.0.1","3.0.2","3.0.3","3.0.4"}{t.Run(version,func(t *testing.T){source:="openapi: "+version+"\ninfo: {title: Old, version: '1'}\npaths: {}\ncomponents:\n  schemas:\n    Exact:\n      type: number\n      minimum: 90071992547409931234567890\n      exclusiveMinimum: true\n      nullable: true\n";project,err:=IngestProject(OpenAPI,[]byte(source),ProjectOptions{Root:ResourceSelector{Pointer:"/components/schemas/Exact",TypeName:"Exact"}});if err!=nil{t.Fatal(err)};for payload,valid:=range map[string]bool{"90071992547409931234567890":false,"90071992547409931234567891":true,"null":true,`"90071992547409931234567891"`:false}{err:=project.ValidateJSON([]byte(payload));if (err==nil)!=valid{t.Fatalf("payload %s valid=%t: %v",payload,valid,err)}}})}
    referenced:="openapi: 3.0.4\ninfo: {title: Ref, version: '1'}\npaths: {}\ncomponents:\n  schemas:\n    Root: {$ref: '#/components/schemas/Word'}\n    Word: {type: string, minLength: 2}\n";project,err:=IngestProject(OpenAPI,[]byte(referenced),ProjectOptions{Root:ResourceSelector{Pointer:"/components/schemas/Root",TypeName:"Root"}});if err!=nil{t.Fatal(err)};if err:=project.ValidateJSON([]byte(`"ok"`));err!=nil{t.Fatal(err)};if err:=project.ValidateJSON([]byte(`"x"`));problemCode(err)!="native.payload"{t.Fatalf("3.0 reference target not enforced: %v",err)}
    closed:="openapi: 3.0.4\ninfo: {title: Closed, version: '1'}\npaths: {}\ncomponents:\n  schemas:\n    Root:\n      type: object\n      properties: {name: {type: string}}\n      additionalProperties: false\n";project,err=IngestProject(OpenAPI,[]byte(closed),ProjectOptions{Root:ResourceSelector{Pointer:"/components/schemas/Root",TypeName:"Root"}});if err!=nil{t.Fatal(err)};if err:=project.ValidateJSON([]byte(`{"name":"ok"}`));err!=nil{t.Fatal(err)};if err:=project.ValidateJSON([]byte(`{"extra":true}`));problemCode(err)!="native.payload"{t.Fatalf("3.0 Boolean additionalProperties not enforced: %v",err)}
}

func TestOpenAPI30NullableDoesNotOverrideEnumOrNestedApplicators(t *testing.T){
    source:="openapi: 3.0.4\ninfo: {title: Nullable, version: '1'}\npaths: {}\ncomponents:\n  schemas:\n    Value:\n      type: string\n      nullable: true\n      enum: [ok]\n      allOf:\n        - type: string\n";project,err:=IngestProject(OpenAPI,[]byte(source),ProjectOptions{Root:ResourceSelector{Pointer:"/components/schemas/Value",TypeName:"Value"}});if err!=nil{t.Fatal(err)};if err:=project.ValidateJSON([]byte(`"ok"`));err!=nil{t.Fatal(err)};for _,payload:=range []string{`null`,`"no"`}{if err:=project.ValidateJSON([]byte(payload));problemCode(err)!="native.payload"{t.Fatalf("other 3.0 constraints were bypassed for %s: %v",payload,err)}}
}

func TestOpenAPI30AdapterUsesOnlyExplicitExternalResources(t *testing.T){resources:=[]Resource{{URI:"https://example.test/api.yaml",Source:"openapi: 3.0.4\ninfo: {title: External, version: '1'}\npaths: {}\ncomponents:\n  schemas:\n    Root: {$ref: './value.yaml'}\n"},{URI:"https://example.test/value.yaml",Source:"type: integer\nminimum: 10\nexclusiveMinimum: true\nnullable: true\n"}};project,err:=IngestProjectResources(OpenAPI,resources,ProjectOptions{Root:ResourceSelector{Resource:"https://example.test/api.yaml",Pointer:"/components/schemas/Root",TypeName:"Root"}});if err!=nil{t.Fatal(err)};for payload,valid:=range map[string]bool{"11":true,"10":false,"null":true}{err:=project.ValidateJSON([]byte(payload));if (err==nil)!=valid{t.Fatalf("external 3.0 payload %s valid=%t: %v",payload,valid,err)}}}

func TestOpenAPISchemaLocationsIgnorePayloadNamesAndExamples(t *testing.T){
    source:="openapi: 3.1.2\ninfo: {title: Locations, version: '1'}\npaths: {}\nx-refine:\n  source: 'type Envelope = {pattern :: String}'\n  root: Envelope\ncomponents:\n  schemas:\n    Envelope:\n      type: object\n      required: ['$schema', pattern]\n      properties:\n        '$schema': {type: string}\n        pattern: {type: string}\n      examples:\n        - {'$schema': 'https://example.test/unsupported', pattern: 'not a regex'}\n";project,err:=IngestProject(OpenAPI,[]byte(source),ProjectOptions{Root:ResourceSelector{Pointer:"/components/schemas/Envelope",TypeName:"Envelope"},Metadata:WireMetadata{ExtraFields:map[string]ExtraFieldMode{"Envelope":PreserveExtraFields}}});if err!=nil{t.Fatal(err)};if err:=project.ValidateJSON([]byte(`{"$schema":"payload","pattern":"plain"}`));err!=nil{t.Fatalf("payload keyword lookalikes changed schema dialect: %v",err)}
    detached:="openapi: 3.1.2\ninfo: {title: BadRoot, version: '1'}\npaths: {}\ncomponents:\n  examples:\n    Fake:\n      value: {type: string}\n";if _,err:=IngestProject(OpenAPI,[]byte(detached),ProjectOptions{Root:ResourceSelector{Pointer:"/components/examples/Fake/value",TypeName:"Fake"}});problemCode(err)!="native.root"{t.Fatalf("non-Schema Object root accepted: %v",err)}
}

func TestOpenAPIPayloadIntegerProperty(t *testing.T){source:="openapi: 3.2.0\ninfo: {title: Bounds, version: '1'}\npaths: {}\ncomponents:\n  schemas:\n    Value: {type: integer, minimum: -1000, maximum: 1000}\n";project,err:=IngestProject(OpenAPI,[]byte(source),ProjectOptions{Root:ResourceSelector{Pointer:"/components/schemas/Value",TypeName:"Value"}});if err!=nil{t.Fatal(err)};property:=func(n int64)bool{valid:=n>=-1000&&n<=1000;return (project.ValidateJSON([]byte(fmt.Sprint(n)))==nil)==valid};if err:=quick.Check(property,&quick.Config{MaxCount:2000});err!=nil{t.Fatal(err)}}

func FuzzOpenAPIPayloadValidation(f *testing.F){source:="openapi: 3.1.2\ninfo: {title: Fuzz, version: '1'}\npaths: {}\ncomponents:\n  schemas:\n    Value: {type: string, pattern: '^[a-z]*$'}\n";project,err:=IngestProject(OpenAPI,[]byte(source),ProjectOptions{Root:ResourceSelector{Pointer:"/components/schemas/Value",TypeName:"Value"}});if err!=nil{f.Fatal(err)};for _,seed:=range []string{`"abc"`,`"ABC"`,`null`,`{"x":1}`}{f.Add(seed)};f.Fuzz(func(t *testing.T,input string){if len(input)>65536{t.Skip()};_ = project.ValidateJSON([]byte(input))})}
