// Code generated by goplus from openapi_provenance_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package native

import (
	"encoding/json"
	"strings"
	"testing"

	"goforge.dev/refine/provenance"
	"goforge.dev/refine/validation"
)

func openAPIProvenanceConstraint(t *testing.T, project *Project, resource, keyword string) provenance.Constraint {
	t.Helper()
	for _, item := range project.NativeConstraints() {
		if item.Resource == resource && item.Constraint.Keyword == keyword {
			return item.Constraint
		}
	}
	t.Fatalf("missing %s provenance for %s: %+v", keyword, resource, project.NativeConstraints())
	return provenance.Constraint{}
}
func openAPIProvenanceUnit(t *testing.T, project *Project, resource string) string {
	t.Helper()
	for _, unit := range project.NativeConstraintSources() {
		if unit.URI == resource {
			return unit.Source
		}
	}
	t.Fatalf("missing provenance source for %s: %+v", resource, project.NativeConstraintSources())
	return ""
}

func TestOpenAPIProvenanceJSONEditsValidationExportBundleAndImmutability(t *testing.T) {
	resource := "https://example.test/exact.json"
	original := `{"openapi":"3.1.2","info":{"title":"Exact","version":"1"},"components":{"schemas":{"Root":{"type":"integer","minimum":0,"const":5}}}}`
	project, err := IngestProject(OpenAPI, []byte(original), ProjectOptions{ResourceID: resource, Root: ResourceSelector{TypeName: "Root"}})
	if err != nil {
		t.Fatal(err)
	}
	minimum := openAPIProvenanceConstraint(t, project, resource, "minimum")
	constant := openAPIProvenanceConstraint(t, project, resource, "const")
	if minimum.SchemaPointer != "/components/schemas/Root" || constant.SchemaPointer != minimum.SchemaPointer {
		t.Fatalf("constraints lost Schema Object scope: %+v %+v", minimum, constant)
	}
	source := openAPIProvenanceUnit(t, project, resource)
	editedSource := strings.Replace(source, constant.Predicate, "(it == (JSONNumber (6 / 1)))", 1)
	if editedSource == source {
		t.Fatal("const fixture did not edit")
	}
	edited, err := project.WithEditedNativeConstraintSource(resource, editedSource)
	if err != nil {
		t.Fatal(err)
	}
	if err := edited.ValidateJSON([]byte(`6`)); err != nil {
		t.Fatal(err)
	}
	if err := edited.ValidateJSON([]byte(`5`)); problemCode(err) != "native.payload" {
		t.Fatalf("edited const was not enforced: %v", err)
	}
	if err := edited.ValidateJSON([]byte(`-1`)); problemCode(err) != "native.payload" {
		t.Fatalf("independent minimum was lost: %v", err)
	}
	if err := project.ValidateJSON([]byte(`5`)); err != nil {
		t.Fatalf("edit mutated prior project: %v", err)
	}
	if project.Resources()[0].Source != original {
		t.Fatal("immutable JSON origin changed")
	}
	canonical, err := edited.CanonicalJSONResources()
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(canonical[0].Source, `"const":6`) || strings.Contains(canonical[0].Source, `"const":5`) {
		t.Fatalf("effective SchemaPointer edit absent: %s", canonical[0].Source)
	}
	exported, err := edited.Export(LowerOptions{Mode: Refined})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(exported.Resources()[0].Source, `"const": 6`) {
		t.Fatalf("export used stale native assertion: %s", exported.Resources()[0].Source)
	}
	bundle, err := edited.Bundle()
	if err != nil {
		t.Fatal(err)
	}
	again, err := ParseBundle(bundle)
	if err != nil {
		t.Fatal(err)
	}
	if openAPIProvenanceUnit(t, again, resource) != editedSource {
		t.Fatal("bundle lost explicit scoped unit edit")
	}
	if err := again.ValidateJSON([]byte(`5`)); problemCode(err) != "native.payload" {
		t.Fatalf("bundle reload lost edited const: %v", err)
	}
}

const openAPIProvenanceOperations = `{"openapi":"3.1.2","info":{"title":"Values","version":"1"},"paths":{"/values":{"post":{"operationId":"putValue","requestBody":{"required":true,"content":{"application/json":{"schema":{"type":"array","minItems":1,"maxItems":3,"items":{"type":"integer"}}}}},"responses":{"204":{"description":"ok"}}}}},"components":{"schemas":{"External":{"$ref":"value.yaml#/schema"}}}}`
const openAPIProvenanceExternalYAML = "schema:\n  type: integer\n  minimum: 10\n  maximum: 20\n"

func TestOpenAPIProvenanceYAMLExternalRootlessRebuildsOperationIndex(t *testing.T) {
	entry := "https://example.test/api.json"
	external := "https://example.test/value.yaml"
	resources := []Resource{{URI: entry, Source: openAPIProvenanceOperations}, {URI: external, Source: openAPIProvenanceExternalYAML}}
	project, err := IngestOpenAPIOperationResources(resources, OpenAPIOperationIngestOptions{EntryResource: entry})
	if err != nil {
		t.Fatal(err)
	}
	if project.Resources()[1].Source != openAPIProvenanceExternalYAML {
		t.Fatal("exact YAML origin changed")
	}
	minimum := openAPIProvenanceConstraint(t, project, entry, "minItems")
	maximum := openAPIProvenanceConstraint(t, project, entry, "maxItems")
	externalMinimum := openAPIProvenanceConstraint(t, project, external, "minimum")
	if minimum.Native != "1" || maximum.Native != "3" || externalMinimum.Native != "10" || externalMinimum.SchemaPointer != "/schema" {
		t.Fatalf("unexpected scoped units: %+v %+v %+v", minimum, maximum, externalMinimum)
	}
	request := OpenAPIRequestJSON{Body: &OpenAPIMediaJSON{MediaType: "application/json", Value: []byte(`[1]`)}}
	if _, report, err := project.DecodeAndValidateOpenAPIRequest("putValue", request, OpenAPILimits{}, validation.Limits{}); err != nil || validation.StateName(report.State()) != "valid" {
		t.Fatalf("baseline request failed: %v %+v", err, report)
	}
	source := openAPIProvenanceUnit(t, project, entry)
	editedSource := strings.Replace(source, minimum.Predicate, "(length it >= 2)", 1)
	edited, err := project.WithEditedNativeConstraintSource(entry, editedSource)
	if err != nil {
		t.Fatal(err)
	}
	if edited.Resources()[1].Source != openAPIProvenanceExternalYAML {
		t.Fatal("effective edit replaced exact YAML origin")
	}
	externalSource := openAPIProvenanceUnit(t, project, external)
	if recovered, err := project.RecoverResourceNative(external, externalMinimum.Name, externalSource); err != nil || recovered != "10" {
		t.Fatalf("external YAML recovery: %q %v", recovered, err)
	}
	if _, _, err := edited.DecodeAndValidateOpenAPIRequest("putValue", request, OpenAPILimits{}, validation.Limits{}); problemCode(err) != "native.payload" {
		t.Fatalf("rebuilt operation index accepted stale minimum: %v", err)
	}
	if _, report, err := project.DecodeAndValidateOpenAPIRequest("putValue", request, OpenAPILimits{}, validation.Limits{}); err != nil || validation.StateName(report.State()) != "valid" {
		t.Fatalf("edit mutated old operation index: %v %+v", err, report)
	}
	request.Body.Value = []byte(`[1,2]`)
	if _, report, err := edited.DecodeAndValidateOpenAPIRequest("putValue", request, OpenAPILimits{}, validation.Limits{}); err != nil || validation.StateName(report.State()) != "valid" {
		t.Fatalf("edited request failed: %v %+v", err, report)
	}
	request.Body.Value = []byte(`[1,2,3,4]`)
	if _, _, err := edited.DecodeAndValidateOpenAPIRequest("putValue", request, OpenAPILimits{}, validation.Limits{}); problemCode(err) != "native.payload" {
		t.Fatalf("independent maximum was lost: %v", err)
	}
	catalog, err := edited.OpenAPIOperationIndex()
	if err != nil {
		t.Fatal(err)
	}
	found := false
	for _, resource := range catalog.Resources {
		if resource.URI == entry {
			found = strings.Contains(resource.Source, `"minItems":2`)
		}
	}
	if !found {
		t.Fatalf("operation catalog retained stale resources: %+v", catalog.Resources)
	}
	bundle, err := edited.Bundle()
	if err != nil {
		t.Fatal(err)
	}
	again, err := ParseBundle(bundle)
	if err != nil {
		t.Fatal(err)
	}
	if openAPIProvenanceUnit(t, again, entry) != editedSource || openAPIProvenanceUnit(t, again, external) != externalSource {
		t.Fatal("rootless bundle lost resource-scoped units")
	}
	request.Body.Value = []byte(`[1]`)
	if _, _, err := again.DecodeAndValidateOpenAPIRequest("putValue", request, OpenAPILimits{}, validation.Limits{}); problemCode(err) != "native.payload" {
		t.Fatalf("rootless bundle reloaded a stale operation index: %v", err)
	}
	var wire map[string]any
	if err := json.Unmarshal(bundle, &wire); err != nil {
		t.Fatal(err)
	}
	units := wire["nativeConstraintSources"].([]any)
	changed := false
	for _, raw := range units {
		unit := raw.(map[string]any)
		if unit["URI"] == entry || unit["uri"] == entry {
			prior := unit["Source"].(string)
			next := strings.Replace(prior, "(length it >= 2)", "(length it + 1 >= 2)", 1)
			if next == prior {
				t.Fatal("bundled edited predicate was absent")
			}
			unit["Source"] = next
			changed = true
		}
	}
	if !changed {
		t.Fatalf("entry unit absent from bundle: %+v", units)
	}
	bad, err := json.Marshal(wire)
	if err != nil {
		t.Fatal(err)
	}
	if project, err := ParseBundle(bad); project != nil || problemCode(err) != "native.enforcement" {
		t.Fatalf("unrepresentable bundled edit was not rejected atomically: %v", err)
	}
}

func TestOpenAPI30NumericBoundsProjectWhileOtherFamiliesRemainOpaque(t *testing.T) {
	entry := "https://example.test/oas30.json"
	external := "https://example.test/value.yaml"
	source := strings.Replace(openAPIProvenanceOperations, "3.1.2", "3.0.4", 1)
	project, err := IngestOpenAPIOperationResources([]Resource{{URI: entry, Source: source}, {URI: external, Source: openAPIProvenanceExternalYAML}}, OpenAPIOperationIngestOptions{EntryResource: entry})
	if err != nil {
		t.Fatal(err)
	}
	constraints := project.NativeConstraints()
	if len(constraints) != 2 {
		t.Fatalf("OpenAPI 3.0 numeric subset was not isolated: %+v", constraints)
	}
	for _, item := range constraints {
		if item.Resource != external || item.Constraint.Keyword != "minimum" && item.Constraint.Keyword != "maximum" || item.Constraint.PairedKeyword == "" {
			t.Fatalf("unexpected OpenAPI 3.0 unit: %+v", item)
		}
	}
	if strings.Contains(openAPIProvenanceUnit(t, project, external), "length it") {
		t.Fatal("unsupported OpenAPI 3.0 item-count family became editable")
	}
	request := OpenAPIRequestJSON{Body: &OpenAPIMediaJSON{MediaType: "application/json", Value: []byte(`[1]`)}}
	if _, report, err := project.DecodeAndValidateOpenAPIRequest("putValue", request, OpenAPILimits{}, validation.Limits{}); err != nil || validation.StateName(report.State()) != "valid" {
		t.Fatalf("opaque OpenAPI 3.0 families stopped working: %v %+v", err, report)
	}
}
