package native

import (
    "encoding/json"
    "fmt"
    "strings"

    "goforge.dev/refine/language"
    "goforge.dev/refine/schemajson"
)

// OpenAPIDirection fixes the operation side for direction-dependent OpenAPI
// Schema Object semantics. Runtime callers never choose this value: checked
// operation bindings select it before their validators are compiled.
type OpenAPIDirection string

const OpenAPIRequest OpenAPIDirection = "request"
const OpenAPIResponse OpenAPIDirection = "response"

const openAPIDirectionWorkLimit=65536
const openAPIDirectionMaterializationBytesLimit=64<<20

// OpenAPIValidationResources returns an immutable canonical resource view for
// one checked operation direction. OAS 3.0 required lists omit readOnly
// properties in requests and writeOnly properties in responses. All property
// schemas remain present, so supplied SHOULD-NOT properties are still accepted
// and validated. OAS 3.1 and 3.2 use their unchanged canonical resource view.
func (p *Project)OpenAPIValidationResources(direction OpenAPIDirection)([]Resource,error){
    if direction!=OpenAPIRequest&&direction!=OpenAPIResponse{return nil,&Error{Code:"native.enforcement",Format:OpenAPI,Message:"OpenAPI validation direction must be request or response"}}
    if p==nil{return nil,&Error{Code:"native.project",Format:OpenAPI,Message:"a project is required"}}
    if p.Format()!=OpenAPI{return nil,&Error{Code:"native.format",Format:p.Format(),Message:"directional validation resources require an OpenAPI project"}}
    if p.openAPIOperations==nil{return nil,&Error{Code:"native.enforcement",Format:OpenAPI,Message:"checked native OpenAPI operation bindings are required"}}
    resources,err:=p.CanonicalJSONResources();if err!=nil{return nil,err};if !strings.HasPrefix(p.Version(),"3.0."){return append([]Resource(nil),resources...),nil}
    seeds:=[]ResourceSelector{};for _,operation:=range p.openAPIOperations.catalog.Operations{if direction==OpenAPIRequest{for _,part:=range operation.RequestParts{seeds=append(seeds,ResourceSelector{Resource:part.Resource,Pointer:part.Pointer})}}else{for _,response:=range operation.Responses{for _,part:=range response.Parts{seeds=append(seeds,ResourceSelector{Resource:part.Resource,Pointer:part.Pointer})}}}}
    return openAPI30DirectionalResources(resources,seeds,direction)
}

func openAPI30DirectionalResources(resources []Resource,seeds []ResourceSelector,direction OpenAPIDirection)([]Resource,error){
    docs:=map[string]schemajson.Document{};materializedBytes:=0;materializedNodes:=0;for _,resource:=range resources{if len(resource.Source)>openAPIDirectionMaterializationBytesLimit-materializedBytes{return nil,&Error{Code:"native.limit",Format:OpenAPI,Pointer:resource.URI,Message:"OpenAPI directional resource materialization exceeds the 64 MiB resource-bundle limit"}};materializedBytes+=len(resource.Source);doc,err:=schemajson.Parse([]byte(resource.Source),schemajson.Limits{});if err!=nil{return nil,wrap(OpenAPI,"native.structure",resource.URI,err)};if err:=openAPIDirectionMaterializationPreflight(doc.Root(),resource.URI,&materializedNodes);err!=nil{return nil,err};docs[resource.URI]=doc}
    roots:=map[string]any{};for _,resource:=range resources{decoder:=json.NewDecoder(strings.NewReader(resource.Source));decoder.UseNumber();var root any;if err:=decoder.Decode(&root);err!=nil{return nil,wrap(OpenAPI,"native.structure",resource.URI,err)};roots[resource.URI]=root}
    annotation:="readOnly";if direction==OpenAPIResponse{annotation="writeOnly"};pending:=[]openAPINode{};for _,seed:=range seeds{doc,ok:=docs[seed.Resource];if !ok{return nil,&Error{Code:"native.resource",Format:OpenAPI,Pointer:seed.Resource,Message:"operation Schema Object resource is absent"}};node,err:=doc.At(seed.Pointer);if err!=nil{return nil,wrap(OpenAPI,"native.resource",seed.Resource+"#"+seed.Pointer,err)};pending=append(pending,openAPINode{resource:seed.Resource,pointer:seed.Pointer,node:node})}
    seen:=map[string]bool{};work:=0;for len(pending)>0{current:=pending[len(pending)-1];pending=pending[:len(pending)-1];key:=current.resource+"#"+current.pointer;if seen[key]{continue};seen[key]=true;if err:=openAPIDirectionStep(&work,key);err!=nil{return nil,err};kind:=schemajson.KindName(current.node.Kind());if kind=="boolean"{continue};if kind!="object"{return nil,&Error{Code:"native.enforcement",Format:OpenAPI,Pointer:key,Message:"directional OpenAPI Schema Object is not an object or Boolean"}}
        if openAPI30HasComposition(current.node){ambiguous,err:=openAPI30CompositionAmbiguous(current,docs,annotation,&work);if err!=nil{return nil,err};if ambiguous{return nil,&Error{Code:"native.enforcement",Format:OpenAPI,Pointer:key,Message:"OpenAPI 3.0 direction-dependent requiredness is distributed across schema applicators and cannot yet be transformed exactly"}}}
        remove:=map[string]bool{};required,hasRequired:=current.node.Lookup("required");properties,hasProperties:=current.node.Lookup("properties");if hasRequired&&hasProperties&&schemajson.KindName(required.Kind())=="array"&&schemajson.KindName(properties.Kind())=="object"{members:=map[string]schemajson.Node{};for _,member:=range properties.Members(){name,_:=member.Key.UTF8();members[name]=member.Value};for _,item:=range required.Elements(){name,ok:=nodeString(item);if !ok{continue};property,exists:=members[name];if !exists{continue};flag,ambiguous,err:=openAPI30DirectionalProperty(openAPINode{resource:current.resource,pointer:current.pointer+"/properties/"+escapePointer(name),node:property},docs,annotation,&work);if err!=nil{return nil,err};if ambiguous{return nil,&Error{Code:"native.enforcement",Format:OpenAPI,Pointer:key+"/properties/"+escapePointer(name),Message:"OpenAPI 3.0 direction annotation is composed through an unsupported schema applicator"}};if flag{remove[name]=true}}}
        if len(remove)>0{target,err:=openAPI30At(roots[current.resource],current.pointer);if err!=nil{return nil,&Error{Code:"native.enforcement",Format:OpenAPI,Pointer:key,Message:"directional required list cannot be addressed exactly",Cause:err}};raw,ok:=target["required"].([]any);if !ok{return nil,&Error{Code:"native.enforcement",Format:OpenAPI,Pointer:key+"/required",Message:"directional required list has an unexpected representation"}};filtered:=make([]any,0,len(raw));for _,item:=range raw{name,ok:=item.(string);if !ok||!remove[name]{filtered=append(filtered,item)}};target["required"]=filtered}
        children,err:=openAPI30SchemaChildren(current,docs);if err!=nil{return nil,err};pending=append(pending,children...)
    }
    out:=make([]Resource,len(resources));for i,resource:=range resources{encoded,err:=json.Marshal(roots[resource.URI]);if err!=nil{return nil,wrap(OpenAPI,"native.enforcement",resource.URI,err)};doc,err:=schemajson.Parse(encoded,schemajson.Limits{});if err!=nil{return nil,wrap(OpenAPI,"native.enforcement",resource.URI,err)};out[i]=Resource{URI:resource.URI,Source:doc.Raw()}};return out,nil
}

// The direction transform needs a second mutable JSON tree. Count the complete
// canonical resource closure before allocating that tree, sharing the logical
// transformation work ceiling and the existing project resource-byte ceiling.
// Cardinality is checked before Members or Elements makes a defensive copy.
func openAPIDirectionMaterializationPreflight(root schemajson.Node,resource string,total *int)error{
    if *total>=openAPIDirectionWorkLimit{return &Error{Code:"native.limit",Format:OpenAPI,Pointer:resource,Message:"OpenAPI directional resource materialization exceeds the 65,536 aggregate JSON-node limit"}};*total=*total+1
    pending:=[]schemajson.Node{root};for len(pending)>0{current:=pending[len(pending)-1];pending=pending[:len(pending)-1];children:=current.MemberCount();if schemajson.KindName(current.Kind())=="array"{children=current.ElementCount()};if children>openAPIDirectionWorkLimit-*total{return &Error{Code:"native.limit",Format:OpenAPI,Pointer:resource,Message:"OpenAPI directional resource materialization exceeds the 65,536 aggregate JSON-node limit"}};*total+=children;switch schemajson.KindName(current.Kind()){case "object":for _,member:=range current.Members(){pending=append(pending,member.Value)};case "array":pending=append(pending,current.Elements()...)} };return nil
}

func openAPIDirectionStep(work *int,pointer string)error{*work=*work+1;if *work>openAPIDirectionWorkLimit{return &Error{Code:"native.limit",Format:OpenAPI,Pointer:pointer,Message:"OpenAPI directional schema transformation work limit exceeded"}};return nil}

func openAPI30HasComposition(node schemajson.Node)bool{for _,name:=range []string{"allOf","anyOf","oneOf","not","if","then","else"}{if _,ok:=node.Lookup(name);ok{return true}};return false}

func openAPI30CompositionAmbiguous(start openAPINode,docs map[string]schemajson.Document,annotation string,work *int)(bool,error){
    requiredSites:=map[string]map[string]bool{};annotationSites:=map[string]map[string]bool{};pending:=[]openAPINode{start};seen:=map[string]bool{};for len(pending)>0{current:=pending[len(pending)-1];pending=pending[:len(pending)-1];key:=current.resource+"#"+current.pointer;if seen[key]{continue};seen[key]=true;if err:=openAPIDirectionStep(work,key);err!=nil{return false,err};resolved,err:=resolveOpenAPIObject(current,docs,64);if err!=nil{return false,err};site:=resolved.resource+"#"+resolved.pointer;if required,ok:=resolved.node.Lookup("required");ok&&schemajson.KindName(required.Kind())=="array"{for _,item:=range required.Elements(){if name,ok:=nodeString(item);ok{if requiredSites[name]==nil{requiredSites[name]=map[string]bool{}};requiredSites[name][site]=true}}};if properties,ok:=resolved.node.Lookup("properties");ok&&schemajson.KindName(properties.Kind())=="object"{for _,member:=range properties.Members(){name,_:=member.Key.UTF8();flag,ambiguous,err:=openAPI30DirectionalProperty(openAPINode{resource:resolved.resource,pointer:resolved.pointer+"/properties/"+escapePointer(name),node:member.Value},docs,annotation,work);if err!=nil{return false,err};if ambiguous{return true,nil};if flag{if annotationSites[name]==nil{annotationSites[name]=map[string]bool{}};annotationSites[name][site]=true}}};next,err:=openAPI30CompositionChildren(resolved,docs);if err!=nil{return false,err};pending=append(pending,next...)}
    for name,sites:=range requiredSites{annotations:=annotationSites[name];if len(annotations)==0{continue};for site:=range sites{if !annotations[site]{return true,nil}}};return false,nil
}

func openAPI30DirectionalProperty(start openAPINode,docs map[string]schemajson.Document,annotation string,work *int)(bool,bool,error){resolved,err:=resolveOpenAPIObject(start,docs,64);if err!=nil{return false,false,err};if err:=openAPIDirectionStep(work,resolved.resource+"#"+resolved.pointer);err!=nil{return false,false,err};if flag,ok:=resolved.node.Lookup(annotation);ok&&flag.Raw()=="true"{return true,false,nil};if !openAPI30HasComposition(resolved.node){return false,false,nil};pending,err:=openAPI30CompositionChildren(resolved,docs);if err!=nil{return false,false,err};seen:=map[string]bool{};for len(pending)>0{current:=pending[len(pending)-1];pending=pending[:len(pending)-1];checked,err:=resolveOpenAPIObject(current,docs,64);if err!=nil{return false,false,err};key:=checked.resource+"#"+checked.pointer;if seen[key]{continue};seen[key]=true;if err:=openAPIDirectionStep(work,key);err!=nil{return false,false,err};if flag,ok:=checked.node.Lookup(annotation);ok&&flag.Raw()=="true"{return false,true,nil};next,err:=openAPI30CompositionChildren(checked,docs);if err!=nil{return false,false,err};pending=append(pending,next...)};return false,false,nil}

func openAPI30CompositionChildren(parent openAPINode,docs map[string]schemajson.Document)([]openAPINode,error){out:=[]openAPINode{};if ref,ok:=parent.node.Lookup("$ref");ok{raw,ok:=nodeString(ref);if !ok{return nil,&Error{Code:"native.enforcement",Format:OpenAPI,Pointer:parent.resource+"#"+parent.pointer+"/$ref",Message:"reference must be text"}};resource,pointer,err:=resolveOpenAPIReference(parent.resource,raw);if err!=nil{return nil,err};doc,ok:=docs[resource];if !ok{return nil,&Error{Code:"native.resource",Format:OpenAPI,Pointer:resource,Message:"reference is absent from explicit resources"}};node,err:=doc.At(pointer);if err!=nil{return nil,wrap(OpenAPI,"native.resource",resource+"#"+pointer,err)};out=append(out,openAPINode{resource:resource,pointer:pointer,node:node})};for _,name:=range []string{"not","if","then","else"}{if child,ok:=parent.node.Lookup(name);ok{out=append(out,openAPINode{resource:parent.resource,pointer:parent.pointer+"/"+name,node:child})}};for _,name:=range []string{"allOf","anyOf","oneOf"}{if list,ok:=parent.node.Lookup(name);ok&&schemajson.KindName(list.Kind())=="array"{for i,child:=range list.Elements(){out=append(out,openAPINode{resource:parent.resource,pointer:fmt.Sprintf("%s/%s/%d",parent.pointer,name,i),node:child})}}};return out,nil}

func openAPI30SchemaChildren(parent openAPINode,docs map[string]schemajson.Document)([]openAPINode,error){out,err:=openAPI30CompositionChildren(parent,docs);if err!=nil{return nil,err};for _,name:=range []string{"additionalProperties","propertyNames","items","additionalItems"}{if child,ok:=parent.node.Lookup(name);ok{out=append(out,openAPINode{resource:parent.resource,pointer:parent.pointer+"/"+name,node:child})}};for _,name:=range []string{"properties","patternProperties"}{if object,ok:=parent.node.Lookup(name);ok&&schemajson.KindName(object.Kind())=="object"{for _,member:=range object.Members(){memberName,_:=member.Key.UTF8();out=append(out,openAPINode{resource:parent.resource,pointer:parent.pointer+"/"+name+"/"+escapePointer(memberName),node:member.Value})}}};return out,nil}

func (p *sourceProjector)jsonDirectionalOptional(node schemajson.Node,path string)(bool,error){if p.openAPIDirection==""{return false,nil};annotation:="readOnly";if p.openAPIDirection==OpenAPIResponse{annotation="writeOnly"};current:=node;seen:=map[string]bool{};for step:=0;step<64;step++{if flag,ok:=current.Lookup(annotation);ok&&flag.Raw()=="true"{return true,nil};if openAPI30HasComposition(current){return false,&Error{Code:"native.projection",Format:OpenAPI,Pointer:path,Message:"OpenAPI 3.0 direction annotation composed through a schema applicator cannot yet be projected exactly"}};ref,ok:=current.Lookup("$ref");if !ok{return false,nil};raw,ok:=nodeString(ref);if !ok{return false,&Error{Code:"native.projection",Format:OpenAPI,Pointer:path+"/$ref",Message:"reference must be text"}};if seen[raw]{return false,&Error{Code:"native.projection",Format:OpenAPI,Pointer:path+"/$ref",Message:"cyclic directional property reference"}};seen[raw]=true;target,ok:=p.definitionNodes[raw];if !ok{return false,nil};current=target};return false,&Error{Code:"native.limit",Format:OpenAPI,Pointer:path,Message:"directional property reference depth limit exceeded"}}

// checkOpenAPIDirectionalType prevents a checked record from reintroducing a
// mandatory field whose native OAS 3.0 requiredness was removed. JSON and Map
// carriers are absence-safe; an omitted record field retains the established
// discard-extra-fields policy.
func checkOpenAPIDirectionalType(program *language.Program,typ *language.Type,schema openAPINode,docs map[string]schemajson.Document,direction OpenAPIDirection)error{if direction!=OpenAPIRequest&&direction!=OpenAPIResponse{return nil};annotation:="readOnly";if direction==OpenAPIResponse{annotation="writeOnly"};declarations:=map[string]language.TypeDecl{};for _,decl:=range program.Syntax().Types{declarations[decl.Name]=decl};work:=0;return checkOpenAPIDirectionalTypeAt(typ,schema,docs,annotation,declarations,&work,map[string]bool{})}

func checkOpenAPIDirectionalTypeAt(typ *language.Type,schema openAPINode,docs map[string]schemajson.Document,annotation string,declarations map[string]language.TypeDecl,work *int,seen map[string]bool)error{
    resolved,err:=resolveOpenAPIObject(schema,docs,64);if err!=nil{return err};key:=resolved.resource+"#"+resolved.pointer+"\x00"+language.FormatType(typ);if seen[key]{return nil};seen[key]=true;if err:=openAPIDirectionStep(work,resolved.resource+"#"+resolved.pointer);err!=nil{return err};if schemajson.KindName(resolved.node.Kind())!="object"{return nil}
    if openAPIDirectionalJSON(typ,declarations,map[string]bool{},0){return nil};mapElement,isMap:=openAPIDirectionalMap(typ,declarations,map[string]bool{},0);fields,recordErr:=openAPIDirectionalRecord(typ,declarations,map[string]bool{},0);required:=map[string]bool{};if list,ok:=resolved.node.Lookup("required");ok&&schemajson.KindName(list.Kind())=="array"{for _,item:=range list.Elements(){if name,ok:=nodeString(item);ok{required[name]=true}}};if properties,ok:=resolved.node.Lookup("properties");ok&&schemajson.KindName(properties.Kind())=="object"{for _,member:=range properties.Members(){name,_:=member.Key.UTF8();child:=openAPINode{resource:resolved.resource,pointer:resolved.pointer+"/properties/"+escapePointer(name),node:member.Value};flag,ambiguous,err:=openAPI30DirectionalProperty(child,docs,annotation,work);if err!=nil{return err};if ambiguous&&required[name]{return &Error{Code:"native.enforcement",Format:OpenAPI,Pointer:child.resource+"#"+child.pointer,Message:"OpenAPI 3.0 direction annotation is composed through an unsupported schema applicator"}};field:=fields[name];if isMap{field=mapElement};if flag&&required[name]&&!isMap{if recordErr!=nil{return &Error{Code:"native.enforcement",Format:OpenAPI,Pointer:child.resource+"#"+child.pointer,Message:"checked directional body type cannot prove optional field "+name}};if field!=nil{optional,inner:=openAPIDirectionalMaybe(field,declarations,map[string]bool{},0);if !optional{return &Error{Code:"native.enforcement",Format:OpenAPI,Pointer:child.resource+"#"+child.pointer,Message:"checked field "+name+" must be Maybe because its OpenAPI 3.0 requiredness does not apply in this direction"}};field=inner}};if field!=nil{_,field=openAPIDirectionalMaybe(field,declarations,map[string]bool{},0);if err:=checkOpenAPIDirectionalTypeAt(field,child,docs,annotation,declarations,work,seen);err!=nil{return err}}}}
    if isMap{for _,name:=range []string{"additionalProperties"}{if child,ok:=resolved.node.Lookup(name);ok{if err:=checkOpenAPIDirectionalTypeAt(mapElement,openAPINode{resource:resolved.resource,pointer:resolved.pointer+"/"+name,node:child},docs,annotation,declarations,work,seen);err!=nil{return err}}};if patterns,ok:=resolved.node.Lookup("patternProperties");ok&&schemajson.KindName(patterns.Kind())=="object"{for _,member:=range patterns.Members(){name,_:=member.Key.UTF8();if err:=checkOpenAPIDirectionalTypeAt(mapElement,openAPINode{resource:resolved.resource,pointer:resolved.pointer+"/patternProperties/"+escapePointer(name),node:member.Value},docs,annotation,declarations,work,seen);err!=nil{return err}}}}
    if items,ok:=resolved.node.Lookup("items");ok{if element,ok:=openAPIDirectionalList(typ,declarations,map[string]bool{},0);ok{if err:=checkOpenAPIDirectionalTypeAt(element,openAPINode{resource:resolved.resource,pointer:resolved.pointer+"/items",node:items},docs,annotation,declarations,work,seen);err!=nil{return err}}}
    for _,name:=range []string{"allOf","anyOf","oneOf"}{if list,ok:=resolved.node.Lookup(name);ok&&schemajson.KindName(list.Kind())=="array"{for i,child:=range list.Elements(){if err:=checkOpenAPIDirectionalTypeAt(typ,openAPINode{resource:resolved.resource,pointer:fmt.Sprintf("%s/%s/%d",resolved.pointer,name,i),node:child},docs,annotation,declarations,work,seen);err!=nil{return err}}}};return nil
}

func openAPIDirectionalRecord(typ *language.Type,declarations map[string]language.TypeDecl,seen map[string]bool,depth int)(map[string]*language.Type,error){if typ==nil||depth>128{return nil,fmt.Errorf("directional checked type resolution limit exceeded")};match typ.Form{case language.RefinedType(base,_):return openAPIDirectionalRecord(base,declarations,seen,depth+1);case language.RecordType(fields):out:=map[string]*language.Type{};for _,field:=range fields{out[field.Name]=field.Type};return out,nil;case language.NamedType(name):if seen[name]{return nil,fmt.Errorf("cyclic directional checked type alias")};seen[name]=true;if decl,ok:=declarations[name];ok&&len(decl.Parameters)==0&&decl.Body!=nil{return openAPIDirectionalRecord(decl.Body,declarations,seen,depth+1)};case language.AppliedType(_,_):name,args,ok:=jsonApplied(typ);if !ok{return nil,fmt.Errorf("unsupported directional checked type")};if (name=="Maybe"||name=="Nullable")&&len(args)==1{return openAPIDirectionalRecord(args[0],declarations,seen,depth+1)};if decl,ok:=declarations[name];ok&&decl.Body!=nil&&len(decl.Parameters)==len(args){bindings:=map[string]*language.Type{};for i,param:=range decl.Parameters{bindings[param]=args[i]};closed,err:=language.SubstituteType(decl.Body,bindings);if err!=nil{return nil,err};return openAPIDirectionalRecord(closed,declarations,seen,depth+1)};case _:};return nil,fmt.Errorf("checked type is not a record")}

func openAPIDirectionalMaybe(typ *language.Type,declarations map[string]language.TypeDecl,seen map[string]bool,depth int)(bool,*language.Type){if typ==nil||depth>128{return false,typ};match typ.Form{case language.RefinedType(base,_):return openAPIDirectionalMaybe(base,declarations,seen,depth+1);case language.AppliedType(_,_):name,args,ok:=jsonApplied(typ);if !ok{return false,typ};if name=="Maybe"&&len(args)==1{return true,args[0]};key:=name+"\x00"+language.FormatType(typ);if seen[key]{return false,typ};if decl,found:=declarations[name];found&&decl.Body!=nil&&len(decl.Parameters)==len(args){seen[key]=true;bindings:=map[string]*language.Type{};for i,param:=range decl.Parameters{bindings[param]=args[i]};closed,err:=language.SubstituteType(decl.Body,bindings);if err==nil{return openAPIDirectionalMaybe(closed,declarations,seen,depth+1)}};case language.NamedType(name):if seen[name]{return false,typ};seen[name]=true;if decl,ok:=declarations[name];ok&&len(decl.Parameters)==0&&decl.Body!=nil{return openAPIDirectionalMaybe(decl.Body,declarations,seen,depth+1)};case _:};return false,typ}

func openAPIDirectionalList(typ *language.Type,declarations map[string]language.TypeDecl,seen map[string]bool,depth int)(*language.Type,bool){if typ==nil||depth>128{return nil,false};_,typ=openAPIDirectionalMaybe(typ,declarations,map[string]bool{},0);match typ.Form{case language.RefinedType(base,_):return openAPIDirectionalList(base,declarations,seen,depth+1);case language.ListType(element):return element,true;case language.AppliedType(_,_):name,args,ok:=jsonApplied(typ);if !ok{return nil,false};if name=="Nullable"&&len(args)==1{return openAPIDirectionalList(args[0],declarations,seen,depth+1)};key:=name+"\x00"+language.FormatType(typ);if seen[key]{return nil,false};if decl,found:=declarations[name];found&&decl.Body!=nil&&len(decl.Parameters)==len(args){seen[key]=true;bindings:=map[string]*language.Type{};for i,param:=range decl.Parameters{bindings[param]=args[i]};closed,err:=language.SubstituteType(decl.Body,bindings);if err==nil{return openAPIDirectionalList(closed,declarations,seen,depth+1)}};case language.NamedType(name):if seen[name]{return nil,false};seen[name]=true;if decl,ok:=declarations[name];ok&&len(decl.Parameters)==0&&decl.Body!=nil{return openAPIDirectionalList(decl.Body,declarations,seen,depth+1)};case _:};return nil,false}

func openAPIDirectionalMap(typ *language.Type,declarations map[string]language.TypeDecl,seen map[string]bool,depth int)(*language.Type,bool){if typ==nil||depth>128{return nil,false};_,typ=openAPIDirectionalMaybe(typ,declarations,map[string]bool{},0);match typ.Form{case language.RefinedType(base,_):return openAPIDirectionalMap(base,declarations,seen,depth+1);case language.AppliedType(_,_):name,args,ok:=jsonApplied(typ);if ok&&name=="Map"&&len(args)==2{return args[1],true};if ok&&name=="Nullable"&&len(args)==1{return openAPIDirectionalMap(args[0],declarations,seen,depth+1)};if ok{key:=name+"\x00"+language.FormatType(typ);if seen[key]{return nil,false};if decl,found:=declarations[name];found&&decl.Body!=nil&&len(decl.Parameters)==len(args){seen[key]=true;bindings:=map[string]*language.Type{};for i,param:=range decl.Parameters{bindings[param]=args[i]};closed,err:=language.SubstituteType(decl.Body,bindings);if err==nil{return openAPIDirectionalMap(closed,declarations,seen,depth+1)}}};case language.NamedType(name):if seen[name]{return nil,false};seen[name]=true;if decl,ok:=declarations[name];ok&&len(decl.Parameters)==0&&decl.Body!=nil{return openAPIDirectionalMap(decl.Body,declarations,seen,depth+1)};case _:};return nil,false}

func openAPIDirectionalJSON(typ *language.Type,declarations map[string]language.TypeDecl,seen map[string]bool,depth int)bool{if typ==nil||depth>128{return false};_,typ=openAPIDirectionalMaybe(typ,declarations,map[string]bool{},0);match typ.Form{case language.RefinedType(base,_):return openAPIDirectionalJSON(base,declarations,seen,depth+1);case language.AppliedType(_,_):name,args,ok:=jsonApplied(typ);if !ok{return false};if name=="Nullable"&&len(args)==1{return openAPIDirectionalJSON(args[0],declarations,seen,depth+1)};key:=name+"\x00"+language.FormatType(typ);if seen[key]{return false};if decl,found:=declarations[name];found&&decl.Body!=nil&&len(decl.Parameters)==len(args){seen[key]=true;bindings:=map[string]*language.Type{};for i,param:=range decl.Parameters{bindings[param]=args[i]};closed,err:=language.SubstituteType(decl.Body,bindings);if err==nil{return openAPIDirectionalJSON(closed,declarations,seen,depth+1)}};case language.NamedType(name):if name=="JSON"{return true};if seen[name]{return false};seen[name]=true;if decl,ok:=declarations[name];ok&&len(decl.Parameters)==0&&decl.Body!=nil{return openAPIDirectionalJSON(decl.Body,declarations,seen,depth+1)};case _:};return false}
