package native

import (
    "encoding/json"
    "strings"
    "testing"

    "goforge.dev/refine/validation"
)

const rootlessOpenAPI=`{
  "openapi":"3.1.2","info":{"title":"Operations only","version":"1"},
  "paths":{"/items/{id}":{"post":{
    "operationId":"createItem",
    "parameters":[
      {"in":"path","name":"id","required":true,"schema":{"type":"integer","minimum":1}},
      {"in":"query","name":"tag","schema":{"type":"string","pattern":"^[a-z]+$"}}
    ],
    "requestBody":{"$ref":"https://example.test/body.json#/components/requestBodies/Create"},
    "responses":{"201":{"description":"created","content":{"application/json":{"schema":{"type":"string","minLength":2}}}}}
  }}}
}`

const rootlessBody=`{
  "openapi":"3.1.2","info":{"title":"Body","version":"1"},"paths":{},
  "components":{"requestBodies":{"Create":{"required":true,"content":{"application/json":{"schema":{"type":"object","required":["amount"],"properties":{"amount":{"type":"integer","minimum":2}},"additionalProperties":false}}}}}}
}`

func rootlessOperationProject(t *testing.T)*Project{t.Helper();project,err:=IngestOpenAPIOperationResources([]Resource{{URI:"https://example.test/api.json",Source:rootlessOpenAPI},{URI:"https://example.test/body.json",Source:rootlessBody}},OpenAPIOperationIngestOptions{EntryResource:"https://example.test/api.json"});if err!=nil{t.Fatal(err)};return project}
func validRootlessRequest()OpenAPIRequestJSON{return OpenAPIRequestJSON{Parameters:[]OpenAPIParameterJSON{{In:"path",Name:"id",Value:[]byte(`1`)},{In:"query",Name:"tag",Value:[]byte(`"abc"`)}},Body:&OpenAPIMediaJSON{MediaType:"application/json",Value:[]byte(`{"amount":3}`)}}}

func TestRootlessOpenAPIOperationsIngestAndBoundary(t *testing.T){project:=rootlessOperationProject(t);if project.Kind()!=OpenAPIOperationsProject||project.HasPayloadRoot()||project.EntryResource()!="https://example.test/api.json"||project.Root()!=(ResourceSelector{}){t.Fatalf("unexpected target: %+v",project.Target())};if !project.HasOpenAPINativeBindings(){t.Fatal("derived native bindings absent")};if project.Resources()[0].Source!=rootlessOpenAPI||project.Resources()[1].Source!=rootlessBody||project.NativeDocument().Original()!=rootlessOpenAPI{t.Fatal("original OpenAPI resources changed")};catalog,err:=project.OpenAPIOperationIndex();if err!=nil||len(catalog.Operations)!=1{t.Fatalf("unexpected operation catalog: %v %+v",err,catalog)};request:=validRootlessRequest();token,report,err:=project.DecodeAndValidateOpenAPIRequest("createItem",request,OpenAPILimits{},validation.Limits{});if err!=nil||token==nil||validation.StateName(report.State())!="valid"{t.Fatalf("valid rootless request failed: %v %+v",err,report)};request.Parameters[1].Value=[]byte(`"BAD"`);if _,_,err=project.DecodeAndValidateOpenAPIRequest("createItem",request,OpenAPILimits{},validation.Limits{});problemCode(err)!="native.payload"{t.Fatalf("native parameter pattern bypassed: %v",err)};request=validRootlessRequest();request.Body.Value=[]byte(`{"amount":1}`);if _,_,err=project.DecodeAndValidateOpenAPIRequest("createItem",request,OpenAPILimits{},validation.Limits{});problemCode(err)!="native.payload"{t.Fatalf("external native body minimum bypassed: %v",err)};response:=OpenAPIResponseJSON{Status:"201",Body:&OpenAPIMediaJSON{MediaType:"application/json",Value:[]byte(`"ok"`)}};if _,report,err=project.DecodeAndValidateOpenAPIResponse("createItem",response,token,OpenAPILimits{},validation.Limits{});err!=nil||validation.StateName(report.State())!="valid"{t.Fatalf("valid response failed: %v %+v",err,report)};response.Body.Value=[]byte(`"x"`);if _,_,err=project.DecodeAndValidateOpenAPIResponse("createItem",response,token,OpenAPILimits{},validation.Limits{});problemCode(err)!="native.payload"{t.Fatalf("native response minimum bypassed: %v",err)};if _,err=project.PayloadType();problemCode(err)!="native.root"{t.Fatalf("rootless PayloadType did not fail closed: %v",err)};if err=project.ValidateJSON([]byte(`{}`));problemCode(err)!="native.root"{t.Fatalf("rootless standalone JSON validation did not fail closed: %v",err)}}

func TestRootlessOpenAPIOperationsBundleRestoresEditedAuthority(t *testing.T){project:=rootlessOperationProject(t);requestType:=project.Metadata().OpenAPI.Operations[0].RequestType;start:=strings.Index(project.EditableSource(),"type "+requestType+" = ");if start<0{t.Fatal("derived request declaration absent")};end:=strings.Index(project.EditableSource()[start:],"\n");if end<0{t.Fatal("derived request declaration is not line terminated")};end+=start;edited:=project.EditableSource()[:end]+" where it.body.amount < 5 @code \"rootless.amount\""+project.EditableSource()[end:];project,err:=project.WithEditedSource(edited);if err!=nil{t.Fatal(err)};bundle,err:=project.Bundle();if err!=nil{t.Fatal(err)};var wire map[string]any;if err:=json.Unmarshal(bundle,&wire);err!=nil{t.Fatal(err)};if wire["version"]!=float64(2)||wire["root"]!=nil{t.Fatalf("rootless bundle encoded a payload root: %s",bundle)};target:=wire["target"].(map[string]any);if target["kind"]!="openapi-operations"||target["resource"]!="https://example.test/api.json"{t.Fatalf("unexpected bundle target: %+v",target)};again,err:=ParseBundle(bundle);if err!=nil{t.Fatal(err)};if again.EditableSource()!=edited||again.Metadata().OpenAPI.Native==nil||again.Resources()[0].Source!=rootlessOpenAPI{t.Fatal("bundle did not restore edited source, binding authority, and originals")};request:=validRootlessRequest();request.Body.Value=[]byte(`{"amount":7}`);token,report,err:=again.DecodeAndValidateOpenAPIRequest("createItem",request,OpenAPILimits{},validation.Limits{});if err!=nil||token!=nil||validation.StateName(report.State())!="invalid"{t.Fatalf("edited refinement was not restored: %v %+v",err,report)};metadata:=again.Metadata();metadata.OpenAPI.Native=nil;if _,err=again.WithMetadata(metadata);problemCode(err)!="native.metadata"{t.Fatalf("native operation authority was removable: %v",err)};tampered:=map[string]any{};for key,value:=range wire{tampered[key]=value};tampered["metadata"]=map[string]any{};tampered["editableSource"]="type Innocent = Int\n";delete(tampered,"languageEntry");delete(tampered,"languageFiles");unbound,_:=json.Marshal(tampered);if _,err=ParseBundle(unbound);problemCode(err)!="native.bundle"{t.Fatalf("bundle rederived erased native operation authority: %v",err)};wire["root"]=map[string]any{"Resource":"https://example.test/api.json","Pointer":"/components/schemas/Fake","TypeName":"Fake"};mixed,_:=json.Marshal(wire);if _,err=ParseBundle(mixed);problemCode(err)!="native.bundle"{t.Fatalf("mixed root/operation target accepted: %v",err)}}

func TestRootlessOpenAPIOperationsExportDoesNotInventSchemaRoot(t *testing.T){project:=rootlessOperationProject(t);if _,err:=project.Export(LowerOptions{Mode:Ordinary});problemCode(err)!="native.unrepresentable"{t.Fatalf("ordinary loss was not gated: %v",err)};ordinary,err:=project.Export(LowerOptions{Mode:Ordinary,AllowDocumentedLoss:true});if err!=nil{t.Fatal(err)};if ordinary.Target().Kind!=OpenAPIOperationsProject||ordinary.Root()!=(ResourceSelector{})||len(ordinary.Losses())==0{t.Fatalf("unexpected ordinary export: %+v",ordinary.Target())};var object map[string]any;if err:=json.Unmarshal([]byte(ordinary.Resources()[0].Source),&object);err!=nil{t.Fatal(err)};if _,exists:=object["components"];exists{t.Fatal("ordinary rootless export invented components")};if _,exists:=object["x-refine"];exists{t.Fatal("ordinary rootless export retained executable annotation")};info:=object["info"].(map[string]any);if !strings.Contains(info["description"].(string),"OpenAPI operation refinement bindings"){t.Fatal("ordinary export lacks self-contained operation explanation")};refined,err:=project.Export(LowerOptions{Mode:Refined});if err!=nil{t.Fatal(err)};object=map[string]any{};if err:=json.Unmarshal([]byte(refined.Resources()[0].Source),&object);err!=nil{t.Fatal(err)};if _,exists:=object["components"];exists{t.Fatal("refined rootless export invented components")};annotation:=object["x-refine"].(map[string]any);if _,exists:=annotation["root"];exists{t.Fatal("refined rootless export invented annotation root")};again,err:=IngestOpenAPIOperationResources(refined.Resources(),OpenAPIOperationIngestOptions{EntryResource:refined.EntryResource()});if err!=nil||!again.HasOpenAPINativeBindings(){t.Fatalf("refined rootless export did not reingest: %v",err)}}

func TestRootlessOpenAPIOperationsRejectBadInputsAndKeepRootedV1(t *testing.T){if _,err:=(*Project)(nil).Bundle();problemCode(err)!="native.project"{t.Fatalf("nil project bundle: %v",err)};if _,err:=(&Project{}).Bundle();problemCode(err)!="native.project"{t.Fatalf("zero project bundle: %v",err)};valid:=rootlessOperationProject(t);invalid:=*valid;invalid.target=ProjectTarget{Kind:"unknown"};if _,err:=invalid.Bundle();problemCode(err)!="native.project"{t.Fatalf("invalid target bundle: %v",err)};if _,err:=IngestOpenAPIOperations([]byte(rootlessOpenAPI),OpenAPIOperationIngestOptions{EntryResource:"relative"});problemCode(err)!="native.resource"{t.Fatalf("relative entry accepted: %v",err)};if _,err:=IngestOpenAPIOperationResources([]Resource{{URI:"https://example.test/api.json",Source:rootlessOpenAPI}},OpenAPIOperationIngestOptions{EntryResource:"https://example.test/api.json"});err==nil{t.Fatal("missing explicit external resource accepted")};annotated:=strings.Replace(rootlessOpenAPI,"\n}",`,"x-refine":{"source":"type Bad = {","root":"Fake"}\n}`,1);if _,err:=IngestOpenAPIOperationResources([]Resource{{URI:"https://example.test/api.json",Source:annotated},{URI:"https://example.test/body.json",Source:rootlessBody}},OpenAPIOperationIngestOptions{EntryResource:"https://example.test/api.json"});err==nil{t.Fatal("bad annotated source/root accepted")}
    rooted,err:=IngestProject(JSONSchema,[]byte(`{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"integer"}`),ProjectOptions{ResourceID:"https://example.test/root.json",Root:ResourceSelector{TypeName:"Root"}});if err!=nil{t.Fatal(err)};bundle,err:=rooted.Bundle();if err!=nil{t.Fatal(err)};var wire map[string]any;if err:=json.Unmarshal(bundle,&wire);err!=nil{t.Fatal(err)};if wire["version"]!=float64(1)||wire["root"]==nil||wire["target"]!=nil{t.Fatalf("rooted v1 bundle shape changed: %s",bundle)};again,err:=ParseBundle(bundle);if err!=nil||again.Kind()!=PayloadProject||again.Root().TypeName!="Root"{t.Fatalf("rooted v1 no longer reloads: %v",err)}}
