package native

import (
    "strings"
    "testing"

    "goforge.dev/refine/language"
    "goforge.dev/refine/provenance"
    "goforge.dev/refine/schemajson"
)

func dependentRequiredPredicate(t *testing.T,keyword string)string{t.Helper();origin,err:=provenance.DiscoverJSONSchema([]byte(`{"type":"object","dependentRequired":`+keyword+`}`),schemajson.Limits{});if err!=nil{t.Fatal(err)};for _,constraint:=range origin.Constraints(){if constraint.Keyword=="dependentRequired"{return constraint.Predicate}};t.Fatal("dependentRequired unit absent");return ""}

func TestDependentRequiredLoweringKeepsOnlyCanonicalLosslessObjectAuthority(t *testing.T){
    predicate:=dependentRequiredPredicate(t,`{"a":["b"]}`);source:="type Values = Map String JSON where "+predicate;program,err:=language.Compile(source);if err!=nil{t.Fatal(err)};payload,err:=program.PayloadType("Values");if err!=nil{t.Fatal(err)}
    for _,format:=range []Format{JSONSchema,OpenAPI}{lowered,err:=LowerPayload(format,payload,LowerOptions{Mode:Ordinary,OpenAPIVersion:"3.1.2"});if err!=nil{t.Fatal(err)};if !strings.Contains(lowered.String(),`"dependentRequired"`){t.Fatalf("canonical object implication lost in %s: %s",format,lowered.String())}}
    for _,bad:=range []string{strings.Replace(source,"Map String JSON","Map String Int",1),source+"\nmember :: String -> Map String JSON -> Bool\nmember _ _ = True\n","type Values = Map String JSON where member \"a\" it"}{program,err:=language.Compile(bad);if err!=nil{t.Fatal(err)};payload,err:=program.PayloadType("Values");if err!=nil{t.Fatal(err)};if _,err:=LowerPayload(JSONSchema,payload,LowerOptions{Mode:Ordinary});problemCode(err)!="native.unrepresentable"{t.Fatalf("unsupported implication acquired native authority: %s: %v",bad,err)}}
}

func TestDependentRequiredNativeEditsAreAtomicIsolatedAndRetainOriginals(t *testing.T){
    uri:="https://example.test/dependencies";original:=`{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"known":{"type":"integer"}},"minProperties":1,"maxProperties":6,"dependentRequired":{"a":["b"]}}`;project,err:=IngestProject(JSONSchema,[]byte(original),ProjectOptions{ResourceID:uri,Root:ResourceSelector{TypeName:"Values"}});if err!=nil{t.Fatal(err)};dependency:=constraintByKeyword(t,project,"dependentRequired");minimum:=constraintByKeyword(t,project,"minProperties");if dependency.Scope!="((Map String) JSON)"{t.Fatalf("dependency acquired lossy domain: %+v",dependency)}
    if err:=project.ValidateJSON([]byte(`{"a":null}`));problemCode(err)!="native.payload"{t.Fatalf("null-valued trigger or discarded extra escaped native presence: %v",err)};if err:=project.ValidateJSON([]byte(`{"a":null,"b":null}`));err!=nil{t.Fatal(err)}
    source:=project.ResourceConstraintSource(uri);changedSource:=strings.Replace(source,dependency.Predicate,dependentRequiredPredicate(t,`{"a":["c"]}`),1);edited,err:=project.WithEditedNativeConstraintSource(uri,changedSource);if err!=nil{t.Fatal(err)};if err:=edited.ValidateJSON([]byte(`{"a":null,"b":null}`));problemCode(err)!="native.payload"{t.Fatalf("dependency edit retained old target: %v",err)};if err:=edited.ValidateJSON([]byte(`{"a":null,"c":null}`));err!=nil{t.Fatal(err)};if _,err:=edited.RecoverResourceNative(uri,dependency.Name,changedSource);err==nil{t.Fatal("edited keyword retained exact original bijection")};if got,err:=edited.RecoverResourceNative(uri,minimum.Name,changedSource);err!=nil||got!="1"{t.Fatalf("adjacent cardinality lost recovery: %q %v",got,err)}
    bundle,err:=edited.Bundle();if err!=nil{t.Fatal(err)};again,err:=ParseBundle(bundle);if err!=nil{t.Fatal(err)};if err:=again.ValidateJSON([]byte(`{"a":null,"b":null}`));problemCode(err)!="native.payload"{t.Fatalf("bundle used stale dependency: %v",err)};exported,err:=edited.Export(LowerOptions{Mode:Refined});if err!=nil{t.Fatal(err)};reingested,err:=IngestProjectResources(JSONSchema,exported.Resources(),ProjectOptions{Root:exported.Root(),Metadata:exported.Metadata()});if err!=nil{t.Fatal(err)};if err:=reingested.ValidateJSON([]byte(`{"a":null,"b":null}`));problemCode(err)!="native.payload"{t.Fatalf("export used stale dependency: %v",err)}
    removedSource:=strings.Replace(source,"type "+dependency.Name+" = "+dependency.Scope+" where "+dependency.Predicate+"\n","",1);removed,err:=project.WithEditedNativeConstraintSource(uri,removedSource);if err!=nil{t.Fatal(err)};if err:=removed.ValidateJSON([]byte(`{"a":null}`));err!=nil{t.Fatal(err)};if err:=removed.ValidateJSON([]byte(`{}`));problemCode(err)!="native.payload"{t.Fatalf("removal erased independent cardinality: %v",err)}
    for _,bad:=range []string{strings.Replace(source,dependency.Predicate,`member "a" it`,1),source+"\nmember :: String -> Map String JSON -> Bool\nmember _ _ = True\n"}{if candidate,err:=project.WithEditedNativeConstraintSource(uri,bad);candidate!=nil||problemCode(err)!="native.enforcement"{t.Fatalf("unsafe dependency edit partially applied: %v",err)}};if project.Resources()[0].Source!=original{t.Fatal("dependency edit mutated original")};if err:=project.ValidateJSON([]byte(`{"a":null,"b":null}`));err!=nil{t.Fatal(err)}
}

func TestDependentRequiredOpenAPIEditsUseCatalogPhysicalPositions(t *testing.T){
    uri:="https://example.test/dependency-api";source:=`{"openapi":"3.1.2","info":{"title":"Dependencies","version":"1"},"paths":{},"components":{"schemas":{"Root":{"$ref":"https://logical.test/value#value"},"Value":{"$id":"https://logical.test/value","$anchor":"value","type":"object","minProperties":1,"dependentRequired":{"a":["b"]}}}}}`;project,err:=IngestProject(OpenAPI,[]byte(source),ProjectOptions{ResourceID:uri,Root:ResourceSelector{TypeName:"Root"}});if err!=nil{t.Fatal(err)};dependency:=openAPIProvenanceConstraint(t,project,uri,"dependentRequired");if dependency.SchemaPointer!="/components/schemas/Value"{t.Fatalf("dependency lost physical scope: %+v",dependency)};unit:=openAPIProvenanceUnit(t,project,uri);edited,err:=project.WithEditedNativeConstraintSource(uri,strings.Replace(unit,dependency.Predicate,dependentRequiredPredicate(t,`{"a":["c"]}`),1));if err!=nil{t.Fatal(err)};if err:=edited.ValidateJSON([]byte(`{"a":null,"b":null}`));problemCode(err)!="native.payload"{t.Fatalf("logical target retained stale dependency: %v",err)};if err:=edited.ValidateJSON([]byte(`{"a":null,"c":null}`));err!=nil{t.Fatal(err)};bundle,err:=edited.Bundle();if err!=nil{t.Fatal(err)};again,err:=ParseBundle(bundle);if err!=nil{t.Fatal(err)};if err:=again.ValidateJSON([]byte(`{"a":null,"b":null}`));problemCode(err)!="native.payload"{t.Fatalf("catalog reconstruction lost dependency: %v",err)}
}
