// Code generated by goplus from regex.gp. DO NOT EDIT.
//goplus:v v0.28.0

package native

import (
	"fmt"
	"time"

	"github.com/dlclark/regexp2"
	"github.com/getkin/kin-openapi/openapi3"
	jsonoracle "github.com/santhosh-tekuri/jsonschema/v6"
)

// regexp2 is substantially closer to JSON Schema/OpenAPI's ECMA-262 pattern
// syntax than Go regexp. It is still an implementation oracle, not a proof of
// parity with every edition/host behavior of ECMAScript RegExp.
type ecmaRegexp struct{ compiled *regexp2.Regexp }
type regexEvaluationFailure struct{ cause error }

func (r *ecmaRegexp) MatchString(input string) bool {
	matched, err := r.compiled.MatchString(input)
	if err != nil {
		panic(regexEvaluationFailure{cause: err})
	}
	return matched
}
func (r *ecmaRegexp) String() string { return r.compiled.String() }

var ecmaMatchTimeout = 250 * time.Millisecond

func compileECMA(source string) (*ecmaRegexp, error) {
	compiled, err := regexp2.Compile(source, regexp2.ECMAScript)
	if err != nil {
		return nil, err
	}
	compiled.MatchTimeout = ecmaMatchTimeout
	return &ecmaRegexp{compiled: compiled}, nil
}
func jsonRegexp(source string) (jsonoracle.Regexp, error)        { return compileECMA(source) }
func openAPIRegexp(source string) (openapi3.RegexMatcher, error) { return compileECMA(source) }

func recoverRegexEvaluation(format Format, failure *error) {
	if caught := recover(); caught != nil {
		if problem, ok := caught.(regexEvaluationFailure); ok {
			*failure = &Error{Code: "native.enforcement", Format: format, Message: "ECMA-262 regular expression evaluation did not complete", Cause: fmt.Errorf("regular expression engine: %w", problem.cause)}
			return
		}
		panic(caught)
	}
}
