// Code generated by goplus from release_policy_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package native

import (
	"bytes"
	"strings"
	"testing"

	"goforge.dev/refine/language"
)

func nativePolicyFixture() *language.ReleasePolicy {
	return &language.ReleasePolicy{Version: 1, Overrides: []language.CompatibilityApproval{{ReleaseComparison: language.ReleaseComparison{Baseline: "1.0.0", BaselineSHA256: strings.Repeat("1", 64), SnapshotSHA256: strings.Repeat("2", 64), Direction: "backward"}, Reason: "reviewed exact native and generated surfaces"}}}
}
func appendNativePolicy(t *testing.T, bundle []byte, policy *language.ReleasePolicy) []byte {
	t.Helper()
	result, err := AppendBundleReleasePolicy(bundle, policy)
	if err != nil {
		t.Fatal(err)
	}
	return result
}

func TestNativeBundleReleasePolicyIsSchemaAuthorityAndMasksExactly(t *testing.T) {
	project, err := IngestProject(JSONSchema, []byte(`{"type":"integer"}`), ProjectOptions{Root: ResourceSelector{TypeName: "Root"}})
	if err != nil {
		t.Fatal(err)
	}
	base, err := project.Bundle()
	if err != nil {
		t.Fatal(err)
	}
	annotated := appendNativePolicy(t, base, nativePolicyFixture())
	masked, policy, err := ReleaseComparisonBundle(annotated)
	if err != nil || !bytes.Equal(masked, base) || policy == nil || len(policy.Overrides) != 1 {
		t.Fatalf("exact native release masking failed: %v %+v", err, policy)
	}
	restored, err := ParseBundle(annotated)
	if err != nil {
		t.Fatal(err)
	}
	copy := restored.ReleasePolicy()
	copy.Overrides[0].Reason = "forged"
	if restored.ReleasePolicy().Overrides[0].Reason == "forged" {
		t.Fatal("mutable release policy escaped project")
	}
	again, err := restored.Bundle()
	if err != nil {
		t.Fatal(err)
	}
	remasked, roundTrip, err := ReleaseComparisonBundle(again)
	if err != nil || !bytes.Equal(remasked, base) || roundTrip.Overrides[0].Reason != policy.Overrides[0].Reason {
		t.Fatalf("bundle round trip changed authority or masked identity: %v", err)
	}
	encoded, _ := language.FormatReleasePolicyJSON(nativePolicyFixture())
	nonfinal := bytes.Replace(base, []byte(",\n  \"metadata\""), append(append([]byte(",\n  \"releasePolicy\": "), encoded...), []byte(",\n  \"metadata\"")...), 1)
	if _, err := ParseBundle(nonfinal); problemCode(err) != "native.bundle" {
		t.Fatalf("non-final policy accepted: %v", err)
	}
	wrongCase := bytes.Replace(annotated, []byte(`"releasePolicy"`), []byte(`"ReleasePolicy"`), 1)
	if _, err := ParseBundle(wrongCase); problemCode(err) != "native.bundle" {
		t.Fatalf("case-folded policy carrier accepted: %v", err)
	}
}
