// Code generated by goplus from resources.gp. DO NOT EDIT.
//goplus:v v0.28.0

package native

import (
	"context"
	"errors"
	"fmt"
	"net/url"
	"sort"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	avro "github.com/hamba/avro/v2"
	yaml "github.com/oasdiff/yaml3"
	jsonoracle "github.com/santhosh-tekuri/jsonschema/v6"
	"goforge.dev/refine/language"
	"goforge.dev/refine/provenance"
	"goforge.dev/refine/schemajson"
)

// IngestProjectResources validates references using only the explicitly
// supplied, ordered resource set. It never falls back to filesystem or network.
func IngestProjectResources(format Format, resources []Resource, options ProjectOptions) (*Project, error) {
	options, err := normalizeProjectOptions(format, options)
	if err != nil {
		return nil, err
	}
	if len(resources) == 0 {
		return nil, &Error{Code: "native.resource", Format: format, Message: "at least one resource is required"}
	}
	if len(resources) > 10000 {
		return nil, &Error{Code: "native.resource", Format: format, Message: "at most 10,000 resources may be supplied"}
	}
	byURI := make(map[string][]byte)
	ordered := make([]Resource, len(resources))
	total := 0
	for i, resource := range resources {
		if len(resource.Source) > (64<<20)-total {
			return nil, &Error{Code: "native.resource", Format: format, Message: "resource bundle exceeds 64 MiB"}
		}
		total += len(resource.Source)
		parsed, err := url.Parse(resource.URI)
		if err != nil || !parsed.IsAbs() || parsed.Fragment != "" {
			return nil, &Error{Code: "native.resource", Format: format, Pointer: resource.URI, Message: "resource URI must be absolute without a fragment"}
		}
		if _, duplicate := byURI[resource.URI]; duplicate {
			return nil, &Error{Code: "native.resource", Format: format, Pointer: resource.URI, Message: "duplicate resource URI"}
		}
		byURI[resource.URI] = []byte(resource.Source)
		ordered[i] = Resource{URI: resource.URI, Source: resource.Source}
	}
	mainBytes, ok := byURI[options.Root.Resource]
	if !ok {
		return nil, &Error{Code: "native.root", Format: format, Pointer: options.Root.Resource, Message: "root resource is not in the explicit resource set"}
	}
	options.ResourceID = options.Root.Resource
	var document *Document
	source := ""
	selectedAnnotation := Annotation{}
	hasSelectedAnnotation := false
	switch format {
	case JSONSchema:
		document, err = validateJSONResources(byURI, options.Root)
		if err == nil {
			if annotated, _, ok := rootAnnotation(document, options.Root); ok {
				source = annotated
			} else {
				source, err = projectJSONResources(ordered, options.Root)
				if err == nil && document.ConstraintSource() != "" {
					source += "\n" + document.ConstraintSource()
				}
			}
		}
	case OpenAPI:
		document, err = validateOpenAPIResources(byURI, options.Root)
		if err == nil {
			selectedAnnotation, hasSelectedAnnotation, err = selectedOpenAPISchemaAnnotation(document, byURI, options.Root)
			if err == nil && hasSelectedAnnotation {
				source = selectedAnnotation.Source
			} else if err == nil {
				source, err = projectJSONResourceRoot(byURI, options.Root, true)
			}
		}
	case Avro:
		if options.Root.Pointer != "" {
			return nil, &Error{Code: "native.root", Format: Avro, Pointer: options.Root.Pointer, Message: "Avro root selector pointer must be empty"}
		}
		document, source, err = validateAvroResources(ordered, options.Root)
	default:
		return nil, &Error{Code: "native.format", Format: format, Message: "unsupported project format"}
	}
	if err != nil {
		return nil, err
	}
	if format != OpenAPI {
		selectedAnnotation, hasSelectedAnnotation = selectedRootAnnotation(document, options.Root)
	}
	if hasSelectedAnnotation {
		source = selectedAnnotation.Source
		if selectedAnnotation.Root != options.Root.TypeName {
			source, err = appendNativeSourceDeclarations(source, "type "+options.Root.TypeName+" = "+selectedAnnotation.Root)
			if err != nil {
				return nil, wrap(format, "native.projection", options.Root.Pointer, err)
			}
		}
		options.Metadata, err = mergeAnnotationMetadata(format, options.Metadata, selectedAnnotation)
		if err != nil {
			return nil, err
		}
	}
	nativeOrigins := map[string]nativeConstraintOrigin{}
	avroUnits := map[string]string{}
	if format == Avro {
		nativeOrigins, avroUnits = discoverAvroConstraintOrigins(ordered)
		if !hasSelectedAnnotation {
			source, err = appendAvroConstraintDeclarations(source, ordered, avroUnits)
			if err != nil {
				return nil, err
			}
		}
	}
	program, err := language.Compile(source)
	if err != nil {
		return nil, wrap(format, "native.projection", "", err)
	}
	if _, err := program.PayloadType(options.Root.TypeName); err != nil {
		return nil, wrap(format, "native.root", options.Root.Pointer, err)
	}
	if err := validateMetadata(program, options.Metadata); err != nil {
		return nil, wrap(format, "native.metadata", "", err)
	}
	origins := make(map[string]*provenance.JSONSchema)
	units := make(map[string]string)
	linked := make(map[string]bool)
	if format == JSONSchema {
		for _, resource := range ordered {
			origin, e := provenance.DiscoverJSONSchema([]byte(resource.Source), schemajson.Limits{})
			if e != nil {
				return nil, wrap(JSONSchema, "native.provenance", resource.URI, e)
			}
			origins[resource.URI] = origin
			if canonical := origin.ConstraintSource(); canonical != "" {
				units[resource.URI] = canonical
			}
		}
		if rootOrigin := origins[options.Root.Resource]; rootOrigin != nil && nativeConstraintUnitsUnchanged(rootOrigin, source) {
			linked[options.Root.Resource] = true
		}
	}
	for resource, unit := range avroUnits {
		units[resource] = unit
		linked[resource] = nativeConstraintUnitsUnchanged(nativeOrigins[resource], source)
	}
	_ = mainBytes
	project := &Project{document: document, root: options.Root, source: source, program: program, metadata: copyMetadata(options.Metadata), resources: ordered, jsonOrigins: origins, nativeOrigins: nativeOrigins, nativeUnitSources: units, nativeUnitsInEditable: linked}
	if format == OpenAPI {
		installOpenAPIConstraintOrigins(project, options.Root.Resource)
	}
	return validateProject(project)
}

func sortedResourceURIs(resources map[string][]byte) []string {
	uris := make([]string, 0, len(resources))
	for uri := range resources {
		uris = append(uris, uri)
	}
	sort.Strings(uris)
	return uris
}
func validateJSONResources(resources map[string][]byte, root ResourceSelector) (document *Document, failure error) {
	defer recoverRegexEvaluation(JSONSchema, &failure)
	scope := newRegexScope()
	compiler := newOfflineJSONCompiler()
	compiler.DefaultDraft(jsonoracle.Draft2020)
	compiler.UseRegexpEngine(scope.jsonRegexp)
	var rootDoc schemajson.Document
	numericExpansion := 0
	ordered := make([]Resource, 0, len(resources))
	for _, uri := range sortedResourceURIs(resources) {
		input := resources[uri]
		ordered = append(ordered, Resource{URI: uri, Source: string(input)})
		doc, err := schemajson.Parse(input, schemajson.Limits{})
		if err != nil {
			return nil, wrap(JSONSchema, "native.syntax", uri, err)
		}
		if err := scalarJSONBudget(doc.Root(), "", DefaultNumericExpansion, &numericExpansion); err != nil {
			return nil, wrap(JSONSchema, "native.encoding", uri, err)
		}
		if err := checkJSONDraft(doc.Root(), uri); err != nil {
			return nil, err
		}
		value, err := jsonoracle.UnmarshalJSON(strings.NewReader(doc.Raw()))
		if err != nil {
			return nil, wrap(JSONSchema, "native.syntax", uri, err)
		}
		if err := compiler.AddResource(uri, value); err != nil {
			return nil, wrap(JSONSchema, "native.resource", uri, err)
		}
		if uri == root.Resource {
			rootDoc = doc
		}
	}
	catalog, err := newJSONProjectionCatalog(ordered)
	if err != nil {
		return nil, err
	}
	compiler.UseLoader(jsonProjectionLoader{catalog: catalog})
	location := root.Resource
	if root.Pointer != "" {
		location += "#" + root.Pointer
	}
	if err := scope.run(JSONSchema, true, func() error { _, compileErr := compiler.Compile(location); return compileErr }); err != nil {
		return nil, wrapRegexResult(JSONSchema, "native.structure", root.Pointer, err)
	}
	annotations, err := jsonSchemaAnnotations(rootDoc.Root())
	if err != nil {
		return nil, err
	}
	origins, err := provenance.DiscoverJSONSchema([]byte(rootDoc.Raw()), schemajson.Limits{})
	if err != nil {
		return nil, wrap(JSONSchema, "native.provenance", "", err)
	}
	return &Document{format: JSONSchema, version: "2020-12", raw: rootDoc.Raw(), annotations: annotations, jsonProvenance: origins}, nil
}

func validateOpenAPIResources(resources map[string][]byte, root ResourceSelector) (document *Document, failure error) {
	if !strings.HasPrefix(root.Pointer, "/components/schemas/") {
		return nil, &Error{Code: "native.root", Format: OpenAPI, Pointer: root.Pointer, Message: "selected OpenAPI root must be a Schema Object under /components/schemas"}
	}
	return validateOpenAPIDocumentResources(resources, root.Resource)
}

// validateOpenAPIDocumentResources validates a complete OpenAPI entry document
// and its explicit offline closure without inventing or requiring a payload
// Schema Object. Operation projects use this document-level oracle.
func validateOpenAPIDocumentResources(resources map[string][]byte, entryResource string) (document *Document, failure error) {
	defer recoverRegexEvaluation(OpenAPI, &failure)
	main, exists := resources[entryResource]
	if !exists {
		return nil, &Error{Code: "native.resource", Format: OpenAPI, Pointer: entryResource, Message: "OpenAPI entry resource is not in the explicit resource set"}
	}
	l, _ := limits(Options{})
	var yamlRoot *yaml.Node
	yamlRoots := []*yaml.Node{}
	numericExpansion := 0
	for _, uri := range sortedResourceURIs(resources) {
		input := resources[uri]
		node, err := parseYAMLWithNumericExpansion(input, l, &numericExpansion)
		if err != nil {
			return nil, wrap(OpenAPI, "native.syntax", uri, err)
		}
		yamlRoots = append(yamlRoots, node)
		if strings.HasPrefix(strings.TrimSpace(string(input)), "{") {
			doc, err := schemajson.Parse(input, l)
			if err != nil {
				return nil, wrap(OpenAPI, "native.syntax", uri, err)
			}
			if err := scalarJSONText(doc.Root(), ""); err != nil {
				return nil, wrap(OpenAPI, "native.encoding", uri, err)
			}
		}
		if uri == entryResource {
			yamlRoot = node
		}
	}
	version, ok := declaredOpenAPIVersion(yamlRoot)
	if !ok || !openAPIVersion.MatchString(version) || !supportedOpenAPI(version) {
		return nil, &Error{Code: "native.version", Format: OpenAPI, Pointer: "/openapi", Message: "supported published versions are 3.0.0-3.0.4, 3.1.0-3.1.2, and 3.2.0-3.2.1"}
	}
	oracleInput, err := openAPIOracleInput(main, yamlRoot, version)
	if err != nil {
		return nil, wrap(OpenAPI, "native.structure", "", err)
	}
	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(_ *openapi3.Loader, target *url.URL) ([]byte, error) {
		copy := *target
		copy.Fragment = ""
		if data, ok := resources[copy.String()]; ok {
			return append([]byte(nil), data...), nil
		}
		return nil, fmt.Errorf("resource %s is not in the explicit bundle", copy.String())
	}
	location, _ := url.Parse(entryResource)
	parsed, err := loader.LoadFromDataWithPath(oracleInput, location)
	if err != nil {
		return nil, wrap(OpenAPI, "native.structure", "", err)
	}
	scope := newRegexScope()
	if err := scope.run(OpenAPI, false, func() error {
		validationOptions := []openapi3.ValidationOption{openapi3.SetRegexCompiler(scope.openAPIRegexp)}
		if strings.HasPrefix(version, "3.0.") {
			validationOptions = append(validationOptions, openapi3.AllowExtraSiblingFields(openAPI30IgnoredRefSiblingFields(yamlRoots...)...))
		}
		return parsed.Validate(context.Background(), validationOptions...)
	}); err != nil {
		return nil, wrapRegexResult(OpenAPI, "native.structure", "", err)
	}
	annotations, err := yamlRootAnnotation(yamlRoot)
	if err != nil {
		return nil, err
	}
	return &Document{format: OpenAPI, version: version, raw: string(main), annotations: annotations}, nil
}

func validateAvroResources(resources []Resource, root ResourceSelector) (*Document, string, error) {
	cache := &avro.SchemaCache{}
	sources := []string{}
	documents := make([]schemajson.Document, len(resources))
	schemas := make([]avro.Schema, len(resources))
	index := newRawAvroDefaults()
	var main schemajson.Document
	for i, resource := range resources {
		doc, err := schemajson.Parse([]byte(resource.Source), schemajson.Limits{})
		if err != nil {
			return nil, "", wrap(Avro, "native.syntax", resource.URI, err)
		}
		if err := scalarJSON(doc.Root(), ""); err != nil {
			return nil, "", wrap(Avro, "native.encoding", resource.URI, err)
		}
		schema, err := parseAvroStructure([]byte(resource.Source), cache)
		if err != nil {
			return nil, "", wrap(Avro, "native.structure", resource.URI, err)
		}
		documents[i] = doc
		schemas[i] = schema
		index.walk(doc.Root(), schema, resource.URI, "")
	}
	matcher := newAvroDefaultMatcher(index, schemajson.DefaultNodes, schemajson.DefaultBytes)
	for i, resource := range resources {
		doc := documents[i]
		schema := schemas[i]
		if err := auditAvroDefaultsWithMatcher(doc.Root(), schema, "", matcher); err != nil {
			var limited *Error
			if errors.As(err, &limited) && limited.Code == "native.limit" {
				pointer := resource.URI
				if limited.Pointer != "" {
					pointer += "#" + limited.Pointer
				}
				return nil, "", &Error{Code: "native.limit", Format: Avro, Pointer: pointer, Message: limited.Message, Cause: err}
			}
			return nil, "", wrap(Avro, "native.default", resource.URI, err)
		}
		selector := ResourceSelector{TypeName: fmt.Sprintf("NativeResource%d", i+1)}
		if resource.URI == root.Resource {
			selector.TypeName = root.TypeName
			main = doc
		}
		projected, err := projectAvro(doc, selector)
		if err != nil {
			return nil, "", err
		}
		sources = append(sources, projected)
	}
	if main.Raw() == "" {
		return nil, "", &Error{Code: "native.root", Format: Avro, Message: "root resource missing"}
	}
	annotations, err := avroAnnotations(main.Root())
	if err != nil {
		return nil, "", err
	}
	return &Document{format: Avro, version: "1.12.0", raw: main.Raw(), annotations: annotations}, strings.Join(sources, "\n"), nil
}

// projectJSONResourceRoot resolves a chain of root-level external $ref values
// for the editable projection. Nested external references remain an explicit
// projection error; all are nevertheless validated and retained in the bundle.
func projectJSONResourceRoot(resources map[string][]byte, selector ResourceSelector, openAPI bool) (string, error) {
	current := selector
	visited := make(map[string]bool)
	for {
		key := current.Resource + "#" + current.Pointer
		if visited[key] {
			return "", &Error{Code: "native.resource", Pointer: key, Message: "cyclic root reference"}
		}
		visited[key] = true
		input, ok := resources[current.Resource]
		if !ok {
			return "", &Error{Code: "native.resource", Pointer: current.Resource, Message: "referenced resource is absent"}
		}
		var doc schemajson.Document
		var err error
		if openAPI {
			l, _ := limits(Options{})
			yamlRoot, e := parseYAML(input, l)
			if e != nil {
				return "", e
			}
			doc, err = yamlToJSONDocument(yamlRoot)
		} else {
			doc, err = schemajson.Parse(input, schemajson.Limits{})
		}
		if err != nil {
			return "", err
		}
		node, err := doc.At(current.Pointer)
		if err != nil {
			return "", err
		}
		refNode, hasRef := node.Lookup("$ref")
		if !hasRef {
			current.TypeName = selector.TypeName
			return projectJSON(doc, current, openAPI)
		}
		ref, ok := nodeString(refNode)
		if !ok {
			return "", errors.New("reference must be a string")
		}
		base, _ := url.Parse(current.Resource)
		relative, err := url.Parse(ref)
		if err != nil {
			return "", err
		}
		resolved := base.ResolveReference(relative)
		pointer := ""
		if resolved.Fragment != "" {
			if !strings.HasPrefix(resolved.Fragment, "/") {
				return "", &Error{Code: "native.projection", Format: pFormat(openAPI), Pointer: ref, Message: "anchor references are retained but not yet projected; use a JSON Pointer root reference"}
			}
			pointer = resolved.Fragment
		}
		resolved.Fragment = ""
		current = ResourceSelector{Resource: resolved.String(), Pointer: pointer, TypeName: selector.TypeName}
	}
}
func pFormat(openAPI bool) Format {
	if openAPI {
		return OpenAPI
	}
	return JSONSchema
}
