// GoPlus-authored offline Java artifact inventory tests.
package release

import (
    "archive/zip"
    "bytes"
    "encoding/binary"
    "fmt"
    "os"
    "reflect"
    "strings"
    "testing"
)

type javaArtifactTestEntry struct{name string;content []byte;mode os.FileMode;method uint16}
func buildJavaArtifact(entries []javaArtifactTestEntry)([]byte,error){var output bytes.Buffer;writer:=zip.NewWriter(&output);for _,entry:=range entries{header:=&zip.FileHeader{Name:entry.name,Method:entry.method};if entry.mode!=0{header.SetMode(entry.mode)};stream,err:=writer.CreateHeader(header);if err!=nil{return nil,err};if _,err=stream.Write(entry.content);err!=nil{return nil,err}};if err:=writer.Close();err!=nil{return nil,err};return output.Bytes(),nil}
func mustJavaArtifact(t *testing.T,entries []javaArtifactTestEntry)[]byte{t.Helper();result,err:=buildJavaArtifact(entries);if err!=nil{t.Fatal(err)};return result}
func javaArtifactIssueText(result JavaArtifactVerification)string{parts:=[]string{};for _,issue:=range result.Issues(){parts=append(parts,issue.Code+": "+issue.Message)};return strings.Join(parts,"; ")}

func TestInspectJavaArtifactAndVerifyPublishedLedger(t *testing.T){
    first:=[]byte{0xca,0xfe,0xba,0xbe,1};second:=[]byte{0xca,0xfe,0xba,0xbe,2};jar:=mustJavaArtifact(t,[]javaArtifactTestEntry{{"META-INF/",nil,os.ModeDir|0755,zip.Store},{"META-INF/MANIFEST.MF",[]byte("Manifest-Version: 1.0\n"),0644,zip.Deflate},{"example/Zed.class",second,0644,zip.Deflate},{"example/Alpha.class",first,0644,zip.Store}})
    inventory,err:=InspectJavaArtifact(jar,JavaArtifactLimits{});if err!=nil{t.Fatal(err)};if inventory.ArtifactSHA256()!=Digest(jar)||inventory.EntryCount()!=4||inventory.ExpandedBytes()!=int64(len(first)+len(second)+len("Manifest-Version: 1.0\n")){t.Fatalf("wrong immutable inventory summary: %s %d %d",inventory.ArtifactSHA256(),inventory.EntryCount(),inventory.ExpandedBytes())};classes:=inventory.Classes();want:=[]PublicationFile{{Path:"example/Alpha.class",SHA256:Digest(first)},{Path:"example/Zed.class",SHA256:Digest(second)}};if !reflect.DeepEqual(classes,want){t.Fatalf("wrong sorted classes: %+v",classes)};classes[0].Path="mutated";if inventory.Classes()[0].Path!="example/Alpha.class"{t.Fatal("class inventory accessor aliases internal state")}
    record:=publicationRecord(PublicationPublished);record.ArtifactSHA256=Digest(jar);record.Classes=[]PublicationFile{want[0]};record.InventorySHA256=PublicationInventoryDigest(record);ledger:=&PublicationLedger{Version:1,GroupID:"dev.example",ArtifactID:"models",Records:[]PublicationRecord{record}};verified:=VerifyPublishedArtifact(ledger,inventory);if !verified.Ready()||verified.Unknown()||len(verified.Issues())!=0{t.Fatalf("exact actual JAR evidence rejected: %s",javaArtifactIssueText(verified))};copied:=verified.Issues();copied=append(copied,Issue{Code:"caller"});if len(verified.Issues())!=0{t.Fatal("verification issues accessor aliases internal state")}
    absent:=VerifyPublishedArtifact(ledger,nil);if absent.Ready()||!absent.Unknown()||!strings.Contains(javaArtifactIssueText(absent),"actual published JAR bytes are unavailable"){t.Fatalf("missing artifact evidence was not unknown: %+v",absent)};unpublished:=publicationRecord(PublicationUnpublished);unpublishedLedger:=&PublicationLedger{Version:1,GroupID:"dev.example",ArtifactID:"models",Records:[]PublicationRecord{unpublished}};if result:=VerifyPublishedArtifact(unpublishedLedger,nil);!result.Ready()||result.Unknown(){t.Fatalf("unpublished record required invented artifact evidence: %+v",result)}
}

func TestVerifyPublishedArtifactRejectsByteClaimMismatchesWithoutABIClaim(t *testing.T){
    content:=[]byte("class bytes");jar:=mustJavaArtifact(t,[]javaArtifactTestEntry{{"example/Order.class",content,0644,zip.Store}});inventory,err:=InspectJavaArtifact(jar,JavaArtifactLimits{});if err!=nil{t.Fatal(err)}
    cases:=[]struct{name string;mutate func(*PublicationRecord);want string}{{"artifact",func(record *PublicationRecord){record.ArtifactSHA256=Digest([]byte("other jar"))},"artifact SHA-256"},{"missing class",func(record *PublicationRecord){record.Classes=[]PublicationFile{{Path:"example/Missing.class",SHA256:Digest(content)}}},"absent from the supplied JAR"},{"different class bytes",func(record *PublicationRecord){record.Classes=[]PublicationFile{{Path:"example/Order.class",SHA256:Digest([]byte("different"))}}},"not an ABI conclusion"}}
    for _,tc:=range cases{t.Run(tc.name,func(t *testing.T){record:=publicationRecord(PublicationPublished);record.ArtifactSHA256=Digest(jar);record.Classes=[]PublicationFile{{Path:"example/Order.class",SHA256:Digest(content)}};tc.mutate(&record);record.InventorySHA256=PublicationInventoryDigest(record);ledger:=&PublicationLedger{Version:1,GroupID:"dev.example",ArtifactID:"models",Records:[]PublicationRecord{record}};result:=VerifyPublishedArtifact(ledger,inventory);if result.Ready()||result.Unknown()||!strings.Contains(javaArtifactIssueText(result),tc.want){t.Fatalf("claim mismatch accepted or misclassified: %+v %s",result,javaArtifactIssueText(result))}})}
}

func markJavaArtifactFlags(input []byte,want uint16)[]byte{output:=append([]byte(nil),input...);for offset:=0;offset+10<len(output);offset++{signature:=binary.LittleEndian.Uint32(output[offset:]);field:=-1;if signature==0x04034b50{field=offset+6}else if signature==0x02014b50{field=offset+8};if field>=0{flags:=binary.LittleEndian.Uint16(output[field:]);binary.LittleEndian.PutUint16(output[field:],flags|want)}};return output}
func corruptJavaArtifactContent(input,content []byte)[]byte{output:=append([]byte(nil),input...);at:=bytes.Index(output,content);if at>=0{output[at]^=0xff};return output}
func alterJavaArtifactEnd(input []byte,entries uint16,directorySize uint32)[]byte{output:=append([]byte(nil),input...);for at:=len(output)-22;at>=0;at--{if binary.LittleEndian.Uint32(output[at:])==0x06054b50{binary.LittleEndian.PutUint16(output[at+8:],entries);binary.LittleEndian.PutUint16(output[at+10:],entries);if directorySize!=0{binary.LittleEndian.PutUint32(output[at+12:],directorySize)};return output}};return output}

func TestInspectJavaArtifactRejectsUnsafeArchivesAndLimits(t *testing.T){
    ordinary:=mustJavaArtifact(t,[]javaArtifactTestEntry{{"example/One.class",[]byte("1234"),0644,zip.Store},{"example/Two.class",[]byte("56"),0644,zip.Store}});one:=func(name string,content []byte,mode os.FileMode)[]byte{return mustJavaArtifact(t,[]javaArtifactTestEntry{{name,content,mode,zip.Store}})};duplicate:=func(a,b string)[]byte{return mustJavaArtifact(t,[]javaArtifactTestEntry{{a,[]byte("a"),0644,zip.Store},{b,[]byte("b"),0644,zip.Store}})};crcContent:=[]byte("unique-crc-content")
    cases:=[]struct{name string;jar []byte;limits JavaArtifactLimits;want string}{
        {"input bytes",ordinary,JavaArtifactLimits{InputBytes:int64(len(ordinary)-1)},"input byte limit"},{"entries",ordinary,JavaArtifactLimits{Entries:1},"entry limit"},{"expanded total",ordinary,JavaArtifactLimits{ExpandedBytes:5},"expanded byte limit"},{"expanded entry",ordinary,JavaArtifactLimits{EntryBytes:3},"expanded byte limit"},{"name",ordinary,JavaArtifactLimits{NameBytes:8},"name byte limit"},
        {"declared entries preflight",alterJavaArtifactEnd(ordinary,2,0),JavaArtifactLimits{Entries:1},"entry limit"},{"directory count consistency",alterJavaArtifactEnd(ordinary,1,0),JavaArtifactLimits{},"count does not match"},{"ZIP64 preflight",alterJavaArtifactEnd(ordinary,0xffff,0),JavaArtifactLimits{},"ZIP64"},{"directory range",alterJavaArtifactEnd(ordinary,2,1),JavaArtifactLimits{},"central directory range"},
        {"duplicate",duplicate("example/A.class","example/A.class"),JavaArtifactLimits{},"duplicate portable"},{"ASCII case fold",duplicate("example/A.class","EXAMPLE/a.CLASS"),JavaArtifactLimits{},"duplicate portable"},{"Unicode case fold",duplicate("example/K.class","example/K.class"),JavaArtifactLimits{},"duplicate portable"},{"dot",one(".",nil,0644),JavaArtifactLimits{},"unsafe"},{"dot dot",one("..",nil,0644),JavaArtifactLimits{},"unsafe"},{"traversal",one("../A.class",[]byte("a"),0644),JavaArtifactLimits{},"unsafe"},{"absolute",one("/A.class",[]byte("a"),0644),JavaArtifactLimits{},"unsafe"},{"backslash",one("example\\A.class",[]byte("a"),0644),JavaArtifactLimits{},"unsafe"},{"colon",one("example/A.class:stream",[]byte("a"),0644),JavaArtifactLimits{},"unsafe"},{"symlink",one("example/link",[]byte("target"),os.ModeSymlink|0777),JavaArtifactLimits{},"symbolic-link"},{"nonregular",one("example/pipe",nil,os.ModeNamedPipe|0600),JavaArtifactLimits{},"nonregular"},{"traditional encryption",markJavaArtifactFlags(one("example/A.class",[]byte("a"),0644),1),JavaArtifactLimits{},"encrypted or masked"},{"strong encryption",markJavaArtifactFlags(one("example/A.class",[]byte("a"),0644),1<<6),JavaArtifactLimits{},"encrypted or masked"},{"masked header",markJavaArtifactFlags(one("example/A.class",[]byte("a"),0644),1<<13),JavaArtifactLimits{},"encrypted or masked"},{"truncated",ordinary[:len(ordinary)-7],JavaArtifactLimits{},"malformed JAR"},{"crc",corruptJavaArtifactContent(one("example/A.class",crcContent,0644),crcContent),JavaArtifactLimits{},"malformed JAR entry"},
    }
    for _,tc:=range cases{t.Run(tc.name,func(t *testing.T){if _,err:=InspectJavaArtifact(tc.jar,tc.limits);err==nil||!strings.Contains(err.Error(),tc.want){t.Fatalf("unsafe/malformed JAR accepted or wrong error: %v",err)}})}
    for _,limits:=range []JavaArtifactLimits{{InputBytes:-1},{Entries:-1},{ExpandedBytes:-1},{EntryBytes:-1},{NameBytes:-1},{InputBytes:javaArtifactHardLimits.InputBytes+1}}{if _,err:=InspectJavaArtifact(ordinary,limits);err==nil{t.Fatalf("invalid limits accepted: %+v",limits)}}
}

func TestJavaArtifactInventoryDeterministicProperties(t *testing.T){
    for n:=1;n<=64;n++{leftName:=fmt.Sprintf("pkg/C%03d.class",65-n);rightName:=fmt.Sprintf("pkg/C%03d.class",n);left:=[]byte(strings.Repeat("L",n));right:=[]byte(strings.Repeat("R",65-n));jar:=mustJavaArtifact(t,[]javaArtifactTestEntry{{leftName,left,0644,zip.Deflate},{rightName,right,0644,zip.Store}});first,err:=InspectJavaArtifact(jar,JavaArtifactLimits{Entries:2,ExpandedBytes:65,EntryBytes:64,NameBytes:32});if err!=nil{t.Fatal(err)};second,err:=InspectJavaArtifact(jar,JavaArtifactLimits{Entries:2,ExpandedBytes:65,EntryBytes:64,NameBytes:32});if err!=nil{t.Fatal(err)};if first.ArtifactSHA256()!=second.ArtifactSHA256()||!reflect.DeepEqual(first.Classes(),second.Classes())||first.ExpandedBytes()!=65{t.Fatalf("inventory is nondeterministic for %d",n)};for _,class:=range first.Classes(){if !class.SHA256.Valid(){t.Fatalf("invalid class digest for %d: %+v",n,class)}}}
}

func FuzzInspectJavaArtifact(f *testing.F){valid,_:=buildJavaArtifact([]javaArtifactTestEntry{{"A.class",[]byte{0xca,0xfe,0xba,0xbe},0644,zip.Store}});f.Add(valid);f.Add([]byte("not a jar"));f.Add(valid[:len(valid)-3]);f.Fuzz(func(t *testing.T,input []byte){inventory,err:=InspectJavaArtifact(input,JavaArtifactLimits{InputBytes:1<<16,Entries:128,ExpandedBytes:1<<16,EntryBytes:1<<14,NameBytes:256});if err!=nil{return};if !inventory.ArtifactSHA256().Valid()||inventory.EntryCount()>128||inventory.ExpandedBytes()>1<<16{t.Fatalf("successful bounded inventory is invalid: %s %d %d",inventory.ArtifactSHA256(),inventory.EntryCount(),inventory.ExpandedBytes())};last:="";for _,class:=range inventory.Classes(){if class.Path<=last||!class.SHA256.Valid(){t.Fatalf("noncanonical successful class inventory: %+v",inventory.Classes())};last=class.Path}})}
