// Code generated by goplus from maven_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

// GoPlus-authored Maven policy tests.
package release

import "testing"

func TestMavenNoCodegenPolicy(t *testing.T) {
	current := Version{Major: 3, Minor: 4, Patch: 5}
	tests := []struct {
		name           string
		previous, next []GeneratedVersion
		other          ArtifactChange
		want           Version
		kind           ArtifactChange
	}{
		{"ordinary regeneration", nil, nil, ArtifactPatchChange, Version{Major: 3, Minor: 4, Patch: 6}, ArtifactPatchChange},
		{"remove current family major", []GeneratedVersion{{"foo", Version{Major: 2}, true}}, []GeneratedVersion{{"foo", Version{Major: 2, Minor: 1}, true}}, ArtifactNoChange, Version{Major: 3, Minor: 5}, ArtifactFeatureChange},
		{"remove prior family major", []GeneratedVersion{{"foo", Version{Major: 1}, true}, {"foo", Version{Major: 2}, true}}, []GeneratedVersion{{"foo", Version{Major: 1}, false}, {"foo", Version{Major: 2}, true}}, ArtifactNoChange, Version{Major: 4}, ArtifactBreakingChange},
		{"new no-codegen major still makes old prior", []GeneratedVersion{{"foo", Version{Major: 2}, true}}, []GeneratedVersion{{"foo", Version{Major: 3}, false}}, ArtifactNoChange, Version{Major: 4}, ArtifactBreakingChange},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			in := MavenPlanningInput{Current: current, PreviouslyPublished: tc.previous, Next: tc.next, OtherChange: tc.other, Intended: vp(tc.want)}
			got := PlanMavenVersion(in)
			if !got.Ready || got.Suggested != tc.want || got.RequiredChange != tc.kind {
				t.Fatalf("got %+v", got)
			}
		})
	}
}
func TestMavenUnchangedHasNoBlindPatch(t *testing.T) {
	got := PlanMavenVersion(MavenPlanningInput{Current: Version{Major: 1}})
	if !got.Ready || !got.NoPendingVersion || got.Suggested != (Version{Major: 1}) {
		t.Fatalf("got %+v", got)
	}
}

func TestMavenRejectsNegativeSchemaVersionsWithoutUsingThem(t *testing.T) {
	cases := []MavenPlanningInput{{Current: Version{Major: 1}, PreviouslyPublished: []GeneratedVersion{{Family: "foo", SchemaVersion: Version{Major: -1}, Generated: true}}, Next: []GeneratedVersion{{Family: "foo", SchemaVersion: Version{Major: 1}, Generated: false}}}, {Current: Version{Major: 1}, PreviouslyPublished: []GeneratedVersion{{Family: "foo", SchemaVersion: Version{Major: 1}, Generated: true}}, Next: []GeneratedVersion{{Family: "foo", SchemaVersion: Version{Major: 1, Minor: -1}, Generated: false}}}}
	for i, input := range cases {
		got := PlanMavenVersion(input)
		if got.Ready || len(got.Issues) == 0 || got.Issues[0].Code != "maven.schema_version" {
			t.Fatalf("case %d accepted invalid schema version: %+v", i, got)
		}
		if i == 0 && len(got.Removed) != 0 {
			t.Fatalf("invalid historical evidence influenced removal planning: %+v", got)
		}
	}
}
