// Code generated by goplus from openapi_positions.gp. DO NOT EDIT.
//goplus:v v0.28.0

package provenance

import (
	"fmt"
	"io"
	"net/url"
	"strconv"
	"strings"

	yaml "github.com/oasdiff/yaml3"
	"goforge.dev/refine/language"
	"goforge.dev/refine/schemajson"
)

func openAPIChild(parent openAPIProvenanceNode, name string) (openAPIProvenanceNode, bool) {
	child, ok := yamlMappingValue(parent.node, name)
	if !ok {
		return openAPIProvenanceNode{}, false
	}
	return openAPIProvenanceNode{doc: parent.doc, node: child, pointer: parent.pointer + "/" + pointerKeyOpenAPI(name)}, true
}
func openAPIMappingChildren(parent openAPIProvenanceNode) ([]openAPIProvenanceNode, error) {
	if parent.node.Kind != yaml.MappingNode {
		return nil, &Error{Code: "openapi.position", Pointer: parent.doc.resource.URI + "#" + parent.pointer, Message: "expected an object"}
	}
	out := []openAPIProvenanceNode{}
	for i := 0; i < len(parent.node.Content); i += 2 {
		name := parent.node.Content[i].Value
		if strings.HasPrefix(name, "x-") {
			continue
		}
		out = append(out, openAPIProvenanceNode{doc: parent.doc, node: parent.node.Content[i+1], pointer: parent.pointer + "/" + pointerKeyOpenAPI(name)})
	}
	return out, nil
}
func openAPISequenceChildren(parent openAPIProvenanceNode) ([]openAPIProvenanceNode, error) {
	if parent.node.Kind != yaml.SequenceNode {
		return nil, &Error{Code: "openapi.position", Pointer: parent.doc.resource.URI + "#" + parent.pointer, Message: "expected an array"}
	}
	out := make([]openAPIProvenanceNode, len(parent.node.Content))
	for i, item := range parent.node.Content {
		out[i] = openAPIProvenanceNode{doc: parent.doc, node: item, pointer: fmt.Sprintf("%s/%d", parent.pointer, i)}
	}
	return out, nil
}

func (w *openAPIProvenanceWalker) walkDocument(root openAPIProvenanceNode, dialect string, depth int) error {
	if err := w.enter(root, "document", depth); err != nil {
		if err == io.EOF {
			return nil
		}
		return err
	}
	if root.node.Kind != yaml.MappingNode {
		return &Error{Code: "openapi.position", Pointer: root.doc.resource.URI, Message: "OpenAPI document must be an object"}
	}
	if components, ok := openAPIChild(root, "components"); ok {
		if err := w.walkComponents(components, dialect, depth+1); err != nil {
			return err
		}
	}
	if paths, ok := openAPIChild(root, "paths"); ok {
		children, err := openAPIMappingChildren(paths)
		if err != nil {
			return err
		}
		for _, path := range children {
			if err := w.walkPathItem(path, dialect, depth+1); err != nil {
				return err
			}
		}
	}
	if !w.openAPI30 {
		if webhooks, ok := openAPIChild(root, "webhooks"); ok {
			children, err := openAPIMappingChildren(webhooks)
			if err != nil {
				return err
			}
			for _, hook := range children {
				if err := w.walkPathItem(hook, dialect, depth+1); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func (w *openAPIProvenanceWalker) walkComponents(node openAPIProvenanceNode, dialect string, depth int) error {
	if node.node.Kind != yaml.MappingNode {
		return &Error{Code: "openapi.position", Pointer: node.doc.resource.URI + "#" + node.pointer, Message: "components must be an object"}
	}
	if schemas, ok := openAPIChild(node, "schemas"); ok {
		children, err := openAPIMappingChildren(schemas)
		if err != nil {
			return err
		}
		root := openAPIProvenanceNode{doc: node.doc, node: node.doc.root, pointer: ""}
		for _, child := range children {
			if err := w.walkSchema(child, dialect, node.doc.resource.URI, root, depth+1); err != nil {
				return err
			}
		}
	}
	kinds := []struct {
		name string
		walk func(openAPIProvenanceNode, string, int) error
	}{{"parameters", w.walkParameter}, {"headers", w.walkHeader}, {"requestBodies", w.walkRequestBody}, {"responses", w.walkResponse}, {"callbacks", w.walkCallback}}
	if !w.openAPI30 {
		kinds = append(kinds, struct {
			name string
			walk func(openAPIProvenanceNode, string, int) error
		}{"pathItems", w.walkPathItem})
	}
	if w.openAPI32 {
		kinds = append(kinds, struct {
			name string
			walk func(openAPIProvenanceNode, string, int) error
		}{"mediaTypes", w.walkMediaType})
	}
	for _, kind := range kinds {
		group, ok := openAPIChild(node, kind.name)
		if !ok {
			continue
		}
		children, err := openAPIMappingChildren(group)
		if err != nil {
			return err
		}
		for _, child := range children {
			if err := kind.walk(child, dialect, depth+1); err != nil {
				return err
			}
		}
	}
	return nil
}

func (w *openAPIProvenanceWalker) walkPathItem(node openAPIProvenanceNode, dialect string, depth int) error {
	resolved, err := w.resolveWrapper(node, depth)
	if err != nil {
		return err
	}
	node = resolved
	if err := w.enter(node, "path-item", depth); err != nil {
		if err == io.EOF {
			return nil
		}
		return err
	}
	if node.node.Kind != yaml.MappingNode {
		return &Error{Code: "openapi.position", Pointer: node.doc.resource.URI + "#" + node.pointer, Message: "Path Item must be an object"}
	}
	if parameters, ok := openAPIChild(node, "parameters"); ok {
		items, err := openAPISequenceChildren(parameters)
		if err != nil {
			return err
		}
		for _, item := range items {
			if err := w.walkParameter(item, dialect, depth+1); err != nil {
				return err
			}
		}
	}
	methods := []string{"get", "put", "post", "delete", "options", "head", "patch", "trace"}
	if !w.openAPI30 {
		methods = append(methods, "query")
	}
	for _, method := range methods {
		if operation, ok := openAPIChild(node, method); ok {
			if err := w.walkOperation(operation, dialect, depth+1); err != nil {
				return err
			}
		}
	}
	if w.openAPI32 {
		if additional, ok := openAPIChild(node, "additionalOperations"); ok {
			items, err := openAPIMappingChildren(additional)
			if err != nil {
				return err
			}
			for _, operation := range items {
				if err := w.walkOperation(operation, dialect, depth+1); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func (w *openAPIProvenanceWalker) walkOperation(node openAPIProvenanceNode, dialect string, depth int) error {
	if err := w.enter(node, "operation", depth); err != nil {
		if err == io.EOF {
			return nil
		}
		return err
	}
	if node.node.Kind != yaml.MappingNode {
		return &Error{Code: "openapi.position", Pointer: node.doc.resource.URI + "#" + node.pointer, Message: "Operation must be an object"}
	}
	if parameters, ok := openAPIChild(node, "parameters"); ok {
		items, err := openAPISequenceChildren(parameters)
		if err != nil {
			return err
		}
		for _, item := range items {
			if err := w.walkParameter(item, dialect, depth+1); err != nil {
				return err
			}
		}
	}
	if body, ok := openAPIChild(node, "requestBody"); ok {
		if err := w.walkRequestBody(body, dialect, depth+1); err != nil {
			return err
		}
	}
	if responses, ok := openAPIChild(node, "responses"); ok {
		items, err := openAPIMappingChildren(responses)
		if err != nil {
			return err
		}
		for _, item := range items {
			if err := w.walkResponse(item, dialect, depth+1); err != nil {
				return err
			}
		}
	}
	if callbacks, ok := openAPIChild(node, "callbacks"); ok {
		items, err := openAPIMappingChildren(callbacks)
		if err != nil {
			return err
		}
		for _, item := range items {
			if err := w.walkCallback(item, dialect, depth+1); err != nil {
				return err
			}
		}
	}
	return nil
}

func (w *openAPIProvenanceWalker) walkParameter(node openAPIProvenanceNode, dialect string, depth int) error {
	resolved, err := w.resolveWrapper(node, depth)
	if err != nil {
		return err
	}
	node = resolved
	if err := w.enter(node, "parameter", depth); err != nil {
		if err == io.EOF {
			return nil
		}
		return err
	}
	return w.walkSchemaOrContent(node, dialect, depth+1)
}
func (w *openAPIProvenanceWalker) walkHeader(node openAPIProvenanceNode, dialect string, depth int) error {
	resolved, err := w.resolveWrapper(node, depth)
	if err != nil {
		return err
	}
	node = resolved
	if err := w.enter(node, "header", depth); err != nil {
		if err == io.EOF {
			return nil
		}
		return err
	}
	return w.walkSchemaOrContent(node, dialect, depth+1)
}
func (w *openAPIProvenanceWalker) walkSchemaOrContent(node openAPIProvenanceNode, dialect string, depth int) error {
	schema, hasSchema := openAPIChild(node, "schema")
	content, hasContent := openAPIChild(node, "content")
	if hasSchema && hasContent {
		return &Error{Code: "openapi.position", Pointer: node.doc.resource.URI + "#" + node.pointer, Message: "schema and content cannot both supply the same parameter/header schema"}
	}
	if hasSchema {
		root := openAPIProvenanceNode{doc: node.doc, node: node.doc.root, pointer: ""}
		return w.walkSchema(schema, dialect, node.doc.resource.URI, root, depth)
	}
	if hasContent {
		return w.walkContent(content, dialect, depth)
	}
	return nil
}
func (w *openAPIProvenanceWalker) walkRequestBody(node openAPIProvenanceNode, dialect string, depth int) error {
	resolved, err := w.resolveWrapper(node, depth)
	if err != nil {
		return err
	}
	if err := w.enter(resolved, "request-body", depth); err != nil {
		if err == io.EOF {
			return nil
		}
		return err
	}
	content, ok := openAPIChild(resolved, "content")
	if !ok {
		return nil
	}
	return w.walkContent(content, dialect, depth+1)
}
func (w *openAPIProvenanceWalker) walkResponse(node openAPIProvenanceNode, dialect string, depth int) error {
	resolved, err := w.resolveWrapper(node, depth)
	if err != nil {
		return err
	}
	if err := w.enter(resolved, "response", depth); err != nil {
		if err == io.EOF {
			return nil
		}
		return err
	}
	if headers, ok := openAPIChild(resolved, "headers"); ok {
		items, err := openAPIMappingChildren(headers)
		if err != nil {
			return err
		}
		for _, item := range items {
			if err := w.walkHeader(item, dialect, depth+1); err != nil {
				return err
			}
		}
	}
	if content, ok := openAPIChild(resolved, "content"); ok {
		return w.walkContent(content, dialect, depth+1)
	}
	return nil
}
func (w *openAPIProvenanceWalker) walkContent(node openAPIProvenanceNode, dialect string, depth int) error {
	items, err := openAPIMappingChildren(node)
	if err != nil {
		return err
	}
	for _, media := range items {
		if err := w.walkMediaType(media, dialect, depth+1); err != nil {
			return err
		}
	}
	return nil
}
func (w *openAPIProvenanceWalker) walkMediaType(node openAPIProvenanceNode, dialect string, depth int) error {
	resolved, err := w.resolveWrapper(node, depth)
	if err != nil {
		return err
	}
	node = resolved
	if err := w.enter(node, "media-type", depth); err != nil {
		if err == io.EOF {
			return nil
		}
		return err
	}
	root := openAPIProvenanceNode{doc: node.doc, node: node.doc.root, pointer: ""}
	if schema, ok := openAPIChild(node, "schema"); ok {
		if err := w.walkSchema(schema, dialect, node.doc.resource.URI, root, depth+1); err != nil {
			return err
		}
	}
	if w.openAPI32 {
		if schema, ok := openAPIChild(node, "itemSchema"); ok {
			if err := w.walkSchema(schema, dialect, node.doc.resource.URI, root, depth+1); err != nil {
				return err
			}
		}
	}
	if encodings, ok := openAPIChild(node, "encoding"); ok {
		items, err := openAPIMappingChildren(encodings)
		if err != nil {
			return err
		}
		for _, encoding := range items {
			if err := w.walkEncoding(encoding, dialect, depth+1); err != nil {
				return err
			}
		}
	}
	if w.openAPI32 {
		if encodings, ok := openAPIChild(node, "prefixEncoding"); ok {
			items, err := openAPISequenceChildren(encodings)
			if err != nil {
				return err
			}
			for _, encoding := range items {
				if err := w.walkEncoding(encoding, dialect, depth+1); err != nil {
					return err
				}
			}
		}
		if encoding, ok := openAPIChild(node, "itemEncoding"); ok {
			if err := w.walkEncoding(encoding, dialect, depth+1); err != nil {
				return err
			}
		}
	}
	return nil
}
func (w *openAPIProvenanceWalker) walkEncoding(node openAPIProvenanceNode, dialect string, depth int) error {
	if err := w.enter(node, "encoding", depth); err != nil {
		if err == io.EOF {
			return nil
		}
		return err
	}
	if headers, ok := openAPIChild(node, "headers"); ok {
		items, err := openAPIMappingChildren(headers)
		if err != nil {
			return err
		}
		for _, header := range items {
			if err := w.walkHeader(header, dialect, depth+1); err != nil {
				return err
			}
		}
	}
	if !w.openAPI32 {
		return nil
	}
	if encodings, ok := openAPIChild(node, "encoding"); ok {
		items, err := openAPIMappingChildren(encodings)
		if err != nil {
			return err
		}
		for _, encoding := range items {
			if err := w.walkEncoding(encoding, dialect, depth+1); err != nil {
				return err
			}
		}
	}
	if encodings, ok := openAPIChild(node, "prefixEncoding"); ok {
		items, err := openAPISequenceChildren(encodings)
		if err != nil {
			return err
		}
		for _, encoding := range items {
			if err := w.walkEncoding(encoding, dialect, depth+1); err != nil {
				return err
			}
		}
	}
	if encoding, ok := openAPIChild(node, "itemEncoding"); ok {
		return w.walkEncoding(encoding, dialect, depth+1)
	}
	return nil
}
func (w *openAPIProvenanceWalker) walkCallback(node openAPIProvenanceNode, dialect string, depth int) error {
	resolved, err := w.resolveWrapper(node, depth)
	if err != nil {
		return err
	}
	if err := w.enter(resolved, "callback", depth); err != nil {
		if err == io.EOF {
			return nil
		}
		return err
	}
	items, err := openAPIMappingChildren(resolved)
	if err != nil {
		return err
	}
	for _, item := range items {
		if err := w.walkPathItem(item, dialect, depth+1); err != nil {
			return err
		}
	}
	return nil
}

func (w *openAPIProvenanceWalker) resolveWrapper(node openAPIProvenanceNode, depth int) (openAPIProvenanceNode, error) {
	seen := map[string]bool{}
	for {
		ref, ok := openAPIChild(node, "$ref")
		if !ok {
			return node, nil
		}
		if node.node.Kind != yaml.MappingNode {
			return node, &Error{Code: "openapi.reference", Pointer: node.doc.resource.URI + "#" + node.pointer, Message: "reference wrapper must be an object"}
		}
		for i := 0; i < len(node.node.Content); i += 2 {
			name := node.node.Content[i].Value
			if name == "$ref" || name == "summary" || name == "description" || strings.HasPrefix(name, "x-") {
				continue
			}
			return node, &Error{Code: "openapi.reference", Pointer: node.doc.resource.URI + "#" + node.pointer, Message: "structural siblings of a wrapper $ref require merge semantics and are not projected"}
		}
		key := node.doc.resource.URI + "#" + node.pointer
		if seen[key] {
			return node, &Error{Code: "openapi.reference", Pointer: key, Message: "cyclic wrapper reference"}
		}
		seen[key] = true
		raw, err := yamlScalarString(ref.node)
		if err != nil {
			return node, &Error{Code: "openapi.reference", Pointer: node.doc.resource.URI + "#" + ref.pointer, Message: "$ref must be a string"}
		}
		node, err = w.resolve(node, raw, node.doc.resource.URI, depth+len(seen))
		if err != nil {
			return node, err
		}
	}
}
func (w *openAPIProvenanceWalker) resolve(node openAPIProvenanceNode, raw, base string, depth int) (openAPIProvenanceNode, error) {
	baseRoot := openAPIProvenanceNode{doc: node.doc, node: node.doc.root, pointer: ""}
	target, _, _, err := w.resolveSchema(node, raw, base, baseRoot, depth)
	return target, err
}
func (w *openAPIProvenanceWalker) resolveSchema(node openAPIProvenanceNode, raw, base string, baseRoot openAPIProvenanceNode, depth int) (openAPIProvenanceNode, string, openAPIProvenanceNode, error) {
	w.refs++
	if w.refs > openAPIProvenanceRefs {
		return node, base, baseRoot, &Error{Code: "openapi.limit", Pointer: node.doc.resource.URI + "#" + node.pointer, Message: "reference traversal limit exceeded"}
	}
	baseURI, err := url.Parse(base)
	if err != nil {
		return node, base, baseRoot, err
	}
	relative, err := url.Parse(raw)
	if err != nil {
		return node, base, baseRoot, &Error{Code: "openapi.reference", Pointer: node.doc.resource.URI + "#" + node.pointer, Message: "invalid reference URI"}
	}
	resolved := baseURI.ResolveReference(relative)
	fragment := resolved.Fragment
	resolved.Fragment = ""
	resource := resolved.String()
	target, targetBase, targetRoot := baseRoot, base, baseRoot
	if resource != base {
		targetDoc, ok := w.docs[resource]
		if !ok {
			return node, base, baseRoot, &Error{Code: "openapi.reference", Pointer: node.doc.resource.URI + "#" + node.pointer, Message: "reference target is absent from explicit resources; references to another schema's logical $id are not yet indexed"}
		}
		target = openAPIProvenanceNode{doc: targetDoc, node: targetDoc.root, pointer: ""}
		targetBase = resource
		targetRoot = target
	}
	if fragment != "" {
		if !strings.HasPrefix(fragment, "/") {
			return node, base, baseRoot, &Error{Code: "openapi.reference", Pointer: node.doc.resource.URI + "#" + node.pointer, Message: "anchors and non-JSON-Pointer fragments are not supported by exact provenance"}
		}
		targetNode, pointerErr := yamlAt(target.node, fragment)
		if pointerErr != nil {
			return node, base, baseRoot, &Error{Code: "openapi.reference", Pointer: node.doc.resource.URI + "#" + node.pointer, Message: pointerErr.Error()}
		}
		target.node = targetNode
		target.pointer = target.pointer + fragment
	}
	return target, targetBase, targetRoot, nil
}

func yamlAt(root *yaml.Node, pointer string) (*yaml.Node, error) {
	if pointer == "" {
		return root, nil
	}
	tokens, err := openAPIPointerTokens(pointer)
	if err != nil {
		return nil, err
	}
	current := root
	for _, token := range tokens {
		switch current.Kind {
		case yaml.MappingNode:
			next, ok := yamlMappingValue(current, token)
			if !ok {
				return nil, fmt.Errorf("JSON Pointer member is absent")
			}
			current = next
		case yaml.SequenceNode:
			index, err := strconv.Atoi(token)
			if err != nil || index < 0 || strconv.Itoa(index) != token || index >= len(current.Content) {
				return nil, fmt.Errorf("JSON Pointer array index is invalid")
			}
			current = current.Content[index]
		default:
			return nil, fmt.Errorf("JSON Pointer descends into a scalar")
		}
	}
	return current, nil
}
func openAPIPointerTokens(pointer string) ([]string, error) {
	if pointer == "" {
		return nil, nil
	}
	if !strings.HasPrefix(pointer, "/") {
		return nil, fmt.Errorf("JSON Pointer must start with slash")
	}
	parts := strings.Split(pointer[1:], "/")
	for i, part := range parts {
		var out strings.Builder
		for j := 0; j < len(part); j++ {
			if part[j] != '~' {
				out.WriteByte(part[j])
				continue
			}
			j++
			if j >= len(part) || part[j] != '0' && part[j] != '1' {
				return nil, fmt.Errorf("invalid JSON Pointer escape")
			}
			if part[j] == '0' {
				out.WriteByte('~')
			} else {
				out.WriteByte('/')
			}
		}
		parts[i] = out.String()
	}
	return parts, nil
}

func (w *openAPIProvenanceWalker) walkSchema(node openAPIProvenanceNode, dialect, base string, baseRoot openAPIProvenanceNode, depth int) error {
	if err := w.enter(node, "schema\x00"+base, depth); err != nil {
		if err == io.EOF {
			return nil
		}
		return err
	}
	if node.node.Kind == yaml.ScalarNode && node.node.ShortTag() == "!!bool" {
		return nil
	}
	if node.node.Kind != yaml.MappingNode {
		return &Error{Code: "openapi.position", Pointer: node.doc.resource.URI + "#" + node.pointer, Message: "Schema Object must be an object or Boolean"}
	}
	currentBase, currentRoot, currentDialect := base, baseRoot, dialect
	if !w.openAPI30 {
		if dynamic, ok := openAPIChild(node, "$dynamicRef"); ok {
			return &Error{Code: "openapi.reference", Pointer: node.doc.resource.URI + "#" + dynamic.pointer, Message: "dynamic references require an exact dynamic-scope resolver and are not projected"}
		}
		for _, anchor := range []string{"$anchor", "$dynamicAnchor"} {
			if child, ok := openAPIChild(node, anchor); ok {
				return &Error{Code: "openapi.reference", Pointer: node.doc.resource.URI + "#" + child.pointer, Message: "schema anchors are not supported by exact provenance"}
			}
		}
		if id, ok := openAPIChild(node, "$id"); ok {
			raw, err := yamlScalarString(id.node)
			if err != nil {
				return &Error{Code: "openapi.reference", Pointer: node.doc.resource.URI + "#" + id.pointer, Message: "$id must be a string"}
			}
			baseURI, _ := url.Parse(base)
			relative, err := url.Parse(raw)
			if err != nil {
				return &Error{Code: "openapi.reference", Pointer: node.doc.resource.URI + "#" + id.pointer, Message: "invalid $id URI"}
			}
			resolved := baseURI.ResolveReference(relative)
			if resolved.Fragment != "" {
				return &Error{Code: "openapi.reference", Pointer: node.doc.resource.URI + "#" + id.pointer, Message: "fragment-bearing $id is not supported"}
			}
			currentBase = resolved.String()
			currentRoot = node
		}
		if declared, ok := openAPIChild(node, "$schema"); ok {
			raw, err := yamlScalarString(declared.node)
			if err != nil {
				return &Error{Code: "openapi.dialect", Pointer: node.doc.resource.URI + "#" + declared.pointer, Message: "$schema must be a string"}
			}
			if err := supportedOpenAPIDialect(raw, node.doc.resource.URI+"#"+declared.pointer); err != nil {
				return err
			}
			currentDialect = raw
		}
		if err := w.discoverSchemaAssertions(node, currentDialect); err != nil {
			return err
		}
	}
	if ref, ok := openAPIChild(node, "$ref"); ok {
		raw, err := yamlScalarString(ref.node)
		if err != nil {
			return &Error{Code: "openapi.reference", Pointer: node.doc.resource.URI + "#" + ref.pointer, Message: "$ref must be a string"}
		}
		target, targetBase, targetRoot, err := w.resolveSchema(node, raw, currentBase, currentRoot, depth+1)
		if err != nil {
			return err
		}
		if err := w.walkSchema(target, currentDialect, targetBase, targetRoot, depth+1); err != nil {
			return err
		}
		if w.openAPI30 {
			return nil
		}
	}
	if w.openAPI30 {
		if err := w.discoverSchemaAssertions(node, currentDialect); err != nil {
			return err
		}
	}
	singles := []string{"additionalProperties", "unevaluatedProperties", "propertyNames", "contains", "items", "additionalItems", "unevaluatedItems", "if", "then", "else", "not", "contentSchema"}
	maps := []string{"$defs", "definitions", "properties", "patternProperties", "dependentSchemas"}
	arrays := []string{"allOf", "anyOf", "oneOf", "prefixItems"}
	if w.openAPI30 {
		singles = []string{"additionalProperties", "items", "not"}
		maps = []string{"properties"}
		arrays = []string{"allOf", "anyOf", "oneOf"}
	}
	for _, name := range singles {
		if child, ok := openAPIChild(node, name); ok {
			if err := w.walkSchema(child, currentDialect, currentBase, currentRoot, depth+1); err != nil {
				return err
			}
		}
	}
	for _, name := range maps {
		if group, ok := openAPIChild(node, name); ok {
			items, err := openAPIMappingChildren(group)
			if err != nil {
				return err
			}
			for _, child := range items {
				if err := w.walkSchema(child, currentDialect, currentBase, currentRoot, depth+1); err != nil {
					return err
				}
			}
		}
	}
	for _, name := range arrays {
		if group, ok := openAPIChild(node, name); ok {
			items, err := openAPISequenceChildren(group)
			if err != nil {
				return err
			}
			for _, child := range items {
				if err := w.walkSchema(child, currentDialect, currentBase, currentRoot, depth+1); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func (w *openAPIProvenanceWalker) discoverSchemaAssertions(node openAPIProvenanceNode, dialect string) error {
	if w.openAPI30 {
		return w.discoverOpenAPI30NumericAssertions(node, dialect)
	}
	scope := openAPINumericScope(node.node)
	for _, pair := range []struct {
		keyword  string
		operator string
	}{{"minimum", ">="}, {"maximum", "<="}, {"exclusiveMinimum", ">"}, {"exclusiveMaximum", "<"}, {"multipleOf", "multipleOf"}} {
		value, ok := openAPIChild(node, pair.keyword)
		if !ok {
			continue
		}
		raw, normalized, exact := openAPINumericToken(value)
		if !exact {
			continue
		}
		if scope != "" {
			predicate, err := canonicalBound(scope, pair.operator, normalized)
			if err != nil {
				return err
			}
			builtins := []string{}
			if pair.keyword == "multipleOf" {
				if !positiveJSONNumber(normalized) {
					return &Error{Code: "openapi.assertion", Pointer: node.doc.resource.URI + "#" + value.pointer, Message: "multipleOf must be strictly positive"}
				}
				builtins = []string{"isInteger"}
			}
			if err := w.add(node, pair.keyword, scope, predicate, raw, dialect, builtins); err != nil {
				return err
			}
		}
	}
	if err := w.discoverCardinalityAssertions(node, dialect); err != nil {
		return err
	}
	if !node.doc.isJSON {
		return nil
	}
	jsonNode, err := node.doc.json.At(node.pointer)
	if err != nil {
		return err
	}
	builder := &JSONSchema{maxValueNodes: 1000000, maxValueDepth: 508}
	for _, keyword := range []string{"const", "enum"} {
		value, ok := jsonNode.Lookup(keyword)
		if !ok {
			continue
		}
		values := []schemajson.Node{value}
		if keyword == "enum" {
			if schemajson.KindName(value.Kind()) != "array" {
				return &Error{Code: "openapi.assertion", Pointer: node.doc.resource.URI + "#" + node.pointer + "/enum", Message: "enum must be an array"}
			}
			values = value.Elements()
		}
		expressions := make([]*language.Expr, len(values))
		projectable := true
		for i, item := range values {
			expression, buildErr := builder.canonicalJSONValue(item, 2)
			if valueLimit(buildErr) {
				projectable = false
				break
			}
			if buildErr != nil {
				return buildErr
			}
			expressions[i] = expression
		}
		if !projectable {
			continue
		}
		var predicate *language.Expr
		builtins := []string{}
		if keyword == "const" {
			predicate = &language.Expr{Form: language.Binary{Operator: "==", Left: &language.Expr{Form: language.Variable{Name: "it"}}, Right: expressions[0]}}
		} else {
			predicate = &language.Expr{Form: language.Apply{Function: &language.Expr{Form: language.Apply{Function: &language.Expr{Form: language.Variable{Name: "oneOf"}}, Argument: &language.Expr{Form: language.Variable{Name: "it"}}}}, Argument: &language.Expr{Form: language.ListLiteral{Elements: expressions}}}}
			builtins = []string{"oneOf"}
		}
		if err := w.add(node, keyword, "JSON", language.FormatExpression(predicate), value.Raw(), dialect, builtins); err != nil {
			return err
		}
	}
	return nil
}

func openAPINumericScope(node *yaml.Node) string {
	typ, ok := yamlMappingValue(node, "type")
	if !ok {
		return ""
	}
	if typ.Kind == yaml.SequenceNode {
		if len(typ.Content) != 1 {
			return ""
		}
		typ = typ.Content[0]
	}
	name, err := yamlScalarString(typ)
	if err != nil {
		return ""
	}
	if name == "integer" {
		return "Int"
	}
	if name == "number" {
		return "Real"
	}
	return ""
}
func openAPINumericToken(node openAPIProvenanceNode) (raw, normalized string, ok bool) {
	if node.doc.isJSON {
		value, err := node.doc.json.At(node.pointer)
		if err != nil || schemajson.KindName(value.Kind()) != "number" {
			return "", "", false
		}
		return value.Raw(), value.Raw(), true
	}
	scalar := node.node
	if scalar.Kind != yaml.ScalarNode || scalar.Style != 0 || scalar.Anchor != "" {
		return "", "", false
	}
	raw, ok = yamlExactScalar(node.doc, scalar)
	if !ok {
		return "", "", false
	}
	switch scalar.ShortTag() {
	case "!!int":
		normalized, ok = normalizeYAMLInteger(raw)
	case "!!float":
		normalized, ok = normalizeYAMLFloat(raw)
	default:
		return "", "", false
	}
	return raw, normalized, ok
}
func positiveJSONNumber(raw string) bool {
	if strings.HasPrefix(raw, "-") {
		return false
	}
	mantissa := strings.SplitN(strings.ToLower(raw), "e", 2)[0]
	return strings.Trim(mantissa, "0.") != ""
}
